### ISSUE TITLE
IPv6 pods crash on start

### ISSUE THREAD

**Issue by samhamilton** [k0sproject/k0s#1027]
**Version**
```
$ k0s version
v1.21.2+k0s.1
```
**Platform**
Which platform did you run k0s on?
```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.2 LTS
Release:	20.04
Codename:	focal
```
**What happened?**
I am unable to standup a dual stack cluster

**How To Reproduce**
- Grab a default config `k0s default-config > k0s.yaml`
- Add the dual stack settings as per the docs page
```
apiVersion: k0s.k0sproject.io/v1beta1
kind: Cluster
metadata:
  name: k0s
spec:
  api:
    address: 168.119.88.161
    port: 6443
    k0sApiPort: 9443
    sans:
    - 168.119.88.161
    - 10.96.0.1
    - 10.96.0.10
    - 10.99.82.25
  storage:
    type: etcd
    etcd:
      peerAddress: 168.119.88.161
  network:
    podCIDR: 10.244.0.0/16
    serviceCIDR: 10.96.0.0/12
    provider: calico
    calico:
      mode: bird
    dualStack:
      enabled: true
      IPv6podCIDR: fd00::/108
      IPv6serviceCIDR: fd01::/108
    kuberouter:
      mtu: 0
      peerRouterIPs: ""
      peerRouterASNs: ""
      autoMTU: true
    kubeProxy:
      disabled: false
      mode: ipvs
  podSecurityPolicy:
    defaultPolicy: 00-k0s-privileged
  telemetry:
    enabled: true
  installConfig:
    users:
      etcdUser: etcd
      kineUser: kube-apiserver
      konnectivityUser: konnectivity-server
      kubeAPIserverUser: kube-apiserver
      kubeSchedulerUser: kube-scheduler
  images:
    konnectivity:
      image: us.gcr.io/k8s-artifacts-prod/kas-network-proxy/proxy-agent
      version: v0.0.21
    metricsserver:
      image: gcr.io/k8s-staging-metrics-server/metrics-server
      version: v0.3.7
    kubeproxy:
      image: k8s.gcr.io/kube-proxy
      version: v1.21.2
    coredns:
      image: docker.io/coredns/coredns
      version: 1.7.0
    calico:
      cni:
        image: docker.io/calico/cni
        version: v3.18.1
      node:
        image: docker.io/calico/node
        version: v3.18.1
      kubecontrollers:
        image: docker.io/calico/kube-controllers
        version: v3.18.1
    kuberouter:
      cni:
        image: docker.io/cloudnativelabs/kube-router
        version: v1.2.1
      cniInstaller:
        image: quay.io/k0sproject/cni-node
        version: 0.1.0
    default_pull_policy: IfNotPresent
  konnectivity:
    agentPort: 8132
    adminPort: 8133
```
- `k0s install controller -c k0s.yaml --enable-worker`
- `k0s start`

**Expected behavior**
I expected pods not to crash

**Screenshots & Logs**
```
$ k0s kubectl logs -n kube-system calico-kube-controllers-6d8ccdbf46-plf6n
2021-07-26 03:00:40.084 [INFO][1] main.go 92: Loaded configuration from environment config=&config.Config{LogLevel:"info", WorkloadEndpointWorkers:1, ProfileWorkers:1, PolicyWorkers:1, NodeWorkers:1, Kubeconfig:"", DatastoreType:"kubernetes"}
W0726 03:00:40.085349       1 client_config.go:552] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
2021-07-26 03:00:40.085 [INFO][1] main.go 113: Ensuring Calico datastore is initialized
2021-07-26 03:00:50.085 [ERROR][1] client.go 261: Error getting cluster information config ClusterInformation="default" error=Get "https://10.96.0.1:443/apis/crd.projectcalico.org/v1/clusterinformations/default": context deadline exceeded
2021-07-26 03:00:50.086 [FATAL][1] main.go 118: Failed to initialize Calico datastore error=Get "https://10.96.0.1:443/apis/crd.projectcalico.org/v1/clusterinformations/default": context deadline exceeded
```

```
$ k0s kubectl get pods -A
NAMESPACE     NAME                                       READY   STATUS             RESTARTS   AGE
kube-system   calico-kube-controllers-6d8ccdbf46-plf6n   0/1     CrashLoopBackOff   8          20m
kube-system   calico-node-q9nhs                          1/1     Running            0          20m
kube-system   coredns-5ccbdcc4c4-4dv25                   0/1     Running            0          20m
kube-system   konnectivity-agent-s4572                   1/1     Running            0          20m
kube-system   kube-proxy-gg9fs                           1/1     Running            0          20m
kube-system   metrics-server-59d8698d9-qvn5g             0/1     Running            8          20m
```

**Additional context**
None
