### ISSUE TITLE
Be able to use the kube-router service proxy

### ISSUE THREAD

**Issue by rgl** [k0sproject/k0s#1114]
**Is your feature request related to a problem? Please describe.**

Not really a problem.

**Describe the solution you'd like**

I would like to use the [kube-router service proxy](https://github.com/cloudnativelabs/kube-router#ipvslvs-based-service-proxy----run-service-proxy), but [kuberouter.go disables it](https://github.com/k0sproject/k0s/blob/1a84ded113370d8d400a36fff9b3529de84c5d75/pkg/component/controller/kuberouter.go#L223).

Was there a reason for not enabling it?

Would it be possible to have a flag to enable it or always enable it?

**Comment by jnummelin** [comment]
> Was there a reason for not enabling it?

I guess the main reason was to avoid too much "variance" and have more typical setup with kube-proxy in place.

> Would it be possible to have a flag to enable it or always enable it?

That would make sense. Something like:
```yaml
spec:
  network:
    kubeproxy:
      enableServiceProxy: true # would default to false for backward compatibility
```
This would also automatically disable kube-proxy.

WDYT?
