### ISSUE TITLE
Dual stack enabled should not validate kube-proxy mode when kube-proxy is disabled

### ISSUE THREAD

**Issue by pdf** [k0sproject/k0s#1183]
**Version**
```
v1.22.2+k0s.1
```
**Platform**
Which platform did you run k0s on?
```
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.3 LTS
Release:        20.04
Codename:       focal
```
**What happened?**
Attempting to install with dualStack enabled, and kube-proxy disabled results in a validation failure:
```
dual-stack requires kube-proxy in ipvs mode
```

**How To Reproduce**
Attempt installation with:
```yaml
spec:
  network:
    provider: custom
    kubeProxy:
      disabled: true
    dualStack:
      enabled: true
      ...
```
And make sure the rest of the config is valid.

**Expected behavior**
Installation should complete successfully, leaving it as an exercise for the user to sort out the networking. Probably just needs the condition updated:
https://github.com/k0sproject/k0s/blob/836fb1a5ad6ca1ffaf8263e1861e6c8ed3321f07/pkg/apis/k0s.k0sproject.io/v1beta1/network.go#L84
```go
if !n.KubeProxy.Disabled && n.KubeProxy.Mode != ModeIPVS {
```

**Additional context**
My use-case is deploying cilium with kube-proxy replacement, but this applies to any dual-stack deployment without kube-proxy.
