### ISSUE TITLE
Manifest Deployer does not accept `kind: List` style manifest.

### ISSUE THREAD

**Issue by cl-lab-k** [k0sproject/k0s#1211]
**Version**
```
$ k0s version
v1.22.2+k0s.1
```
**Platform**
```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.6 LTS
Release:	18.04
Codename:	bionic
```
**What happened?**
Manifest Deployer does not accept `kind: List` style manifest.
I put [Weave Net install manifest](https://www.weave.works/docs/net/latest/kubernetes/kube-addon/#-installation) under `/var/lib/k0s/manifests/weavenet` but is not deployed by Manifest Deployer.  I check k0scontroller's log, it says:

> Oct 25 08:22:34 master k0s[2703]: time="2021-10-25 08:22:34" level=warning msg="stack apply failed" bundle=weavenet component=applier error="unknown api error: name is required"
> Oct 25 08:22:34 master k0s[2703]: time="2021-10-25 08:22:34" level=warning msg="failed to apply manifests: unknown api error: name is required" component=applier-weavenet

The head of Weave Net install manifest:

```yaml
apiVersion: v1
kind: List
items:
  - apiVersion: v1
    kind: ServiceAccount
    metadata:
      name: weave-net
      annotations:
        cloud.weave.works/launcher-info: |-
          {
```

So I add dummy `metadata.name` and `metadata.namespace` into Weave Net manifest's `kind: List`:

```yaml
apiVersion: v1
kind: List
metadata:
  name: weave-net
  namespace: weave-net
items:
  - apiVersion: v1
    kind: ServiceAccount
    metadata:
      name: weave-net
```

But k0scontroller claims error:

> Oct 26 01:53:20 master k0s[2606]: time="2021-10-26 01:53:20" level=warning msg="stack apply failed" bundle=weavenet component=applier error="cannot create resource weave-net: the server could not find the requested resource"
> Oct 26 01:53:20 master k0s[2606]: time="2021-10-26 01:53:20" level=warning msg="stack apply failed" bundle=weavenet component=applier error="cannot create resource weave-net: the server could not find the requested resource"
> Oct 26 01:53:20 master k0s[2606]: time="2021-10-26 01:53:20" level=warning msg="stack apply failed" bundle=weavenet component=applier error="cannot create resource weave-net: the server could not find the requested resource"
> Oct 26 01:53:20 master k0s[2606]: time="2021-10-26 01:53:20" level=warning msg="stack apply failed" bundle=weavenet component=applier error="cannot create resource weave-net: the server could not find the requested resource"
> Oct 26 01:53:20 master k0s[2606]: time="2021-10-26 01:53:20" level=warning msg="stack apply failed" bundle=weavenet component=applier error="cannot create resource weave-net: the server could not find the requested resource"
> Oct 26 01:53:20 master k0s[2606]: time="2021-10-26 01:53:20" level=warning msg="failed to apply manifests: cannot create resource weave-net: the server could not find the requested resource" component=applier-weavenet

Finally, I change Weave Net install manifest from `kind: List` style to splitted YAML block style with `---`, it is accepted and deployed. 

**How To Reproduce**
1. launch vanilla VM.
2. install k0s.
3. do `k0s default-config > k0s.yaml`.
4. change `k0s.yaml`'s `spec.network.provider` from `kuberouter` to `custom`.
5. do `k0s install controller -c k0s.yaml`.
6. do `k0s start`.
7. create `/var/lib/k0s/manifests/weavenet` directory.
8. do `curl -sSLf "https://cloud.weave.works/k8s/net?k8s-version=$(k0s kubectl version | base64 | tr -d '\n')" > /var/lib/k0s/manifests/weavenet/weavenet.yaml`.

**Expected behavior**
Manifest Deployer accepts Weave Net install manifest that I do not need to split it out into YAML blocks.
