### ISSUE TITLE
How to set up Pixie in the local k0s environment？

### ISSUE THREAD

**Issue by pinghe** [k0sproject/k0s#1217]
Pixie
https://docs.px.dev/  https://pixielabs.ai/
https://github.com/pixie-io/pixie

**Comment by soider** [comment]
Actually there is even an easier way to set it up by using k0s helm extensions, just install cluster by using following config

```yaml
spec:
  extensions:
    helm:
      repositories:
      - name: openebs
        url: https://openebs.github.io/charts
      - name: pixie
        url: https://pixie-operator-charts.storage.googleapis.com
      charts:
      - name: openebs
        chartname: openebs/openebs
        version: "3.0.3"
        namespace: openebs
      - name: pixie
        chartname: pixie/pixie-operator-chart
        namespace: pl
        values: |
          deployKey: px-dep-fb24cd76-5b11-4bac-8a95-8b6237a6fdaf
          clusterName: k0s.yaml_based_deployment
```


example:
```bash
$ sudo k0s install controller --enable-worker -c /path/to/config
$ sudo k0s start
```

Note, that it would take quiet a time (aprox 20 minutes) to fully reconcile everything.

**Comment by jberryman** [comment]
FWIW it seems I needed the following:

```
sudo chmod a+r /var/lib/k0s/pki/admin.con
KUBECONFIG=/var/lib/k0s/pki/admin.conf px deploy --check=false
```

if I had added a binary shim `$PATH/kubectl` that was just `k0s kubectl` maybe the checks would have passed, but I didn't try it

**Comment by jnummelin** [comment]
Chmod with a+r for the admin kubeconfig sounds like a bad idea...

**Comment by jberryman** [comment]
I guess? this is for a local dev environment on my laptop, and I would sell my first born at this point to get this stuff actually working. 

FWIW I thought I was good, but now data is just randomly disappearing from the pixie console and I've probably exhausted the time I have to spend on this experiment

**Comment by jnummelin** [comment]
> if I had added a binary shim $PATH/kubectl that was just k0s kubectl maybe the checks would have passed, but I didn't try it

Yes, that seems to be correct. Just having an alias doesn't seem to cut it. I did simple shim as `/usr/local/kubectl`:
```bash
#!/bin/sh

k0s kc $@
```

Then booted up the cluster with config:
```yaml
root@pixie-test:~# cat k0s.yaml 
spec:
  extensions:
    helm:
      repositories:
      - name: openebs-internal
        url: https://openebs.github.io/charts
      charts:
      - name: openebs
        chartname: openebs-internal/openebs
        version: "3.9.0"
        namespace: openebs
        order: 1
        values: |
          localprovisioner:
            hostpathClass:
              enabled: true
              isDefaultClass: false
```

```shell
k0s install controller --singe --config /root/k0s.yaml
```

Once everything comes up online, I deployed Pixie:
```
export PX_CLOUD_ADDR=getcosmic.ai
export KUBECONFIG=/var/lib/k0s/pki/admin.conf 
px auth login
px deploy
```

I see cluster now connected to https://work.getcosmic.ai/
