### ISSUE TITLE
specify kine sqlite db path

### ISSUE THREAD

**Issue by matti** [k0sproject/k0s#1256]
I expected that I could give a path to kine sqlite db:

```
apiVersion: k0s.k0sproject.io/v1beta1
kind: ClusterConfig
spec:
  storage:
    type: kine
    kine:
      data: sqlite:///app/k0s.db
```

but it just configures k0s/kine to use sqlite and it creates the db in `/var/lib/k0s/db/`
