### ISSUE TITLE
externalAddress is not used in worker join

### ISSUE THREAD

**Issue by matti** [k0sproject/k0s#1260]
From the docs:

>externalAddress: Configures all cluster components to connect to this address and also configures this address for use when joining new nodes to the cluster.

```
apiVersion: k0s.k0sproject.io/v1beta1
kind: ClusterConfig
spec:
  api:
    externalAddress: 127.0.0.1
  storage:
    type: kine
```

worker logs: `failed to get kubelet config from API: Get \"https://172.24.0.2:6443`
