### ISSUE TITLE
Null creationTimestamp and empty status:{} in "k0s default-config"

### ISSUE THREAD

**Issue by kke** [k0sproject/k0s#1278]
```yaml
...
metadata:
  creationTimestamp: null
spec:
...
status: {}
```

It's a bit weird that the `json:omitempty` isn't working for those fields.
