### ISSUE TITLE
Apiserver not configured with dual-stack service-cluster-ip-range when dual stack is enabled in k0s configuration

### ISSUE THREAD

**Issue by erdii** [k0sproject/k0s#1319]
**Version**
```
$ k0s version
v1.22.4+k0s.1
```
**Platform**
Which platform did you run k0s on?
Odroid-HC4 ARM64
```
$ cat /etc/os-release 
NAME="Arch Linux ARM"
PRETTY_NAME="Arch Linux ARM"
ID=archarm
ID_LIKE=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinuxarm.org/"
DOCUMENTATION_URL="https://archlinuxarm.org/wiki"
SUPPORT_URL="https://archlinuxarm.org/forum"
BUG_REPORT_URL="https://github.com/archlinuxarm/PKGBUILDs/issues"
LOGO=archlinux-logo
```
**What happened?**
Enabled dual-stack in k0s configuration but I was not able to configure Services with the v6 IP-family even though pod networking had working v4 and v6 networking.
I found out that the kubernetes apiserver was missing the ipv6 part of the `service-cluster-ip-range` even though it was correctly configured on the controller-manager.

This is how the flag looks on the
- apiserver: `--service-cluster-ip-range=10.96.0.0/12`
- controller-manager: `--service-cluster-ip-range=10.96.0.0/12,fd01::/108`

**How To Reproduce**
Enable dual-stack networking in k0s configuration. I used k0sctl with this configuration:

```yaml
apiVersion: k0sctl.k0sproject.io/v1beta1
kind: Cluster
metadata:
  name: homelab
spec:
  hosts:
  - ssh:
      address: odroid-hc4-one.home.erdii.net
      user: root
      port: 22
    role: controller+worker
  - ssh:
      address: odroid-hc4-two.home.erdii.net
      user: root
      port: 22
    role: controller+worker
  - ssh:
      address: odroid-hc4-three.home.erdii.net
      user: root
      port: 22
    role: controller+worker
  k0s:
    version: 1.22.4+k0s.1
    config:
      apiVersion: k0s.k0sproject.io/v1beta1
      kind: Cluster
      metadata:
        name: k0s
      spec:
        api:
          k0sApiPort: 9443
          port: 6443
          externalAddress: kubelab.home.erdii.net
          sans:
          - kubelab.home.erdii.net
        network:
          provider: calico
          kubeProxy:
            mode: ipvs
          calico:
            mode: bird
          dualStack:
            enabled: true
            IPv6podCIDR: "fd00::/108"
            IPv6serviceCIDR: "fd01::/108"
          podCIDR: 10.244.0.0/16
          serviceCIDR: 10.96.0.0/12
```

**Expected behavior**
I expected to be able to create dual-stack and/or ipv6 services in my cluster.
