### ISSUE TITLE
Unable to add worker with manual install (kube-router/CNI issue)

### ISSUE THREAD

**Issue by GBBx** [k0sproject/k0s#1334]
**Version**
```
v1.22.4+k0s.1
```
**Platform**
Which platform did you run k0s on?
```
AlmaLinux 8.5
```
**What happened?**
I was able to set up k0s with controller and worker on the same machine but I cannot add a new worker.

**How To Reproduce**
I try to follow this guide:
https://github.com/k0sproject/k0s/blob/v1.22.4%2Bk0s.1/docs/k0s-multi-node.md

I installed k0s
I try to start it as
```
k0s worker --token-file=...
```

(It didn't work out of the box for me, I had to add some proxy/no_proxy variables to the systemd unit file.)

` get pods -o wide -n kube-system` showed some containers failing, e.g. konnectivity and kube-router (on the new worker only).

I found "no IP ranges specified" error in the `kubectl describe konnectivity...` (which seems to be the same issue as here: https://github.com/k0sproject/k0sctl/issues/158).

I figured that the `/etc/cni/net.d/10-kuberouter.conflist` file was missing on the new worker.
I copied this file from the controller and restarted k0sworker.

Now `kubectl get nodes` shows the new node being `Ready`. However, kube-router is still in a `CrashLoopBackOff`.
Logs (`/var/log/pods/kube-system_kube-router.../kube-router/...log`):
```
network_routes_controller.go:1062] Failed to get pod CIDR from node spec. kube-router relies on kube-controller-manager to allocate pod CIDR for the node or an annotation `kube-router.io/pod-cidr`. Error: node.Spec.PodCIDR not set for node: <new worker>
```

**Expected behavior**
Kube-router should be running on the new worker as it is on the first machine.

**Comment by GBBx** [comment]
OK, I did some more research and I found [this article](https://xcp-ng.org/forum/topic/3686/kubernetes-recipe-basic-setup-not-working).

I tried what they user "ralphsmeets" suggests:
```
kubectl get nodes newworker -o yaml # there was nothing under podCIDR
kubectl patch node newworker -p '{"spec":{"podCIDR":"172.17.0.0/24", "podCIDRs": ["172.17.0.0/24"] }}'
```

And voila, the problem is solved now, kube-router is running.

But does anybody know why it happened? Is kubernetes/kube-router still incompatible with nftables (I use AlmaLinux where legacy mode is not available)? Or is it something specific to k0s?

**Comment by soider** [comment]
@GBBx are you able to share kube-router logs? you can find them on the worker nodes under the `/var/log/containers` path

**Comment by soider** [comment]
@GBBx can I ask you to share the logs from the k0s controller process? based on the kube-router error message you posted there is something wrong with a kube-controller-manager component.

**Comment by GBBx** [comment]
Hi @soider, thanks for your message.
There's a lot of kube-controller-manager log:
```
grep kube-controller-manager /var/log/messages | wc -l
511
```

Nearly all log is info. So I tried this:
```
grep kube-controller-manager /var/log/messages | grep -v level=info
Dec 29 12:22:23 ........ k0s[2666]: time="2021-12-29 12:22:23" level=warning msg="running kube-controller-manager as root: user: unknown user kube-apiserver"
```

I'm not sure it is relevant though.
And here's the config:
```
apiVersion: k0s.k0sproject.io/v1beta1
kind: ClusterConfig
metadata:
  creationTimestamp: null
  name: k0s
spec:
  api:
    address: < controller IP >
    k0sApiPort: 9443
    port: 6443
    sans:
    - < controller IP >
    - 172.17.0.1
  controllerManager: {}
  images:
    calico:
      cni:
        image: docker.io/calico/cni
        version: v3.18.1
      kubecontrollers:
        image: docker.io/calico/kube-controllers
        version: v3.18.1
      node:
        image: docker.io/calico/node
        version: v3.18.1
    coredns:
      image: k8s.gcr.io/coredns/coredns
      version: v1.7.0
    default_pull_policy: IfNotPresent
    konnectivity:
      image: k8s.gcr.io/kas-network-proxy/proxy-agent
      version: v0.0.25
    kubeproxy:
      image: k8s.gcr.io/kube-proxy
      version: v1.22.4
    kuberouter:
      cni:
        image: docker.io/cloudnativelabs/kube-router
        version: v1.3.2
      cniInstaller:
        image: quay.io/k0sproject/cni-node
        version: 0.1.0
    metricsserver:
      image: k8s.gcr.io/metrics-server/metrics-server
      version: v0.5.0
  installConfig:
    users:
      etcdUser: etcd
      kineUser: kube-apiserver
      konnectivityUser: konnectivity-server
      kubeAPIserverUser: kube-apiserver
      kubeSchedulerUser: kube-scheduler
  konnectivity:
    adminPort: 8133
    agentPort: 8132
  network:
    calico: null
    dualStack: {}
    kubeProxy:
      mode: iptables
    kuberouter:
      autoMTU: true
      mtu: 0
      peerRouterASNs: ""
      peerRouterIPs: ""
    podCIDR: 172.17.0.0/24
    provider: kuberouter
    serviceCIDR: 172.18.0.0/24
  podSecurityPolicy:
    defaultPolicy: 00-k0s-privileged
  scheduler: {}
  storage:
    etcd:
      peerAddress: < controller IP >
    type: etcd
  telemetry:
    enabled: true
status: {}
```
