### ISSUE TITLE
pulling image quay.io/k0sproject/cni-node:0.1.0 not work

### ISSUE THREAD

**Issue by walejandromt** [k0sproject/k0s#1415]
### Before creating an issue, make sure you've checked the following:

- [X] You are running the latest released version of k0s
- [X] Make sure you've searched for existing issues, both open and closed
- [X] Make sure you've searched for PRs too, a fix might've been merged already
- [X] You're looking at docs for the released version, "main" branch docs are usually ahead of released versions.

### Version

v1.23.1+k0s.0

### Platform

```shell
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.3 LTS
Release:        20.04
Codename:       focal
```

### What happened?

the pulling image not work with quay.io/k0sproject/cni-node:0.1.0
i try installing k0s with k0sctl but when worker its install and the pods of the kube-system are initializer failed Pulling image "quay.io/k0sproject/cni-node:0.1.0"

status nodes and pods
![get nodes pods](https://user-images.githubusercontent.com/14278594/148141809-59c2003a-ea5a-46f2-8bab-acff72934c2c.png)

other pods with pulling image work:
![pulling work](https://user-images.githubusercontent.com/14278594/148142347-1359a9e7-7e22-4569-99a6-45834f6a1929.png)

describe kube-router-6k8r6:
![kubectl describe](https://user-images.githubusercontent.com/14278594/148141867-cbb2290e-473d-4a1e-8675-0d56036c98b0.png)

log kubectl:
![log kubectl](https://user-images.githubusercontent.com/14278594/148141890-bb63e316-25b6-4ab0-b53d-b5174c2c126a.png)

logs files
[k0sctl.log](https://github.com/k0sproject/k0s/files/7811181/k0sctl.log)

k0sctl.yaml
```yaml
apiVersion: k0sctl.k0sproject.io/v1beta1
kind: Cluster
metadata:
  name: k0s-cluster
spec:
  hosts:
  - ssh:
      address: 10.51.44.17
      user: ubuntu
      port: 22
      keyPath: /home/user/.ssh/id_rsa
    role: controller
  - ssh:
      address: 10.51.44.31
      user: ubuntu
      port: 22
      keyPath: /home/user/.ssh/id_rsa
    role: worker
  k0s:
    version: 1.21.3+k0s.0
    config:
      apiVersion: k0s.k0sproject.io/v1beta1
      kind: Cluster
      metadata:
        name: k0s
      spec:
        api:
          k0sApiPort: 9443
          port: 6443
        images:
          calico:
            cni:
              image: docker.io/calico/cni
              version: v3.18.1
            kubecontrollers:
              image: docker.io/calico/kube-controllers
              version: v3.18.1
            node:
              image: docker.io/calico/node
              version: v3.18.1
          coredns:
            image: docker.io/coredns/coredns
            version: 1.7.0
          default_pull_policy: IfNotPresent
          konnectivity:
            image: us.gcr.io/k8s-artifacts-prod/kas-network-proxy/proxy-agent
            version: v0.0.24
          kubeproxy:
            image: k8s.gcr.io/kube-proxy
            version: v1.22.1
          kuberouter:
            cni:
              image: docker.io/cloudnativelabs/kube-router
              version: v1.2.1
            cniInstaller:
              image: quay.io/k0sproject/cni-node
              version: 0.1.0
          metricsserver:
            image: gcr.io/k8s-staging-metrics-server/metrics-server
            version: v0.5.0
        installConfig:
          users:
            etcdUser: etcd
            kineUser: kube-apiserver
            konnectivityUser: konnectivity-server
            kubeAPIserverUser: kube-apiserver
            kubeSchedulerUser: kube-scheduler
        konnectivity:
          adminPort: 8133
          agentPort: 8132
        network:
          kubeProxy:
            disabled: false
            mode: iptables
          kuberouter:
            autoMTU: true
            mtu: 0
            peerRouterASNs: ""
            peerRouterIPs: ""
          podCIDR: 10.244.0.0/16
          provider: kuberouter
          serviceCIDR: 10.96.0.0/12
        podSecurityPolicy:
          defaultPolicy: 00-k0s-privileged
        storage:
          type: etcd
        telemetry:
          enabled: true
```

### Steps to reproduce

1.
2.
3.
