### ISSUE TITLE
support adding private registry through k0s configuration file

### ISSUE THREAD

**Issue by soider** [k0sproject/k0s#1424]
### Is your feature request related to a problem? Please describe.

As a user I want to be able to pull images from my own hosted registry secured by auth.

To support it currently user needs to manually follow containerd documentation and add certificates.

https://github.com/containerd/containerd/blob/main/docs/cri/config.md#registry-configuration

### Describe the solution you would like

Would be great if we introduce k0s config section related to the cri settings which will allow to easy setup certificates for private registry

### Describe alternatives you've considered

Manual setup.

### Additional context

Request for corresponding guide appeared in the k0s slack channel couple of times.

**Comment by soider** [comment]
https://mrzik.medium.com/how-to-configure-private-registry-for-kubernetes-cluster-running-with-containerd-cf74697fa382

some configuration examples

**Comment by martencassel** [comment]
How should k0s controllers handle automatic configurations managed by the k0s when users have setup custom settings in containerd for runtimes ?

**Comment by martencassel** [comment]
I've started working on this...

Should we support multiple registries or just one ?
The containerd host conigurations support multiple registry host configuration files..
https://fossies.org/linux/containerd/docs/hosts.md

It would also be a good idea to support more settings in the future ?

Should we also support http only authentication to insecure registries ?
(The legacy configuration way in containerd: https://fossies.org/linux/containerd/docs/hosts.md )

A Single registry configuration,

```yaml
runtime:
  registry:
    docker.io:
      server: "https://docker.io"
      capabilities:
        - "pull"
      skip_verify: true
      ca: <base64 encoded ca>
      client: <base64 encoded client cert>
      key: <base64 encoded client key>
      credential:
        username: "admin"
        password: "password"
```

or

Multiple

```yaml
runtime:
  registries:
    docker.io:
      server: "https://docker.io"
      capabilities:
        - "pull"
      skip_verify: true
      ca: <base64 encoded ca>
      client: <base64 encoded client cert>
      key: <base64 encoded client key>
      credential:
        username: "admin"
        password: "password"
    gcr.io:
      server: "https://gcr.io"
      capabilities:
        - "pull"
      skip_verify: true
      ca: <base64 encoded ca>
      client: <base64 encoded client cert>
      key: <base64 encoded client key>
    ghcr.io:
      server: "https://ghcr.io"
      capabilities:
        - "pull"
      skip_verify: false
      ca: <base64 encoded ca>
      client: <base64 encoded client cert>
      key: <base64 encoded client key>
```

**Comment by martencassel** [comment]
I think i can do this one.

Is supporting a single registry configuration enough ? Containerd support defining multiple registries.

Do you want also to support insecure registry settings ?

**Comment by soider** [comment]
@martencassel let's go with multiple registries.

Something like
```
spec:
  runtime:
   registries:
    - name: docker.io:
      server: "https://docker.io"
      capabilities:
        - "pull"
      skip_verify: true
      ca: <base64 encoded ca>
      client: <base64 encoded client cert>
      key: <base64 encoded client key>
      credential:
        username: "admin"
        password: "password"
    - name: gcr.io:
      server: "https://gcr.io"
      capabilities:
        - "pull"
      skip_verify: true
      ca: <base64 encoded ca>
      client: <base64 encoded client cert>
      key: <base64 encoded client key>
    ghcr.io:
      server: "https://ghcr.io"
      capabilities:
        - "pull"
      skip_verify: false
      ca: <base64 encoded ca>
      client: <base64 encoded client cert>
      key: <base64 encoded client key>
—
```

I like your idea of having separate runtime section in the config, because we might want to have some other runtime related settings been introduced as well soon 👍
