### ISSUE TITLE
manifest deployer doesn't work when yaml targets controller instead of worker

### ISSUE THREAD

**Issue by xinity** [k0sproject/k0s#1425]
### Before creating an issue, make sure you've checked the following:

- [X] You are running the latest released version of k0s
- [X] Make sure you've searched for existing issues, both open and closed
- [X] Make sure you've searched for PRs too, a fix might've been merged already
- [X] You're looking at docs for the released version, "main" branch docs are usually ahead of released versions.

### Version

v0.12.1

### Platform

```shell
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 21.10
Release:	21.10
Codename:	impish
```

### What happened?

tried to use the manifest deployer this way:
create a directory in the first master : `/var/lib/k0s/manifests/kubevip/`
the manifest looks like:
```
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube-vip
  namespace: kube-system
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: vip-role
  namespace: kube-system
rules:
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["get", "create", "update", "list", "put"]
  - apiGroups: [""]
    resources: ["configmaps", "endpoints"]
    verbs: ["watch", "get"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: vip-role-bind
  namespace: kube-system
subjects:
  - kind: ServiceAccount
    name: kube-vip
    apiGroup: ""
roleRef:
  kind: Role
  name: vip-role
  apiGroup: ""
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  creationTimestamp: null
  name: kube-vip-ds
  namespace: kube-system
spec:
  selector:
    matchLabels:
      name: kube-vip-ds
  template:
    metadata:
      creationTimestamp: null
      labels:
        name: kube-vip-ds
    spec:
      containers:
      - args:
        - manager
        env:
        - name: vip_arp
          value: "true"
        - name: vip_interface
          value: enp0s2
        - name: port
          value: "6443"
        - name: vip_cidr
          value: "32"
        - name: cp_enable
          value: "true"
        - name: cp_namespace
          value: kube-system
        - name: svc_enable
          value: "false"
        - name: vip_address
          value: 192.168.157.253
        image: ghcr.io/kube-vip/kube-vip:v0.3.7
        imagePullPolicy: Always
        name: kube-vip
        resources: {}
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
            - NET_RAW
            - SYS_TIME
      hostNetwork: true
      nodeSelector:
        node-role.kubernetes.io/control-plane: "true"
      serviceAccountName: kube-vip
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
  updateStrategy: {}
status:
  currentNumberScheduled: 0
  desiredNumberScheduled: 0
  numberMisscheduled: 0
  numberReady: 0
```

nothing happens while doing this same with the documentation example works perfectly

### Steps to reproduce

1. create the appropriate directory on a k0s cluster controller
2. push the manifest into the directory
3. ...

### Expected behavior

Kube-Vip Daemonset should be automatically deployed on all controllers

### Actual behavior

nothing happens :(

**Comment by soider** [comment]
```
Version

v0.12.1
```

What is the k0s version you use? The 0.12.1 doesn't look like any of the recent releases.

>Kube-Vip Daemonset should be automatically deployed on all controllers

what is the way to validate deployment? daemon set itself doesn't create any pods if you have no matching nodes.


The issue requires more info:
- how did you set up the cluster (controllers and workers)
- configuration file for k0s or k0sctl
- logs from the controller

**Comment by xinity** [comment]
@soider here are the information required:
```
NAME              STATUS   ROLES           AGE   VERSION
rpi4pico1-node1   Ready    control-plane   38h   v1.23.1+k0s
rpi4pico1-node2   Ready    control-plane   38h   v1.23.1+k0s
rpi4pico1-node3   Ready    control-plane   38h   v1.23.1+k0s
rpi4pico1-node4   Ready    <none>          38h   v1.23.1+k0s
rpi4pico1-node5   Ready    <none>          38h   v1.23.1+k0s
rpi4pico1-node6   Ready    <none>          38h   v1.23.1+k0s
rpi4pico1-node7   Ready    <none>          38h   v1.23.1+k0s
rpi4pico1-node8   Ready    <none>          38h   v1.23.1+k0s
```
 find below the yaml file used by k0sctl:
```
apiVersion: k0sctl.k0sproject.io/v1beta1
kind: Cluster
metadata:
  name: rpi4pico1
spec:
  hosts:
  - ssh:
      address: 192.168.2.141
      user: ubuntu
      port: 22
      keyPath: /Users/xinity/.ssh/id_rsa_k0s_rock64
    role: controller
    installFlags:
    - --enable-worker
  - ssh:
      address: 192.168.2.142
      user: ubuntu
      port: 22
      keyPath: /Users/xinity/.ssh/id_rsa_k0s_rock64
    role: controller
    installFlags:
    - --enable-worker
  - ssh:
      address: 192.168.2.143
      user: ubuntu
      port: 22
      keyPath: /Users/xinity/.ssh/id_rsa_k0s_rock64
    role: controller
    installFlags:
    - --enable-worker
  - ssh:
      address: 192.168.2.144
      user: ubuntu
      port: 22
      keyPath: /Users/xinity/.ssh/id_rsa_k0s_rock64
    role: worker
  - ssh:
      address: 192.168.2.145
      user: ubuntu
      port: 22
      keyPath: /Users/xinity/.ssh/id_rsa_k0s_rock64
    role: worker
  - ssh:
      address: 192.168.2.146
      user: ubuntu
      port: 22
      keyPath: /Users/xinity/.ssh/id_rsa_k0s_rock64
    role: worker
  - ssh:
      address: 192.168.2.147
      user: ubuntu
      port: 22
      keyPath: /Users/xinity/.ssh/id_rsa_k0s_rock64
    role: worker
  - ssh:
      address: 192.168.2.148
      user: ubuntu
      port: 22
      keyPath: /Users/xinity/.ssh/id_rsa_k0s_rock64
    role: worker
  k0s:
    version: 1.23.1+k0s.0
    config:
      apiVersion: k0s.k0sproject.io/v1beta1
      kind: Cluster
      metadata:
        name: k0s
      spec:
        api:
          k0sApiPort: 9443
          port: 6443
          sans:
          - kubernetes
          - kubernetes.default
          - kubernetes.default.svc
          - kubernetes.default.svc.cluster
          - kubernetes.svc.cluster.local
          - localhost
          - rpi4pico1-node1
          - rpi4pico1-node2
          - rpi4pico1-node3
          - 192.168.2.141
          - 192.168.2.142
          - 192.168.2.143
          - 192.168.2.40
        images:
          calico:
            cni:
              image: docker.io/calico/cni
              version: v3.18.1
            kubecontrollers:
              image: docker.io/calico/kube-controllers
              version: v3.18.1
            node:
              image: docker.io/calico/node
              version: v3.18.1
          coredns:
            image: docker.io/coredns/coredns
            version: 1.7.0
          default_pull_policy: IfNotPresent
          konnectivity:
            image: us.gcr.io/k8s-artifacts-prod/kas-network-proxy/proxy-agent
            version: v0.0.24
          kubeproxy:
            image: k8s.gcr.io/kube-proxy
            version: v1.22.1
          kuberouter:
            cni:
              image: docker.io/cloudnativelabs/kube-router
              version: v1.2.1
            cniInstaller:
              image: quay.io/k0sproject/cni-node
              version: 0.1.0
          metricsserver:
            image: gcr.io/k8s-staging-metrics-server/metrics-server
            version: v0.5.0
        installConfig:
          users:
            etcdUser: etcd
            kineUser: kube-apiserver
            konnectivityUser: konnectivity-server
            kubeAPIserverUser: kube-apiserver
            kubeSchedulerUser: kube-scheduler
        konnectivity:
          adminPort: 8133
          agentPort: 8132
        network:
          kubeProxy:
            disabled: false
            mode: iptables
          kuberouter:
            autoMTU: true
            mtu: 0
            peerRouterASNs: ""
            peerRouterIPs: ""
          podCIDR: 10.244.0.0/16
          provider: kuberouter
          serviceCIDR: 10.96.0.0/12
        podSecurityPolicy:
          defaultPolicy: 00-k0s-privileged
        storage:
          type: etcd
        telemetry:
          enabled: true
```

no logs in journalctl so far
