### ISSUE TITLE
Add token type validation during the join process and fail with explicit message if type non matched

### ISSUE THREAD

**Issue by soider** [k0sproject/k0s#1446]
### Is your feature request related to a problem? Please describe.

I'd love to have explicit fail if I try to join worker with controller token or vice verse

### Describe the solution you would like

Fail with message ```Wrong token type <token type>, expected <node type>```

Now it fails with 403 message.

**Comment by jnummelin** [comment]
A worker token:
```
apiVersion: v1
clusters:
- cluster:
    server: https://172.17.0.2:6443
    certificate-authority-data: LS0...
  name: k0s
contexts:
- context:
    cluster: k0s
    user: kubelet-bootstrap
  name: k0s
current-context: k0s
kind: Config
preferences: {}
users:
- name: kubelet-bootstrap
  user:
    token: bne42c.hfhyfbckkt7xo2da
```
Controller token:
```
apiVersion: v1
clusters:
- cluster:
    server: https://172.17.0.2:9443
    certificate-authority-data: LS0...
  name: k0s
contexts:
- context:
    cluster: k0s
    user: controller-bootstrap
  name: k0s
current-context: k0s
kind: Config
preferences: {}
users:
- name: controller-bootstrap
  user:
    token: qdcx8o.sw3c2kw2wqhdg07r
```

So the only difference we could use to detect the role is the `users[0].name`. On the API side of things, the username is actually irrelevant, API only operates based on the token itself.
