### ISSUE TITLE
"extensions.helm.charts[].name" can't modify.

### ISSUE THREAD

**Issue by chattytak** [k0sproject/k0s#1456]
### Before creating an issue, make sure you've checked the following:

- [X] You are running the latest released version of k0s
- [X] Make sure you've searched for existing issues, both open and closed
- [X] Make sure you've searched for PRs too, a fix might've been merged already
- [X] You're looking at docs for the released version, "main" branch docs are usually ahead of released versions.

### Version

v1.23.1+k0s.1

### Platform

```shell
rocky linux 8.4
```

### What happened?

I modify "extension.helm.charts[].name" section in k0s.yaml.
I think old-name delete and new-name install.
It doesn't really happen.
What if I want to remove the helm?
"/var/lib/k0s/manifests/helm/addon_crd_manifest_ingress-nginx.yaml" wasn't deleted after k0s.yaml modify and commit.
Also, ingress-nginx-internal will not be installed.

before
```
extensions:
  helm:
    charts: 
    - chartname: ingress-nginx/ingress-nginx
      name: ingress-nginx
      namespace: ingress-nginx
      values: |
        controller:
          ingressClassResource:
            default: true
```
after
```
extensions:
  helm:
    charts: 
    - chartname: ingress-nginx/ingress-nginx
      name: ingress-nginx-internal
      namespace: ingress-nginx
      values: |
        controller:
          ingressClassResource:
            default: true
```

### Steps to reproduce

1. Install the helm chart with k0s.yaml.
2. Change the helm name.

### Expected behavior

I think old-name delete and new-name install.

### Actual behavior

Nothing happens. helm will not be updated.

**Comment by soider** [comment]
@chattytak can I ask you to fix identation and use quotes in the config examples? otherwise they are not usable.

**Comment by chattytak** [comment]
> @chattytak can I ask you to fix identation and use quotes in the config examples? otherwise they are not usable.

fixed.

**Comment by chattytak** [comment]
I don't truly understand how k0s saves helm, but I tried uninstalling it from the helm command.
However, it came back again and again.
````
helm uninstall -n ingress-nginx ingress-nginx-XXXXXXXXXXX
```

So, I tried deleting the manifest files, But I didn't know if this meant anything, 
because it didn't seem to disappear from "kubectl get charts -n kube-system".
```
rm /var/lib/k0s/manifests/helm/addon_crd_manifest_ingress-nginx.yaml
```

I had no choice, I tried further, but this did not even return a response.
```
kubectl delete -n kube-system charts k0s-addon-chart-ingress-nginx
```

I tried to learn how to use it from the documentation, but I couldn't even tell if that was a bug or a range of specifications, because there was almost nothing written about the extension of helm in k0s.

But whichever it is, I can't find any way to remove chart once it is installed, and I don't want to be unable to remove it.

**Comment by soider** [comment]
The expected behavior is that once you deleted helm from the config and corresponding chart file from /var/lib/k0s/manifests/helm the chart is going to be uninstalled.

If it doesn't work, this is a bug and needs to be addressed.

**Comment by chattytak** [comment]
I also have a question related to "extensions.helm.charts[].name". 
I thought this name would be the Release Name on the helm, but it is not.
The Release Name is the string obtained by adding Epoch Time to the end of Chart Name.
Intuitively, I feel that this is not what was intended.
There is no point in naming it with "extensions.helm.charts[].name".
There is a slight point of naming the "charts.helm.k0sproject.io" object...

Is it better to raise a separate Issue for this?

**Comment by makhov** [comment]
@chattytak The PR for using `extensions.helm.charts[].name` as a release name has been merged.

**Comment by chattytak** [comment]
I have found out an additional thing.
"extentions.helm.charts[]" has evaluated the order.

For example, let's say the state before editing is as follows.
```
        extensions:
          helm:
            repositories:
            - name: ingress-nginx
              url: https://kubernetes.github.io/ingress-nginx
            charts:
            - name: external-ingress-nginx
              chartname: ingress-nginx/ingress-nginx
              namespace: ingress-nginx
              values: |
                controller:
                  ingressClass: external-nginx
                  ingressClassByName: true
                  ingressClassResource:
                    name: external-nginx  # default: nginx
                    enabled: true
                    default: false
                    controllerValue: "k8s.io/external-ingress-nginx"  # default: k8s.io/ingress-nginx
```

In this case, if you add a new chart to the end, it will be added correctly.
```
        extensions:
          helm:
            repositories:
            - name: ingress-nginx
              url: https://kubernetes.github.io/ingress-nginx
            charts:
            - name: external-ingress-nginx
              chartname: ingress-nginx/ingress-nginx
              namespace: ingress-nginx
              values: |
                controller:
                  ingressClass: external-nginx
                  ingressClassByName: true
                  ingressClassResource:
                    name: external-nginx  # default: nginx
                    enabled: true
                    default: false
                    controllerValue: "k8s.io/external-ingress-nginx"  # default: k8s.io/ingress-nginx
            - name: internal-ingress-nginx
              chartname: ingress-nginx/ingress-nginx
              namespace: ingress-nginx
              values: |
                controller:
                  ingressClass: internal-nginx
                  ingressClassByName: true
                  ingressClassResource:
                    name: internal-nginx  # default: nginx
                    enabled: true
                    default: fa;lse
                    controllerValue: "k8s.io/internal-ingress-nginx"  # default: k8s.io/ingress-nginx
```

However, I noticed that if I insert it in the middle as shown below, the change is not detected correctly.
```
        extensions:
          helm:
            repositories:
            - name: ingress-nginx
              url: https://kubernetes.github.io/ingress-nginx
            charts:
            - name: internal-ingress-nginx
              chartname: ingress-nginx/ingress-nginx
              namespace: ingress-nginx
              values: |
                controller:
                  ingressClass: internal-nginx
                  ingressClassByName: true
                  ingressClassResource:
                    name: internal-nginx  # default: nginx
                    enabled: true
                    default: fa;lse
                    controllerValue: "k8s.io/internal-ingress-nginx"  # default: k8s.io/ingress-nginx
            - name: external-ingress-nginx
              chartname: ingress-nginx/ingress-nginx
              namespace: ingress-nginx
              values: |
                controller:
                  ingressClass: external-nginx
                  ingressClassByName: true
                  ingressClassResource:
                    name: external-nginx  # default: nginx
                    enabled: true
                    default: false
                    controllerValue: "k8s.io/external-ingress-nginx"  # default: k8s.io/ingress-nginx
```

The order should not be evaluated in yaml arrays.
Therefore, I think it is strange that it does not work unless the insertion position is at the end.
