### ISSUE TITLE
Connection refused error when trying to connect to NodePort service

### ISSUE THREAD

**Issue by Ed87** [k0sproject/k0s#1483]
I have deployed a NodePort service as well as the associated deployment but when I attempt to connect to the API running inside the pod I get `Could  not send request`. I am doing this from Postman on another host.

I have also attempted to do a curl on the actual server but I get `"Failed to connect to localhost port 32518: Connection refused"` :

`curl http://localhost:32518/account?field4=3025202645050&field7=GENERIC01&field10=ABC076`

As a check I have ran a command to see if the port is blocked in firewall :

`iptables  -S`

and in the output I can notice where the issue is coming from. Appears traffic is being rejected to the pod :

`-A KUBE-POD-FW-TLU4DFCYW4R6VQRF -m comment --comment "rule to log dropped traffic POD name:flextoeco-depl-67497787-dgq2m namespace: default" -m mark ! --mark 0x10000/0x10000 -m limit --limit 10/min --limit-burst 10 -j NFLOG --nflog-group 100
-A KUBE-POD-FW-TLU4DFCYW4R6VQRF -m comment --comment "rule to REJECT traffic destined for POD name:flextoeco-depl-67497787-dgq2m namespace: default" -m mark ! --mark 0x10000/0x10000 -j REJECT --reject-with icmp-port-unreachable
-A KUBE-POD-FW-NOB4JG276L6ELVOZ -m comment --comment "rule to REJECT traffic destined for POD name:konnectivity-agent-zx42l namespace: kube-system" -m mark ! --mark 0x10000/0x10000 -j REJECT --reject-with icmp-port-unreachable`

Im not quite sure where I should be looking but it appears an issue with either calico or kube-proxy.

My NodePort service (flextoeco-np-svc.yaml) :

```
apiVersion: v1
kind: Service
metadata:
  name: flextoeco-np-svc
spec:
  type: NodePort
  selector:
    app: flextoeco
  ports:
    - name: flextoeco
      protocol: TCP
      port: 80
      targetPort: 80
```

And my deployment (flextoeco-depl.yaml) :
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flextoeco-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flextoeco
  template:
    metadata:
      labels:
        app: flextoeco
    spec:
      containers:
        - name: flextoeco
          image: golide/flextoeco:latest
---
apiVersion: v1
kind: Service
metadata:
  name: flextoeco-clusterip-svc
spec:
  type: ClusterIP
  selector:
    app: flextoeco
  ports:
  - name: flextoeco
    protocol: TCP
    port: 80
    targetPort: 80
```

What am I missing ?
