### ISSUE TITLE
Can't override chart name

### ISSUE THREAD

**Issue by baznikin** [k0sproject/k0s#1488]
### Before creating an issue, make sure you've checked the following:

- [X] You are running the latest released version of k0s
- [X] Make sure you've searched for existing issues, both open and closed
- [X] Make sure you've searched for PRs too, a fix might've been merged already
- [X] You're looking at docs for the released version, "main" branch docs are usually ahead of released versions.

### Version

v1.23.1+k0s.0

### Platform

```shell
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 11 (bullseye)
Release:	11
Codename:	bullseye
```

### What happened?

I can't find way to specify name for Helm chart - it is always deployed with timestamp added to it's name. Because of it service names are unpredictable and manual configuration of other services required.

### Steps to reproduce

k0s.yaml

```
spec:
  extensions:
    storage:
      type: openebs_local_storage
    helm:
      repositories:
      - name: bitnami
        url: https://charts.bitnami.com/bitnami
      charts:
      - name: postgres
        namespace: db
        chartname: bitnami/postgresql
        version: "10.16.2"
        values: |
          image:
            repository: myrepo/postgres_ru
            tag: "11"
          nameOverride: "postgres"
          fullnameOverride: "postgres"
          # https://github.com/bitnami/charts/tree/master/bitnami/postgresql/#deploy-chart-using-docker-official-postgresql-image
          postgresqlDataDir=/data/pgdata
          persistence.mountPath=/data/
          existingSecret: postgres-passwords
```

`/var/lib/k0s/manifests/helm/addon_crd_manifest_postgres.yaml`:

```
apiVersion: helm.k0sproject.io/v1beta1
kind: Chart
metadata:
  name: k0s-addon-chart-postgres
  namespace: "kube-system"
  finalizers:
    - helm.k0sproject.io/uninstall-helm-release 
spec:
  chartName: bitnami/postgresql
  values: |

    image:
      repository: cr.yandex/crpnr7n530cvru3edimp/postgres_ru
      tag: "11"
    nameOverride: "postgres"
    fullnameOverride: "postgres"
    # https://github.com/bitnami/charts/tree/master/bitnami/postgresql/#deploy-chart-using-docker-official-postgresql-image
    postgresqlDataDir=/data/pgdata
    persistence.mountPath=/data/
    existingSecret: postgres-passwords
    
  version: 10.16.2
  namespace: db
```

### Expected behavior

`k0s kubectl -n db get all`:

```
NAME                                     READY   STATUS    RESTARTS   AGE
pod/postgresql-postgresql-0   1/1     Running   0          6m38s

NAME                                     TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)    AGE
service/postgresql            ClusterIP   10.106.243.194   <none>        5432/TCP   6m39s
service/postgresql-headless   ClusterIP   None             <none>        5432/TCP   6m39s

NAME                                                READY   AGE
statefulset.apps/postgresql-postgresql   1/1     6m39s
```

### Actual behavior

`k0s kubectl -n db get all`:

```
NAME                                     READY   STATUS    RESTARTS   AGE
pod/postgresql-1643802624-postgresql-0   1/1     Running   0          6m38s

NAME                                     TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)    AGE
service/postgresql-1643802624            ClusterIP   10.106.243.194   <none>        5432/TCP   6m39s
service/postgresql-1643802624-headless   ClusterIP   None             <none>        5432/TCP   6m39s

NAME                                                READY   AGE
statefulset.apps/postgresql-1643802624-postgresql   1/1     6m39s
```
