### ISSUE TITLE
konnectivity-agent not running on tainted worker nodes

### ISSUE THREAD

**Issue by fbozic** [k0sproject/k0s#1567]
### Before creating an issue, make sure you've checked the following:

- [X] You are running the latest released version of k0s
- [X] Make sure you've searched for existing issues, both open and closed
- [X] Make sure you've searched for PRs too, a fix might've been merged already
- [X] You're looking at docs for the released version, "main" branch docs are usually ahead of released versions.

### Version

1.23.3+k0s.1

### Platform

```shell
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.2 LTS
Release:	20.04
Codename:	focal
```

### What happened?

On newly deployed HA cluster konnectivity-agents are running only on non tainted workes.

### Steps to reproduce

We are running each controller/worker on dedicated VM in VMWare Cloud Director.
We have 3 controller nodes and 5 worker nodes. 2 out of 5 workers nodes are tainted and labeled.
Our setup has 2 load balancers which route traffic to masters on ports 6443, 9443 and 8132.
I have deployed this cluster with k0sctl.
k0sctl version
```
version: v0.12.6
commit: d5f7d66
```

k0sctl yaml
```
apiVersion: k0sctl.k0sproject.io/v1beta1
kind: Cluster
spec:
  hosts:
    - role: controller
      ssh:
        address: 10.22.7.6
        user: ubuntu
        keyPath: /root/.ssh/dev-key
    - role: controller
      ssh:
        address: 10.22.7.11
        user: ubuntu
        keyPath: /root/.ssh/dev-key
    - role: controller
      ssh:
        address: 10.22.7.9
        user: ubuntu
        keyPath: /root/.ssh/dev-key
    - role: worker
      ssh:
        address: 10.22.7.14
        user: ubuntu
        keyPath: /root/.ssh/dev-key
    - role: worker
      ssh:
        address: 10.22.7.13
        user: ubuntu
        keyPath: /root/.ssh/dev-key
    - role: worker
      ssh:
        address: 10.22.7.12
        user: ubuntu
        keyPath: /root/.ssh/dev-key
    - role: worker
      installFlags:
        - --labels="ingress=public"
        - --taints="ingress=public:NoSchedule"
      ssh:
        address: 10.22.7.10
        user: ubuntu
        keyPath: /root/.ssh/dev-key
    - role: worker
      installFlags:
        - --labels="ingress=public"
        - --taints="ingress=public:NoSchedule"
      ssh:
        address: 10.22.7.7
        user: ubuntu
        keyPath: /root/.ssh/dev-key
  k0s:
    version: v1.23.3+k0s.1
    config:
      apiVersion: k0s.k0sproject.io/v1beta1
      kind: Cluster
      metadata:
        name: k0s
      spec:
        api:
          externalAddress: k8s-masters.my-domain.com
          sans:
            - k8s-masters.my-domain.com
```
1. Run k0sctl apply -c k0sctl.yaml

### Expected behavior

konnectivity-agents running on all worker nodes.

### Actual behavior

konnectivity-agents running only on non tainted worker nodes.

### Screenshots and logs

All nodes in cluster
```
root@arbiter-1:/etc/k0sctl# kubectl get no
NAME                   STATUS   ROLES    AGE   VERSION
k8s-ingress-public-1   Ready    <none>   20m   v1.23.3+k0s
k8s-ingress-public-2   Ready    <none>   20m   v1.23.3+k0s
k8s-worker-1           Ready    <none>   20m   v1.23.3+k0s
k8s-worker-2           Ready    <none>   20m   v1.23.3+k0s
k8s-worker-3           Ready    <none>   20m   v1.23.3+k0s
```

Only 3 konnectivity-agents pods running
```
NAMESPACE     NAME                              READY   STATUS    RESTARTS   AGE
kube-system   coredns-8565977d9b-jwlnw          1/1     Running   0          21m
kube-system   coredns-8565977d9b-r9vf9          1/1     Running   0          22m
kube-system   konnectivity-agent-4gsr9          1/1     Running   0          21m
kube-system   konnectivity-agent-gr7w2          1/1     Running   0          21m
kube-system   konnectivity-agent-s4bgs          1/1     Running   0          21m
kube-system   kube-proxy-25jv8                  1/1     Running   0          22m
kube-system   kube-proxy-85spb                  1/1     Running   0          22m
kube-system   kube-proxy-9t5cn                  1/1     Running   0          22m
kube-system   kube-proxy-bh8lq                  1/1     Running   0          22m
kube-system   kube-proxy-crnc6                  1/1     Running   0          22m
kube-system   kube-router-hstgp                 1/1     Running   0          22m
kube-system   kube-router-l7qt8                 1/1     Running   0          22m
kube-system   kube-router-pktr6                 1/1     Running   0          22m
kube-system   kube-router-xb8ck                 1/1     Running   0          22m
kube-system   kube-router-xtql9                 1/1     Running   0          22m
kube-system   metrics-server-74c967d8d4-hjh6x   1/1     Running   0          22m
```

Only k8s-worker-(i) nodes have konnectivity agents running
```
root@arbiter-1:/etc/k0sctl# kubectl get no k8s-worker-1 -o yaml | grep apiserver-network-proxy-agent
    - quay.io/k0sproject/apiserver-network-proxy-agent@sha256:3305618100a721c694a9e0a86dcc163fe5280a32a10c9562b4efeb75f80314e0
    - quay.io/k0sproject/apiserver-network-proxy-agent:0.0.27-k0s2
root@arbiter-1:/etc/k0sctl# kubectl get no k8s-worker-2 -o yaml | grep apiserver-network-proxy-agent
    - quay.io/k0sproject/apiserver-network-proxy-agent@sha256:3305618100a721c694a9e0a86dcc163fe5280a32a10c9562b4efeb75f80314e0
    - quay.io/k0sproject/apiserver-network-proxy-agent:0.0.27-k0s2
root@arbiter-1:/etc/k0sctl# kubectl get no k8s-worker-3 -o yaml | grep apiserver-network-proxy-agent
    - quay.io/k0sproject/apiserver-network-proxy-agent@sha256:3305618100a721c694a9e0a86dcc163fe5280a32a10c9562b4efeb75f80314e0
    - quay.io/k0sproject/apiserver-network-proxy-agent:0.0.27-k0s2
root@arbiter-1:/etc/k0sctl# kubectl get no k8s-ingress-public-1 -o yaml | grep apiserver-network-proxy-agent
root@arbiter-1:/etc/k0sctl# kubectl get no k8s-ingress-public-2 -o yaml | grep apiserver-network-proxy-agent
```

### Additional context

I've deleted cluster, removed labels and taints from worker nodes and than applied cluster again. Now I have 5 konnectivity-agents running. Also not sure if restarts here are okay.
```
root@arbiter-1:/etc/k0sctl# kubectl get po -A
NAMESPACE     NAME                              READY   STATUS    RESTARTS      AGE
kube-system   coredns-8565977d9b-cmpcp          1/1     Running   0             2m6s
kube-system   coredns-8565977d9b-zs8fl          1/1     Running   0             2m32s
kube-system   konnectivity-agent-cff52          1/1     Running   0             99s
kube-system   konnectivity-agent-cz7jk          1/1     Running   1 (34s ago)   99s
kube-system   konnectivity-agent-lj599          1/1     Running   0             119s
kube-system   konnectivity-agent-mnm42          1/1     Running   1 (24s ago)   99s
kube-system   konnectivity-agent-s4twr          1/1     Running   1 (34s ago)   100s
kube-system   kube-proxy-5l8jp                  1/1     Running   0             2m30s
kube-system   kube-proxy-nh26n                  1/1     Running   0             2m30s
kube-system   kube-proxy-pn24t                  1/1     Running   0             2m31s
kube-system   kube-proxy-tvphd                  1/1     Running   0             2m31s
kube-system   kube-proxy-xlwmw                  1/1     Running   0             2m30s
kube-system   kube-router-c8pp7                 1/1     Running   0             2m30s
kube-system   kube-router-hv77j                 1/1     Running   0             2m30s
kube-system   kube-router-rz9qk                 1/1     Running   0             2m31s
kube-system   kube-router-smms6                 1/1     Running   0             2m30s
kube-system   kube-router-trnth                 1/1     Running   0             2m30s
kube-system   metrics-server-74c967d8d4-mr9g5   1/1     Running   0             2m25s
```
