### ISSUE TITLE
Virgin Install, metrics server crash loop.

### ISSUE THREAD

**Issue by Daxcor69** [k0sproject/k0s#1621]
### Before creating an issue, make sure you've checked the following:

- [X] You are running the latest released version of k0s
- [X] Make sure you've searched for existing issues, both open and closed
- [X] Make sure you've searched for PRs too, a fix might've been merged already
- [X] You're looking at docs for the released version, "main" branch docs are usually ahead of released versions.

### Version

v1.23.3+k0s.1

### Platform

```shell
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.4 LTS
Release:        20.04
Codename:       focal
```

### What happened?

I have installed k0s on bare metal servers, using Ubuntu minimal.  The install completes with no errors.  When I issue the command kubectl get nodes, I get the expected results.  The cluster does seem to perform except with the following:

I have configured the Lens kubernetes k8s manager with the kube config and have successfully connected to the cluster.  I get the following error:

![image](https://user-images.githubusercontent.com/61804230/160218622-05e94898-a0ca-4d6c-98c5-c3393aa337e9.png)

Now when I look at the pod details for the desc of the error:

![image](https://user-images.githubusercontent.com/61804230/160218662-82879905-6772-472d-a769-fc0924d6d8c8.png)

![image](https://user-images.githubusercontent.com/61804230/160218687-61ce0b79-79b2-4ae1-986d-3655fe541251.png)

![image](https://user-images.githubusercontent.com/61804230/160218913-a24ae684-e7f7-4513-a750-9b9e55248407.png)

### Steps to reproduce

1.
2.
3.

### Screenshots and logs
Name:                 metrics-server-66c5dcf84f-vgdd7
Namespace:            kube-system
Priority:             2000000000
Priority Class Name:  system-cluster-critical
Node:                 master1/173.201.19.146
Start Time:           Fri, 25 Mar 2022 17:55:32 -0700
Labels:               k8s-app=metrics-server
                      pod-template-hash=66c5dcf84f
Annotations:          kubernetes.io/psp: 00-k0s-privileged
Status:               Running
IP:                   10.244.0.7
IPs:
  IP:           10.244.0.7
Controlled By:  ReplicaSet/metrics-server-66c5dcf84f
Containers:
  metrics-server:
    Container ID:  containerd://6c1e3480e892424825130314f87d31799a98e2d75ce81a08895d49d447e72c6b
    Image:         gcr.io/k8s-staging-metrics-server/metrics-server:v0.5.0
    Image ID:      gcr.io/k8s-staging-metrics-server/metrics-server@sha256:6c5603956c0aed6b4087a8716afce8eb22f664b13162346ee852b4fab305ca15
    Port:          10250/TCP
    Host Port:     0/TCP
    Args:
      --cert-dir=/tmp
      --secure-port=10250
      --kubelet-preferred-address-types=InternalIP,ExternalIP,Hostname
      --kubelet-use-node-status-port
      --metric-resolution=15s
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    2
      Started:      Fri, 25 Mar 2022 18:16:42 -0700
      Finished:     Fri, 25 Mar 2022 18:17:12 -0700
    Ready:          False
    Restart Count:  11
    Requests:
      cpu:        10m
      memory:     30M
    Liveness:     http-get https://:https/livez delay=0s timeout=1s period=10s #success=1 #failure=3
    Readiness:    http-get https://:https/readyz delay=20s timeout=1s period=10s #success=1 #failure=3
    Environment:  <none>
    Mounts:
      /tmp from tmp-dir (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-gmttq (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  tmp-dir:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:
    SizeLimit:  <unset>
  kube-api-access-gmttq:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   Burstable
Node-Selectors:              kubernetes.io/os=linux
Tolerations:                 node-role.kubernetes.io/master:NoSchedule op=Exists
                             node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason     Age                   From               Message
  ----     ------     ----                  ----               -------
  Normal   Scheduled  22m                   default-scheduler  Successfully assigned kube-system/metrics-server-66c5dcf84f-vgdd7 to master1
  Normal   Pulling    22m                   kubelet            Pulling image "gcr.io/k8s-staging-metrics-server/metrics-server:v0.5.0"
  Normal   Pulled     22m                   kubelet            Successfully pulled image "gcr.io/k8s-staging-metrics-server/metrics-server:v0.5.0" in 5.027302161s
  Normal   Killing    21m (x2 over 22m)     kubelet            Container metrics-server failed liveness probe, will be restarted
  Warning  Unhealthy  21m (x4 over 22m)     kubelet            Readiness probe failed: Get "https://10.244.0.7:10250/readyz": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
  Normal   Pulled     21m (x2 over 22m)     kubelet            Container image "gcr.io/k8s-staging-metrics-server/metrics-server:v0.5.0" already present on machine
  Normal   Created    21m (x3 over 22m)     kubelet            Created container metrics-server
  Normal   Started    21m (x3 over 22m)     kubelet            Started container metrics-server
  Warning  Unhealthy  21m                   kubelet            Readiness probe failed: Get "https://10.244.0.7:10250/readyz": dial tcp 10.244.0.7:10250: connect: connection refused
  Warning  Unhealthy  7m51s (x26 over 22m)  kubelet            Liveness probe failed: Get "https://10.244.0.7:10250/livez": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
  Warning  BackOff    2m42s (x76 over 20m)  kubelet            Back-off restarting failed container

### Additional context

Here is the k0sctl config I used to build the cluster
```
apiVersion: k0sctl.k0sproject.io/v1beta1
kind: Cluster
metadata:
  name: production
spec:
  hosts:
    - ssh:
        address: 10.0.0.2
        user: root
        port: 22
        keyPath: /root/.ssh/id_rsa
      role: controller+worker
      privateInterface: eth1
    - ssh:
        address: 10.0.0.3
        user: root
        port: 22
        keyPath: /root/.ssh/id_rsa
      role: worker
      privateInterface: eth1
    - ssh:
        address: 10.0.0.4
        user: root
        port: 22
        keyPath: /root/.ssh/id_rsa
      role: worker
      privateInterface: eth1
  k0s:
    version: 1.23.3+k0s.1
    config:
      apiVersion: k0s.k0sproject.io/v1beta1
      kind: Cluster
      metadata:
        name: k0s
      spec:
        api:
          address: 10.0.0.2
          port: 6443
          k0sApiPort: 9443
          externalAddress: master1.vpc
          sans:
            - 10.0.0.2
        images:
          calico:
            cni:
              image: docker.io/calico/cni
              version: v3.18.1
            kubecontrollers:
              image: docker.io/calico/kube-controllers
              version: v3.18.1
            node:
              image: docker.io/calico/node
              version: v3.18.1
          coredns:
            image: docker.io/coredns/coredns
            version: 1.7.0
          default_pull_policy: IfNotPresent
          konnectivity:
            image: us.gcr.io/k8s-artifacts-prod/kas-network-proxy/proxy-agent
            version: v0.0.24
          kubeproxy:
            image: k8s.gcr.io/kube-proxy
            version: v1.22.1
          kuberouter:
            cni:
              image: docker.io/cloudnativelabs/kube-router
              version: v1.2.1
            cniInstaller:
              image: quay.io/k0sproject/cni-node
              version: 0.1.0
          metricsserver:
            image: gcr.io/k8s-staging-metrics-server/metrics-server
            version: v0.5.0
        installConfig:
          users:
            etcdUser: etcd
            kineUser: kube-apiserver
            konnectivityUser: konnectivity-server
            kubeAPIserverUser: kube-apiserver
            kubeSchedulerUser: kube-scheduler
        konnectivity:
          adminPort: 8133
          agentPort: 8132
        network:
          kubeProxy:
            disabled: false
            mode: iptables
          kuberouter:
            autoMTU: true
            mtu: 0
            peerRouterASNs: ""
            peerRouterIPs: ""
          podCIDR: 10.244.0.0/16
          provider: kuberouter
          serviceCIDR: 10.96.0.0/12
        podSecurityPolicy:
          defaultPolicy: 00-k0s-privileged
        storage:
          type: etcd
        telemetry:
          enabled: true
```
