### ISSUE TITLE
Nodes can't join when using external address (need to add certificate authority)

### ISSUE THREAD

**Issue by bruno-lopes** [k0sproject/k0s#1648]
### Before creating an issue, make sure you've checked the following:

- [X] You are running the latest released version of k0s
- [X] Make sure you've searched for existing issues, both open and closed
- [X] Make sure you've searched for PRs too, a fix might've been merged already
- [X] You're looking at docs for the released version, "main" branch docs are usually ahead of released versions.

### Version

v1.23.5+k0s.0

### Platform

```shell
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.3 LTS
Release:	20.04
Codename:	focal
```

### What happened?

Hello everybody. I'm using the following k0s config with external address set:

```
apiVersion: k0s.k0sproject.io/v1beta1
kind: ClusterConfig
metadata:
  creationTimestamp: null
  name: k0s
spec:
  api:
    externalAddress: <my_domain>.tk
    address: 11.0.1.77
    k0sApiPort: 9443
    port: 6443
    sans:
    - 11.0.1.77
    - <my_domain>
    tunneledNetworkingMode: true
  controllerManager: {}
  extensions:
    helm:
      charts: null
      repositories: null
    storage:
      create_default_storage_class: false
      type: external_storage
  images:
    calico:
      cni:
        image: docker.io/calico/cni
        version: v3.21.2
      kubecontrollers:
        image: docker.io/calico/kube-controllers
        version: v3.21.2
      node:
        image: docker.io/calico/node
        version: v3.21.2
    coredns:
      image: k8s.gcr.io/coredns/coredns
      version: v1.7.0
    default_pull_policy: IfNotPresent
    konnectivity:
      image: quay.io/k0sproject/apiserver-network-proxy-agent
      version: 0.0.30-k0s
    kubeproxy:
      image: k8s.gcr.io/kube-proxy
      version: v1.23.5
    kuberouter:
      cni:
        image: docker.io/cloudnativelabs/kube-router
        version: v1.3.2
      cniInstaller:
        image: quay.io/k0sproject/cni-node
        version: 0.1.0
    metricsserver:
      image: k8s.gcr.io/metrics-server/metrics-server
      version: v0.5.2
  installConfig:
    users:
      etcdUser: etcd
      kineUser: kube-apiserver
      konnectivityUser: konnectivity-server
      kubeAPIserverUser: kube-apiserver
      kubeSchedulerUser: kube-scheduler
  konnectivity:
    adminPort: 8133
    agentPort: 8132
  network:
    calico: null
    dualStack: {}
    kubeProxy:
      mode: iptables
    kuberouter:
      autoMTU: true
      mtu: 0
      peerRouterASNs: ""
      peerRouterIPs: ""
    podCIDR: 10.244.0.0/16
    provider: kuberouter
    serviceCIDR: 10.96.0.0/12
  podSecurityPolicy:
    defaultPolicy: 00-k0s-privileged
  scheduler: {}
  storage:
    etcd:
      externalCluster: null
      peerAddress: 11.0.1.77
    type: etcd
  telemetry:
    enabled: true
status: {}
```
The nodes try to connect in <my_domain>.tk, but they fail with "x509: certificate signed by unknown authority", although it is a valid certificate accepted by major browsers . Then, I found that changing the file `/var/lib/k0s/kubelet-bootstrap.conf` like the following, and creating the file `/var/lib/k0s/server-certificate-authority.crt` with the certificate authority certificates, it does work:

```
apiVersion: v1
clusters:
- cluster:
    server: https://<my_domain>.tk:6443
    #certificate-authority-data: <OLD CERTIFICATE AUTHORITY DATA>
    certificate-authority: server-certificate-authority.crt
  name: k0s
contexts:
- context:
    cluster: k0s
    user: kubelet-bootstrap
  name: k0s
current-context: k0s
kind: Config
preferences: {}
users:
- name: kubelet-bootstrap
  user:
    token: <TOKEN>

```
Is it the right way of doing this? Also, the certificate is accepted by all major browsers. Why isn't it recognized by kubelet?

### Steps to reproduce

1. Create a valid certificate, like in ZeroSSL
2. Configure your cluster, opening the right ports
3. Use an external address that returns the certificate created in step 1
4. Try to join a node in the cluster

### Expected behavior

I would expect that the node would be able to join the cluster, without having to add the certificate authority data.

### Actual behavior

Nodes can't join the cluster, with "x509: certificate signed by unknown authority".
