### ISSUE TITLE
Fresh install issue with some k0s.config.spec.extensions.helm

### ISSUE THREAD

**Issue by fabiorleal** [k0sproject/k0s#1654]
### Before creating an issue, make sure you've checked the following:

- [X] You are running the latest released version of k0s
- [X] Make sure you've searched for existing issues, both open and closed
- [X] Make sure you've searched for PRs too, a fix might've been merged already
- [X] You're looking at docs for the released version, "main" branch docs are usually ahead of released versions.

### Version

v1.23.5+k0s.0

### Platform

```shell
Distributor ID: Ubuntu
Description:    Ubuntu 21.04
Release:        21.04
```

### What happened?

I performed a clean install using k0sctl apply --config k0sctl.yaml and noticed that several releases of helm were not installed.

### Steps to reproduce

1. k0sctl apply --config k0sctl.yaml
2. K0sctl.yaml configured by below
``` yaml
apiVersion: k0sctl.k0sproject.io/v1beta1
kind: Cluster
metadata:
  name: k0s-cluster
spec:
  hosts:
  - ssh:
      address: 10.0.0.201
      user: root
      port: 22
      keyPath: /home/user/.ssh/id_rsa_k0s
    role: controller
  - ssh:
      address: 10.0.0.202
      user: root
      port: 22
      keyPath: /home/user/.ssh/id_rsa_k0s
    role: controller
  - ssh:
      address: 10.0.0.203
      user: root
      port: 22
      keyPath: /home/user/.ssh/id_rsa_k0s
    role: controller        
  - ssh:
      address: 10.0.0.211
      user: root
      port: 22
      keyPath: /home/user/.ssh/id_rsa_k0s
    role: worker
  - ssh:
      address: 10.0.0.212
      user: root
      port: 22
      keyPath: /home/user/.ssh/id_rsa_k0s
    role: worker
  - ssh:
      address: 10.0.0.213
      user: root
      port: 22
      keyPath: /home/user/.ssh/id_rsa_k0s
    role: worker        
  k0s:
    config:
      spec:
        api:
          externalAddress: 10.0.0.200
          sans:
          - 10.0.0.200
        extensions:
          helm:
            repositories:
            - name: nfs-subdir-provisioner
              url: https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner/
            - name: metallb
              url: https://metallb.github.io/metallb
            - name: ingress-nginx
              url: https://kubernetes.github.io/ingress-nginx/
            - name: prometheus-community
              url: https://prometheus-community.github.io/helm-charts
            - name: cert-manager
              url: https://charts.jetstack.io
            - name: openebs-cstor
              url: https://openebs.github.io/cstor-operators
            charts:
            - name: nfsv4-subdir-provisioner
              chartname: nfs-subdir-provisioner/nfs-subdir-external-provisioner
              version: "4.0.16"
              values: |
                nfs:
                  server: 10.0.1.42
                  path: /subdir-ops-nfs
                storageClass:
                  create: true
                  name: subdir-ops-nfsv4 
                  defaultClass: true 
                  provisionerName: cluster.local/nfsv4-subdir-provisioner-nfs-subdir-provisioner          
              namespace: storagenfsv4
            - name: metallb
              chartname: metallb/metallb
              version: "0.12.1"
              values: |
                configInline:
                  address-pools:
                    - name: default
                      protocol: layer2
                      addresses:
                      - 10.0.0.240-10.0.0.241
              namespace: metallb-system
            - name: ingress-nginx
              chartname: ingress-nginx/ingress-nginx
              version: "4.1.0"
              values: |
                controller:
                  ingressClassResource:
                    default: true
              namespace: ingress-nginx
            - name: prometheus
              chartname: prometheus-community/prometheus
              version: "15.8.5"
              values: |
                serviceAccounts:
                  nodeExporter:
                    create: false
                alertmanager:
                  enabled: false
                  ingress:
                    enabled: true
                    ingressClassName: nginx
                  persistentVolume:
                    storageClass: subdir-ops-nfsv4
                  statefulSet:
                    enabled: true
                nodeExporter:
                  enabled: false
                server:
                  persistentVolume:
                    storageClass: subdir-ops-nfsv4
                  statefulSet:
                    enabled: true  
                  service:
                    nodePort: 30909
                    type: NodePort                  
              namespace: monitoring
            - name: node-exporter
              chartname: prometheus-community/prometheus-node-exporter
              version: "3.1.1"
              values:
              namespace: monitoring
            - name: kube-state-metrics
              chartname: prometheus-community/kube-state-metrics
              version: "4.7.0"
              values:
              namespace: monitoring
            - name: cert-manager
              chartname: cert-manager/cert-manager
              version: "1.8.0"
              values: |
                installCRDs: true
              namespace: cert-manager
            - name: openebs-cstor
              chartname: openebs-cstor/cstor
              version: "3.1.0"
              values: |
                csiNode:
                  kubeletDir: /var/lib/k0s/kubelet/
              namespace: openebs          
    version: 1.23.5+k0s.0
```

### Expected behavior

Install all helm release indicated on file k0sctl.yaml

### Actual behavior

Only installed the following helms:
- cert-manager
- ingress-nginx
- nfs-subdir-external

### Screenshots and logs

Namespaces:
![image](https://user-images.githubusercontent.com/96831219/164952569-070a8abd-486e-4dcf-a1a3-42f6c4948d06.png)

Pods:
![image](https://user-images.githubusercontent.com/96831219/164952592-766ca75f-1611-4b18-909d-1ecda7778fbe.png)

Helm Releases:
![image](https://user-images.githubusercontent.com/96831219/164952602-0aa1b334-b666-45e1-9280-69eaaac5e020.png)

### Additional context

In the file /etc/k0s/k0s.yaml all releases and charts are registered, but the installation did not take place
k0s.yaml from one of the controller:
``` yaml
# generated-by-k0sctl 2022-04-23T22:51:40-03:00
apiVersion: k0s.k0sproject.io/v1beta1
kind: ClusterConfig
spec:
  api:
    address: 10.0.0.201
    externalAddress: 10.0.0.200
    sans:
    - 10.0.0.201
    - 10.0.0.200
    - 10.0.0.202
    - 10.0.0.203
    - 127.0.0.1
  extensions:
    helm:
      charts:
      - chartname: nfs-subdir-provisioner/nfs-subdir-external-provisioner
        name: nfsv4-subdir-provisioner
        namespace: storagenfsv4
        values: "nfs:\n  server: 10.0.1.42\n  path: /subdir-ops-nfs\nstorageClass:\n
          \ create: true\n  name: subdir-ops-nfsv4 \n  defaultClass: true \n  provisionerName:
          cluster.local/nfsv4-subdir-provisioner-nfs-subdir-provisioner          \n"
        version: 4.0.16
      - chartname: metallb/metallb
        name: metallb
        namespace: metallb-system
        values: |
          configInline:
            address-pools:
              - name: default
                protocol: layer2
                addresses:
                - 10.0.0.240-10.0.0.241
        version: 0.12.1
      - chartname: ingress-nginx/ingress-nginx
        name: ingress-nginx
        namespace: ingress-nginx
        values: |
          controller:
            ingressClassResource:
              default: true
        version: 4.1.0
      - chartname: prometheus-community/prometheus
        name: prometheus
        namespace: monitoring
        values: "serviceAccounts:\n  nodeExporter:\n    create: false\nalertmanager:\n
          \ enabled: false\n  ingress:\n    enabled: true\n    ingressClassName: nginx\n
          \ persistentVolume:\n    storageClass: subdir-ops-nfsv4\n  statefulSet:\n
          \   enabled: true\nnodeExporter:\n  enabled: false\nserver:\n  persistentVolume:\n
          \   storageClass: subdir-ops-nfsv4\n  statefulSet:\n    enabled: true  \n
          \ service:\n    nodePort: 30909\n    type: NodePort                  \n"
        version: 15.8.5
      - chartname: prometheus-community/prometheus-node-exporter
        name: node-exporter
        namespace: monitoring
        values: null
        version: 3.1.1
      - chartname: prometheus-community/kube-state-metrics
        name: kube-state-metrics
        namespace: monitoring
        values: null
        version: 4.7.0
      - chartname: cert-manager/cert-manager
        name: cert-manager
        namespace: cert-manager
        values: |
          installCRDs: true
        version: 1.8.0
      - chartname: openebs-cstor/cstor
        name: openebs-cstor
        namespace: openebs
        values: |
          csiNode:
            kubeletDir: /var/lib/k0s/kubelet/
        version: 3.1.0
      repositories:
      - name: nfs-subdir-provisioner
        url: https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner/
      - name: metallb
        url: https://metallb.github.io/metallb
      - name: ingress-nginx
        url: https://kubernetes.github.io/ingress-nginx/
      - name: prometheus-community
        url: https://prometheus-community.github.io/helm-charts
      - name: cert-manager
        url: https://charts.jetstack.io
      - name: openebs-cstor
        url: https://openebs.github.io/cstor-operators
