### ISSUE TITLE
Issues with K0s konnectivity - affected: logs, metrics, connectivity

### ISSUE THREAD

**Issue by krzwiatrzyk** [k0sproject/k0s#1669]
### Before creating an issue, make sure you've checked the following:

- [X] You are running the latest released version of k0s
- [X] Make sure you've searched for existing issues, both open and closed
- [X] Make sure you've searched for PRs too, a fix might've been merged already
- [X] You're looking at docs for the released version, "main" branch docs are usually ahead of released versions.

### Version

1.21.11+k0s.0 and 1.2.11+k0s.0

### Platform

```shell
cat `/etc/os-release`
NAME="Oracle Linux Server"
VERSION="8.3"
ID="ol"
ID_LIKE="fedora"
VARIANT="Server"
VARIANT_ID="server"
VERSION_ID="8.3"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Oracle Linux Server 8.3"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:oracle:linux:8:3:server"
HOME_URL="https://linux.oracle.com/"
BUG_REPORT_URL="https://bugzilla.oracle.com/"

ORACLE_BUGZILLA_PRODUCT="Oracle Linux 8"
ORACLE_BUGZILLA_PRODUCT_VERSION=8.3
ORACLE_SUPPORT_PRODUCT="Oracle Linux"
ORACLE_SUPPORT_PRODUCT_VERSION=8.3
```

### What happened?

Few issues:
- some commands run slow, some commands fast,  I believe  it may be related to konnectivity and HA: https://github.com/k0sproject/k0s/issues/1113 
- metrics are visible only for one node, see below
```
❯ kubectl top nodes
NAME                                      CPU(cores)   CPU%   MEMORY(bytes)   MEMORY%     
worker-4137e3b66a6d14ad   53m          0%     461Mi           0%          
worker-674ff7ce0baa1a46   <unknown>                           <unknown>               <unknown>               <unknown>               
worker-c20b8f9e02729078   <unknown>                           <unknown>               <unknown>               <unknown>               
worker-c7912512a8df0112   <unknown>                           <unknown>               <unknown>               <unknown>                             
worker-4828a278dc60d793   <unknown>                           <unknown>               <unknown>               <unknown> 
```
logs:
```
E0429 11:31:08.750886       1 scraper.go:139] "Failed to scrape node" err="Get \"https://192.168.0.154:10250/stats/summary?only_cpu_and_memory=true\": dial tcp 192.168.0.154:10250: i/o timeout" node="worker-c7912512a8df0112"
```
- kubectl logs often fails with `timeout i/o` for kubelet's port 10250
```
│ stream logs failed Get "https://192.168.0.244:10250/containerLogs/kube-system/konnectivity-agent-lcz76/konnectivity-agent?follow=true&tailLines=100&timestamps=true": dial tcp 192.168.0.244:10250: i/o timeout for  │
│ kube-system/konnectivity-agent-lcz76 (konnectivity-agent)
```
- CoreDNS errors (I can obtain logs from only one instance of CoreDNS...):
```
│ E0429 10:50:38.780106       1 reflector.go:382] pkg/mod/k8s.io/client-go@v0.18.3/tools/cache/reflector.go:125: Failed to watch *v1.Namespace: Get "https://10.96.0.1:443/api/v1/namespaces?allowWatchBookmarks=true& │
│ resourceVersion=198&timeout=6m27s&timeoutSeconds=387&watch=true": dial tcp 10.96.0.1:443: connect: connection refused                                                                                                │
│ E0429 10:50:38.781008       1 reflector.go:382] pkg/mod/k8s.io/client-go@v0.18.3/tools/cache/reflector.go:125: Failed to watch *v1.Endpoints: Get "https://10.96.0.1:443/api/v1/endpoints?allowWatchBookmarks=true&r │
│ esourceVersion=1084&timeout=8m23s&timeoutSeconds=503&watch=true": dial tcp 10.96.0.1:443: connect: connection refused 
```

### Steps to reproduce

1. Use my k0sctl config file
```
apiVersion: k0sctl.k0sproject.io/v1beta1
kind: Cluster
spec:
  hosts:
    - role: controller
      ssh:
        address: 192.168.0.150
        user: cloud-user
        keyPath: ./ssh_key
        bastion:
          address: 10.155.22.63
          user: centos
          keyPath: ./ssh_key
    - role: worker
      ssh:
        address: 192.168.0.8
        user: cloud-user
        keyPath: ./ssh_key
        bastion:
          address: 10.155.22.63
          user: centos
          keyPath: ./ssh_key
    - role: worker
      ssh:
        address: 192.168.0.199
        user: cloud-user
        keyPath: ./ssh_key
        bastion:
          address: 10.155.22.63
          user: centos
          keyPath: ./ssh_key
    - role: worker
      ssh:
        address: 192.168.0.154
        user: cloud-user
        keyPath: ./ssh_key
        bastion:
          address: 10.155.22.63
          user: centos
          keyPath: ./ssh_key
    - role: worker
      ssh:
        address: 192.168.0.51
        user: cloud-user
        keyPath: ./ssh_key
        bastion:
          address: 10.155.22.63
          user: centos
          keyPath: ./ssh_key
    - role: worker
      ssh:
        address: 192.168.0.9
        user: cloud-user
        keyPath: ./ssh_key
        bastion:
          address: 10.155.22.63
          user: centos
          keyPath: ./ssh_key
    - role: worker
      ssh:
        address: 192.168.0.171
        user: cloud-user
        keyPath: ./ssh_key
        bastion:
          address: 10.155.22.63
          user: centos
          keyPath: ./ssh_key
    - role: worker
      ssh:
        address: 192.168.0.244
        user: cloud-user
        keyPath: ./ssh_key
        bastion:
          address: 10.155.22.63
          user: centos
          keyPath: ./ssh_key
  k0s:
    version: 1.21.11+k0s.0
    config:
      apiVersion: k0s.k0sproject.io/v1beta1
      kind: Cluster
      metadata:
        name: k0s
      spec:
        api:
          k0sApiPort: 9443
          port: 6443
          sans:
          - 10.155.24.25
          externalAddress: 10.155.24.25
```

### Expected behavior

Everything works.

### Additional context

I have checked following things:
- run `yum update -y` and again installed cluster
- installed cluster with different versions (1.21.11, 1.23.6, 1.20.6)
- changed **machine-id** on each host to be unique
- checked if ports aren't blocked (inter-cluster communiation is allowed)
- LoadBalancer is setup according to documentation

`k0sctl` config:
```

**Comment by krzwiatrzyk** [comment]
FYI: I have also checked installation with only one controller, the result is the same

**Comment by SnJForever** [comment]
I have the same problem.I ignore it, but there was no way to read the log when I was using Rancher.  Just now, I reinstalled it, and it was the same problem.

**Comment by soider** [comment]
@krzwiatrzyk may I ask you for the k0scontroller logs and for the konnectivity-agent pod logs? the pod logs are under the /var/lib/containers on the machine which runs kubelet.

**Comment by jnummelin** [comment]
```
dial tcp 10.96.0.1:443: connect: connection refused
```

kinda hints that kube-proxy might have some issues setting up the in-cluster API service. Check also kube-proxy logs, if you cannot get them via `kubectl logs ...`, then SSH into one of the workers and check `/var/log/containers/...`

**Comment by krzwiatrzyk** [comment]
Logs (from HA installation according to config provided above, if you want from single cluster instalataion let me know)

`kube-proxy` logs from one of the workers:
```
W0504 07:35:40.628620       1 proxier.go:669] Failed to load kernel module nf_conntrack_ipv4 with modprobe. You can ignore this message when kube-proxy is running inside container without mounting /lib/modules
I0504 07:35:40.671755       1 node.go:172] Successfully retrieved node IP: 192.168.0.171
I0504 07:35:40.671836       1 server_others.go:140] Detected node IP 192.168.0.171
I0504 07:35:40.732043       1 server_others.go:206] kube-proxy running in dual-stack mode, IPv4-primary
I0504 07:35:40.732093       1 server_others.go:212] Using iptables Proxier.
I0504 07:35:40.732112       1 server_others.go:219] creating dualStackProxier for iptables.
W0504 07:35:40.732144       1 server_others.go:495] detect-local-mode set to ClusterCIDR, but no IPv6 cluster CIDR defined, , defaulting to no-op detect-local for IPv6
I0504 07:35:40.732861       1 server.go:647] Version: v1.21.11
I0504 07:35:40.733824       1 config.go:315] Starting service config controller
I0504 07:35:40.733845       1 shared_informer.go:240] Waiting for caches to sync for service config
I0504 07:35:40.733862       1 config.go:224] Starting endpoint slice config controller
I0504 07:35:40.733880       1 shared_informer.go:240] Waiting for caches to sync for endpoint slice config
W0504 07:35:40.742205       1 warnings.go:70] discovery.k8s.io/v1beta1 EndpointSlice is deprecated in v1.21+, unavailable in v1.25+; use discovery.k8s.io/v1 EndpointSlice
W0504 07:35:40.744580       1 warnings.go:70] discovery.k8s.io/v1beta1 EndpointSlice is deprecated in v1.21+, unavailable in v1.25+; use discovery.k8s.io/v1 EndpointSlice
I0504 07:35:40.834269       1 shared_informer.go:247] Caches are synced for service config 
I0504 07:35:40.834327       1 shared_informer.go:247] Caches are synced for endpoint slice config 
```

Logs from one of the k0scontrollers: https://drive.google.com/file/d/1DPp12k6p2elFx9rdctlr52jwmwZ-jfV2/view?usp=sharing 
Logs from one of the konnectivity-agents: https://drive.google.com/file/d/1VCAhMgSyVnXsSc0sX4y5w5xY6OMvyXtz/view?usp=sharing


I am curious if this issue is caused by  OS I am running it on (Oracle Linux 8.5). In another installation, we are using Centos Streams 8 and I am not seeing such problems. 
@SnJForever which OS are you running your K0s cluster on?

**Comment by krzwiatrzyk** [comment]
After some test performed in https://github.com/krzwiatrzyk/k0s-vagrant/tree/k0s-issue/1669 i believe that issue is related to OS distribution (Oracle Linux 8.5).

For Centos Streams 8 no problems were visible:
- fast `kubectl` responses
- ability to exec into pods
- ability to get logs
- metrics visible for all nodes

**Comment by ftong2020** [comment]
My experience with K0S on centos stream 8 is that, SELinux is on by default ,so is the firewall, and these 2 brothers have very strict default, which mess up a lot of things. The kube-state-metric with complain host machine is not reachable, and process in pod will not be able to query dns record outside the cluster(google.com, etc).

And I do notice k0s have some glitches with configurations, too. If I do not set CNI explicitly, sometimes it will bring up Calico instead of kuberouter for no reason. I can not reproduce this issue in a reliable way, but it does happen every now and then. Same configuration file used in Docker/Ubuntu/CentOs might also yield different result.

**Comment by jnummelin** [comment]
@krzwiatrzyk in the core maintainers group, none of us is using Oracle Linux unfortunately thus hasn't been really tested.

```
dial tcp 10.96.0.1:443: connect: connection refused
```

I'm still in the suspect that for one reason or another, kube-proxy has not been able to create the SVC VIP iptable rules properly, or some FW or something is blocking the connections. kube-proxy logs do look clean (i.e. no errors on setting up the rules) so have you checked there's no FW blocking anything?

I'll try out your Vagrant setup to see if I can find something, thanks for sharing that.

**Comment by krzwiatrzyk** [comment]
Firewall was disabled, only Selinux was on but I'm not aware if that should impact anything?

**Comment by jnummelin** [comment]
@krzwiatrzyk I tried out your [Vagrant setup](https://github.com/krzwiatrzyk/k0s-vagrant/tree/k0s-issue/1669) and got everything to work properly. I did have to do some tweaks:
```
- role: worker
      privateInterface: eth1
      ssh:
        address: 192.168.56.103
        user: vagrant
        keyPath: /Users/jussi/.vagrant.d/insecure_private_key
      installFlags:
        - --kubelet-extra-args="--node-ip=192.168.56.103"
```
So we need to force kubelet to pick up the 192.168... address as otherwise it'll pick up the vbox NAT interface address which is SAME for all nodes. That'll break konnectivity "routing" and you'll hit some weird issues for sure.

Kubelet picking up the "wrong" IP manifests itself like this:
```
[root@machine1 ~]# k0s kc get node -o wide
NAME       STATUS   ROLES    AGE    VERSION       INTERNAL-IP   EXTERNAL-IP   OS-IMAGE                  KERNEL-VERSION                      CONTAINER-RUNTIME
machine2   Ready    <none>   120m   v1.23.6+k0s   10.0.2.15     <none>        Oracle Linux Server 8.5   5.4.17-2136.301.1.4.el8uek.x86_64   containerd://1.5.11
machine3   Ready    <none>   120m   v1.23.6+k0s   10.0.2.15     <none>        Oracle Linux Server 8.5   5.4.17-2136.301.1.4.el8uek.x86_64   containerd://1.5.11
```
