### ISSUE TITLE
Kubernetes serviceaccount authentication not working on long lived cluster

### ISSUE THREAD

**Issue by adamlamar** [k0sproject/k0s#1705]
### Before creating an issue, make sure you've checked the following:

- [X] You are running the latest released version of k0s
- [X] Make sure you've searched for existing issues, both open and closed
- [X] Make sure you've searched for PRs too, a fix might've been merged already
- [X] You're looking at docs for the released version, "main" branch docs are usually ahead of released versions.

### Version

v1.23.1+k0s.0

### Platform

```shell
# lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 21.10
Release:	21.10
Codename:	impish
```

Running on a raspberry pi 4b.

### What happened?

On a fresh cluster single node cluster, kubernetes serviceaccount authentication within pods works as expected. The following receives a valid json response from the kubeapi:

```
kubectl exec -ti <pod> -- /bin/bash

TOKEN=$(cat /var/run/secrets/kubernetes.io/serviceaccount/token)
CACERT=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt

curl --cacert $CACERT -H "Authorization: Bearer $TOKEN" https://kubernetes.default/api/v1/namespaces/default
```

On my cluster that is 126 days old, with one controller+worker and one worker, I'm unable to connect to the kubeapi using the same commands:

```
kubectl exec -ti <pod> -- /bin/bash

# curl --cacert $CACERT -H "Authorization: Bearer $TOKEN" https://10.96.0.1/api/v1/namespaces/default
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
```

Other services appear to have a similar problem:

openebs-localpv:
```
Cannot start Provisioner: failed to get Kubernetes server version: Get "https://10.96.0.1:443/version?timeout=32s": x509: certificate signed by unknown authority (possibly because of "crypto/rsa: verification error" while trying to verify candidate authority certificate "kubernetes-ca")
```

metrics-server:
```
panic: unable to load configmap based request-header-client-ca-file: Get "https://10.96.0.1:443/api/v1/namespaces/kube-system/configmaps/extension-apiserver-authentication": x509: certificate signed by unknown authority (possibly because of "crypto/rsa: verification error" while trying to verify candidate authority certificate "kubernetes-ca")
```

Restarting the pod does not resolve the problem.

### Steps to reproduce

1. Run a cluster for a long time (time unknown)
2. Reboot the controller+worker node
3. See that all services using serviceaccount authentication are unable to authenticate

### Expected behavior

Kubernetes serviceaccount authentication should continue to work.

### Actual behavior

Kubernetes serviceaccount authentication does not work.

### Additional context

Initially when I ran into this problem, I rebooted the system a few times with no change. At that time, I didn't capture the error message, but the `curl` command was failing with `invalid token`, not the TLS error I see now. The CA certificate chain was validating at that time.

I left the system in a bad state for about a week, and the problem changed to the `unknown certificate authority` error.

Then while writing up this bug report, I rebooted the controller+worker, and serviceaccount authentication began working again.

**Comment by jnummelin** [comment]
That is quite weird behaviour, especially the part where a reboot fixed everything. And that makes it also very hard to debug.

Let's look at the timestamps of the certs, could you dump the following output: `ls -lah /var/lib/k0s/pki/`. That'll show us if and when the PKI files have been changed.

You can also dive deeper into the individual certs with e.g.:
```
openssl x509 -in /var/lib/k0s/pki/ca.crt -text -noout
```

On k0s service restart, k0s re-creates all the SERVING certs, but of course the CA and SA keys are preserved.

The only _hunch_ we got was that maybe at some point the system time was off (AFAIK rasperries do not have any HW clock) and that might've screwed up the cert validation and/or SA tokens.

**Comment by jnummelin** [comment]
What details do you see with `kubectl get svc,ep kubernetes`. kube-proxy should automatically "re-sync" the iptables rules based on the service endpoint for the kubernetes API service. Kinda looks like that is out-of-sync for some reason. For the svc endpoints you _should_ see only rp1 and rp3 addresses. What config have you given for k0s itself?

> I deleted with `kubectl delete node rp2`

That gets rid of the node object, but that does NOT remove the node from controlplane cluster (etcd). You probably still see rp2 as part of the etcd cluster, you can check with `k0s etcd member-list`. Also worth of mentioning, with etcd 2 nodes are as bad as one node as etcd is quorum based... 😄

**Comment by adamlamar** [comment]
Here's the k0sctl config:

```
apiVersion: k0sctl.k0sproject.io/v1beta1
kind: Cluster
metadata:
  name: datacore
spec:
  hosts:
  - role: controller+worker
    ssh:
      address: 192.168.1.20
      user: ubuntu
      keyPath: ~/.ssh/id_rsa
    installFlags:
      - --disable-components konnectivity-server
  - role: controller+worker
    ssh:
      address: 192.168.1.21
      user: ubuntu
      keyPath: ~/.ssh/id_rsa
    installFlags:
      - --disable-components konnectivity-server
  - role: controller+worker
    ssh:
      address: 192.168.1.22
      user: ubuntu
      keyPath: ~/.ssh/id_rsa
    installFlags:
      - --disable-components konnectivity-server
```

And the svc output (same from both rp1 and rp3):
```
# kubectl get svc,ep kubernetes
NAME                 TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)   AGE
service/kubernetes   ClusterIP   10.96.0.1    <none>        443/TCP   129d

NAME                   ENDPOINTS                             AGE
endpoints/kubernetes   192.168.1.20:6443,192.168.1.22:6443   129d
```
I'm not sure why rp3's iptables rules still use rp2's IP.

Yes that's understood about the etcd quorum failure semantics. Is there documentation on joining another controller node in place of rp2?
