### ISSUE TITLE
The default config from k0s create config is not suitable for single node

### ISSUE THREAD

**Issue by kke** [k0sproject/k0s#1707]
### Is your feature request related to a problem? Please describe.

`k0s config create` will create a config which has `etcd` as storage. That's not the default config for a controller with `--single`.

### Describe the solution you would like

Maybe it could have a flag? 

### Describe alternatives you've considered

This comes up mainly as a problem in k0sctl, so k0sctl should probably take care of it internally.

**Comment by jnummelin** [comment]
It might be that giving a partial config and also `--single` might break the single option properly propagating into all places

**Comment by 1player** [comment]
Any update? k0s single-node clusters created with k0sctl are at the moment broken because of this issue.

**Comment by jnummelin** [comment]
> k0s single-node clusters created with k0sctl are at the moment broken because of this issue.

hmm, I think you should be able to workaround this by pushing a `spec.k0s.config` in `k0sctl.yaml` which specifies kine instead of etcd as the storage. So something like this:
```
apiVersion: k0sctl.k0sproject.io/v1beta1
kind: Cluster
spec:
  hosts:
    - role: single
      privateInterface: eth1
      ssh:
        address: 192.168.56.101
        user: vagrant
        keyPath: /Users/jussi/.vagrant.d/insecure_private_key
  k0s:
    version: 1.23.6+k0s.1
    config:
      apiVersion: k0s.k0sproject.io/v1beta1
      kind: Cluster
      metadata:
        name: k0s
      spec:
        storage:
          type: kine
```
