### ISSUE TITLE
K0s error with proxy - "http: no such host"

### ISSUE THREAD

**Issue by krzwiatrzyk** [k0sproject/k0s#1889]
### Before creating an issue, make sure you've checked the following:

- [X] You are running the latest released version of k0s
- [X] Make sure you've searched for existing issues, both open and closed
- [X] Make sure you've searched for PRs too, a fix might've been merged already
- [X] You're looking at docs for the released version, "main" branch docs are usually ahead of released versions.

### Version

1.21.13+k0s.1

### Platform

```shell
CentOS Linux release 7.7.1908 (Core)
```

### What happened?

While bringing cluster behind proxy, connection between master and worker nodes can't be established:

```
cze 29 11:56:31 worker1 k0s[4130]: time="2022-06-29 11:56:31" level=warning msg="failed to get initial kubelet config with join token: failed to get kubelet config from API: Get \"https://192.168.0.157:6443/api/v1/namespaces/kube-system/configmaps/kubelet-config-default-1.21\": proxyconnect tcp: dial tcp: lookup \"http: no such host
```

Proxy is set correctly, because access to the internet can be achievied:
```
[centos@worker-1 ~]$ curl google.com

<HTML><HEAD><meta http-equiv="content-type" content="text/html;charset=utf-8">

<TITLE>301 Moved</TITLE></HEAD><BODY>

<H1>301 Moved</H1>

The document has moved

<A HREF="http://www.google.com/">here</A>.

</BODY></HTML>
```

as well to the master node with private IP:
```
[centos@worker-1 ~]$ curl -k https://192.168.0.157:6443

{

  "kind": "Status",

  "apiVersion": "v1",

  "metadata": {

    

  },

  "status": "Failure",

  "message": "Unauthorized",

  "reason": "Unauthorized",

  "code": 401

}
```

Proxy is set in following way:
```
apiVersion: k0sctl.k0sproject.io/v1beta1
kind: Cluster
spec:
  hosts:
    - role: controller+worker
      ssh:
        address: 10.232.24.221
        user: centos
        keyPath: /tmp/id_rsa
      environment:
        HTTP_PROXY: http://193.201.136.51:8080
        HTTPS_PROXY: http://193.201.136.51:8080
        NO_PROXY: localhost,127.0.0.1,.cluster.local,.svc,192.168.0.13,192.168.0.164,192.168.0.46,192.168.0.247,192.168.0.157
        http_proxy: http://193.201.136.51:8080
        https_proxy: http://193.201.136.51:8080
        no_proxy: localhost,127.0.0.1,.cluster.local,.svc,192.168.0.13,192.168.0.164,192.168.0.46,192.168.0.247,192.168.0.157
    
    - role: worker
      ssh:
        address: 10.232.27.19
        user: centos
        keyPath: /tmp/id_rsa
      environment:
        HTTP_PROXY: http://193.201.136.51:8080
        HTTPS_PROXY: http://193.201.136.51:8080
        NO_PROXY: localhost,127.0.0.1,.cluster.local,.svc,192.168.0.13,192.168.0.164,192.168.0.46,192.168.0.247,192.168.0.157
        http_proxy: http://193.201.136.51:8080
        https_proxy: http://193.201.136.51:8080
        no_proxy: localhost,127.0.0.1,.cluster.local,.svc,192.168.0.13,192.168.0.164,192.168.0.46,192.168.0.247,192.168.0.157
    
    - role: worker
      ssh:
        address: 10.232.26.125
        user: centos
        keyPath: /tmp/id_rsa
      environment:
        HTTP_PROXY: http://193.201.136.51:8080
        HTTPS_PROXY: http://193.201.136.51:8080
        NO_PROXY: localhost,127.0.0.1,.cluster.local,.svc,192.168.0.13,192.168.0.164,192.168.0.46,192.168.0.247,192.168.0.157
        http_proxy: http://193.201.136.51:8080
        https_proxy: http://193.201.136.51:8080
        no_proxy: localhost,127.0.0.1,.cluster.local,.svc,192.168.0.13,192.168.0.164,192.168.0.46,192.168.0.247,192.168.0.157
    
    - role: worker
      ssh:
        address: 10.232.25.221
        user: centos
        keyPath: /tmp/id_rsa
      environment:
        HTTP_PROXY: http://193.201.136.51:8080
        HTTPS_PROXY: http://193.201.136.51:8080
        NO_PROXY: localhost,127.0.0.1,.cluster.local,.svc,192.168.0.0/24
        http_proxy: http://193.201.136.51:8080
        https_proxy: http://193.201.136.51:8080
        no_proxy: localhost,127.0.0.1,.cluster.local,.svc,192.168.0.0/24

  k0s:
    version: 1.21.13+k0s.1
    config:
      apiVersion: k0s.k0sproject.io/v1beta1
      kind: Cluster
      metadata:
        name: k0s
      spec:
        telemetry:
          enabled: false
```

### Steps to reproduce

1. Isolated environment with no access to the internet
2. Creating proxy server
3. Apply my configuration

### Expected behavior

Clsuter created successfuly

### Actual behavior

Cluster not created
