### ISSUE TITLE
how to airgap install k0s single node with bundle image like "k0s-airgap-bundle-v1.24.2+k0s.0-amd64"?

### ISSUE THREAD

**Issue by m2acgi** [k0sproject/k0s#1944]
### Is your feature request related to a problem? Please describe.

how to airgap install k0s single node with bundle image like "k0s-airgap-bundle-v1.24.2+k0s.0-amd64"?

**Comment by jsalgado78** [comment]
I use a yaml file like this running k0sctl to install k0s:

```
apiVersion: k0sctl.k0sproject.io/v1beta1
kind: Cluster
metadata:
  name: k0s-des
spec:
  hosts:
  - ssh:
      address: myserver
      user: root
      port: 22
    role: controller+worker
    uploadBinary: true
    k0sBinaryPath: ./k0s-v1.24.2+k0s.0-amd64
    files:
      - name: bundle-file
        src: ./k0s-airgap-bundle-v1.24.2+k0s.0-amd64
        dstDir: /var/lib/k0s/images/
        perm: 0755
  k0s:
    version: v1.24.2+k0s.0
    config:
      apiVersion: k0s.k0sproject.io/v1beta1
      kind: Cluster
      metadata:
        name: k0s
      spec:
        images:
          default_pull_policy: Never
        telemetry:
          enabled: false
```
