### ISSUE TITLE
k0sctl cluster does not re-add node if it was reset

### ISSUE THREAD

**Issue by pagalba-com** [k0sproject/k0s#1996]
Hi,

tried to create new cluster wit this config:
```
apiVersion: k0sctl.k0sproject.io/v1beta1
kind: Cluster
metadata:
  name: k0s-cluster
spec:
  hosts:
  - ssh:
      address: 192.168.1.3
    role: controller+worker
    noTaints: true
    installFlags:
    - --debug
    uploadBinary: true
    privateInterface: br0
  - ssh:
      address: 192.168.1.4
    role: controller+worker
    noTaints: true
    installFlags:
    - --debug
    uploadBinary: true
    privateInterface: br0
  - ssh:
      address: 192.168.1.2
    role: controller+worker
    noTaints: true
    installFlags:
    - --debug
    uploadBinary: true
    privateInterface: br0
  k0s:
    version: v1.24.2+k0s.0
    dynamicConfig: false
    config:
      kind: Cluster
      metadata:
        name: k0s-cluster
      spec:
        api:
          externalAddress: 192.168.1.111
          sans:
          - 192.168.1.111
```
and it creates ok, get nodes shows all nodes in Ready state.
```
kubectl get node
NAME      STATUS     ROLES           AGE   VERSION
n1   Ready      control-plane   10h   v1.24.2+k0s
n2   Ready      control-plane   10h   v1.24.2+k0s
n3   Ready      control-plane   10h   v1.24.2+k0s
```
But if I reset one node (locally run k0s reset), and then try to k0sctl apply this config, it reinstalls the node, but it never gies to ready state.
Also tried to remove node from kube cluster, then it just not appears again.
```
kubectl get node
NAME      STATUS     ROLES           AGE   VERSION
n1   NotReady   control-plane   10h   v1.24.2+k0s
n2   Ready      control-plane   10h   v1.24.2+k0s
n3   Ready      control-plane   10h   v1.24.2+k0s
```
The install log shows no issues.
