### ISSUE TITLE
Both Calico and Kuberouter are running

### ISSUE THREAD

**Issue by dza89** [k0sproject/k0s#2004]
### Before creating an issue, make sure you've checked the following:

- [X] You are running the latest released version of k0s
- [X] Make sure you've searched for existing issues, both open and closed
- [X] Make sure you've searched for PRs too, a fix might've been merged already
- [X] You're looking at docs for the released version, "main" branch docs are usually ahead of released versions.

### Version

v1.24.3+k0s.0

### Platform

```shell
LSB Version:    n/a
Distributor ID: Arch
Description:    Arch Linux
Release:        rolling
Codename:       n/a
```

### What happened?

Both kube-router and calico are running the kube-system ns, although calico never enters a ready state.

```
NAME                                       READY   STATUS    RESTARTS      AGE
calico-kube-controllers-578cb968c7-sjm6n   1/1     Running   2 (19d ago)   30d
calico-node-582qb                          0/1     Running   1 (19d ago)   30d
calico-node-pnsv5                          0/1     Running   1 (19d ago)   30d
coredns-8565977d9b-754s2                   1/1     Running   1 (19d ago)   30d
coredns-8565977d9b-ln8r4                   1/1     Running   1 (19d ago)   30d
konnectivity-agent-7t58w                   1/1     Running   0             119s
konnectivity-agent-b847h                   1/1     Running   0             116s
kube-proxy-886qw                           1/1     Running   0             26h
kube-proxy-sgk98                           1/1     Running   0             26h
kube-router-sc5d8                          1/1     Running   0             26h
kube-router-sq5d2                          1/1     Running   2 (25h ago)   26h
metrics-server-74c967d8d4-wwdlm            1/1     Running   4 (25h ago)   30d
```

Configured my cluster with k0sctl:
Specified kube router under networking after seeing this comment https://github.com/k0sproject/k0s/issues/1669#issuecomment-1119678121,  but it has no further effect.

```
apiVersion: k0sctl.k0sproject.io/v1beta1
kind: Cluster
metadata:
  name: home-cluster
spec:
  hosts:
  - ssh:
      address: 192.168.178.7
      user: root
      port: 22
      keyPath: /home/daan/.ssh/id_rsa
    noTaints: true
    role: controller+worker
  - ssh:
      address: 192.168.178.8
      user: root
      port: 22
      keyPath: /home/daan/.ssh/id_rsa
    noTaints: true 
    role: controller+worker
  - ssh:
      address: 192.168.178.9
      user: root
      port: 22
      keyPath: /home/daan/.ssh/id_rsa
    role: controller
  k0s:
    version: 1.24.3+k0s.0
    dynamicConfig: false
    config:
      spec:
        network:
          provider: kuberouter
```

### Steps to reproduce

1. Rollout with the above k0sctl
2. Done

### Expected behavior

Having one single cni, kuberouter as that;s the default

### Actual behavior

Both cnis are there
