### ISSUE TITLE
Metrics server has issues with konnectivity agent

### ISSUE THREAD

**Issue by dza89** [k0sproject/k0s#2068]
### Before creating an issue, make sure you've checked the following:

- [X] You are running the latest released version of k0s
- [X] Make sure you've searched for existing issues, both open and closed
- [X] Make sure you've searched for PRs too, a fix might've been merged already
- [X] You're looking at docs for the released version, "main" branch docs are usually ahead of released versions.

### Version

v1.24.3+k0s.0

### Platform

```shell
LSB Version:    n/a
Distributor ID: Arch
Description:    Arch Linux
Release:        rolling
Codename:       n/a
```

### What happened?

Metrics server is behaving erratic, seems some issue with konnectiviy.
I've upgraded metrics server to 0.6.1 to check if that has any effect, unfortunately same issue.

### Steps to reproduce

1. k0sctl apply config:
```yaml
# k0sctl apply --config cluster.yaml
apiVersion: k0sctl.k0sproject.io/v1beta1
kind: Cluster
metadata:
  name: home-cluster
spec:
  hosts:
    - ssh:
        address: 192.168.178.7
        user: root
        port: 22
        keyPath: /home/daan/.ssh/id_rsa
      noTaints: true
      role: controller+worker
    - ssh:
        address: 192.168.178.8
        user: root
        port: 22
        keyPath: /home/daan/.ssh/id_rsa
      noTaints: true 
      role: controller+worker
```
3. Check metrics agent

### Expected behavior

A working metrics server :)

### Actual behavior

See logs

### Screenshots and logs

```
http2: server: error reading preface from client 10.244.1.44:54142: read tcp 10.244.1.45:10250->10.244.1.44:54142: read: connection reset by peer
http2: server: error reading preface from client 10.244.1.44:58076: read tcp 10.244.1.45:10250->10.244.1.44:58076: read: connection reset by peer
http2: server: error reading preface from client 10.244.0.32:46364: read tcp 10.244.1.45:10250->10.244.0.32:46364: read: connection reset by peer
http2: server: error reading preface from client 10.244.1.44:57106: read tcp 10.244.1.45:10250->10.244.1.44:57106: read: connection reset by peer
http2: server: error reading preface from client 10.244.1.44:33328: read tcp 10.244.1.45:10250->10.244.1.44:33328: read: connection reset by peer
http2: server: error reading preface from client 10.244.0.32:32872: read tcp 10.244.1.45:10250->10.244.0.32:32872: read: connection reset by peer
http2: server: error reading preface from client 10.244.1.44:35440: read tcp 10.244.1.45:10250->10.244.1.44:35440: read: connection reset by peer
http2: server: error reading preface from client 10.244.0.32:35754: read tcp 10.244.1.45:10250->10.244.0.32:35754: read: connection reset by peer
http2: server: error reading preface from client 10.244.1.44:33544: read tcp 10.244.1.45:10250->10.244.1.44:33544: read: connection reset by peer
http2: server: error reading preface from client 10.244.1.44:36082: read tcp 10.244.1.45:10250->10.244.1.44:36082: read: connection reset by peer
http2: server: error reading preface from client 10.244.1.44:38712: read tcp 10.244.1.45:10250->10.244.1.44:38712: read: connection reset by peer
```

```
konnectivity-agent-dnv69          1/1     Running   0             21m     10.244.0.31   
konnectivity-agent-j8cdk          1/1     Running   0             21m     10.244.1.37    
```

### Additional context

Did a k0s reset on both nodes before applying the yaml above.
