### ISSUE TITLE
Fedora CoreOS instructions.

### ISSUE THREAD

**Issue by dwarf-king-hreidmar** [k0sproject/k0s#2075]
### Is your feature request related to a problem? Please describe.

I switched over to running k0s on CoreOS from Ubuntu on my RPi cluster and there are some differences in the manual install. I'm also not sure if k0sctl supports CoreOS 

Examples:
installing libcgroup and libcgroup-tools
using `rpm-ostree kargs ..` to set the necessary kernel arguments

### Describe the solution you would like

Would it be helpful if I PR'd some notes about CoreOS to the docs or wrote a new doc?

### Describe alternatives you've considered

k0sctl might just support the install on Fedora CoreOS or other ostree backed OS.

**Comment by twz123** [comment]
FYI there's an [open issue](https://github.com/k0sproject/k0sctl/issues/107) and [PR](https://github.com/k0sproject/k0sctl/pull/309) for CoreOS support in k0sctl.

**Comment by dwarf-king-hreidmar** [comment]
We can close this issue now. CoreOS support is baked in!

**Comment by andyrue** [comment]
@dwarf-king-hreidmar Could you expand on how CoreOS is baked in now? I'm trying to get it setup right, but when I restart the Fedora CoreOS servers, k0s is no longer installed as a service and won't run. I have mounted /var to a second drive and set `wipeTable: false`. It seems everything is still there under `/var/lib/k0s. I found a few hints here and there looking over some of the linked issues, but not sure what I'm missing. I appreciate any guidance! This is what my config file looks like.

```
apiVersion: k0sctl.k0sproject.io/v1beta1
kind: Cluster
metadata:
  name: k0s-cluster
spec:
  hosts:
  - ssh:
      address: 10.3.3.21
      user: core
      port: 22
      keyPath: ~/.ssh/.id_rsa
    role: controller
    installFlags:
      - "--profile coreos"
  - ssh:
      address: 10.3.3.22
      user: core
      port: 22
      keyPath: ~/.ssh/.id_rsa
    role: controller
    installFlags:
      - "--profile coreos"
  - ssh:
      address: 10.3.3.23
      user: core
      port: 22
      keyPath: ~/.ssh/.id_rsa
    role: controller
    installFlags:
      - "--profile coreos"
  - ssh:
      address: 10.3.3.24
      user: core
      port: 22
      keyPath: ~/.ssh/.id_rsa
    role: worker
    installFlags:
      - "--profile coreos"
  - ssh:
      address: 10.3.3.25
      user: core
      port: 22
      keyPath: ~/.ssh/.id_rsa
    role: worker
    installFlags:
      - "--profile coreos"
  - ssh:
      address: 10.3.3.26
      user: core
      port: 22
      keyPath: ~/.ssh/.id_rsa
    role: worker
    installFlags:
      - "--profile coreos"
  k0s:
    version: 1.27.4+k0s.0
    dynamicConfig: false
    config:
      spec:
        controllerManager:
          extraArgs:
            flex-volume-plugin-dir: "/etc/kubernetes/kubelet-plugins/volume/exec"
        workerProfiles:
          - name: coreos
            values:
              volumePluginDir: /etc/k0s/kubelet-plugins/volume/exec/
        network:
          provider: custom
          kubeProxy:
            disabled: true
        api:
          externalAddress: 10.3.3.20
          sans:
          - 10.3.3.20

```
