### ISSUE TITLE
[QUESTION] Accessing Service NodePort from k0s in a container

### ISSUE THREAD

**Issue by FilBot3** [k0sproject/k0s#2123]
# Background

I followed the [k0s in Docker](https://docs.k0sproject.io/v1.24.4+k0s.0/k0s-in-docker/), but modified it for Podman. I ran the following command and waited until the Controller was up and running. For this, I am doing a single controller+worker.

```bash
sudo podman volume create k0s-controller
sudo podman run \
  --detach \
  --name k0s \
  --hostname k0s \
  --privileged \
  --volume k0s-controller:/var/lib/k0s \
  --cgroupns=host \
  --volume /sys/fs/cgroup:/sys/fs/cgroup:rw \
  --publish 6443:6443 docker.io/k0sproject/k0s:latest

sudo podman exec k0s kubectl get nodes
NAME   STATUS   ROLES           AGE   VERSION
k0s    Ready    control-plane   36s   v1.23.10+k0s

sudo podman exec k0s cat /var/lib/k0s/pki/admin.conf > k0s.kubeconfig.yaml
```

I then apply the following Kubernetes manifest files to the k0s instance.

```bash
kubectl --kubeconfig=k0s.kubeconfig.yaml apply -f .
```

Which the current working directory has:

My deployment

```yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
          name: http-nginx-web-svc
...
```

My service

```yaml
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  labels:
    service: nginx
spec:
  type: NodePort
  selector:
    matchLabels:
      app: nginx
  ports:
    - protocol: TCP
      port: 9876
      targetPort: http-nginx-web-svc
      nodePort: 31234
...
```

With the results of

```bash
> kubectl --kubeconfig=./kubeconfig apply -f .
deployment.apps/nginx-deployment created
service/nginx-service created
```

# The problem

When I attempt to access `http://localhost:311234`, it doesn't resolve. 

# The question

So, the question is, do I need to `--publish 31234:31234` when I start up my k0s instance as well and all subsequent worker instances?
