### ISSUE TITLE
Incomplete Cluster Role Binding for Calico

### ISSUE THREAD

**Issue by debackerl** [k0sproject/k0s#2554]
### Before creating an issue, make sure you've checked the following:

- [X] You are running the latest released version of k0s
- [X] Make sure you've searched for existing issues, both open and closed
- [X] Make sure you've searched for PRs too, a fix might've been merged already
- [X] You're looking at docs for the released version, "main" branch docs are usually ahead of released versions.

### Platform

```shell
NAME="AlmaLinux"
VERSION="9.1 (Lime Lynx)"
ID="almalinux"
ID_LIKE="rhel centos fedora"
VERSION_ID="9.1"
PLATFORM_ID="platform:el9"
PRETTY_NAME="AlmaLinux 9.1 (Lime Lynx)"
ANSI_COLOR="0;34"
LOGO="fedora-logo-icon"
CPE_NAME="cpe:/o:almalinux:almalinux:9::baseos"
HOME_URL="https://almalinux.org/"
DOCUMENTATION_URL="https://wiki.almalinux.org/"
BUG_REPORT_URL="https://bugs.almalinux.org/"

ALMALINUX_MANTISBT_PROJECT="AlmaLinux-9"
ALMALINUX_MANTISBT_PROJECT_VERSION="9.1"
REDHAT_SUPPORT_PRODUCT="AlmaLinux"
REDHAT_SUPPORT_PRODUCT_VERSION="9.1"
```

### Version

1.25.4+k0s.0

### Sysinfo

<details><summary>`k0s sysinfo`</summary>
```text
Machine ID: "98c3d103b1177537cbcec120cbe1555ef22fac3c921b6d8974e81ab40d6f3368" (from machine) (pass)
Total memory: 1.9 GiB (pass)
Disk space available for /var/lib/k0s: 15.4 GiB (pass)
Operating system: Linux (pass)
  Linux kernel release: 5.14.0-162.6.1.el9_1.x86_64 (pass)
  Max. file descriptors per process: current: 524288 / max: 524288 (pass)
  Executable in path: modprobe: /sbin/modprobe (pass)
  /proc file system: mounted (0x9fa0) (pass)
  Control Groups: version 2 (pass)
    cgroup controller "cpu": available (pass)
    cgroup controller "cpuacct": available (via cpu in version 2) (pass)
    cgroup controller "cpuset": available (pass)
    cgroup controller "memory": available (pass)
    cgroup controller "devices": available (assumed) (pass)
    cgroup controller "freezer": available (assumed) (pass)
    cgroup controller "pids": available (pass)
    cgroup controller "hugetlb": available (pass)
    cgroup controller "blkio": available (via io in version 2) (pass)
  CONFIG_CGROUPS: Control Group support: built-in (pass)
    CONFIG_CGROUP_FREEZER: Freezer cgroup subsystem: built-in (pass)
    CONFIG_CGROUP_PIDS: PIDs cgroup subsystem: built-in (pass)
    CONFIG_CGROUP_DEVICE: Device controller for cgroups: built-in (pass)
    CONFIG_CPUSETS: Cpuset support: built-in (pass)
    CONFIG_CGROUP_CPUACCT: Simple CPU accounting cgroup subsystem: built-in (pass)
    CONFIG_MEMCG: Memory Resource Controller for Control Groups: built-in (pass)
    CONFIG_CGROUP_HUGETLB: HugeTLB Resource Controller for Control Groups: built-in (pass)
    CONFIG_CGROUP_SCHED: Group CPU scheduler: built-in (pass)
      CONFIG_FAIR_GROUP_SCHED: Group scheduling for SCHED_OTHER: built-in (pass)
        CONFIG_CFS_BANDWIDTH: CPU bandwidth provisioning for FAIR_GROUP_SCHED: built-in (pass)
    CONFIG_BLK_CGROUP: Block IO controller: built-in (pass)
  CONFIG_NAMESPACES: Namespaces support: built-in (pass)
    CONFIG_UTS_NS: UTS namespace: built-in (pass)
    CONFIG_IPC_NS: IPC namespace: built-in (pass)
    CONFIG_PID_NS: PID namespace: built-in (pass)
    CONFIG_NET_NS: Network namespace: built-in (pass)
  CONFIG_NET: Networking support: built-in (pass)
    CONFIG_INET: TCP/IP networking: built-in (pass)
      CONFIG_IPV6: The IPv6 protocol: built-in (pass)
    CONFIG_NETFILTER: Network packet filtering framework (Netfilter): built-in (pass)
      CONFIG_NETFILTER_ADVANCED: Advanced netfilter configuration: built-in (pass)
      CONFIG_NETFILTER_XTABLES: Netfilter Xtables support: built-in (pass)
        CONFIG_NETFILTER_XT_TARGET_REDIRECT: REDIRECT target support: module (pass)
        CONFIG_NETFILTER_XT_MATCH_COMMENT: "comment" match support: module (pass)
        CONFIG_NETFILTER_XT_MARK: nfmark target and match support: module (pass)
        CONFIG_NETFILTER_XT_SET: set target and match support: module (pass)
        CONFIG_NETFILTER_XT_TARGET_MASQUERADE: MASQUERADE target support: module (pass)
        CONFIG_NETFILTER_XT_NAT: "SNAT and DNAT" targets support: module (pass)
        CONFIG_NETFILTER_XT_MATCH_ADDRTYPE: "addrtype" address type match support: module (pass)
        CONFIG_NETFILTER_XT_MATCH_CONNTRACK: "conntrack" connection tracking match support: module (pass)
        CONFIG_NETFILTER_XT_MATCH_MULTIPORT: "multiport" Multiple port match support: module (pass)
        CONFIG_NETFILTER_XT_MATCH_RECENT: "recent" match support: module (pass)
        CONFIG_NETFILTER_XT_MATCH_STATISTIC: "statistic" match support: module (pass)
      CONFIG_NETFILTER_NETLINK: module (pass)
      CONFIG_NF_CONNTRACK: Netfilter connection tracking support: module (pass)
      CONFIG_NF_NAT: module (pass)
      CONFIG_IP_SET: IP set support: module (pass)
        CONFIG_IP_SET_HASH_IP: hash:ip set support: module (pass)
        CONFIG_IP_SET_HASH_NET: hash:net set support: module (pass)
      CONFIG_IP_VS: IP virtual server support: module (pass)
        CONFIG_IP_VS_NFCT: Netfilter connection tracking: built-in (pass)
      CONFIG_NF_CONNTRACK_IPV4: IPv4 connetion tracking support (required for NAT): unknown (warning)
      CONFIG_NF_REJECT_IPV4: IPv4 packet rejection: module (pass)
      CONFIG_NF_NAT_IPV4: IPv4 NAT: unknown (warning)
      CONFIG_IP_NF_IPTABLES: IP tables support: module (pass)
        CONFIG_IP_NF_FILTER: Packet filtering: module (pass)
          CONFIG_IP_NF_TARGET_REJECT: REJECT target support: module (pass)
        CONFIG_IP_NF_NAT: iptables NAT support: module (pass)
        CONFIG_IP_NF_MANGLE: Packet mangling: module (pass)
      CONFIG_NF_DEFRAG_IPV4: module (pass)
      CONFIG_NF_CONNTRACK_IPV6: IPv6 connetion tracking support (required for NAT): unknown (warning)
      CONFIG_NF_NAT_IPV6: IPv6 NAT: unknown (warning)
      CONFIG_IP6_NF_IPTABLES: IP6 tables support: module (pass)
        CONFIG_IP6_NF_FILTER: Packet filtering: module (pass)
        CONFIG_IP6_NF_MANGLE: Packet mangling: module (pass)
        CONFIG_IP6_NF_NAT: ip6tables NAT support: module (pass)
      CONFIG_NF_DEFRAG_IPV6: module (pass)
    CONFIG_BRIDGE: 802.1d Ethernet Bridging: module (pass)
      CONFIG_LLC: module (pass)
      CONFIG_STP: module (pass)
  CONFIG_EXT4_FS: The Extended 4 (ext4) filesystem: module (pass)
  CONFIG_PROC_FS: /proc file system support: built-in (pass)
```
</details>

### What happened?

After a fresh install of k0s using k0sctl, Calico Kube Controller pod is reporting errors as shown below.

### Steps to reproduce

Use this k0s spec:

```
    version: "1.25.4+k0s.0"
    dynamicConfig: false
    config:
      apiVersion: k0s.k0sproject.io/v1beta1
      kind: ClusterConfig
      metadata:
        name: katanoo-prod-cluster
      spec:
        api:
          # address used by components to reach kube-apiserver, and as address in kubeconfig
          externalAddress: ""
          # address for socket binding
          address: ""
          # extra addresses
          sans:
            # add loopback address when using SSH tunnel to reach kube-api
            - 127.0.0.1
          # kube-apiserver
          port: 6443
          # k0s cluster join API
          k0sApiPort: 9443
          # use Konnectivity tunnels
          tunneledNetworkingMode: false
          # extra key-value arguments passed to kube-apiserver
          extraArgs: {}
        controllerManager:
          extraArgs: {}
        scheduler:
          extraArgs: {}
        extensions:
          helm:
            charts: null
            repositories: null
          storage:
            # 'external_storage' or 'openebs_local_storage'
            type: external_storage
            create_default_storage_class: false
        installConfig:
          users:
            etcdUser: etcd
            kineUser: kube-apiserver
            #konnectivityUser: konnectivity-server
            kubeAPIserverUser: kube-apiserver
            kubeSchedulerUser: kube-scheduler
        network:
          # 'calico', 'kuberouter', or 'custom'
          provider: calico
          clusterDomain: cluster.local
          podCIDR: 10.244.0.0/16
          serviceCIDR: 10.96.0.0/12
          dualStack:
            # only for calico in bird mode, and cross-pod must be activated to allow pod communication between nodes
            enabled: false
            #IPv6PodCIDR: "fd00::/108"
            #IPv6ServiceCIDR: "fd01::/108"
          calico:
            mode: ipip
            mtu: 0
            wireguard: false
            overlay: Always
            ipAutodetectionMethod: ""
            ipV6AutodetectionMethod: ""
            envVars: {}
          kubeProxy:
            disabled: false
            mode: iptables
        storage:
          # 'etcd' or 'kine'
          type: etcd
          #etcd:
            #externalCluster:
              #endpoints: []
              #etcdPrefix: ""
          #kine:
            #dataSource: ""
        #konnectivity:
          # used by control plane nodes to connect to worker nodes (kubelet, pod, service)
          # the Konnectivity agents on workers will initiate a tunnel to the Konnectivity server
          # in the control plane
          #agentPort: 8132
          #adminPort: 8133
        telemetry:
          enabled: true
        workerProfiles: []
```

### Expected behavior

Accordingly to the logs of Calico Kube Controller, the Cluster Role Binding should allow:
1. "get" on IPPools
2. "list" on clusterinformations

### Actual behavior

The current Cluster Role Binding allows only this:

```
rules:
  - verbs:
      - watch
      - list
      - get
    apiGroups:
      - ''
    resources:
      - nodes
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - ''
    resources:
      - pods
  - verbs:
      - list
    apiGroups:
      - crd.projectcalico.org
    resources:
      - ippools
      - ipreservations
  - verbs:
      - get
      - list
      - create
      - update
      - delete
      - watch
    apiGroups:
      - crd.projectcalico.org
    resources:
      - blockaffinities
      - ipamblocks
      - ipamhandles
  - verbs:
      - get
      - list
      - create
      - update
      - delete
    apiGroups:
      - crd.projectcalico.org
    resources:
      - hostendpoints
  - verbs:
      - get
      - create
      - update
    apiGroups:
      - crd.projectcalico.org
    resources:
      - clusterinformations
  - verbs:
      - get
      - create
      - update
      - watch
    apiGroups:
      - crd.projectcalico.org
    resources:
      - kubecontrollersconfigurations

```

### Screenshots and logs

2022-12-24 16:01:50.721 [INFO][1] watchercache.go 181: Full resync is required ListRoot="/calico/resources/v3/projectcalico.org/ippools"
2022-12-24 16:01:50.787 [INFO][1] watchercache.go 248: Failed to create watcher ListRoot="/calico/resources/v3/projectcalico.org/ippools" error=connection is unauthorized: unknown (get IPPools.crd.projectcalico.org) performFullResync=false
2022-12-24 16:01:51.094 [INFO][1] watchercache.go 181: Full resync is required ListRoot="/calico/resources/v3/projectcalico.org/clusterinformations"
2022-12-24 16:01:51.123 [INFO][1] watchercache.go 194: Failed to perform list of current data during resync ListRoot="/calico/resources/v3/projectcalico.org/clusterinformations" error=connection is unauthorized: clusterinformations.crd.projectcalico.org is forbidden: User "system:serviceaccount:kube-system:calico-kube-controllers" cannot list resource "clusterinformations" in API group "crd.projectcalico.org" at the cluster scope
