### ISSUE TITLE
nodeLocalLoadBalancing blocking hostPort 80

### ISSUE THREAD

**Issue by pschichtel** [k0sproject/k0s#2659]
### Before creating an issue, make sure you've checked the following:

- [X] You are running the latest released version of k0s
- [X] Make sure you've searched for existing issues, both open and closed
- [X] Make sure you've searched for PRs too, a fix might've been merged already
- [X] You're looking at docs for the released version, "main" branch docs are usually ahead of released versions.

### Platform

```shell
uname -srvmo; cat /etc/os-release || lsb_release -a
Linux 3.10.0-1160.83.1.el7.x86_64 #1 SMP Wed Jan 25 16:41:43 UTC 2023 x86_64 GNU/Linux
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```

### Version

v1.26.0+k0s.0

### Sysinfo

<details><summary>`k0s sysinfo`</summary>
```text
Machine ID: "2fca800d7d5b622bcb86b305f0d6e41fd1d67bdf9dde2c7b6199cc29a425c653" (from machine) (pass)
Total memory: 3.7 GiB (pass)
Disk space available for /var/lib/k0s: 4.1 GiB (pass)
Operating system: Linux (pass)
  Linux kernel release: 3.10.0-1160.83.1.el7.x86_64 (pass)
  Max. file descriptors per process: current: 4096 / max: 4096 (warning: < 65536)
  Executable in path: modprobe: /usr/sbin/modprobe (pass)
  /proc file system: mounted (0x9fa0) (pass)
  Control Groups: version 1 (pass)
    cgroup controller "cpu": available (pass)
    cgroup controller "cpuacct": available (pass)
    cgroup controller "cpuset": available (pass)
    cgroup controller "memory": available (pass)
    cgroup controller "devices": available (pass)
    cgroup controller "freezer": available (pass)
    cgroup controller "pids": available (pass)
    cgroup controller "hugetlb": available (pass)
    cgroup controller "blkio": available (pass)
  CONFIG_CGROUPS: Control Group support: built-in (pass)
    CONFIG_CGROUP_FREEZER: Freezer cgroup subsystem: built-in (pass)
    CONFIG_CGROUP_PIDS: PIDs cgroup subsystem: built-in (pass)
    CONFIG_CGROUP_DEVICE: Device controller for cgroups: built-in (pass)
    CONFIG_CPUSETS: Cpuset support: built-in (pass)
    CONFIG_CGROUP_CPUACCT: Simple CPU accounting cgroup subsystem: built-in (pass)
    CONFIG_MEMCG: Memory Resource Controller for Control Groups: built-in (pass)
    CONFIG_CGROUP_HUGETLB: HugeTLB Resource Controller for Control Groups: built-in (pass)
    CONFIG_CGROUP_SCHED: Group CPU scheduler: built-in (pass)
      CONFIG_FAIR_GROUP_SCHED: Group scheduling for SCHED_OTHER: built-in (pass)
        CONFIG_CFS_BANDWIDTH: CPU bandwidth provisioning for FAIR_GROUP_SCHED: built-in (pass)
    CONFIG_BLK_CGROUP: Block IO controller: built-in (pass)
  CONFIG_NAMESPACES: Namespaces support: built-in (pass)
    CONFIG_UTS_NS: UTS namespace: built-in (pass)
    CONFIG_IPC_NS: IPC namespace: built-in (pass)
    CONFIG_PID_NS: PID namespace: built-in (pass)
    CONFIG_NET_NS: Network namespace: built-in (pass)
  CONFIG_NET: Networking support: built-in (pass)
    CONFIG_INET: TCP/IP networking: built-in (pass)
      CONFIG_IPV6: The IPv6 protocol: built-in (pass)
    CONFIG_NETFILTER: Network packet filtering framework (Netfilter): built-in (pass)
      CONFIG_NETFILTER_ADVANCED: Advanced netfilter configuration: built-in (pass)
      CONFIG_NETFILTER_XTABLES: Netfilter Xtables support: built-in (pass)
        CONFIG_NETFILTER_XT_TARGET_REDIRECT: REDIRECT target support: module (pass)
        CONFIG_NETFILTER_XT_MATCH_COMMENT: "comment" match support: module (pass)
        CONFIG_NETFILTER_XT_MARK: nfmark target and match support: module (pass)
        CONFIG_NETFILTER_XT_SET: set target and match support: module (pass)
        CONFIG_NETFILTER_XT_TARGET_MASQUERADE: MASQUERADE target support: unknown (warning: also tried CONFIG_IP_NF_TARGET_MASQUERADE, CONFIG_IP6_NF_TARGET_MASQUERADE)
        CONFIG_NETFILTER_XT_NAT: "SNAT and DNAT" targets support: module (pass)
        CONFIG_NETFILTER_XT_MATCH_ADDRTYPE: "addrtype" address type match support: module (pass)
        CONFIG_NETFILTER_XT_MATCH_CONNTRACK: "conntrack" connection tracking match support: module (pass)
        CONFIG_NETFILTER_XT_MATCH_MULTIPORT: "multiport" Multiple port match support: module (pass)
        CONFIG_NETFILTER_XT_MATCH_RECENT: "recent" match support: module (pass)
        CONFIG_NETFILTER_XT_MATCH_STATISTIC: "statistic" match support: module (pass)
      CONFIG_NETFILTER_NETLINK: module (pass)
      CONFIG_NF_CONNTRACK: Netfilter connection tracking support: module (pass)
      CONFIG_NF_NAT: module (pass)
      CONFIG_IP_SET: IP set support: module (pass)
        CONFIG_IP_SET_HASH_IP: hash:ip set support: module (pass)
        CONFIG_IP_SET_HASH_NET: hash:net set support: module (pass)
      CONFIG_IP_VS: IP virtual server support: module (pass)
        CONFIG_IP_VS_NFCT: Netfilter connection tracking: built-in (pass)
      CONFIG_NF_CONNTRACK_IPV4: IPv4 connetion tracking support (required for NAT): module (pass)
      CONFIG_NF_REJECT_IPV4: IPv4 packet rejection: module (pass)
      CONFIG_NF_NAT_IPV4: IPv4 NAT: module (pass)
      CONFIG_IP_NF_IPTABLES: IP tables support: module (pass)
        CONFIG_IP_NF_FILTER: Packet filtering: module (pass)
          CONFIG_IP_NF_TARGET_REJECT: REJECT target support: module (pass)
        CONFIG_IP_NF_NAT: iptables NAT support: module (pass)
        CONFIG_IP_NF_MANGLE: Packet mangling: module (pass)
      CONFIG_NF_DEFRAG_IPV4: module (pass)
      CONFIG_NF_CONNTRACK_IPV6: IPv6 connetion tracking support (required for NAT): module (pass)
      CONFIG_NF_NAT_IPV6: IPv6 NAT: module (pass)
      CONFIG_IP6_NF_IPTABLES: IP6 tables support: module (pass)
        CONFIG_IP6_NF_FILTER: Packet filtering: module (pass)
        CONFIG_IP6_NF_MANGLE: Packet mangling: module (pass)
        CONFIG_IP6_NF_NAT: ip6tables NAT support: module (pass)
      CONFIG_NF_DEFRAG_IPV6: module (pass)
    CONFIG_BRIDGE: 802.1d Ethernet Bridging: module (pass)
      CONFIG_LLC: module (pass)
      CONFIG_STP: module (pass)
  CONFIG_EXT4_FS: The Extended 4 (ext4) filesystem: module (pass)
  CONFIG_PROC_FS: /proc file system support: built-in (pass)
```
</details>

### What happened?

I deployed k0s 1.26 (3 controllers with workers enabled, 2 workers) with NLLB enabled. After that I attempted to deploy the ingress-nginx helm chart with hostPorts enabled, because I don't intent to deploy a load balancer. The nginx stayed in Pending state, because kubernetes was unable to find nodes with port 80 and 443 still available. Since nginx was the only deployment besides things deployed by k0s, I started looking for other pods that might use hostPorts. I eventually found the `pod/nllb-*` pods that have `hostPort: 80` configured. Running curl against localhost:80 results in connection refused, so it seems like nothing is actually listening on port 80.

The ingress-nginx helm chart values:

```yaml
controller:
  hostPort:
    enabled: true
    #ports: # uncommenting this "fixes" the problem
    #  http: 81
  service:
    enabled: false
```

### Steps to reproduce

1. Deploy multi-node k0s cluster with NLLB enabled
2. Deploy the `ingress-nginx` helm chart (I used verison 4.4.2)
3. Checkout the nginx pods, all of them should be Pending since the requested host ports are not available.

### Expected behavior

Since the port 80 is not being used, it should not be declared as a host port, so other applications can use hostPort 80, most likely ingress controllers in setups without a load balancer.

### Actual behavior

HostPort 80 is blocked.

**Comment by pschichtel** [comment]
@twz123 

this is the spec of one of the pods:

```yaml
spec:
  containers:
  - image: docker.io/envoyproxy/envoy-distroless:v1.24.1
    imagePullPolicy: IfNotPresent
    livenessProbe:
      failureThreshold: 3
      periodSeconds: 10
      successThreshold: 1
      tcpSocket:
        host: 127.0.0.1
        port: 7443
      timeoutSeconds: 3
    name: nllb
    ports:
    - containerPort: 80
      hostPort: 80
      name: nllb
      protocol: TCP
    resources: {}
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      privileged: false
      readOnlyRootFilesystem: true
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /etc/envoy
      name: envoy-config
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  hostNetwork: true
  nodeName: some name
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext:
    runAsNonRoot: true
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - hostPath:
      path: /run/k0s/nllb/envoy
      type: Directory
    name: envoy-config
```

I also found https://github.com/k0sproject/k0s/blob/657b17f0facb8164197f72aed27d3de4b3d1cb5a/pkg/component/worker/nllb/envoy.go#L260, which seems to create the spec for these pods. I assume the `hostPort: 80` is automatically added due to the declaration of `containerPort: 80` in combination with `hostNetwork: true`. Question that remains: why is `containerPort: 80` declared there, while `apiServerBindPort` is set to 7443 and `konnectivityServerBindPort` is set to 7123.

netstat confirms these are the only ports bound by envoy:

```
# netstat -tlpen | grep envoy
tcp        0      0 127.0.0.1:7443          0.0.0.0:*               LISTEN      65532      37384      3452/envoy          
tcp        0      0 127.0.0.1:7132          0.0.0.0:*               LISTEN      65532      37394      3452/envoy
```

Feels like the easiest fix would be to simply delete the declaration of port 80, the "correct" fix would probably be to declare the configuration values of `apiServerBindPort` and `konnectivityServerBindPort` as ports.

**Comment by pschichtel** [comment]
Just realized that the function already has access to a `envoyParams` instance, so at least the value for `apiServerBindPort` is already right there. the `konnectivityServerBindPort` is missing, which seems to be part of the `envoyFilesParams` struct which could easily be passed to `makePodManifest` function from `provision`.

**Comment by twz123** [comment]
Thanks for digging into this! I think you're right. The port shouldn't be hard coded.

**Comment by pschichtel** [comment]
@twz123 I just built a version of k0s with that patch and tested in my cluster. works as expected.

Should I submit this as an PR ?

here a spec of one of the pods with the patch:

```yaml
spec:
  containers:
  - image: docker.io/envoyproxy/envoy-distroless:v1.24.1
    imagePullPolicy: IfNotPresent
    livenessProbe:
      failureThreshold: 3
      periodSeconds: 10
      successThreshold: 1
      tcpSocket:
        host: 127.0.0.1
        port: 7443
      timeoutSeconds: 3
    name: nllb
    ports:
    - containerPort: 7443
      hostPort: 7443
      name: api-server
      protocol: TCP
    - containerPort: 7132
      hostPort: 7132
      name: konnectivity
      protocol: TCP
    resources: {}
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      privileged: false
      readOnlyRootFilesystem: true
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /etc/envoy
      name: envoy-config
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  hostNetwork: true
  nodeName: some name
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext:
    runAsNonRoot: true
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - hostPath:
      path: /run/k0s/nllb/envoy
      type: Directory
    name: envoy-config
```
