### ISSUE TITLE
Allow Helm Chart Extensions to be installed via local package

### ISSUE THREAD

**Issue by adityati** [k0sproject/k0s#2664]

**Comment by jnummelin** [comment]
@adityati Could you please elaborate a bit more what you'd want to do?

**Comment by adityati** [comment]
@jnummelin Sorry for the delayed response. It would be interesting to know whether k0s can install offline helm charts (.tgz) stored locally on the host running the k0s controller via helm extensions. This would be very helpful during complete airgapped installation.

**Comment by mikhail-sakhnov** [comment]
@adityati I think it will work, if you use file-path to the local tgz archive instead of the chart name.

For example, something like this should work
```
spec:
  extensions:
    helm:
      charts:
        - name: somechart
          chartname: /tmp/charts/echo-server-0.5.0.tgz
          version: "0.3.1"
          values: ""
          namespace: default
```
