### ISSUE TITLE
workerProfile not applying with k0sctl

### ISSUE THREAD

**Issue by chris-sanders** [k0sproject/k0s#2714]
### Before creating an issue, make sure you've checked the following:

- [ ] You are running the latest released version of k0s
- [X] Make sure you've searched for existing issues, both open and closed
- [X] Make sure you've searched for PRs too, a fix might've been merged already
- [X] You're looking at docs for the released version, "main" branch docs are usually ahead of released versions.

### Platform

```shell
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.5 LTS
Release:        20.04
Codename:       focal
```

### Version

1.25.5+k0s

### Sysinfo

<details><summary>`k0s sysinfo`</summary>

```text

Machine ID: "c9f3de9db5718d6d979c36539e1de2c274f930bd26b03488daa48a6c5e81071b" (from machine) (pass)
Total memory: 15.5 GiB (pass)
Disk space available for /var/lib/k0s: 121.9 GiB (pass)
Operating system: Linux (pass)
  Linux kernel release: 5.4.0-137-generic (pass)
  Max. file descriptors per process: current: 1048576 / max: 1048576 (pass)
  Executable in path: modprobe: /usr/sbin/modprobe (pass)
  /proc file system: mounted (0x9fa0) (pass)
  Control Groups: version 1 (pass)
    cgroup controller "cpu": available (pass)
    cgroup controller "cpuacct": available (pass)
    cgroup controller "cpuset": available (pass)
    cgroup controller "memory": available (pass)
    cgroup controller "devices": available (pass)
    cgroup controller "freezer": available (pass)
    cgroup controller "pids": available (pass)
    cgroup controller "hugetlb": available (pass)
    cgroup controller "blkio": available (pass)
  CONFIG_CGROUPS: Control Group support: built-in (pass)
    CONFIG_CGROUP_FREEZER: Freezer cgroup subsystem: built-in (pass)
    CONFIG_CGROUP_PIDS: PIDs cgroup subsystem: built-in (pass)
    CONFIG_CGROUP_DEVICE: Device controller for cgroups: built-in (pass)
    CONFIG_CPUSETS: Cpuset support: built-in (pass)
    CONFIG_CGROUP_CPUACCT: Simple CPU accounting cgroup subsystem: built-in (pass)
    CONFIG_MEMCG: Memory Resource Controller for Control Groups: built-in (pass)
    CONFIG_CGROUP_HUGETLB: HugeTLB Resource Controller for Control Groups: built-in (pass)
    CONFIG_CGROUP_SCHED: Group CPU scheduler: built-in (pass)
      CONFIG_FAIR_GROUP_SCHED: Group scheduling for SCHED_OTHER: built-in (pass)
        CONFIG_CFS_BANDWIDTH: CPU bandwidth provisioning for FAIR_GROUP_SCHED: built-in (pass)
    CONFIG_BLK_CGROUP: Block IO controller: built-in (pass)
  CONFIG_NAMESPACES: Namespaces support: built-in (pass)
    CONFIG_UTS_NS: UTS namespace: built-in (pass)
    CONFIG_IPC_NS: IPC namespace: built-in (pass)
    CONFIG_PID_NS: PID namespace: built-in (pass)
    CONFIG_NET_NS: Network namespace: built-in (pass)
  CONFIG_NET: Networking support: built-in (pass)
    CONFIG_INET: TCP/IP networking: built-in (pass)
      CONFIG_IPV6: The IPv6 protocol: built-in (pass)
    CONFIG_NETFILTER: Network packet filtering framework (Netfilter): built-in (pass)
      CONFIG_NETFILTER_ADVANCED: Advanced netfilter configuration: built-in (pass)
      CONFIG_NETFILTER_XTABLES: Netfilter Xtables support: module (pass)
        CONFIG_NETFILTER_XT_TARGET_REDIRECT: REDIRECT target support: module (pass)
        CONFIG_NETFILTER_XT_MATCH_COMMENT: "comment" match support: module (pass)
        CONFIG_NETFILTER_XT_MARK: nfmark target and match support: module (pass)
        CONFIG_NETFILTER_XT_SET: set target and match support: module (pass)
        CONFIG_NETFILTER_XT_TARGET_MASQUERADE: MASQUERADE target support: module (pass)
        CONFIG_NETFILTER_XT_NAT: "SNAT and DNAT" targets support: module (pass)
        CONFIG_NETFILTER_XT_MATCH_ADDRTYPE: "addrtype" address type match support: module (pass)
        CONFIG_NETFILTER_XT_MATCH_CONNTRACK: "conntrack" connection tracking match support: module (pass)
        CONFIG_NETFILTER_XT_MATCH_MULTIPORT: "multiport" Multiple port match support: module (pass)
        CONFIG_NETFILTER_XT_MATCH_RECENT: "recent" match support: module (pass)
        CONFIG_NETFILTER_XT_MATCH_STATISTIC: "statistic" match support: module (pass)
      CONFIG_NETFILTER_NETLINK: module (pass)
      CONFIG_NF_CONNTRACK: Netfilter connection tracking support: module (pass)
      CONFIG_NF_NAT: module (pass)
      CONFIG_IP_SET: IP set support: module (pass)
        CONFIG_IP_SET_HASH_IP: hash:ip set support: module (pass)
        CONFIG_IP_SET_HASH_NET: hash:net set support: module (pass)
      CONFIG_IP_VS: IP virtual server support: module (pass)
        CONFIG_IP_VS_NFCT: Netfilter connection tracking: built-in (pass)
      CONFIG_NF_CONNTRACK_IPV4: IPv4 connetion tracking support (required for NAT): unknown (warning)
      CONFIG_NF_REJECT_IPV4: IPv4 packet rejection: module (pass)
      CONFIG_NF_NAT_IPV4: IPv4 NAT: unknown (warning)
      CONFIG_IP_NF_IPTABLES: IP tables support: module (pass)
        CONFIG_IP_NF_FILTER: Packet filtering: module (pass)
          CONFIG_IP_NF_TARGET_REJECT: REJECT target support: module (pass)
        CONFIG_IP_NF_NAT: iptables NAT support: module (pass)
        CONFIG_IP_NF_MANGLE: Packet mangling: module (pass)
      CONFIG_NF_DEFRAG_IPV4: module (pass)
      CONFIG_NF_CONNTRACK_IPV6: IPv6 connetion tracking support (required for NAT): unknown (warning)
      CONFIG_NF_NAT_IPV6: IPv6 NAT: unknown (warning)
      CONFIG_IP6_NF_IPTABLES: IP6 tables support: module (pass)
        CONFIG_IP6_NF_FILTER: Packet filtering: module (pass)
        CONFIG_IP6_NF_MANGLE: Packet mangling: module (pass)
        CONFIG_IP6_NF_NAT: ip6tables NAT support: module (pass)
      CONFIG_NF_DEFRAG_IPV6: module (pass)
    CONFIG_BRIDGE: 802.1d Ethernet Bridging: module (pass)
      CONFIG_LLC: module (pass)
      CONFIG_STP: module (pass)
  CONFIG_EXT4_FS: The Extended 4 (ext4) filesystem: built-in (pass)
  CONFIG_PROC_FS: /proc file system support: built-in (pass)

```

</details>

### What happened?

Following https://docs.k0sproject.io/v1.25.4+k0s.0/worker-node-config/#worker-profiles and the example https://docs.k0sproject.io/head/configuration/#unsafe-sysctls I'm trying to add an allowance for an unsafeSysctl with the following in my k0sctl configuraiton.

```yaml

spec:
  hosts:
  - ssh:
      address: bakugo
    role: controller+worker
    noTaints: true
    installFlags: &installFlags
      - --disable-components konnectivity-server
  - ssh:
      address: todoroki
    role: controller+worker
    noTaints: true
    installFlags: *installFlags
  - ssh:
      address: deku
    role: controller+worker
    noTaints: true
    installFlags: *installFlags
  k0s:
    version: 1.25.5+k0s.0
    config:
      spec:
        network:
          provider: kuberouter
        workerProfiles:
          - name: ip-forward
            values:
              allowedUnsafeSysctls:
                - net.ipv4.ip_forward
```

I can see on one of my nodes that the manifest is created

```yaml
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kubelet-config-ip-forward-1.25
  namespace: kube-system
data:
  kubelet: |

    allowedUnsafeSysctls:
    - net.ipv4.ip_forward
    apiVersion: kubelet.config.k8s.io/v1beta1
    clusterDNS:
    - 10.96.0.10
    clusterDomain: cluster.local
    eventRecordQPS: 0
    failSwapOn: false
    kind: KubeletConfiguration
    rotateCertificates: true
    serverTLSBootstrap: true
    tlsCipherSuites:
    - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
    - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
    - TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305
    - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
    - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305
    - TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
    - TLS_RSA_WITH_AES_256_GCM_SHA384
    - TLS_RSA_WITH_AES_128_GCM_SHA256

```

However the file `/var/lib/k0s/kubelet-config.yaml` does not have the allowedUnsafeSysctls. I restarted the k0scontroller.service just to be sure. I've added the fields myself and after a restart it's removed again.

As shown above it's a 3 node hyperconverged (controller+worker) cluster.

I did see a note about specifying the profile here https://docs.k0sproject.io/head/configuration/#specworkerprofiles but that's talking about the worker command which I don't run with k0sctl. Am I just missing some configuration option in k0sctl to tell the nodes to use the new profile, or should they be applying the additional values automatically as the docs seem to imply?

### Steps to reproduce

see above

### Expected behavior

see above

### Actual behavior

see above

### Screenshots and logs

I don't know what pod logs you would want here as I'm not clear how things are reconciled. Let me know which ones would be helpful.

### Additional context

see above

**Comment by chris-sanders** [comment]
A bit more digging, I found the setting was also applied to `/etc/k0s/k0s.yaml`.
I was able to get it to apply by adding `--profile=ip-forward` to the systemd service file. I tried to do this with the `installFlags` via k0sctl although that doesn't seem to update the systemd file. Manually adding it has worked, but I'm curious to know if I can manage this with k0sctl to avoid having to manually configure this on all the nodes in a cluster.

**Comment by jnummelin** [comment]
@chris-sanders you can do it like this:

```
spec:
  hosts:
  - ssh:
      address: bakugo
    role: controller+worker
    noTaints: true
    installFlags: &installFlags
      - --disable-components konnectivity-server
      - --profile ip-forward
```

But like you found out, k0sctl is currently not able to overwrite the systemd unit file unfortunately. You know, it's systemd and there's some dragons... :D
