### ISSUE TITLE
k0sctl / k0s did not create kube-dns service (reopens #1058)

### ISSUE THREAD

**Issue by doctorpangloss** [k0sproject/k0s#2865]
### Before creating an issue, make sure you've checked the following:

- [X] You are running the latest released version of k0s
- [X] Make sure you've searched for existing issues, both open and closed
- [X] Make sure you've searched for PRs too, a fix might've been merged already
- [X] You're looking at docs for the released version, "main" branch docs are usually ahead of released versions.

### Platform

```shell
Linux 5.15.0-67-generic #74-Ubuntu SMP Wed Feb 22 14:14:39 UTC 2023 x86_64 GNU/Linux
PRETTY_NAME="Ubuntu 22.04.1 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.1 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
```

### Version

v1.26.2+k0s.0

### Sysinfo

<details><summary>`k0s sysinfo`</summary>
<pre>
Machine ID: "6d34ddb675fce71b194b9e62e68ee71f939daef7f5d02a41bea60a0e50f99e4b" (from machine) (pass)
Total memory: 31.1 GiB (pass)
Disk space available for /var/lib/k0s: 426.7 GiB (pass)
Operating system: Linux (pass)
  Linux kernel release: 5.15.0-67-generic (pass)
  Max. file descriptors per process: current: 1048576 / max: 1048576 (pass)
  Executable in path: modprobe: /usr/sbin/modprobe (pass)
  /proc file system: mounted (0x9fa0) (pass)
  Control Groups: version 2 (pass)
    cgroup controller "cpu": available (pass)
    cgroup controller "cpuacct": available (via cpu in version 2) (pass)
    cgroup controller "cpuset": available (pass)
    cgroup controller "memory": available (pass)
    cgroup controller "devices": available (assumed) (pass)
    cgroup controller "freezer": available (assumed) (pass)
    cgroup controller "pids": available (pass)
    cgroup controller "hugetlb": available (pass)
    cgroup controller "blkio": available (via io in version 2) (pass)
  CONFIG_CGROUPS: Control Group support: built-in (pass)
    CONFIG_CGROUP_FREEZER: Freezer cgroup subsystem: built-in (pass)
    CONFIG_CGROUP_PIDS: PIDs cgroup subsystem: built-in (pass)
    CONFIG_CGROUP_DEVICE: Device controller for cgroups: built-in (pass)
    CONFIG_CPUSETS: Cpuset support: built-in (pass)
    CONFIG_CGROUP_CPUACCT: Simple CPU accounting cgroup subsystem: built-in (pass)
    CONFIG_MEMCG: Memory Resource Controller for Control Groups: built-in (pass)
    CONFIG_CGROUP_HUGETLB: HugeTLB Resource Controller for Control Groups: built-in (pass)
    CONFIG_CGROUP_SCHED: Group CPU scheduler: built-in (pass)
      CONFIG_FAIR_GROUP_SCHED: Group scheduling for SCHED_OTHER: built-in (pass)
        CONFIG_CFS_BANDWIDTH: CPU bandwidth provisioning for FAIR_GROUP_SCHED: built-in (pass)
    CONFIG_BLK_CGROUP: Block IO controller: built-in (pass)
  CONFIG_NAMESPACES: Namespaces support: built-in (pass)
    CONFIG_UTS_NS: UTS namespace: built-in (pass)
    CONFIG_IPC_NS: IPC namespace: built-in (pass)
    CONFIG_PID_NS: PID namespace: built-in (pass)
    CONFIG_NET_NS: Network namespace: built-in (pass)
  CONFIG_NET: Networking support: built-in (pass)
    CONFIG_INET: TCP/IP networking: built-in (pass)
      CONFIG_IPV6: The IPv6 protocol: built-in (pass)
    CONFIG_NETFILTER: Network packet filtering framework (Netfilter): built-in (pass)
      CONFIG_NETFILTER_ADVANCED: Advanced netfilter configuration: built-in (pass)
      CONFIG_NETFILTER_XTABLES: Netfilter Xtables support: module (pass)
        CONFIG_NETFILTER_XT_TARGET_REDIRECT: REDIRECT target support: module (pass)
        CONFIG_NETFILTER_XT_MATCH_COMMENT: "comment" match support: module (pass)
        CONFIG_NETFILTER_XT_MARK: nfmark target and match support: module (pass)
        CONFIG_NETFILTER_XT_SET: set target and match support: module (pass)
        CONFIG_NETFILTER_XT_TARGET_MASQUERADE: MASQUERADE target support: module (pass)
        CONFIG_NETFILTER_XT_NAT: "SNAT and DNAT" targets support: module (pass)
        CONFIG_NETFILTER_XT_MATCH_ADDRTYPE: "addrtype" address type match support: module (pass)
        CONFIG_NETFILTER_XT_MATCH_CONNTRACK: "conntrack" connection tracking match support: module (pass)
        CONFIG_NETFILTER_XT_MATCH_MULTIPORT: "multiport" Multiple port match support: module (pass)
        CONFIG_NETFILTER_XT_MATCH_RECENT: "recent" match support: module (pass)
        CONFIG_NETFILTER_XT_MATCH_STATISTIC: "statistic" match support: module (pass)
      CONFIG_NETFILTER_NETLINK: module (pass)
      CONFIG_NF_CONNTRACK: Netfilter connection tracking support: module (pass)
      CONFIG_NF_NAT: module (pass)
      CONFIG_IP_SET: IP set support: module (pass)
        CONFIG_IP_SET_HASH_IP: hash:ip set support: module (pass)
        CONFIG_IP_SET_HASH_NET: hash:net set support: module (pass)
      CONFIG_IP_VS: IP virtual server support: module (pass)
        CONFIG_IP_VS_NFCT: Netfilter connection tracking: built-in (pass)
      CONFIG_NF_CONNTRACK_IPV4: IPv4 connetion tracking support (required for NAT): unknown (warning)
      CONFIG_NF_REJECT_IPV4: IPv4 packet rejection: module (pass)
      CONFIG_NF_NAT_IPV4: IPv4 NAT: unknown (warning)
      CONFIG_IP_NF_IPTABLES: IP tables support: module (pass)
        CONFIG_IP_NF_FILTER: Packet filtering: module (pass)
          CONFIG_IP_NF_TARGET_REJECT: REJECT target support: module (pass)
        CONFIG_IP_NF_NAT: iptables NAT support: module (pass)
        CONFIG_IP_NF_MANGLE: Packet mangling: module (pass)
      CONFIG_NF_DEFRAG_IPV4: module (pass)
      CONFIG_NF_CONNTRACK_IPV6: IPv6 connetion tracking support (required for NAT): unknown (warning)
      CONFIG_NF_NAT_IPV6: IPv6 NAT: unknown (warning)
      CONFIG_IP6_NF_IPTABLES: IP6 tables support: module (pass)
        CONFIG_IP6_NF_FILTER: Packet filtering: module (pass)
        CONFIG_IP6_NF_MANGLE: Packet mangling: module (pass)
        CONFIG_IP6_NF_NAT: ip6tables NAT support: module (pass)
      CONFIG_NF_DEFRAG_IPV6: module (pass)
    CONFIG_BRIDGE: 802.1d Ethernet Bridging: module (pass)
      CONFIG_LLC: module (pass)
      CONFIG_STP: module (pass)
  CONFIG_EXT4_FS: The Extended 4 (ext4) filesystem: built-in (pass)
  CONFIG_PROC_FS: /proc file system support: built-in (pass)
</pre>
</details>

### What happened?

`kube-dns` service was not installed in my cluster, breaking applications. Underlying issue is probably related to https://github.com/k0sproject/k0sctl/issues/469

### Steps to reproduce

0. Prepare ubuntu host DNS resolution with:
```sh
sudo rm /etc/resolv.conf
sudo ln -s /run/systemd/resolve/resolv.conf /etc/resolv.conf
```
2. Create a cluster using `k0sctl` with a similar configuration:

```yaml
apiVersion: k0sctl.k0sproject.io/v1beta1
kind: Cluster
metadata:
  name: k0s-cluster
spec:
  hosts:
  - ssh:
      address: 10.2.0.19
      user: administrator
      port: 22
    role: controller
  - ssh:
      address: 10.2.0.20
      user: administrator
      port: 22
    role: controller
  - ssh:
      address: 10.2.0.22
      user: administrator
      port: 22
    role: controller
  - ssh:
      address: 10.2.0.65
      user: administrator
      port: 22
    role: worker
  k0s:
    version: 1.26.2+k0s.0
    dynamicConfig: true
    config:
      apiVersion: k0s.k0sproject.io/v1beta1
      kind: Cluster
      metadata:
        name: k0s
      spec:
        api:
          k0sApiPort: 9443
          port: 6443
          tunneledNetworkingMode: false
          extraArgs:
            service-cluster-ip-range: 10.152.184.0/24
          sans:
            # included from service CIDR to resolve calico issue
            - 10.152.184.1
        controllerManager:
          extraArgs:
            horizontal-pod-autoscaler-sync-period: 1s
        extensions:
          helm:
            charts: null
            repositories: null
          storage:
            create_default_storage_class: false
            type: external_storage
        images:
          calico:
            cni:
              image: docker.io/calico/cni
              version: v3.23.5
            kubecontrollers:
              image: docker.io/calico/kube-controllers
              version: v3.23.5
            node:
              image: docker.io/calico/node
              version: v3.23.5
          coredns:
            image: docker.io/coredns/coredns
            version: 1.10.1
          default_pull_policy: IfNotPresent
          konnectivity:
            image: quay.io/k0sproject/apiserver-network-proxy-agent
            version: 0.0.33-k0s
          kubeproxy:
            image: registry.k8s.io/kube-proxy
            version: v1.26.2
          kuberouter:
            cni:
              image: docker.io/cloudnativelabs/kube-router
              version: v1.5.1
            cniInstaller:
              image: quay.io/k0sproject/cni-node
              version: 1.1.1-k0s.0
          metricsserver:
            image: registry.k8s.io/metrics-server/metrics-server
            version: v0.6.2
          pushgateway:
            image: quay.io/k0sproject/pushgateway-ttl
            version: edge@sha256:7031f6bf6c957e2fdb496161fe3bea0a5bde3de800deeba7b2155187196ecbd9
        installConfig:
          users:
            etcdUser: etcd
            kineUser: kube-apiserver
            konnectivityUser: konnectivity-server
            kubeAPIserverUser: kube-apiserver
            kubeSchedulerUser: kube-scheduler
        konnectivity:
          adminPort: 8133
          agentPort: 8132
        network:
          calico:
            mode: bird
            overlay: Never
          clusterDomain: cluster.local
          dualStack: { }
          kubeProxy:
            iptables:
              masqueradeAll: true
              minSyncPeriod: 0s
              syncPeriod: 0s
            ipvs:
              minSyncPeriod: 0s
              syncPeriod: 0s
              tcpFinTimeout: 0s
              tcpTimeout: 0s
              udpTimeout: 0s
            metricsBindAddress: 0.0.0.0:10249
            mode: iptables
          kuberouter: null
          nodeLocalLoadBalancing:
            envoyProxy:
              apiServerBindPort: 7443
              image:
                image: docker.io/envoyproxy/envoy-distroless
                version: v1.24.1
              konnectivityServerBindPort: 7132
            type: EnvoyProxy
          podCIDR: 10.3.0.0/16
          provider: calico
          serviceCIDR: 10.152.184.0/24
        scheduler: { }
        storage:
          type: etcd
        telemetry:
          enabled: true
```
 3. Observe `kube-dns` service is missing. This breaks DNS requests:
```text
$ kubectl get svc -n kube-system
NAME             TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)   AGE
metrics-server   ClusterIP   10.152.184.191   <none>        443/TCP   25m
```
 4. Observe `coredns` has no issues:
```text
$ kubectl logs -n kube-system coredns-7bf57bcbd8-sh4hd
.:53
[INFO] plugin/reload: Running configuration SHA512 = a0c06adb3aa41fc5baa9a525a356d4f8e0206ad810f6a0d1f005e63150f4cd85bb682bac617e725b3996ba493aee5bd94a076b3ff9c64726e7e00a033b2ab1ba
CoreDNS-1.10.1
linux/amd64, go1.20, 055b2c3

...
Conditions:
  Type              Status
  Initialized       True 
  Ready             True 
  ContainersReady   True 
  PodScheduled      True 
```
 5. Applying kube-dns resolves issues:
```yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    addonmanager.kubernetes.io/mode: Reconcile
    k8s-app: kube-dns
    kubernetes.io/cluster-service: "true"
    kubernetes.io/name: CoreDNS
  name: kube-dns
  namespace: kube-system
spec:
  clusterIP: 10.152.184.10
  clusterIPs:
  - 10.152.184.10
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: dns
    port: 53
    protocol: UDP
    targetPort: 53
  - name: dns-tcp
    port: 53
    protocol: TCP
    targetPort: 53
  - name: metrics
    port: 9153
    protocol: TCP
    targetPort: 9153
  selector:
    k8s-app: kube-dns
  sessionAffinity: None
  type: ClusterIP
```

### Expected behavior

`k0sctl` ought to install `kube-dns`. 

### Actual behavior

No DNS resolution inside the cluster.

### Screenshots and logs

Issue from source-controller from flux reaching the DNS server:
```
{"level":"error","ts":"2023-03-07T19:32:04.731Z","msg":"Reconciler error","controller":"gitrepository","controllerGroup":"source.toolkit.fluxcd.io","controllerKind":"GitRepository","GitRepository":{"name":"flux-system","namespace":"flux-system"},"namespace":"flux-system","name":"flux-system","reconcileID":"4a7e39a5-6a59-4e47-9120-fa1215e861fa","error":"failed to checkout and determine revision: unable to clone 'ssh://git@github.com/appmana/appmana-cluster': dial tcp: lookup github.com on 10.152.184.10:53: read udp 10.3.104.7:59910->10.152.184.10:53: i/o timeout"}
```
This hinted to me that the coredns kube-dns service was not installed.

**Comment by jnummelin** [comment]
@doctorpangloss Can you check on the controller(s) how the related core-dns manifests are rendered by k0s, they are in `/var/lib/k0s/manifests/coredns/`

**Comment by doctorpangloss** [comment]
`coredns.yaml` has the wrong CIDR for the service IP. As I suggested this is probably the root cause, and also why it was probably rejected:
```

apiVersion: v1
kind: ServiceAccount
metadata:
  name: coredns
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    kubernetes.io/bootstrapping: rbac-defaults
  name: system-coredns
rules:
- apiGroups:
  - ""
  resources:
  - endpoints
  - services
  - pods
  - namespaces
  verbs:
  - list
  - watch
- apiGroups:
  - discovery.k8s.io
  resources:
  - endpointslices
  verbs:
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
  labels:
    kubernetes.io/bootstrapping: rbac-defaults
  name: system-coredns
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system-coredns
subjects:
- kind: ServiceAccount
  name: coredns
  namespace: kube-system
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns
  namespace: kube-system
data:
  Corefile: |
    .:53 {
        errors
        health
        ready
        kubernetes cluster.local in-addr.arpa ip6.arpa {
          pods insecure
          ttl 30
          fallthrough in-addr.arpa ip6.arpa
        }
        prometheus :9153
        forward . /etc/resolv.conf
        cache 30
        loop
        reload
        loadbalance
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: coredns
  namespace: kube-system
  labels:
    k8s-app: kube-dns
    kubernetes.io/name: "CoreDNS"
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  selector:
    matchLabels:
      k8s-app: kube-dns
  template:
    metadata:
      labels:
        k8s-app: kube-dns
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '9153'
    spec:
      serviceAccountName: coredns
      tolerations:
        - key: "CriticalAddonsOnly"
          operator: "Exists"
        - key: "node-role.kubernetes.io/master"
          operator: "Exists"
          effect: "NoSchedule"
      nodeSelector:
        kubernetes.io/os: linux
      # Require running coredns replicas on different nodes
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - topologyKey: "kubernetes.io/hostname"
            labelSelector:
              matchExpressions:
              - key: k8s-app
                operator: In
                values: ['kube-dns']
      containers:
      - name: coredns
        image: docker.io/coredns/coredns:1.10.1
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: 170Mi
          requests:
            cpu: 100m
            memory: 70Mi
        args: [ "-conf", "/etc/coredns/Corefile" ]
        volumeMounts:
        - name: config-volume
          mountPath: /etc/coredns
          readOnly: true
        ports:
        - containerPort: 53
          name: dns
          protocol: UDP
        - containerPort: 53
          name: dns-tcp
          protocol: TCP
        - containerPort: 9153
          name: metrics
          protocol: TCP
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            add:
            - NET_BIND_SERVICE
            drop:
            - all
          readOnlyRootFilesystem: true
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /ready
            port: 8181
            scheme: HTTP
          initialDelaySeconds: 0
          periodSeconds: 2
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 3
      dnsPolicy: Default
      volumes:
        - name: config-volume
          configMap:
            name: coredns
            items:
            - key: Corefile
              path: Corefile
---
apiVersion: v1
kind: Service
metadata:
  name: kube-dns
  namespace: kube-system
  annotations:
    prometheus.io/port: "9153"
    prometheus.io/scrape: "true"
  labels:
    k8s-app: kube-dns
    kubernetes.io/cluster-service: "true"
    kubernetes.io/name: "CoreDNS"
spec:
  selector:
    k8s-app: kube-dns
  clusterIP: 10.96.0.10
  ports:
  - name: dns
    port: 53
    protocol: UDP
  - name: dns-tcp
    port: 53
    protocol: TCP
  - name: metrics
    port: 9153
    protocol: TCP
```


new config (as I proceed on the journey to a working cluster), same issue
```
apiVersion: k0sctl.k0sproject.io/v1beta1
kind: Cluster
metadata:
  name: k0s-cluster
spec:
  hosts:
  - ssh:
      address: 10.2.0.19
      user: administrator
      port: 22
    role: controller+worker
    noTaints: true
    installFlags:
      - --disable-components=konnectivity-server
  - ssh:
      address: 10.2.0.20
      user: administrator
      port: 22
    role: controller+worker
    noTaints: true
    installFlags:
     - --disable-components=konnectivity-server
  - ssh:
      address: 10.2.0.22
      user: administrator
      port: 22
    role: controller+worker
    noTaints: true
    installFlags:
      - --disable-components=konnectivity-server
  - ssh:
      address: 10.2.0.65
      user: administrator
      port: 22
    role: worker
  k0s:
    version: 1.26.1+k0s.0
    dynamicConfig: true
    config:
      apiVersion: k0s.k0sproject.io/v1beta1
      kind: Cluster
      metadata:
        name: k0s
      spec:
        api:
          k0sApiPort: 9443
          port: 6443
          tunneledNetworkingMode: false
          extraArgs:
            service-cluster-ip-range: 10.152.184.0/24
            enable-aggregator-routing: "true"
          sans:
            # included from service CIDR to resolve calico issue
            - 10.152.184.1
        controllerManager:
          extraArgs:
            horizontal-pod-autoscaler-sync-period: 1s
        extensions:
          helm:
            charts: null
            repositories: null
          storage:
            create_default_storage_class: false
            type: external_storage
        images:
          calico:
            cni:
              image: docker.io/calico/cni
              version: v3.23.5
            kubecontrollers:
              image: docker.io/calico/kube-controllers
              version: v3.23.5
            node:
              image: docker.io/calico/node
              version: v3.23.5
          coredns:
            image: docker.io/coredns/coredns
            version: 1.10.1
          default_pull_policy: IfNotPresent
          konnectivity:
            image: quay.io/k0sproject/apiserver-network-proxy-agent
            version: 0.0.33-k0s
          kubeproxy:
            image: registry.k8s.io/kube-proxy
            version: v1.26.2
          kuberouter:
            cni:
              image: docker.io/cloudnativelabs/kube-router
              version: v1.5.1
            cniInstaller:
              image: quay.io/k0sproject/cni-node
              version: 1.1.1-k0s.0
          metricsserver:
            image: registry.k8s.io/metrics-server/metrics-server
            version: v0.6.2
          pushgateway:
            image: quay.io/k0sproject/pushgateway-ttl
            version: edge@sha256:7031f6bf6c957e2fdb496161fe3bea0a5bde3de800deeba7b2155187196ecbd9
        installConfig:
          users:
            etcdUser: etcd
            kineUser: kube-apiserver
            konnectivityUser: konnectivity-server
            kubeAPIserverUser: kube-apiserver
            kubeSchedulerUser: kube-scheduler
        konnectivity:
          adminPort: 8133
          agentPort: 8132
        network:
          calico:
            mode: bird
            overlay: Never
          clusterDomain: cluster.local
          dualStack: { }
          kubeProxy:
            iptables:
              masqueradeAll: true
              minSyncPeriod: 0s
              syncPeriod: 0s
            ipvs:
              minSyncPeriod: 0s
              syncPeriod: 0s
              tcpFinTimeout: 0s
              tcpTimeout: 0s
              udpTimeout: 0s
            metricsBindAddress: 0.0.0.0:10249
            mode: iptables
          kuberouter: null
          nodeLocalLoadBalancing:
            enabled: true
            envoyProxy:
              apiServerBindPort: 7443
              image:
                image: docker.io/envoyproxy/envoy-distroless
                version: v1.24.1
              konnectivityServerBindPort: 7132
            type: EnvoyProxy
          podCIDR: 10.3.0.0/16
          provider: calico
          serviceCIDR: 10.152.184.0/24
        scheduler: { }
        storage:
          type: etcd
        telemetry:
          enabled: true
```
