### ISSUE TITLE
$ Variable passed into k0s yaml is null or empty

### ISSUE THREAD

**Issue by sitamoni** [k0sproject/k0s#2885]
### Before creating an issue, make sure you've checked the following:

- [ ] You are running the latest released version of k0s
- [X] Make sure you've searched for existing issues, both open and closed
- [X] Make sure you've searched for PRs too, a fix might've been merged already
- [x] You're looking at docs for the released version, "main" branch docs are usually ahead of released versions.

### Platform

```shell
Linux 5.15.0-67-generic #74-Ubuntu 2023 x86_64 GNU/Linux
PRETTY_NAME="Ubuntu 22.04.2 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.2 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
```

### Version

1.26.1+k0s.0

### Sysinfo

<details><summary>`k0s sysinfo`</summary>
<pre>
➡️ Please replace this text with the output of `k0s sysinfo`. ⬅️
</pre>
</details>

### What happened?

I am using the k0s cluster and set up as described in this [repo](https://github.com/jlnhnng/k0s-hetzner). i added in the extensions my kubernetes resources and all have worked except the kube-prometheus-stack values, because it contains $. a snippet of the code is looking as following:

```
extensions:
          helm:
            repositories:
            - name: prometheus-community
              url: https://prometheus-community.github.io/helm-charts
            charts: 
            - name: k0s-monitoring
              chartname: prometheus-community/kube-prometheus-stack
              version: "45.7.0"
              namespace: prometheus
              values: |
                defaultRules:
                  create: false
                prometheus:
                  prometheusSpec:
                    additionalScrapeConfigs:
                      - job_name: "kubernetes-deployment-endpoints"
                        kubernetes_sd_configs:
                          - role: endpoints
                        relabel_configs:
                          - source_labels: 
                              [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
                            action: keep
                            regex: true
                          - source_labels: 
                              [__meta_kubernetes_pod_annotation_prometheus_io_scheme]
                            action: replace
                            target_label: __scheme__
                            regex: (https?)
                          - source_labels:  [__meta_kubernetes_pod_annotation_prometheus_io_path]
                            action: replace
                            target_label: __metrics_path__
                            regex: (.+)
                          - source_labels: 
                              [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
                            action: replace
                            target_label: __address__
                            regex: ([^:]+)(?::\d+)?;(\d+)
                            replacement: {$1:$2}
                           .....

```
After applying this config i get with  `helm get values k0s-monitoring -n prometheus --kubeconfig kubeconfig` the follwoing line related to replacement where the $ are:
`replacement: '{:}'`

### Steps to reproduce

1. Define $ somewhere inside the config yaml
2. setting douple "" symbol in the code
3. indent and nindent didn't work as well

### Expected behavior

Prometheus alerts and rules must be scraping the correct pod of the application. 

### Actual behavior

Unfunctional result due to $ symbol at replacement parameter:
```
additionalScrapeConfigs:
    - job_name: kubernetes-deployment-endpoints
      kubernetes_sd_configs:
      - role: endpoints
      relabel_configs:
      - action: keep
        regex: true
        source_labels:
        - __meta_kubernetes_pod_annotation_prometheus_io_scrape
      - action: replace
        regex: (https?)
        source_labels:
        - __meta_kubernetes_pod_annotation_prometheus_io_scheme
        target_label: __scheme__
      - action: replace
        regex: (.+)
        source_labels:
        - __meta_kubernetes_pod_annotation_prometheus_io_path
        target_label: __metrics_path__
      - action: replace
        regex: ([^:]+)(?::\d+)?;(\d+)
        replacement: '{:}'
        source_labels:
        - __address__
        - __meta_kubernetes_pod_annotation_prometheus_io_port
        target_label: __address__
      - action: replace
        source_labels:
        - __meta_kubernetes_namespace
        target_label: kubernetes_namespace
      - action: replace
        source_labels:
        - __meta_kubernetes_service_name
        target_label: kubernetes_service
      - action: replace
        source_labels:
        - __meta_kubernetes_pod_name
        target_label: kubernetes_pod
    - job_name: blackbox-kubernetes-ingresses
      kubernetes_sd_configs:
      - role: ingress
      metrics_path: /probe
      params:
        module:
        - http_2xx
      relabel_configs:
      - regex: (.+);(.+);(.+)
        replacement: :///
        source_labels:
        - __meta_kubernetes_ingress_scheme
        - __address__
        - __meta_kubernetes_ingress_label_blackbox_path
        target_label: __param_target
      - replacement: prometheus-blackbox-prometheus-blackbox-exporter:9115
        target_label: __address__
      - source_labels:
        - __param_target
        target_label: instance
      - action: labelmap
        regex: __meta_kubernetes_ingress_label_(.+)
      - source_labels:
        - __meta_kubernetes_namespace
        target_label: kubernetes_namespace
      - source_labels:
        - __meta_kubernetes_ingress_name
        target_label: ingress_name
    - job_name: exporter
      kubernetes_sd_configs:
      - role: pod
      metrics_path: /metrics
      relabel_configs:
      - action: keep
        regex: true
        source_labels:
        - __meta_kubernetes_pod_annotation_prometheus_io_exporter
      - action: replace
        source_labels:
        - __meta_kubernetes_namespace
        target_label: kubernetes_namespace
      - action: replace
        source_labels:
        - __meta_kubernetes_pod_name

```
