### ISSUE TITLE
how to upgrade helm charts defined in extensions helm section of k0s config

### ISSUE THREAD

**Issue by acollign** [k0sproject/k0s#3071]
### Is your feature request related to a problem? Please describe.

I couldn't find a documentation that explains how to upgrade helm charts defined in the extension section of the k0s config.

I am trying to update a deployed helm chart by updating the version value in the "extensions helm" configuration section.
```
  extensions:
    helm:
      concurrencyLevel: 5
      repositories:
        - name: traefik
          url: https://traefik.github.io/charts
      charts:
        - name: traefik
          chartname: traefik/traefik
          version: "23.0.1" # previously 20.5.3
          namespace: default
```

I noticed that k0s does not upgrade the corresponding deployment even after a cluster restart. The traefik deployment annotations still refers to "helm.sh/chart=traefik-20.5.3" 

https://docs.k0sproject.io/v1.27.1+k0s.0/helm-charts/

### Describe the solution you would like

It would be awesome if the extension manager would allow updating charts. Also if upgrading is not supported, then it would be great to mention it in the documentation https://docs.k0sproject.io/v1.27.1+k0s.0/helm-charts/

### Describe alternatives you've considered

Beside performing a fresh install, I have not found a working alternative
