### ISSUE TITLE
Prometheus is enabled using annotations by default on most components

### ISSUE THREAD

**Issue by rmannibucau** [k0sproject/k0s#3165]
### Before creating an issue, make sure you've checked the following:

- [X] You are running the latest released version of k0s
- [X] Make sure you've searched for existing issues, both open and closed
- [X] Make sure you've searched for PRs too, a fix might've been merged already
- [X] You're looking at docs for the released version, "main" branch docs are usually ahead of released versions.

### Platform

```shell
Not important (rh8)
```

### Version

1.2.26 - but master has it too

### Sysinfo

<details><summary>`k0s sysinfo`</summary>
<pre>
➡️ Please replace this text with the output of `k0s sysinfo`. ⬅️
</pre>
</details>

### What happened?

prometheus annotations enable scraping for kube-system components (https://github.com/k0sproject/k0s/blob/73a8a11d56c8e0c7535f45c22f9739440c12635e/pkg/component/controller/kubeproxy.go#L312), would be great to make it togglable and deactivable for instances where prometheus is not intended for core components, in particular when it does not work out of the box cause the node ip is not accessible to prometheus for ex.

### Steps to reproduce

Start k0s (in single node mode for ex) .

### Expected behavior

Check annotations of coredns, kube-proxy and kube-router, should get scrape=false for prometheus default setup

### Actual behavior

scrape=true

### Screenshots and logs

-

### Additional context

-

**Comment by jnummelin** [comment]
@rmannibucau Just to make sure I got it right, you'd want to have some config toggle to enable/disable k0s setting up `prometheus.io/scrape:` annotation value?

**Comment by alessiodionisi** [comment]
I've found `prometheus.io/scrape: true` annotation in these components:
- konnectivity
- coredns
- kubeproxy
- kuberouter
- pushgateway
- calico-node

I propose to add a boolean configuration under each component called `prometheusScrapeAnnotation` which by default will be true (for backwards compatibility).

Example `k0s.yaml`:
```yaml
apiVersion: k0s.k0sproject.io/v1beta1
kind: ClusterConfig
metadata:
  name: k0s
spec:
  ...
  coreDNS:
    prometheusScrapeAnnotation: true
  konnectivity:
    ...
    prometheusScrapeAnnotation: true
  network:
    ...
    kubeProxy:
      ...
      prometheusScrapeAnnotation: true
    kuberouter:
      ...
      prometheusScrapeAnnotation: true
```
