### ISSUE TITLE
Configuration of Image repository for pause

### ISSUE THREAD

**Issue by liangyuanpeng** [k0sproject/k0s#3183]
### Is your feature request related to a problem? Please describe.

Hi teams, Thanks for your work and k0s is a great project !

In my case, I want to set mirror images for `registry.k8s.io`. 

Today, the k0s have config of `spec.images.repository` for all of image, and i just want to config for `registry.k8s.io`.

Remind me if i missed something,Thanks!

### Describe the solution you would like

Add a config for mirror images host , like 

```yaml
spec:
  images:
    mirrors:
      registry.k8s.io: registry.my.local
```

Or just add a config for pause image, like :

```yaml
spec:
  images:
    pause:
      image: registry.my.local/pause
```
