### ISSUE TITLE
Updates to helm extensions are not applied

### ISSUE THREAD

**Issue by jannispl** [k0sproject/k0s#3282]
### Before creating an issue, make sure you've checked the following:

- [X] You are running the latest released version of k0s
- [X] Make sure you've searched for existing issues, both open and closed
- [X] Make sure you've searched for PRs too, a fix might've been merged already
- [X] You're looking at docs for the released version, "main" branch docs are usually ahead of released versions.

### Platform

```shell
Linux 6.1.0-9-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.27-1 (2023-05-08) x86_64 GNU/Linux
PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
NAME="Debian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

### Version

1.27.3+k0s.0

### What happened?

I installed k0s using k0sctl, providing the k0s configuration inside of `k0sctl.yaml`. Here I specified that I want to install Traefik as a Helm extension, which worked correctly - once the cluster was bootstrapped, there was a Traefik instance up and running.

Then I went ahead and customized `values` inside of `k0sctl.yaml`, adjusting things like the replica count and adding `hostPort`s.
After applying my changes using `k0sctl apply`, I found that there is still just a single replica of Traefik running.

Browsing through existing issues I found #3071 - which made me aware of the `charts.helm.k0sproject.io` CRD, which I found inside `kube-system`. Unfortunately I don't have the exact console output anymore, but I could gather from a `kubectl describe` on this CRD that it received the new configuration in its `spec`, however in `status` it said something along the lines of `cannot re-use a name that is still in use`, making me think it tried to perform a fresh install for Traefik instead of an upgrade.

### Steps to reproduce

1. install cluster using `k0sctl apply` with Traefik as Helm extension, `.spec.extensions.helm`:
```
            repositories:
            - name: traefik
              url: https://traefik.github.io/charts
            charts:
            - name: traefik
              chartname: traefik/traefik
              version: "23.1.0"
              namespace: traefik
```

2. after cluster is bootstrapped, modify `values` for Helm extension in k0s config:
```
              values: |
                deployment:
                  replicas: 3
                ports:
                  traefik:
                    hostPort: 9000
                  web:
                    hostPort: 8000
                  metrics:
                    hostPort: 9100
```
3. run `k0sctl apply` again

### Expected behavior

The Helm installation of Traefik is upgraded with the new values.

### Actual behavior

The original Traefik configuration was retained.
