### ISSUE TITLE
Worker node API certificates default to 127.0.0.1 after provisioning through k0sctl

### ISSUE THREAD

**Issue by kimattree** [k0sproject/k0s#3300]
### Before creating an issue, make sure you've checked the following:

- [X] You are running the latest released version of k0s
- [X] Make sure you've searched for existing issues, both open and closed
- [X] Make sure you've searched for PRs too, a fix might've been merged already
- [X] You're looking at docs for the released version, "main" branch docs are usually ahead of released versions.

### Platform

```shell
Linux 5.14.0-162.6.1.el9_1.0.1.x86_64 #1 SMP PREEMPT_DYNAMIC Mon Nov 28 18:44:09 UTC 2022 x86_64 GNU/Linux
NAME="Rocky Linux"
VERSION="9.1 (Blue Onyx)"
ID="rocky"
ID_LIKE="rhel centos fedora"
VERSION_ID="9.1"
PLATFORM_ID="platform:el9"
PRETTY_NAME="Rocky Linux 9.1 (Blue Onyx)"
ANSI_COLOR="0;32"
LOGO="fedora-logo-icon"
CPE_NAME="cpe:/o:rocky:rocky:9::baseos"
HOME_URL="https://rockylinux.org/"
BUG_REPORT_URL="https://bugs.rockylinux.org/"
ROCKY_SUPPORT_PRODUCT="Rocky-Linux-9"
ROCKY_SUPPORT_PRODUCT_VERSION="9.1"
REDHAT_SUPPORT_PRODUCT="Rocky Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="9.1"
```

### Version

v1.27.3+k0s.0

### Sysinfo

<details><summary>`k0s sysinfo`</summary>
<pre>
➡️ Machine ID: "1c5f97a3ec1fdc391ca3872c67e5c6cd6246f3ddd3fb43fdce6be9783cc7446a" (from machine) (pass)
Total memory: 219.7 GiB (pass)
Disk space available for /var/lib/k0s: 23.9 GiB (pass)
Operating system: Linux (pass)
  Linux kernel release: 5.14.0-162.6.1.el9_1.0.1.x86_64 (pass)
  Max. file descriptors per process: current: 1048576 / max: 1048576 (pass)
  Executable in path: modprobe: /usr/sbin/modprobe (pass)
  /proc file system: mounted (0x9fa0) (pass)
  Control Groups: version 2 (pass)
    cgroup controller "cpu": available (pass)
    cgroup controller "cpuacct": available (via cpu in version 2) (pass)
    cgroup controller "cpuset": available (pass)
    cgroup controller "memory": available (pass)
    cgroup controller "devices": available (assumed) (pass)
    cgroup controller "freezer": available (assumed) (pass)
    cgroup controller "pids": available (pass)
    cgroup controller "hugetlb": available (pass)
    cgroup controller "blkio": available (via io in version 2) (pass)
  CONFIG_CGROUPS: Control Group support: built-in (pass)
    CONFIG_CGROUP_FREEZER: Freezer cgroup subsystem: built-in (pass)
    CONFIG_CGROUP_PIDS: PIDs cgroup subsystem: built-in (pass)
    CONFIG_CGROUP_DEVICE: Device controller for cgroups: built-in (pass)
    CONFIG_CPUSETS: Cpuset support: built-in (pass)
    CONFIG_CGROUP_CPUACCT: Simple CPU accounting cgroup subsystem: built-in (pass)
    CONFIG_MEMCG: Memory Resource Controller for Control Groups: built-in (pass)
    CONFIG_CGROUP_HUGETLB: HugeTLB Resource Controller for Control Groups: built-in (pass)
    CONFIG_CGROUP_SCHED: Group CPU scheduler: built-in (pass)
      CONFIG_FAIR_GROUP_SCHED: Group scheduling for SCHED_OTHER: built-in (pass)
        CONFIG_CFS_BANDWIDTH: CPU bandwidth provisioning for FAIR_GROUP_SCHED: built-in (pass)
    CONFIG_BLK_CGROUP: Block IO controller: built-in (pass)
  CONFIG_NAMESPACES: Namespaces support: built-in (pass)
    CONFIG_UTS_NS: UTS namespace: built-in (pass)
    CONFIG_IPC_NS: IPC namespace: built-in (pass)
    CONFIG_PID_NS: PID namespace: built-in (pass)
    CONFIG_NET_NS: Network namespace: built-in (pass)
  CONFIG_NET: Networking support: built-in (pass)
    CONFIG_INET: TCP/IP networking: built-in (pass)
      CONFIG_IPV6: The IPv6 protocol: built-in (pass)
    CONFIG_NETFILTER: Network packet filtering framework (Netfilter): built-in (pass)
      CONFIG_NETFILTER_ADVANCED: Advanced netfilter configuration: built-in (pass)
      CONFIG_NF_CONNTRACK: Netfilter connection tracking support: module (pass)
      CONFIG_NETFILTER_XTABLES: Netfilter Xtables support: built-in (pass)
        CONFIG_NETFILTER_XT_TARGET_REDIRECT: REDIRECT target support: module (pass)
        CONFIG_NETFILTER_XT_MATCH_COMMENT: "comment" match support: module (pass)
        CONFIG_NETFILTER_XT_MARK: nfmark target and match support: module (pass)
        CONFIG_NETFILTER_XT_SET: set target and match support: module (pass)
        CONFIG_NETFILTER_XT_TARGET_MASQUERADE: MASQUERADE target support: module (pass)
        CONFIG_NETFILTER_XT_NAT: "SNAT and DNAT" targets support: module (pass)
        CONFIG_NETFILTER_XT_MATCH_ADDRTYPE: "addrtype" address type match support: module (pass)
        CONFIG_NETFILTER_XT_MATCH_CONNTRACK: "conntrack" connection tracking match support: module (pass)
        CONFIG_NETFILTER_XT_MATCH_MULTIPORT: "multiport" Multiple port match support: module (pass)
        CONFIG_NETFILTER_XT_MATCH_RECENT: "recent" match support: module (pass)
        CONFIG_NETFILTER_XT_MATCH_STATISTIC: "statistic" match support: module (pass)
      CONFIG_NETFILTER_NETLINK: module (pass)
      CONFIG_NF_NAT: module (pass)
      CONFIG_IP_SET: IP set support: module (pass)
        CONFIG_IP_SET_HASH_IP: hash:ip set support: module (pass)
        CONFIG_IP_SET_HASH_NET: hash:net set support: module (pass)
      CONFIG_IP_VS: IP virtual server support: module (pass)
        CONFIG_IP_VS_NFCT: Netfilter connection tracking: built-in (pass)
      CONFIG_NF_CONNTRACK_IPV4: IPv4 connetion tracking support (required for NAT): unknown (warning)
      CONFIG_NF_REJECT_IPV4: IPv4 packet rejection: module (pass)
      CONFIG_NF_NAT_IPV4: IPv4 NAT: unknown (warning)
      CONFIG_IP_NF_IPTABLES: IP tables support: module (pass)
        CONFIG_IP_NF_FILTER: Packet filtering: module (pass)
          CONFIG_IP_NF_TARGET_REJECT: REJECT target support: module (pass)
        CONFIG_IP_NF_NAT: iptables NAT support: module (pass)
        CONFIG_IP_NF_MANGLE: Packet mangling: module (pass)
      CONFIG_NF_DEFRAG_IPV4: module (pass)
      CONFIG_NF_CONNTRACK_IPV6: IPv6 connetion tracking support (required for NAT): unknown (warning)
      CONFIG_NF_NAT_IPV6: IPv6 NAT: unknown (warning)
      CONFIG_IP6_NF_IPTABLES: IP6 tables support: module (pass)
        CONFIG_IP6_NF_FILTER: Packet filtering: module (pass)
        CONFIG_IP6_NF_MANGLE: Packet mangling: module (pass)
        CONFIG_IP6_NF_NAT: ip6tables NAT support: module (pass)
      CONFIG_NF_DEFRAG_IPV6: module (pass)
    CONFIG_BRIDGE: 802.1d Ethernet Bridging: module (pass)
      CONFIG_LLC: module (pass)
      CONFIG_STP: module (pass)
  CONFIG_EXT4_FS: The Extended 4 (ext4) filesystem: module (pass)
  CONFIG_PROC_FS: /proc file system support: built-in (pass) ⬅️
</pre>
</details>

### What happened?

After provisioning a cluster with 3 masters and 3 worker nodes, the worker nodes come up with a temporary bootstrap certificate:

```
[root@k0sctl ~]# echo | openssl s_client -showcerts -servername 192.168.79.11 -connect 192.168.79.11:10250 2>/dev/null | openssl x509 -inform pem -noout -text |grep -A 1 "X509v3 Subject Alternative Name:"
            X509v3 Subject Alternative Name: 
                DNS:worker-01.rli.local, IP Address:192.168.79.11
```

after about 2 mins the main certificate is generated, but it defaults to localhost/127.0.0.1

```
[root@k0sctl ~]# echo | openssl s_client -showcerts -servername 192.168.79.11 -connect 192.168.79.11:10250 2>/dev/null | openssl x509 -inform pem -noout -text |grep -A 1 "X509v3 Subject Alternative Name:"
            X509v3 Subject Alternative Name: 
                DNS:localhost, DNS:localhost, IP Address:127.0.0.1
```

### Steps to reproduce

1. k0sctl install with config file:

```
apiVersion: k0sctl.k0sproject.io/v1beta1
kind: Cluster
metadata:
  name: k0s-cluster
spec:
  hosts:
  - ssh:
      address: 192.168.79.1
      user: root
      port: 22
      keyPath: /root/.ssh/id_ecdsa
    role: controller
    hostname: master-01.rli.local
    installFlags:
    - --force
  - ssh:
      address: 192.168.79.2
      user: root
      port: 22
      keyPath: /root/.ssh/id_ecdsa
    role: controller
    hostname: master-02.rli.local
    installFlags:
    - --force
  - ssh:
      address: 192.168.79.3
      user: root
      port: 22
      keyPath: /root/.ssh/id_ecdsa
    role: controller
    hostname: master-03.rli.local
    installFlags:
    - --force
  - ssh:
      address: 192.168.79.11
      user: root
      port: 22
      keyPath: /root/.ssh/id_ecdsa
    role: worker
    privateInterface: ens192
    privateAddress: 192.168.79.11
    installFlags:
    - --force
    - --debug
    - --kubelet-extra-args=--node-ip=192.168.79.11
  - ssh:
      address: 192.168.79.12
      user: root
      port: 22
      keyPath: /root/.ssh/id_ecdsa
    role: worker
    privateInterface: ens192
    privateAddress: 192.168.79.12
    installFlags:
    - --force
    - --kubelet-extra-args=--node-ip=192.168.79.12
  - ssh:
      address: 192.168.79.13
      user: root
      port: 22
      keyPath: /root/.ssh/id_ecdsa
    role: worker
    privateInterface: ens192
    privateAddress: 192.168.79.13
    installFlags:
    - --force
    - --kubelet-extra-args=--node-ip=192.168.79.13
  k0s:
    version: v1.27.3+k0s.0
    dynamicConfig: false
    config:
      spec:
        network:
          podCIDR: 10.244.0.0/16
          serviceCIDR: 10.96.0.0/12
          provider: kuberouter
        api:
          externalAddress: 192.168.79.1
          sans:
            - 192.168.79.1
            - 192.168.79.2
            - 192.168.79.3
        telemetry:
          enabled: false
```

2. kubectl logs of a pod running on a worker node
3. openssl check the certificate running on the worker node for SANs

### Expected behavior

Worker nodes have a valid and working certificate when accessing the API on port 10250

### Actual behavior

When attempting to look at pod logs or any other interaction that requires talking to API port 10250 with TLS, i get this:

```
[root@k0sctl ~]# kk -n kube-system logs kube-proxy-zjkz6
Error from server: Get "https://192.168.79.11:10250/containerLogs/kube-system/kube-proxy-zjkz6/kube-proxy": tls: failed to verify certificate: x509: certificate is valid for 127.0.0.1, not 192.168.79.11
```

reseting and retrying the worker node(s) has no effect.
