### ISSUE TITLE
FeatureGates moved to GA can break some components

### ISSUE THREAD

**Issue by jnummelin** [k0sproject/k0s#3364]
### Before creating an issue, make sure you've checked the following:

- [X] You are running the latest released version of k0s
- [X] Make sure you've searched for existing issues, both open and closed
- [X] Make sure you've searched for PRs too, a fix might've been merged already
- [X] You're looking at docs for the released version, "main" branch docs are usually ahead of released versions.

### Platform

```shell
Linux 5.15.0-73-generic #80-Ubuntu SMP Mon May 15 15:18:26 UTC 2023 x86_64 GNU/Linux
PRETTY_NAME="Ubuntu 22.04.2 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.2 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
```

### Version

1.27.4

### What happened?

Consider the following config:

```yaml
spec:
  network:
    provider: "calico"
    calico:
      overlay: Always
      # More configuration of Calico get be specified here
  featureGates:
    - name: GRPCContainerProbe
      enabled: true
      components: ["kubelet", "kube-controller-manager", "kube-apiserver"]
```

As `kube-scheduler` is NOT marked as component for `GRPCContainerProbe` it will get the flag set as `--featuregates=GRPCContainerProbe=false`. Now as this specific FG is GA kube-scheduler is actually enforcing it:

```
cannot set feature gate GRPCContainerProbe to false, feature is locked to true
```

This unfortunately renders kube-scheduler in crashloop.

### Steps to reproduce

1.
2.
3.

### Expected behavior

In case a component is NOT marked for a feature gate I'd expect it not to have any flag for it. So instead of marking it for `false` value I'd expect it to be completely omitted.

### Actual behavior

kube-scheduler gets `--featuregates=GRPCContainerProbe=false`
