### ISSUE TITLE
Unable to get a HA controller cluster running in v0.5.0 or v0.6.0

### ISSUE THREAD

**Issue by mbentley** [k0sproject/k0s#338]
**Version**
```
$ mke version
v0.6.0
```
**Platform**
Which platform did you run mke on?
```
$ lsb_release -a
n/a; running in an Alpine 3.12.1 based docker container
```

```
FROM alpine:latest
MAINTAINER Matt Bentley <mbentley@mbentley.net>

RUN apk add --no-cache coreutils findutils iptables

COPY mke-v0.6.0-amd64 /usr/local/bin/mke
COPY entrypoint.sh /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh","/usr/local/bin/mke"]
CMD ["help"]
```

My entrypoint is pretty basic, just a hack I've used in the past with mount propagation for issues I've seen in the past with dind as well as generating an `/etc/machine-id` file

```
#!/bin/sh

# set mount propagation
if [ -n "${MOUNT_PROPAGATION}" ]
then
  for MOUNT in ${MOUNT_PROPAGATION}
  do
    echo "Mounting ${MOUNT} as 'rshared'..."
    mount --make-rshared "${MOUNT}"
  done
fi

# generate a machine-id if missing
if [ ! -f "/etc/machine-id" ]
then
  sed 's/-//g' < /proc/sys/kernel/random/uuid > /etc/machine-id
fi

exec "${@}"
```

**What happened?**

When trying to set up an HA control plane, not all of the pods come up successfully.  I typically see that at least one calico pod doesn't come up on all of the nodes.  Typically in a 3 node HA cluster, I see one of the calico-node-* pod logs shows things like this:
```
2020-10-29T11:17:16.589226969Z 2020-10-29 11:17:16.588 [INFO][51] tunnel-ip-allocator/watchercache.go 187: Failed to perform list of current data during resync ListRoot="/calico/resources/v3/projectcalico.org/nodes/mke03" error=connection is unauthorized: Unauthorized
2020-10-29T11:17:16.589267800Z 2020-10-29 11:17:16.588 [INFO][51] tunnel-ip-allocator/watchercache.go 187: Failed to perform list of current data during resync ListRoot="/calico/resources/v3/projectcalico.org/ippools" error=connection is unauthorized: Unauthorized
2020-10-29T11:17:17.591400731Z 2020-10-29 11:17:17.591 [INFO][51] tunnel-ip-allocator/watchercache.go 187: Failed to perform list of current data during resync ListRoot="/calico/resources/v3/projectcalico.org/nodes/mke03" error=connection is unauthorized: Unauthorized
2020-10-29T11:17:17.591460285Z 2020-10-29 11:17:17.591 [INFO][51] tunnel-ip-allocator/watchercache.go 187: Failed to perform list of current data during resync ListRoot="/calico/resources/v3/projectcalico.org/ippools" error=connection is unauthorized: Unauthorized
2020-10-29T11:17:18.593491795Z 2020-10-29 11:17:18.593 [INFO][51] tunnel-ip-allocator/watchercache.go 187: Failed to perform list of current data during resync ListRoot="/calico/resources/v3/projectcalico.org/nodes/mke03" error=connection is unauthorized: Unauthorized
2020-10-29T11:17:18.593551148Z 2020-10-29 11:17:18.593 [INFO][51] tunnel-ip-allocator/watchercache.go 187: Failed to perform list of current data during resync ListRoot="/calico/resources/v3/projectcalico.org/ippools" error=connection is unauthorized: Unauthorized
2020-10-29T11:17:19.595559239Z 2020-10-29 11:17:19.595 [INFO][51] tunnel-ip-allocator/watchercache.go 187: Failed to perform list of current data during resync ListRoot="/calico/resources/v3/projectcalico.org/ippools" error=connection is unauthorized: Unauthorized
2020-10-29T11:17:19.595653657Z 2020-10-29 11:17:19.595 [INFO][51] tunnel-ip-allocator/watchercache.go 187: Failed to perform list of current data during resync ListRoot="/calico/resources/v3/projectcalico.org/nodes/mke03" error=connection is unauthorized: Unauthorized
2020-10-29T11:17:20.196973497Z 2020-10-29 11:17:20.196 [INFO][49] felix/int_dataplane.go 1300: Applying dataplane updates
```

you can see other things in services like coredns.  it's always something about unauthorized connections in `coredns`:
```
1 reflector.go:178] pkg/mod/k8s.io/client-go@v0.18.3/tools/cache/reflector.go:125: Failed to list *v1.Service: Unauthorized
```

or things like this in the mke server logs:
```
time="2020-10-24 17:34:26" level=info msg="E1024 17:34:26.672585      19 authentication.go:53] Unable to authenticate the request due to an error: [invalid bearer token, square/go-jose: error in cryptographic primitive]" component=kube-apiserver
```

also things like `konnectivity` showing:
```
Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "058389970c19dabb3b69de03f333fdf00d2bd98751e86d319c4d38761b74de2b": error getting ClusterInformation: connection is unauthorized: Unauthorized
```

I've tried different ways of generating tokens for the additional controllers - generating them uniquely for each node, generating one that doesn't expire.  Doesn't seem to make a difference.  I've also tried to set up my 3 controllers as HA without workers and then join specific k8s worker nodes and I still see the issue with my workers.

**How To Reproduce**

I can reproduce this regularly with a 3 controller cluster where each controller is also running as a worker.  One node doesn't come up cleanly in k8s.

`mke01.yaml`:
```
apiVersion: mke.mirantis.com/v1beta1
kind: Cluster
metadata:
  name: mke
spec:
  storage:
    type: etcd
    etcd:
      peerAddress: 192.168.3.91
  api:
    address: 192.168.3.91
    sans:
      - 192.168.3.91
      - mke.demo.dckr.org
      - mke.office.mbentley.net
      - mke01.office.mbentley.net
  network:
    provider: calico
    podCIDR: "10.244.0.0/16"
    serviceCIDR: "10.96.0.0/12"
    calico:
      mode: vxlan
      mtu: 1450
      vxlanPort: 4789
      vxlanVNI: 4096
  podSecurityPolicy:
    defaultPolicy: 00-mke-privileged
```

`mke02.yaml`:
```
apiVersion: mke.mirantis.com/v1beta1
kind: Cluster
metadata:
  name: mke
spec:
  storage:
    type: etcd
    etcd:
      peerAddress: 192.168.3.92
  api:
    address: 192.168.3.92
    sans:
      - 192.168.3.92
      - mke.demo.dckr.org
      - mke.office.mbentley.net
      - mke02.office.mbentley.net
  network:
    provider: calico
    podCIDR: "10.244.0.0/16"
    serviceCIDR: "10.96.0.0/12"
    calico:
      mode: vxlan
      mtu: 1450
      vxlanPort: 4789
      vxlanVNI: 4096
  podSecurityPolicy:
    defaultPolicy: 00-mke-privileged
```

`mke03.yaml`:
```
apiVersion: mke.mirantis.com/v1beta1
kind: Cluster
metadata:
  name: mke
spec:
  storage:
    type: etcd
    etcd:
      peerAddress: 192.168.3.93
  api:
    address: 192.168.3.93
    sans:
      - 192.168.3.93
      - mke.demo.dckr.org
      - mke.office.mbentley.net
      - mke03.office.mbentley.net
  network:
    provider: calico
    podCIDR: "10.244.0.0/16"
    serviceCIDR: "10.96.0.0/12"
    calico:
      mode: vxlan
      mtu: 1450
      vxlanPort: 4789
      vxlanVNI: 4096
  podSecurityPolicy:
    defaultPolicy: 00-mke-privileged
```

I wrote a script to launch a cluster:
```
#!/bin/bash

main() {
  kill_all
  launch_controllers
  #launch_workers
}

kill_all() {
  docker kill mke0{1..8}
  docker rm mke0{1..8}
  rm -rf /mnt/dind_mke/mke0{1..8}
}

sleepy_time() {
  echo "no sleep"
  #echo "sleep 180"
  #sleep 180
}

launch_controllers() {
  # controllers are workers
  MKE_CONTROLLER_WORKER="true"
  #MKE_CONTROLLER_WORKER="false"

  # launch first controller
  launch_node 1 "server --enable-worker=${MKE_CONTROLLER_WORKER} --config /mke.yaml"

  # launch second & third controller
  for i in {2..3}
  do
    launch_node "${i}" "server --enable-worker=${MKE_CONTROLLER_WORKER} --config /mke.yaml $(docker exec mke01 mke token create --config /mke.yaml --role=controller)"
  done
}

launch_workers() {
  # join workers
  for i in {4..8}
  do
    launch_node "${i}" "worker $(docker exec mke01 mke token create --config /mke.yaml --role=worker)"
  done
}

launch_node() {
  # set variables
  i="${1}"
  MKE_CMD="${2}"

  # check to see if this is going to be a controller or worker
  if [ "$(echo "${MKE_CMD}" | awk '{print $1}')" = "server" ]
  then
    MKE_CONTROLLER="true"
    MKE_YAML="-v /mnt/dind_mke/mke0${i}.yaml:/mke.yaml:ro"
  else
    MKE_CONTROLLER="false"
    MKE_YAML=""
  fi

  docker kill "mke0${i}"
  docker rm -f "mke0${i}"
  rm -rf "/mnt/dind_mke/mke0${i}"
  mkdir -p "/mnt/dind_mke/mke0${i}"
  dbus-uuidgen --ensure="/mnt/dind_mke/mke0${i}/etc-machine-id"
  docker run -d \
    --name "mke0${i}" \
    --hostname "mke0${i}" \
    --net macvlan1 \
    --ip "192.168.3.9${i}" \
    --restart unless-stopped \
    --privileged \
    --cpus 4 \
    --memory-reservation 12g \
    --memory 16g \
    --memory-swap 17g \
    --mount type=bind,source=/lib/modules,destination=/lib/modules,readonly=true \
    --mount type=bind,source=/etc/resolv.conf,destination=/etc/resolv.conf,readonly=true \
    -v "/mnt/dind_mke/mke0${i}/etc-machine-id:/etc/machine-id:ro" \
    ${MKE_YAML} \
    -v "/mnt/dind_mke/mke0${i}/root:/root" \
    -v "/mnt/dind_mke/mke0${i}/etc-cni:/etc/cni" \
    -v "/mnt/dind_mke/mke0${i}/opt-cni:/opt/cni" \
    -v "/mnt/dind_mke/containerd.toml:/etc/mke/containerd.toml:ro" \
    -v "/mnt/dind_mke/mke0${i}/opt-containerd:/opt/containerd" \
    -v "/mnt/dind_mke/mke0${i}/usr-libexec:/usr/libexec" \
    -v "/mnt/dind_mke/mke0${i}/var-lib-calico:/var/lib/calico" \
    -v "/mnt/dind_mke/mke0${i}/var-lib-cni:/var/lib/cni" \
    -v "/mnt/dind_mke/mke0${i}/var-lib-kubelet:/var/lib/kubelet" \
    -v "/mnt/dind_mke/mke0${i}/var-lib-mke:/var/lib/mke" \
    -v "/mnt/dind_mke/mke0${i}/var-log:/var/log" \
    --tmpfs /run \
    mbentley/mke:v0.6.0 \
    ${MKE_CMD}

  # wait until the kubeapi is available if it is a controller
  if [ "${MKE_CONTROLLER}" = "true" ]
  then
    echo -n "Waiting for kubeapi to be available on mke0${i}..."
    while [ "$(curl -ks -m 1 "https://192.168.3.9${i}:6443/healthz" > /dev/null; echo $?)" != "0" ]
    do
      echo -n "."
      sleep 1
    done

    echo "done"

    # output kubeconfig
    docker exec "mke0${i}" cat /var/lib/mke/pki/admin.conf
  fi

  # sleep
  sleepy_time
}

main "${@}"
```

**Expected behavior**
Cluster should come up cleanly.

**Screenshots & Logs**
Logs from each controller:
[mke01.txt](https://github.com/Mirantis/mke/files/5457954/mke01.txt)
[mke02.txt](https://github.com/Mirantis/mke/files/5457955/mke02.txt)
[mke03.txt](https://github.com/Mirantis/mke/files/5457956/mke03.txt)

**Additional context**
If it helps, I can spin up an example cluster and provide a kubeconfig.  I've made my cluster available over the internet.
