### ISSUE TITLE
Single node setup doesn't seem to work in docker

### ISSUE THREAD

**Issue by nxy7** [k0sproject/k0s#3401]
### Before creating an issue, make sure you've checked the following:

- [X] You are running the latest released version of k0s
- [X] Make sure you've searched for existing issues, both open and closed
- [X] Make sure you've searched for PRs too, a fix might've been merged already
- [X] You're looking at docs for the released version, "main" branch docs are usually ahead of released versions.

### Platform

```shell
Docker inside NixOS 22.11 (Raccoon)
```

### Version

v1.27.4+k0s.0

### Sysinfo

```
Machine ID: "943679fe8340f783066f4878386312a039d025e369a3c0022a3257bff4b299d8" (from machine) (pass)
Total memory: 15.5 GiB (pass)
Disk space available for /var/lib/k0s: 1.2 TiB (pass)
Operating system: Linux (pass)
  Linux kernel release: 6.4.10 (pass)
  Max. file descriptors per process: current: 1048576 / max: 1048576 (pass)
  Executable in path: modprobe: /sbin/modprobe (pass)
  /proc file system: mounted (0x9fa0) (pass)
  Control Groups: version 2 (pass)
    cgroup controller "cpu": available (pass)
    cgroup controller "cpuacct": available (via cpu in version 2) (pass)
    cgroup controller "cpuset": available (pass)
    cgroup controller "memory": available (pass)
    cgroup controller "devices": available (assumed) (pass)
    cgroup controller "freezer": available (assumed) (pass)
    cgroup controller "pids": available (pass)
    cgroup controller "hugetlb": available (pass)
    cgroup controller "blkio": available (via io in version 2) (pass)
  CONFIG_CGROUPS: Control Group support: built-in (pass)
    CONFIG_CGROUP_FREEZER: Freezer cgroup subsystem: built-in (pass)
    CONFIG_CGROUP_PIDS: PIDs cgroup subsystem: built-in (pass)
    CONFIG_CGROUP_DEVICE: Device controller for cgroups: built-in (pass)
    CONFIG_CPUSETS: Cpuset support: built-in (pass)
    CONFIG_CGROUP_CPUACCT: Simple CPU accounting cgroup subsystem: built-in (pass)
    CONFIG_MEMCG: Memory Resource Controller for Control Groups: built-in (pass)
    CONFIG_CGROUP_HUGETLB: HugeTLB Resource Controller for Control Groups: built-in (pass)
    CONFIG_CGROUP_SCHED: Group CPU scheduler: built-in (pass)
      CONFIG_FAIR_GROUP_SCHED: Group scheduling for SCHED_OTHER: built-in (pass)
        CONFIG_CFS_BANDWIDTH: CPU bandwidth provisioning for FAIR_GROUP_SCHED: built-in (pass)
    CONFIG_BLK_CGROUP: Block IO controller: built-in (pass)
  CONFIG_NAMESPACES: Namespaces support: built-in (pass)
    CONFIG_UTS_NS: UTS namespace: built-in (pass)
    CONFIG_IPC_NS: IPC namespace: built-in (pass)
    CONFIG_PID_NS: PID namespace: built-in (pass)
    CONFIG_NET_NS: Network namespace: built-in (pass)
  CONFIG_NET: Networking support: built-in (pass)
    CONFIG_INET: TCP/IP networking: built-in (pass)
      CONFIG_IPV6: The IPv6 protocol: built-in (pass)
    CONFIG_NETFILTER: Network packet filtering framework (Netfilter): built-in (pass)
      CONFIG_NETFILTER_ADVANCED: Advanced netfilter configuration: built-in (pass)
      CONFIG_NF_CONNTRACK: Netfilter connection tracking support: module (pass)
      CONFIG_NETFILTER_XTABLES: Netfilter Xtables support: module (pass)
        CONFIG_NETFILTER_XT_TARGET_REDIRECT: REDIRECT target support: module (pass)
        CONFIG_NETFILTER_XT_MATCH_COMMENT: "comment" match support: module (pass)
        CONFIG_NETFILTER_XT_MARK: nfmark target and match support: module (pass)
        CONFIG_NETFILTER_XT_SET: set target and match support: module (pass)
        CONFIG_NETFILTER_XT_TARGET_MASQUERADE: MASQUERADE target support: module (pass)
        CONFIG_NETFILTER_XT_NAT: "SNAT and DNAT" targets support: module (pass)
        CONFIG_NETFILTER_XT_MATCH_ADDRTYPE: "addrtype" address type match support: module (pass)
        CONFIG_NETFILTER_XT_MATCH_CONNTRACK: "conntrack" connection tracking match support: module (pass)
        CONFIG_NETFILTER_XT_MATCH_MULTIPORT: "multiport" Multiple port match support: module (pass)
        CONFIG_NETFILTER_XT_MATCH_RECENT: "recent" match support: module (pass)
        CONFIG_NETFILTER_XT_MATCH_STATISTIC: "statistic" match support: module (pass)
      CONFIG_NETFILTER_NETLINK: module (pass)
      CONFIG_NF_NAT: module (pass)
      CONFIG_IP_SET: IP set support: module (pass)
        CONFIG_IP_SET_HASH_IP: hash:ip set support: module (pass)
        CONFIG_IP_SET_HASH_NET: hash:net set support: module (pass)
      CONFIG_IP_VS: IP virtual server support: module (pass)
        CONFIG_IP_VS_NFCT: Netfilter connection tracking: built-in (pass)
      CONFIG_NF_CONNTRACK_IPV4: IPv4 connetion tracking support (required for NAT): unknown (warning)
      CONFIG_NF_REJECT_IPV4: IPv4 packet rejection: module (pass)
      CONFIG_NF_NAT_IPV4: IPv4 NAT: unknown (warning)
      CONFIG_IP_NF_IPTABLES: IP tables support: module (pass)
        CONFIG_IP_NF_FILTER: Packet filtering: module (pass)
          CONFIG_IP_NF_TARGET_REJECT: REJECT target support: module (pass)
        CONFIG_IP_NF_NAT: iptables NAT support: module (pass)
        CONFIG_IP_NF_MANGLE: Packet mangling: module (pass)
      CONFIG_NF_DEFRAG_IPV4: module (pass)
      CONFIG_NF_CONNTRACK_IPV6: IPv6 connetion tracking support (required for NAT): unknown (warning)
      CONFIG_NF_NAT_IPV6: IPv6 NAT: unknown (warning)
      CONFIG_IP6_NF_IPTABLES: IP6 tables support: module (pass)
        CONFIG_IP6_NF_FILTER: Packet filtering: module (pass)
        CONFIG_IP6_NF_MANGLE: Packet mangling: module (pass)
        CONFIG_IP6_NF_NAT: ip6tables NAT support: module (pass)
      CONFIG_NF_DEFRAG_IPV6: module (pass)
    CONFIG_BRIDGE: 802.1d Ethernet Bridging: module (pass)
      CONFIG_LLC: module (pass)
      CONFIG_STP: module (pass)
  CONFIG_EXT4_FS: The Extended 4 (ext4) filesystem: module (pass)
  CONFIG_PROC_FS: /proc file system support: built-in (pass)

```

### What happened?

I'm trying to run k0s inside docker, but for some reason it never attaches any nodes to the cluster. I'm starting k0s with `k0s controller --single`, but still there are no nodes shown when i run `kubectl get node` and all pods are pending.

Here is my compose file:
```yaml
services:
  k0s:
    container_name: k0s
    image: docker.io/k0sproject/k0s:v1.27.4-k0s.0
    command: k0s controller --config=/etc/k0s/config.yaml --enable-worker --single
    hostname: k0s
    privileged: true
    volumes:
      - "/var/lib/k0s"
      - ./k0sconfig.yaml:/etc/k0s/config.yaml
    tmpfs:
      - /run
      - /var/run
    ports:
      - "6443:6443"
    network_mode: "bridge"
  # i didnt figure out if there's any easy way to make multiple workers run from one compose file
  # worker1:
  #   container_name: worker1
  #   image: docker.io/k0sproject/k0s:latest
  #   hostname: worker1
```

and config file
```yaml
apiVersion: k0s.k0sproject.io/v1beta1
kind: ClusterConfig
metadata:
  name: k0s
spec:
  extensions:
    helm:
      repositories:
        - name: cilium
          url: https://helm.cilium.io/
      charts:
        - name: cilium
          chartname: cilium/cilium
          version: "1.14.1"
          values: |
            namespace: kube-system
            kubeProxyReplacement: true
            hostServices:
              enabled: true
            externalIPs:
              enabled: true
            nodePort:
              enabled: true
            hostPort:
              enabled: true
            gatewayAPI:
              enabled: true
          namespace: default
  network:
    provider: custom
    kubeProxy:
      disabled: true
```
Even if I run k0s without the config it doesnt change anything, so it's not the cause of my issues.

### Steps to reproduce

I'm sure some1 would have noticed if --single mode wouldn't be working inside docker, so I'm not really sure how to reproduce.
I guess you can try copying my compose.yml and config files and seeing if you get the same issue.

### Expected behavior

Cluster starts successfully and node is attached to it.

### Screenshots and logs

Here are logs from `docker logs k0s`
[logsfile.txt](https://github.com/k0sproject/k0s/files/12389445/logsfile.txt)

and logs from `kubectl cluster-info dump`
[cluster-info.txt](https://github.com/k0sproject/k0s/files/12389447/cluster-info.txt)

### Additional context

I think the issue might be somehow related to NixOS which is the distro I'm using, but I don't really know why would that cause issues if I'm trying to run `k0s` inside docker. I think someone more experienced might be able to narrow it down with logs provided above.

**Comment by kke** [comment]
k0sctl runs `sudo mount --make-rshared /` if it detects the host is a container.

**Comment by twz123** [comment]
Hi @nxy7! There's several things to mention here.

1. I had a quick look at the logs, and it seems that some kernel modules aren't loaded:

    > msg="\terror creating chain \"KUBE-IPTABLES-HINT\": exit status 3: ip6tables v1.8.7 (legacy): can't initialize ip6tables table `mangle': Table does not exist (do you need to insmod?)" component=kubelet

    K0s/kubelet will attempt to load missing modules on demand, but this won't work within a Docker container. Therefore, you need to load them in advance by running `sudo modprobe ip6table_filter` on your host machine.

2. There are some [notes in the docs][k0s-in-docker] regarding running k0s in Docker. In NixOS 22.11, [`systemd.enableUnifiedCgroupHierarchy`] is [enabled by default][2211-cgroups]. Hence, you need to add the appropriate settings to your `compose.yaml`:

    ```yaml
    services:
      k0s:
        cgroup: host
        volumes:
          - /sys/fs/cgroup:/sys/fs/cgroup:rw
    ```

3. If you intend to create a cluster with multiple nodes, using the `--single` flag is not the correct choice. This flag does not permit the addition of new nodes, be it workers or controllers. To add workers only, start a controller using kine as the backend:

    In `k0sconfig.yaml`, specify kine as the storage backend:

    ```yaml
      spec:
        storage:
          type: kine
    ```

    Remove the `--single` flag from the k0s command line arguments: `k0s controller --config=/etc/k0s/config.yaml --enable-worker`.

    When intending to join multiple controllers, you must to use etcd (or some bespoke kine/clustered SQL backend setup).

4. When adding nodes for the first time, you need to provide a join token. This requires some additional first-time setup. Please refer to the [manual installation steps] in the documentation. Alternatively, you might want consider using [pre-shared] certificates and tokens, or utilizing an automatic cluster setup via [k0sctl].

5. Using Cilium as a custom CNI in k0s will likely involve more than a basic Helm chart installation. I recommend starting with either kube-router or Calico. Both are natively supported by k0s. If those work, you can explore Cilium. Please refer to the following resources:

     * #2301
     * [xinity/k0s_cilium_playground](https://github.com/xinity/k0s_cilium_playground)

[k0s-in-docker]: https://docs.k0sproject.io/v1.27.4+k0s.0/k0s-in-docker/
[`systemd.enableUnifiedCgroupHierarchy`]: https://search.nixos.org/options?show=systemd.enableUnifiedCgroupHierarchy
[2211-cgroups]: https://github.com/NixOS/nixpkgs/blob/074059ab30f261bf91d3717bd9337bc0871871fc/nixos/modules/system/boot/systemd.nix#L318-L324
[manual installation steps]: https://docs.k0sproject.io/v1.27.4+k0s.0/k0s-multi-node/#3-create-a-join-token
[pre-shared]: https://docs.k0sproject.io/v1.27.4+k0s.0/custom-ca/
[k0sctl]: https://docs.k0sproject.io/v1.27.4+k0s.0/k0sctl-install/
