### ISSUE TITLE
purelb+kubeproxy, k0s  is not working properly

### ISSUE THREAD

**Issue by pinghe** [k0sproject/k0s#3562]
### Before creating an issue, make sure you've checked the following:

- [X] You are running the latest released version of k0s
- [X] Make sure you've searched for existing issues, both open and closed
- [X] Make sure you've searched for PRs too, a fix might've been merged already
- [X] You're looking at docs for the released version, "main" branch docs are usually ahead of released versions.

### Platform

```shell
Linux 6.5.4-76060504-generic #202309191142~1695998943~22.04~070916d SMP PREEMPT_DYNAMIC Fri S x86_64 GNU/Linux
NAME="Pop!_OS"
VERSION="22.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 22.04 LTS"
VERSION_ID="22.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=jammy
UBUNTU_CODENAME=jammy
LOGO=distributor-logo-pop-os
```

### Version

v1.26.8+k0s.0

### Sysinfo

<details><summary>`k0s sysinfo`</summary>
<pre>
➡️ Total memory: 15.6 GiB (pass)
Disk space available for /var/lib/k0s: 68.9 GiB (pass)
Operating system: Linux (pass)
  Linux kernel release: 6.5.4-76060504-generic (pass)
  Max. file descriptors per process: current: 1048576 / max: 1048576 (pass)
  Executable in path: modprobe: /usr/sbin/modprobe (pass)
  /proc file system: mounted (0x9fa0) (pass)
  Control Groups: version 2 (pass)
    cgroup controller "cpu": available (pass)
    cgroup controller "cpuacct": available (via cpu in version 2) (pass)
    cgroup controller "cpuset": available (pass)
    cgroup controller "memory": available (pass)
    cgroup controller "devices": available (assumed) (pass)
    cgroup controller "freezer": available (assumed) (pass)
    cgroup controller "pids": available (pass)
    cgroup controller "hugetlb": available (pass)
    cgroup controller "blkio": available (via io in version 2) (pass)
  CONFIG_CGROUPS: Control Group support: built-in (pass)
    CONFIG_CGROUP_FREEZER: Freezer cgroup subsystem: built-in (pass)
    CONFIG_CGROUP_PIDS: PIDs cgroup subsystem: built-in (pass)
    CONFIG_CGROUP_DEVICE: Device controller for cgroups: built-in (pass)
    CONFIG_CPUSETS: Cpuset support: built-in (pass)
    CONFIG_CGROUP_CPUACCT: Simple CPU accounting cgroup subsystem: built-in (pass)
    CONFIG_MEMCG: Memory Resource Controller for Control Groups: built-in (pass)
    CONFIG_CGROUP_HUGETLB: HugeTLB Resource Controller for Control Groups: built-in (pass)
    CONFIG_CGROUP_SCHED: Group CPU scheduler: built-in (pass)
      CONFIG_FAIR_GROUP_SCHED: Group scheduling for SCHED_OTHER: built-in (pass)
        CONFIG_CFS_BANDWIDTH: CPU bandwidth provisioning for FAIR_GROUP_SCHED: built-in (pass)
    CONFIG_BLK_CGROUP: Block IO controller: built-in (pass)
  CONFIG_NAMESPACES: Namespaces support: built-in (pass)
    CONFIG_UTS_NS: UTS namespace: built-in (pass)
    CONFIG_IPC_NS: IPC namespace: built-in (pass)
    CONFIG_PID_NS: PID namespace: built-in (pass)
    CONFIG_NET_NS: Network namespace: built-in (pass)
  CONFIG_NET: Networking support: built-in (pass)
    CONFIG_INET: TCP/IP networking: built-in (pass)
      CONFIG_IPV6: The IPv6 protocol: built-in (pass)
    CONFIG_NETFILTER: Network packet filtering framework (Netfilter): built-in (pass)
      CONFIG_NETFILTER_ADVANCED: Advanced netfilter configuration: built-in (pass)
      CONFIG_NETFILTER_XTABLES: Netfilter Xtables support: module (pass)
        CONFIG_NETFILTER_XT_TARGET_REDIRECT: REDIRECT target support: module (pass)
        CONFIG_NETFILTER_XT_MATCH_COMMENT: "comment" match support: module (pass)
        CONFIG_NETFILTER_XT_MARK: nfmark target and match support: module (pass)
        CONFIG_NETFILTER_XT_SET: set target and match support: module (pass)
        CONFIG_NETFILTER_XT_TARGET_MASQUERADE: MASQUERADE target support: module (pass)
        CONFIG_NETFILTER_XT_NAT: "SNAT and DNAT" targets support: module (pass)
        CONFIG_NETFILTER_XT_MATCH_ADDRTYPE: "addrtype" address type match support: module (pass)
        CONFIG_NETFILTER_XT_MATCH_CONNTRACK: "conntrack" connection tracking match support: module (pass)
        CONFIG_NETFILTER_XT_MATCH_MULTIPORT: "multiport" Multiple port match support: module (pass)
        CONFIG_NETFILTER_XT_MATCH_RECENT: "recent" match support: module (pass)
        CONFIG_NETFILTER_XT_MATCH_STATISTIC: "statistic" match support: module (pass)
      CONFIG_NETFILTER_NETLINK: module (pass)
      CONFIG_NF_CONNTRACK: Netfilter connection tracking support: module (pass)
      CONFIG_NF_NAT: module (pass)
      CONFIG_IP_SET: IP set support: module (pass)
        CONFIG_IP_SET_HASH_IP: hash:ip set support: module (pass)
        CONFIG_IP_SET_HASH_NET: hash:net set support: module (pass)
      CONFIG_IP_VS: IP virtual server support: module (pass)
        CONFIG_IP_VS_NFCT: Netfilter connection tracking: built-in (pass)
      CONFIG_NF_CONNTRACK_IPV4: IPv4 connetion tracking support (required for NAT): unknown (warning)
      CONFIG_NF_REJECT_IPV4: IPv4 packet rejection: module (pass)
      CONFIG_NF_NAT_IPV4: IPv4 NAT: unknown (warning)
      CONFIG_IP_NF_IPTABLES: IP tables support: module (pass)
        CONFIG_IP_NF_FILTER: Packet filtering: module (pass)
          CONFIG_IP_NF_TARGET_REJECT: REJECT target support: module (pass)
        CONFIG_IP_NF_NAT: iptables NAT support: module (pass)
        CONFIG_IP_NF_MANGLE: Packet mangling: module (pass)
      CONFIG_NF_DEFRAG_IPV4: module (pass)
      CONFIG_NF_CONNTRACK_IPV6: IPv6 connetion tracking support (required for NAT): unknown (warning)
      CONFIG_NF_NAT_IPV6: IPv6 NAT: unknown (warning)
      CONFIG_IP6_NF_IPTABLES: IP6 tables support: module (pass)
        CONFIG_IP6_NF_FILTER: Packet filtering: module (pass)
        CONFIG_IP6_NF_MANGLE: Packet mangling: module (pass)
        CONFIG_IP6_NF_NAT: ip6tables NAT support: module (pass)
      CONFIG_NF_DEFRAG_IPV6: module (pass)
    CONFIG_BRIDGE: 802.1d Ethernet Bridging: module (pass)
      CONFIG_LLC: module (pass)
      CONFIG_STP: module (pass)
  CONFIG_EXT4_FS: The Extended 4 (ext4) filesystem: built-in (pass)
  CONFIG_PROC_FS: /proc file system support: built-in (pass)⬅️
</pre>
</details>

### What happened?

# Problem statement 

* In k0s 1.24 and 1.25, the kube-proxy configuration in k0sctl.yaml does not work. 
* In k0s 1.25 and 1.26, there is an issue where icmp fails after assigning an lb address. 

## k0s 1.24

Is the backend app correctly assigned the LB address 192.168.21.80: yes  

Is the LB address pingable: yes 

## k0s 1.25

Is the backend app correctly assigned LB address 192.168.21.80: yes  

Can you ping the LB address: false 

## k0s 1.26

Is backend app correctly assigned LB address 192.168.21.80: yes  

Can you ping the LB address: false   `ping 192.168.21.80 : Destination port unreachable`

It looks like there is a problem with k0s integration with kube-proxy. 

[purelb author confirms support for 1.26 without issue](https://gitlab.com/purelb/purelb/-/issues/128)

### Steps to reproduce

# Reproduction steps 

# Install k0s using k0sctl 

```bash
rm ~/.ssh/known_hosts* && k0sctl reset --config k0sctl.yaml

rm ~/.ssh/known_hosts* && k0sctl apply --config k0sctl.yaml && k0sctl kubeconfig > kubeconfig
```

## k0sctl.yaml

```yaml
apiVersion: k0sctl.k0sproject.io/v1beta1
kind: Cluster
metadata:
  name: k0s-cluster
spec:
  hosts:
  - ssh:
      address: host1
      user: user1
      port: 22
      keyPath: /home/user1/.ssh/id_rsa
    # role: single/controller+worker/controller/worker
    role: controller+worker

    hooks:
      reset:
        after:
          - sudo find /etc/k0s/ -type f -exec rm {} \;

    os: ubuntu
    noTaints: true
  
  - ssh:
      address: host2
      user: user1
      port: 22
      keyPath: /home/user1/.ssh/id_rsa
    role: worker

    hooks:
      reset:
        after:
          - sudo find /etc/k0s/ -type f -exec rm {} \;

    os: ubuntu
    # noTaints: true
  
  k0s:
    # version: v1.24.17+k0s.0
    # version: v1.25.13+k0s.0
    version: v1.26.8+k0s.0
    dynamicConfig: true
    config:
      spec:
        network:
          kubeProxy:
            mode: ipvs
            ipvs:
              strictARP: true
          provider: calico
          calico:
            mode: "bird"
          # dualStack:
          #   enabled: true
          #   IPv6podCIDR: "fd00::/108"
          #   IPv6serviceCIDR: "fd01::/108"
          podCIDR: 10.244.0.0/16
          serviceCIDR: 10.96.0.0/12  
   
```

# Configure the LB address pool 

### Host preparation 

ssh login to each host to configure (reboot after configuration is complete): ssh 

```yaml
cat <<EOF | sudo tee /etc/sysctl.d/k8s_arp.conf
net.ipv4.conf.all.arp_ignore=1
net.ipv4.conf.all.arp_announce=2
net.ipv6.conf.all.arp_ignore=1
net.ipv6.conf.all.arp_announce=2
EOF
sudo sysctl --system
```

### Manually modify kube-proxy configuration (due to k0s failure) 

* In k0s 1.24 and 1.25, the kube-proxy configuration in k0sctl.yaml does not work. 
* In k0s 1.26, there is an issue where icmp fails after assigning an lb address. 

```bash
kubectl get configmap kube-proxy -n kube-system -o yaml | sed -e "s/strictARP: false/strictARP: true/" | kubectl apply -f - -n kube-system
```

### Restart kube-proxy to make sure the configuration takes effect. 

```bash
kubectl rollout restart ds kube-proxy -n kube-system
```

### Confirm that the configuration is in effect 

```bash
kubectl get configmap -n kube-system kube-proxy -o yaml | grep strictARP
```

### Install PureLB 

```bash
# https://gitlab.com/api/v4/projects/purelb%2Fpurelb/packages/generic/manifest/purelb-complete.yaml
kubectl apply -f purelb-complete.yaml
kubectl apply -f purelb-complete.yaml

kubectl apply -f purelb-ipam.yaml
```

#### purelb-ipam.yaml

```yaml
apiVersion: purelb.io/v1
kind: ServiceGroup
metadata:
  name: lb-ippool
  namespace: purelb
spec:
  local:
    v4pools:
    - aggregation: default
      subnet: '192.168.20.0/23'
      pool: '192.168.21.80-172.16.21.100'
    v6pools:
    - aggregation: default   
      subnet: 'fd00::2::/64'
      pool: 'fd00::2::80-fd00::2::90'
      # aggregation: /118
```

# backend app

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
      version: v1
  template:
    metadata:
      labels:
        app: backend
        version: v1
    spec:
      serviceAccountName: backend
      containers:
        - image: gcr.io/k8s-staging-ingressconformance/echoserver:v20221109-7ee2f3e
          imagePullPolicy: IfNotPresent
          name: backend
          ports:
            - containerPort: 3000
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
```
