### ISSUE TITLE
API server audit logging seemingly unsupported in k0s cluster

### ISSUE THREAD

**Issue by Starttoaster** [k0sproject/k0s#3738]
### Before creating an issue, make sure you've checked the following:

- [X] You are running the latest released version of k0s
- [X] Make sure you've searched for existing issues, both open and closed
- [X] Make sure you've searched for PRs too, a fix might've been merged already
- [X] You're looking at docs for the released version, "main" branch docs are usually ahead of released versions.

### Platform

```shell
Linux 5.15.0-67-generic #74-Ubuntu SMP Wed Feb 22 14:14:39 UTC 2023 x86_64 GNU/Linux
PRETTY_NAME="Ubuntu 22.04.2 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.2 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
```

### Version

v1.26.7+k0s.0

### Sysinfo

<details><summary>`k0s sysinfo`</summary>
<pre>
Machine ID: "f1028d6abf81c1b8b72ad4e97b70aebac34433f8629b2767f04264d6e9877937" (from machine) (pass)
Total memory: 15.3 GiB (pass)
Disk space available for /var/lib/k0s: 1.2 TiB (pass)
Operating system: Linux (pass)
  Linux kernel release: 5.15.0-67-generic (pass)
  Max. file descriptors per process: current: 1048576 / max: 1048576 (pass)
  Executable in path: modprobe: /usr/sbin/modprobe (pass)
  /proc file system: mounted (0x9fa0) (pass)
  Control Groups: version 2 (pass)
    cgroup controller "cpu": available (pass)
    cgroup controller "cpuacct": available (via cpu in version 2) (pass)
    cgroup controller "cpuset": available (pass)
    cgroup controller "memory": available (pass)
    cgroup controller "devices": available (assumed) (pass)
    cgroup controller "freezer": available (assumed) (pass)
    cgroup controller "pids": available (pass)
    cgroup controller "hugetlb": available (pass)
    cgroup controller "blkio": available (via io in version 2) (pass)
  CONFIG_CGROUPS: Control Group support: built-in (pass)
    CONFIG_CGROUP_FREEZER: Freezer cgroup subsystem: built-in (pass)
    CONFIG_CGROUP_PIDS: PIDs cgroup subsystem: built-in (pass)
    CONFIG_CGROUP_DEVICE: Device controller for cgroups: built-in (pass)
    CONFIG_CPUSETS: Cpuset support: built-in (pass)
    CONFIG_CGROUP_CPUACCT: Simple CPU accounting cgroup subsystem: built-in (pass)
    CONFIG_MEMCG: Memory Resource Controller for Control Groups: built-in (pass)
    CONFIG_CGROUP_HUGETLB: HugeTLB Resource Controller for Control Groups: built-in (pass)
    CONFIG_CGROUP_SCHED: Group CPU scheduler: built-in (pass)
      CONFIG_FAIR_GROUP_SCHED: Group scheduling for SCHED_OTHER: built-in (pass)
        CONFIG_CFS_BANDWIDTH: CPU bandwidth provisioning for FAIR_GROUP_SCHED: built-in (pass)
    CONFIG_BLK_CGROUP: Block IO controller: built-in (pass)
  CONFIG_NAMESPACES: Namespaces support: built-in (pass)
    CONFIG_UTS_NS: UTS namespace: built-in (pass)
    CONFIG_IPC_NS: IPC namespace: built-in (pass)
    CONFIG_PID_NS: PID namespace: built-in (pass)
    CONFIG_NET_NS: Network namespace: built-in (pass)
  CONFIG_NET: Networking support: built-in (pass)
    CONFIG_INET: TCP/IP networking: built-in (pass)
      CONFIG_IPV6: The IPv6 protocol: built-in (pass)
    CONFIG_NETFILTER: Network packet filtering framework (Netfilter): built-in (pass)
      CONFIG_NETFILTER_ADVANCED: Advanced netfilter configuration: built-in (pass)
      CONFIG_NETFILTER_XTABLES: Netfilter Xtables support: module (pass)
        CONFIG_NETFILTER_XT_TARGET_REDIRECT: REDIRECT target support: module (pass)
        CONFIG_NETFILTER_XT_MATCH_COMMENT: "comment" match support: module (pass)
        CONFIG_NETFILTER_XT_MARK: nfmark target and match support: module (pass)
        CONFIG_NETFILTER_XT_SET: set target and match support: module (pass)
        CONFIG_NETFILTER_XT_TARGET_MASQUERADE: MASQUERADE target support: module (pass)
        CONFIG_NETFILTER_XT_NAT: "SNAT and DNAT" targets support: module (pass)
        CONFIG_NETFILTER_XT_MATCH_ADDRTYPE: "addrtype" address type match support: module (pass)
        CONFIG_NETFILTER_XT_MATCH_CONNTRACK: "conntrack" connection tracking match support: module (pass)
        CONFIG_NETFILTER_XT_MATCH_MULTIPORT: "multiport" Multiple port match support: module (pass)
        CONFIG_NETFILTER_XT_MATCH_RECENT: "recent" match support: module (pass)
        CONFIG_NETFILTER_XT_MATCH_STATISTIC: "statistic" match support: module (pass)
      CONFIG_NETFILTER_NETLINK: module (pass)
      CONFIG_NF_CONNTRACK: Netfilter connection tracking support: module (pass)
      CONFIG_NF_NAT: module (pass)
      CONFIG_IP_SET: IP set support: module (pass)
        CONFIG_IP_SET_HASH_IP: hash:ip set support: module (pass)
        CONFIG_IP_SET_HASH_NET: hash:net set support: module (pass)
      CONFIG_IP_VS: IP virtual server support: module (pass)
        CONFIG_IP_VS_NFCT: Netfilter connection tracking: built-in (pass)
      CONFIG_NF_CONNTRACK_IPV4: IPv4 connetion tracking support (required for NAT): unknown (warning)
      CONFIG_NF_REJECT_IPV4: IPv4 packet rejection: module (pass)
      CONFIG_NF_NAT_IPV4: IPv4 NAT: unknown (warning)
      CONFIG_IP_NF_IPTABLES: IP tables support: module (pass)
        CONFIG_IP_NF_FILTER: Packet filtering: module (pass)
          CONFIG_IP_NF_TARGET_REJECT: REJECT target support: module (pass)
        CONFIG_IP_NF_NAT: iptables NAT support: module (pass)
        CONFIG_IP_NF_MANGLE: Packet mangling: module (pass)
      CONFIG_NF_DEFRAG_IPV4: module (pass)
      CONFIG_NF_CONNTRACK_IPV6: IPv6 connetion tracking support (required for NAT): unknown (warning)
      CONFIG_NF_NAT_IPV6: IPv6 NAT: unknown (warning)
      CONFIG_IP6_NF_IPTABLES: IP6 tables support: module (pass)
        CONFIG_IP6_NF_FILTER: Packet filtering: module (pass)
        CONFIG_IP6_NF_MANGLE: Packet mangling: module (pass)
        CONFIG_IP6_NF_NAT: ip6tables NAT support: module (pass)
      CONFIG_NF_DEFRAG_IPV6: module (pass)
    CONFIG_BRIDGE: 802.1d Ethernet Bridging: module (pass)
      CONFIG_LLC: module (pass)
      CONFIG_STP: module (pass)
  CONFIG_EXT4_FS: The Extended 4 (ext4) filesystem: built-in (pass)
  CONFIG_PROC_FS: /proc file system support: built-in (pass)
</pre>
</details>

### What happened?

Attempting to enable audit logging for the kube apiserver I noticed a couple of issues. I'd preface with it would help to write documentation for how to enable this feature of the kube api, since the only k0s documentation around it is how kube-bench complains that it is not enabled by default. I believe this feature is desirable to many looking to deploy k0s in a production environment. Anyway, moving onto the problems:

1) Looking at the output of `kubectl api-resources`, there is no `audit.k8s.io` API in my installation, and there are seemingly no documents around how to install it, which leads me to believe this is potentially an API that was meant to be installed by the kubernetes distribution but for some reason was not. Apologies if that assumption is incorrect. 

2) Adding the following to my k0sctl configuration, kubectl stops responding to commands, and `k0s status` responds with `Error: status: can't do http request: /run/k0s/status.sock status` though `/run/k0s/status.sock` exists:
```yaml
spec:
  k0s:
    config:
      spec:
        api:
          extraArgs:
            audit-policy-file: /var/lib/k0s/audit-policy.yaml
            audit-log-path: /var/log/k0s/audit/audit.log
```
Note: I added the default audit-policy.yaml to the defined `audit-policy-file` path provided on all three of my cluster nodes, and ensured `/var/log/k0s/audit` was a directory that existed on all 3 nodes. 

This is my full k0s cluster config file for k0sctl (note that I made the issue here because I felt it might be more an issue with k0s than the actual cluster deployment method but feel free to route this issue over to the k0sctl repo if required):

```yaml
apiVersion: k0sctl.k0sproject.io/v1beta1
kind: Cluster
metadata:
  name: cluster1
spec:
  hosts:
  - ssh:
      address: 100.85.216.39
      user: bb
      port: 22
    role: controller+worker
    installFlags:
      - --no-taints
  - ssh:
      address: 100.72.143.21
      user: bb
      port: 22
    role: controller+worker
    installFlags:
      - --no-taints
  - ssh:
      address: 100.81.77.109
      user: bb
      port: 22
    role: controller+worker
    installFlags:
      - --no-taints
  k0s:
    config:
      spec:
        api:
          extraArgs:
            audit-policy-file: /var/lib/k0s/audit-policy.yaml
            audit-log-path: /var/log/k0s/audit/audit.log
          externalAddress: 192.168.1.161
          sans:
          - 192.168.1.161
    version: 1.26.7+k0s.0
    dynamicConfig: false
```

### Steps to reproduce

1. Create a k0s cluster using a k0sctl configuration file similar to mine
2. View the output of `kubectl api-resources` and verify if a `audit.k8s.io` API exists.
3. Attempt to run kubectl commands at all with the audit policy configuration options added.

### Expected behavior

I would be able to enable audit logging from the kube apiserver following standard k8s distro documentation provided here: https://kubernetes.io/docs/tasks/debug/debug-cluster/audit/

### Actual behavior

My kube apiserver seems to no longer be responding to requests.

**Comment by Starttoaster** [comment]
This stackoverflow makes it seem like the `kubectl api-resources` bit of the Issue is actually false: https://stackoverflow.com/questions/64179278/kubernetes-api-resource-not-found

Apparently it's some kind of special hidden API resource. So that appears like it might be a red herring. I'm wondering if there is a way I can inspect exactly why my api server stopped responding to all client requests then after I added those audit log flags to my configuration, that apparently doesn't rely on the k0s status.sock since that stops responding when I add those audit options.

**Comment by Starttoaster** [comment]
Ahg, yeah you were right. I expected the kubernetes API to make the file for me, but it looks like it attempts to open a file on service start, so I did:
```
sudo touch /var/log/k0s/audit/audit.log
```
Which did not resolve the issue, but then this did the trick:
```
sudo chmod -R 774 /var/log/k0s/audit
```
You can file this one under user error 😄

**Comment by twz123** [comment]
NB: You can probably add that to your k0sctl config as a [hook](https://github.com/k0sproject/k0sctl/tree/v0.16.0#spechostshooks-mapping-optional). Something like this might work:

```yaml
apiVersion: k0sctl.k0sproject.io/v1beta1
kind: Cluster
metadata:
  name: cluster1
spec:
  hosts:
  - ssh:
      address: 100.85.216.39
      user: bb
      port: 22
    role: controller+worker
    installFlags:
      - --no-taints
    hooks:
      apply:
        before:
        - sudo mkdir -p /var/log/k0s/audit && sudo chmod -R 770 /var/log/k0s/audit
  - ssh:
      address: 100.72.143.21
      user: bb
      port: 22
    role: controller+worker
    installFlags:
      - --no-taints
    hooks:
      apply:
        before:
        - sudo mkdir -p /var/log/k0s/audit && sudo chmod -R 770 /var/log/k0s/audit
  - ssh:
      address: 100.81.77.109
      user: bb
      port: 22
    role: controller+worker
    installFlags:
      - --no-taints
    hooks:
      apply:
        before:
        - sudo mkdir -p /var/log/k0s/audit && sudo chmod -R 770 /var/log/k0s/audit
  k0s:
    config:
      spec:
        api:
          extraArgs:
            audit-policy-file: /var/lib/k0s/audit-policy.yaml
            audit-log-path: /var/log/k0s/audit/audit.log
          externalAddress: 192.168.1.161
          sans:
          - 192.168.1.161
    version: 1.26.7+k0s.0
    dynamicConfig: false
```
