### ISSUE TITLE
Prometheus konnectivity-agent target discovery using wrong port

### ISSUE THREAD

**Issue by andyrue** [k0sproject/k0s#3869]
Prometheus is unable to connect to /metrics of all my konnectivity-agent pods. I have 3 on controllers and 3 on workers. The target endpoint url is using port 80, but the pod annotations are set to 8093, and I noticed in Prometheus if I hover over the labels, it says "Before relabeling.....meta_kubernetes_pod_annotations_io_port="8093". I know this is more of a prometheus question, but hoping someone can help. 

konnectivity-agent pod excerpt

```
apiVersion: v1
kind: Pod
metadata:
  annotations:
    prometheus.io/port: "8093"
    prometheus.io/scrape: "true"
  generateName: konnectivity-agent-
```
Example of one of the prometheus konnectivity-agent targets.

<img width="1215" alt="Screenshot 2024-01-02 at 9 02 03 PM" src="https://github.com/k0sproject/k0s/assets/734208/6d4ad7ec-17b8-40dd-bc2d-bd26d24432f3">
