### ISSUE TITLE
Allow manifest deployer to apply once based on annotations

### ISSUE THREAD

**Issue by onedr0p** [k0sproject/k0s#3966]
### Is your feature request related to a problem? Please describe.

Currently the manifest deployer will manage the lifecycle of user based manifests added to the `/var/lib/k0s/manifests` dir:

> By default, k0s reads all manifests under /var/lib/k0s/manifests and ensures that their state matches the cluster state. Moreover, on removal of a manifest file, k0s will automatically prune all of it associated resources.

> The use of Manifest Deployer is quite similar to the use the kubectl apply command. The main difference between the two is that Manifest Deployer constantly monitors the directory for changes, and thus you do not need to manually apply changes that are made to the manifest files.

In my usecase I would like to use the manifest deployer to deploy a kube-vip daemonset and rbac and then have Flux "take over" the manifests deployed there however this is currently not possible.

### Describe the solution you would like

It would be cool if there was a annotation we could set on each manifests that would change this behavior. Something like this:

```yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kube-vip
  namespace: kube-system
  annotations:
    deployer.k0sproject.io/prune: Disabled
    deployer.k0sproject.io/apply-once: Enabled
```

### Describe alternatives you've considered

There doesn't seem to be any alternative since k0s wants to assume complete ownership of the lifecycle of user added manifests to this directory.

**Comment by jnummelin** [comment]
In your use case, why can't you manage them from GitOps for the first time? In other words, why the first apply is via manifest deployer?

**Comment by onedr0p** [comment]
This is because I am deploying kube-vip as the "external" Kube API LB which is really a core component to the cluster. In my use-case it's nice to have this come up with the cluster as opposed to after with Flux so I can use the kube-vip addr right away in my kubeconfig.

**Comment by onedr0p** [comment]
It would be great if the helm extension also had this functionality. I use renovate bot to keep the k0sctl config updated and from what I read it looks like if this value changes it will override what Flux or Argo has deployed.

```yaml
...
        extensions:
          helm:
            repositories:
              - name: cilium
                url: https://helm.cilium.io
            charts:
              - name: cilium
                chartname: cilium/cilium
                # renovate: datasource=github-releases depName=cilium/cilium
                version: 1.15.0-rc.1
                namespace: kube-system
                values: |2
                  autoDirectNodeRoutes: true
...
```
