### ISSUE TITLE
Better Autopilot signalling visibility

### ISSUE THREAD

**Issue by jnummelin** [k0sproject/k0s#4007]
When autopilot signalling fails for some reason, we do not have good visibility on the progress and/or errors. E.g. in #4006 on the `Plan` object we only see this:

```
status:
  commands:
    - id: 0
      k0supdate:
        controllers:
          - lastUpdatedTimestamp: '2024-02-02T09:56:19Z'
            name: master1
            state: SignalPending
          - lastUpdatedTimestamp: '2024-02-02T09:56:19Z'
            name: master2
            state: SignalApplyFailed
          - lastUpdatedTimestamp: '2024-02-02T09:56:19Z'
            name: master3
            state: SignalPending
      state: ApplyFailed
  state: ApplyFailed
```

We should also provide more detail on why the `SignalApplyFailed`. On the `Node`/`ControlNode` object we do see more details:

```
apiVersion: autopilot.k0sproject.io/v1beta2
kind: ControlNode
metadata:
  annotations:
    autopilot.k0sproject.io/mode: controller+worker
    k0sproject.io/autopilot-signal-data: >-
      {"planId":"id3000","created":"2024-02-02T10:22:36Z","command":{"id":0,"k0supdate":{"url":"https://github.com/k0sproject/k0s/releases/download/v1.29.1+k0s.0/k0s-v1.29.1+k0s.0-amd64","version":"v1.29.1+k0s.0","sha256":"3b0674943409abb8554103708b36459b604f6755c579b3cf594e62ae44357ad2"}},"status":{"status":"FailedDownload","timestamp":"2024-02-02T10:22:41Z"}}
    k0sproject.io/autopilot-signal-version: v2
```

And in the logs of k0s we also see this:

```
time="2024-02-02 10:22:41" level=error msg="Unable to download 'https://github.com/k0sproject/k0s/releases/download/v1.29.1+k0s.0/k0s-v1.29.1+k0s.0-amd64': checksum mismatch" component=a
utopilot controller=ControlNode leadermode=false object=ControlNode reconciler=downloading signalnode=master2
```

So to better tell user what is going on, we need to surface this info on the `Plan` level.
