### ISSUE TITLE
Autopilot's Plan optional fields are not actually optional (spec.id, spec.timestamp)

### ISSUE THREAD

**Issue by nekwar** [k0sproject/k0s#4058]
### Before creating an issue, make sure you've checked the following:

- [X] You are running the latest released version of k0s
- [X] Make sure you've searched for existing issues, both open and closed
- [X] Make sure you've searched for PRs too, a fix might've been merged already
- [X] You're looking at docs for the released version, "main" branch docs are usually ahead of released versions.

### Version

`v1.29.1+k0s`

### What happened?

In the documentation (https://docs.k0sproject.io/stable/autopilot/#spec-fields) it is stated, that `spec.id` and `spec.timestamp` are optional fields (and it makes sense, since it is user-specific fields, autopilot does nothing with them), but in fact, you're not able to create `Plan` without those fields specified.

### Steps to reproduce

1. Apply `Plan` with `spec.id` and `spec.timestamp` commented:
```yaml
apiVersion: autopilot.k0sproject.io/v1beta2
kind: Plan
metadata:
  name: autopilot
spec:
  #  id: id1234
  #  timestamp: now
  commands:
    - k0supdate:
        version: v1.29.1+k0s.1
        platforms:
          linux-amd64:
            url: https://github.com/k0sproject/k0s/releases/download/v1.29.1+k0s.1/k0s-v1.29.1+k0s.1-amd64
        targets:
          controllers:
            discovery:
              selector: {}
```
2. See that API won't let you create it:
```
The Plan "autopilot" is invalid:
* spec.id: Required value
* spec.timestamp: Required value
```

### Expected behavior

`Plan` being created even without `spec.id` and `spec.timestamp` set

### Actual behavior

`Plan` cannot be created with following message:

```
The Plan "autopilot" is invalid:
* spec.id: Required value
* spec.timestamp: Required value
```
