### ISSUE TITLE
Chart.spec.extensions.helm.charts.timeout only accepts numerical value

### ISSUE THREAD

**Issue by ggolin** [k0sproject/k0s#4172]
k0s version: v1.29.2+k0s.0
k0sctl version: version: v0.17.4 commit: 372a589

Given the following config:
```
# generated-by-k0sctl 2024-03-11T14:06:29-07:00
apiVersion: k0s.k0sproject.io/v1beta1
kind: ClusterConfig
spec:
  api:
    address: 10.81.34.223
    sans:
    - 10.81.34.223
    - 10.81.34.225
    - 10.81.34.224
    - 127.0.0.1
  extensions:
    helm:
      charts:
      - chartname: appscode/gateway-api
        name: gateway-api
        namespace: kube-system
        order: 2
        version: v1.0.0
      - chartname: metallb/metallb
        name: metallb
        namespace: metallb
        order: 1
      - chartname: oci://[redacted private registry].com/helm-charts/nginx-ingress-controller
        name: nginx-ingress-controller
        namespace: nginx-ingress
        order: 3
        timeout: 100s
```
Config validation reports the following error:
```
Error: failed to read config: error unmarshaling JSON: while decoding JSON: json: cannot unmarshal string into Go struct field Chart.spec.extensions.helm.charts.timeout of type time.Duration
```
Changing that setting to `10000000` results in a valid config.

According to the [documentation](https://github.com/k0sproject/k0s/blob/b646e9fe45c33f9d370d727c4e7caee263240c88/docs/helm-charts.md?plain=1#L58) this field should accept a user friendly setting.
