### ISSUE TITLE
Support `subPath` in `volumeMounts`

### ISSUE THREAD

**Issue by arxeiss** [k0sproject/k0s#4263]
### Is your feature request related to a problem? Please describe.

When I have 1 persistent volume, but want to map multiple folders into it, I could benefit from `subPath`. 
Is it planned for K0s to support it too?

Currently we are using K0s for educational purposes. So it is not big deal when public/private data are mapped into same directory and mixed together. But I'm curious if my solution would be production ready.

### Describe the solution you would like

See the K8s documentation for example: https://kubernetes.io/docs/concepts/storage/volumes/#using-subpath

### Additional context

```yaml
 volumeMounts:
    - name: app1-persistent-data
      subpath: uploads
      mountPath: /app/public/uploads
    - name: app1-persistent-data
      subpath: app
      mountPath: /app/storage/app
    - name: app1-persistent-data
      subpath: sessions
      mountPath: /app/storage/framework/sessions

volumes:
    - name: app1-persistent-data
      size: "1Gi"
      persistentVolumeClaim:
        claimName: pv-claim-app1-persistent-data
```
