### ISSUE TITLE
Capability to disable some system services

### ISSUE THREAD

**Issue by rlex** [k0sproject/k0s#427]
**Is your feature request related to a problem? Please describe.**
Not sure if this is feature request or bug report. I wanted to create absolute bare minimum setup (control node, couple of workers, with nothing to deploy from start except CoreDNS).  
I tried creating cluster with following config
```
apiVersion: k0s.k0sproject.io/v1beta1
kind: Cluster
metadata:
  name: k0s
spec:
  api:
    address: host_ip_address
    sans:
    - host_ip_address
    - host_fqdn
    extraArgs: {}
  controllerManager:
    extraArgs: {}
  scheduler:
    extraArgs: {}
  storage:
    type: etcd
    kine: null
    etcd:
      peerAddress: host_ip_address
  network:
    podCIDR: 10.244.0.0/16
    serviceCIDR: 10.96.0.0/12
    provider: custom
  podSecurityPolicy:
    defaultPolicy: 00-k0s-privileged
  workerProfiles: []
extensions: null
images:
  konnectivity:
    image: us.gcr.io/k8s-artifacts-prod/kas-network-proxy/proxy-agent
    version: v0.0.13
  coredns:
    image: docker.io/coredns/coredns
    version: 1.7.0
  repository: ""
telemetry:
  interval: 10m0s
  enabled: true
```

I was expecting setup will only end up with konnectivity and coredns, however metrics-server and kube-proxy was still here

**Describe the solution you'd like**
Ability to disable stock pods
