### ISSUE TITLE
Helm extension not applying values

### ISSUE THREAD

**Issue by bfjelds** [k0sproject/k0s#447]
**Version**
```
v0.7.0
```
**Platform**
Which platform did you run k0s on?
```
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.1 LTS
Release:        20.04
Codename:       focal
```
**What happened?**
First, the docs specify some yaml I'm unfamiliar with and was looking for an explanation (the `2` after the pipe character '|'' in the `values` definition).   After playing around with a yaml validator, the `2` seems related to consolidating the indentation when converting everything after the `|` into a single string.  Maybe this is more familiar to other people, but if it is obscure, a mention of what it means would be nice.

```
helm:
 repositories:
 - name: stable
   url: https://charts.helm.sh/stable
 - name: prometheus-community
   url: https://prometheus-community.github.io/helm-charts
 charts:
 - name: prometheus-stack
   chartname: prometheus-community/prometheus
   version: "11.16.8"
   values: |2
       <embed yaml>
   namespace: default
```

I've been trying out k0s with a project I'm working on and am not having luck getting the Helm chart quite right

1. I specify the namespace as something other than `default` but the resulting components end up in `default` namespace.
1. I specify values (that I would normally specify on the command line with --set), but the resulting deployment doesn't seem to reflect the values.

**Is there a way to see some debug output or a log of what Helm is doing?**  Something in a log file that is equivalent to passing the --debug argument to Helm would be **very** helpful.

**How To Reproduce**
Add this to k0s.yaml (I have tried with `values: |2`, `values: |`, and `values:` ... all yield the same results):

```yaml
extensions:
  helm:
    repositories:
    - name: akri
      url: https://deislabs.github.io/akri
    charts:
    - name: akri-dev
      chartname: akri/akri-dev
      version: "0.0.42"
      namespace: akri
      values: |2
        debugEcho.enabled: true
        debugEcho.shared: false
        agent.allowDebugEcho: true
```

I'm trying to do the equivalent of `helm install akri akri-helm-charts/akri-dev --version 0.0.42 --set debugEcho.enabled=true,debugEcho.shared=false,agent.allowDebugEcho=true`

**Expected behavior**
I expected to see the akri components show up in `akri` namespace rather than `default`  ( though, it is entirely possible that akri is messing up :) )

I also expected to see a few more components starting based on the values specified, which makes me wonder if the values are being communicated to Helm ( though, again, it is entirely possible that akri is messing up :) )

```sh
$ kubectl get pods -A
NAMESPACE     NAME                                          READY   STATUS             RESTARTS   AGE
default       akri-agent-daemonset-l84qp                    1/1     Running            10         2d20h
default       akri-controller-deployment-6949859f84-7gml9   1/1     Running            7          2d20h
```

**Screenshots & Logs**

**Additional context**
Following up on the idea that the values were not being applied to the Akri helm chart, I added a paramater that would result in a path being mounted in the resulting containers.

```yaml
extensions:
  helm:
    repositories:
    - name: akri
      url: https://deislabs.github.io/akri
    charts:
    - name: akri-dev
      chartname: akri/akri-dev
      version: "0.0.42"
      namespace: akri
      values: |2
        agent.host.dockerShimSock: /my/new/docker/shim/foo.sock
```

After deploying k0s, I can then test whether this new path was mounted as expected:
```sh
$ sudo crictl --runtime-endpoint unix:///run/k0s/containerd.sock inspect $(sudo crictl --runtime-endpoint unix:///run/k0s/containerd.sock ps | grep agent | awk '{print $1}') | grep hostPath | grep sock | grep /my/new/docker/shim/foo.sock && echo "Successfully passed Helm value" || echo "Failed to pass Helm value"
Failed to pass Helm value
```

It (from this contrived test) seems that the values are not being applied to the Helm chart.
