### ISSUE TITLE
SQLite Documentation

### ISSUE THREAD

**Issue by f0o** [k0sproject/k0s#452]
How to configure k0s.yaml to use SQLite instead of etcd?

```
  storage:
    type: kine
    kine: "sqlite:///root/k0s.sqlite"
    etcd: {}
```

yields in error:

```
time="2020-11-25 08:48:21" level=error msg="Failed to read cluster config: yaml: unmarshal errors:\n  line 19: cannot unmarshal !!str `sqlite:...` into v1beta1.KineConfig"
```

**Comment by jnummelin** [comment]
See https://github.com/k0sproject/k0s/blob/main/docs/configuration.md#specstorage

So basically something like:
```
storage:
  type: kine
  kine:
   dataSource: "sqlite:///root/k0s.sqlite"
```

**Comment by f0o** [comment]
ok after checking the actual golang definition I saw that I need:

```
  storage:
    type: kine
    kine:
      dataSource: "sqlite:///opt/k0s.sqlite"
```

Ironically it now fails with:
```
2020-11-25 08:53:44.254370 I | failed to create dir /opt: directory "/opt" exist, but the permission is 0711. The expected permission is 750
```

It shouldn't bother with the chmod if it exists, 0711 is plenty.
