### ISSUE TITLE
Configurations for calico

### ISSUE THREAD

**Issue by jnummelin** [k0sproject/k0s#47]
We need to make some calico setting configurable through the config yaml. At least the following:
- mode (ipip/vxlan)
- mtu

The config could look something like:
```
apiVersion: mke.mirantis.com/v1beta1
kind: Cluster
metadata:
  name: foobar
spec:
  network:
    provider: calico
    calico:
      mtu: 1234
      mode: vxlan
```

Default to `vxlan` and 1450 MTU.
