### ISSUE TITLE
Add ability to customize calico startup variables

### ISSUE THREAD

**Issue by unixfox** [k0sproject/k0s#479]
**Is your feature request related to a problem? Please describe.**
I would like to set the IP autodetection method of Calico to a different method (https://docs.projectcalico.org/networking/ip-autodetection) but currently I'm unable to do that because I can't modify the environment variables of the calico deployed by k0s.

**Describe the solution you'd like**
I would like to be able to customize the default images, like changing/adding the environment variables of the default DaemonSet of Calico.
Maybe the ideal solution would be to have the default images deployed from a helm chart and then allow to change the value of the helm chart?

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by trawler** [comment]
@unixfox are you unable to set the auto detection method with `kubectl`?
`kubectl set env daemonset/calico-node -n kube-system IP_AUTODETECTION_METHOD=<autodetection-method>`
If so, I'd be interested to know what is the output you are getting.

**Comment by trawler** [comment]
> @unixfox are you unable to set the auto detection method with `kubectl`?
> `kubectl set env daemonset/calico-node -n kube-system IP_AUTODETECTION_METHOD=<autodetection-method>`
> If so, I'd be interested to know what is the output you are getting.

https://github.com/k0sproject/k0s/issues/488#issuecomment-738120583
`kubectl set env` seems to allow calico to set a different ip auto detection method.
I'm keeping this issue open though, to track this requested feature.

**Comment by unixfox** [comment]
Sorry for the late reply.

Using the command that you gave me works fine but I'm still interested to be able to configure the default images (not just Calico) because I often deploy fresh Kubernetes cluster, and I like to have the ability to have everything configured from a single config file instead of executing another command at every new Kubernetes cluster just for configuring Calico.

**Comment by jnummelin** [comment]
> Maybe the ideal solution would be to have the default images deployed from a helm chart and then allow to change the value of the helm chart?

Calico does not yet have official support for Helm chart. https://github.com/projectcalico/calico/issues/717

I see two options to tackle this.

### Allow to customize any envs for calico pods

So user could use something like this:
```yaml
spec:
  network:
    podCIDR: 10.244.0.0/16
    serviceCIDR: 10.96.0.0/12
    provider: calico
    calico:
      mode: vxlan
      vxlanPort: 4789
      vxlanVNI: 4096
      mtu: 1450
      wireguard: false
      envs:
        IP_AUTODETECTION_METHOD: interface=eth.*
        foo: bar
```

The main issue I see is that user might actually use some env var(s) that are already set by k0s. Or have some config setu that cannot even work as k0s will have no way to validate these. (there's quite a few envs we already set by default)

### Build specific options in k0s config

```yaml
spec:
  network:
    podCIDR: 10.244.0.0/16
    serviceCIDR: 10.96.0.0/12
    provider: calico
    calico:
      mode: vxlan
      vxlanPort: 4789
      vxlanVNI: 4096
      mtu: 1450
      wireguard: false
      ipDetectionMode: interface=eth.*
```

The downside here is that we'd need to build that support into k0s for all the flags users might need to configure. But it does also mean that there's less room to create non-working configs by mistake. At least in theory k0s could validate these config options.
