### ISSUE TITLE
Containerd local docker image mirror and config.toml customization

### ISSUE THREAD

**Issue by staylorx** [k0sproject/k0s#487]
Version: v0.8.0-4-ga8c59c8 (build from fetch)

I've been bring up clusters and works for some time now and am enjoying k0s very much. I think it's really interesting and has lots of amazing potential for not just edge computing, but really nails down the problem of deployment complexity. As I'm bringing up clusters and working out ideas I often completely tear down the servers and rebuild them (a big sea of proxmox). It fetches the images every time I do that. I have a large mirror for development that helps us keep bandwidth down.

In containerd, normally I'd be able to use the insecure_skip_verify flag and point to my nexus3 mirror, thereby neatly helping docker.io with their bandwidth, but it keeps things quieter for me too.

``` toml
version = 2
[plugins]
  [plugins."io.containerd.grpc.v1.cri"]
    [plugins."io.containerd.grpc.v1.cri".registry.mirrors]
      [plugins."io.containerd.grpc.v1.cri".registry.mirrors."192.168.1.11:8880"]
        endpoint = ["http://192.168.1.11:8880"]
    [plugins."io.containerd.grpc.v1.cri".registry.configs]
      [plugins."io.containerd.grpc.v1.cri".registry.configs."192.168.1.11:8880".tls]
        insecure_skip_verify = true
```

I saw in #7 that there was an idea to do something with the containerd/config.toml file I'd normally update (or daemon.json in docker, or registries.conf in podman). 

It's not perfect, but I can send a config.toml file to each of my nodes ahead of k0s via Ansible or the like. That'd be enough I suppose. All I'd need is the k0s to pick it up. While I'm writing this, I realize it might already just work that way. If so I could use just a touch of guidance as where to put it since my M.O. is to put it into /etc/containerd/config.toml.

Another option would be to inject it via a kubernetes cluster.yaml file, but I sort of respect that I don't have to do that with k0s.

Thanks!
