### ISSUE TITLE
How to use ingress controller with k0s

### ISSUE THREAD

**Issue by guzmanf** [k0sproject/k0s#4932]
### Before creating an issue, make sure you've checked the following:

- [X] You are running the latest released version of k0s
- [X] Make sure you've searched for existing issues, both open and closed
- [X] Make sure you've searched for PRs too, a fix might've been merged already
- [X] You're looking at docs for the released version, "main" branch docs are usually ahead of released versions.

### Platform

```shell
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.4 LTS
Release:        22.04
Codename:       jammy
```

### Version

1.30

### Sysinfo

<details><summary>`k0s sysinfo`</summary>
<pre>
➡️ Please replace this text with the output of `k0s sysinfo`. ⬅️
</pre>
</details>

### What happened?

i started with kubernetes and testing rke2 and k0s, the idea is basically execute an click and run, in rke2 the step are so simples
1 curl -sfL https://get.rke2.io | sh -
2 systemctl enable rke2-server.service
3 systemctl start rke2-server.service
4 kubectl apply -f test-1.yaml

then replicated the same steps with k0s.. 
1 curl -sSLf https://get.k0s.sh | sudo sh
2 sudo k0s install controller --single
3 sudo k0s start
...and 
4 kubectl apply -f test-1.yaml

but not work. what i make wrong ? what other configuration i need ?

### Steps to reproduce
```
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  selector:
    matchLabels:
      app: nginx-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx-deployment
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-deployment-svc
spec:
  type: ClusterIP
  ports:
    - name: nginx-deployment-http
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: nginx-deployment
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-deployment-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: test.idsxxxxx.pro
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nginx-deployment-svc
                port:
                  number: 80
```

### Screenshots and logs
![image](https://github.com/user-attachments/assets/329945b1-8179-4185-b67f-7c023d931a3f)

but k0s ...
![image](https://github.com/user-attachments/assets/ab21aec8-f8dc-4124-99ea-eb79e472b0d5)
