### ISSUE TITLE
Cannot start k0s inside LXD container.

### ISSUE THREAD

**Issue by a-prokopyev-resume** [k0sproject/k0s#5152]
Hello,

I have some positive experience using your `k0s` in `Docker` container on the host, but unfortunately still cannot  succeed with running `k0s` inside LXD container.

Here is output of the `lxc profile show k8s` command:

```
config:
  linux.kernel_modules: ip_vs,ip_vs_rr,ip_vs_wrr,ip_vs_sh,ip_tables,ip6_tables,netlink_diag,nf_nat,overlay,br_netfilter,nf_conntrack,iscsi_tcp
  raw.lxc: |
    lxc.apparmor.profile=unconfined
    lxc.mount.auto=proc:rw sys:rw cgroup:rw:force
    lxc.cgroup.devices.allow=a
    lxc.cgroup2.devices.allow=c 10:200 rwm
    lxc.cap.drop=
    lxc.seccomp.profile=
  security.nesting: "true"
  security.privileged: "true"
description: ""
devices:
  aadisable:
    path: /sys/module/nf_conntrack/parameters/hashsize
    source: /sys/module/nf_conntrack/parameters/hashsize
    type: disk
  aadisable2:
    path: /dev/zfs
    source: /dev/zfs
    type: disk
  aadisable3:
    path: /dev/kmsg
    source: /dev/kmsg
    type: unix-char
  aadisable4:
    path: /sys/fs/bpf
    source: /sys/fs/bpf
    type: disk
  aadisable5:
    path: /proc/sys/net/netfilter/nf_conntrack_max
    source: /proc/sys/net/netfilter/nf_conntrack_max
    type: disk
  root:
    path: /
    pool: default
    type: disk
name: k8s
used_by:
- /1.0/instances/wp-1
- /1.0/instances/alpine2
- /1.0/instances/alpine3
- /1.0/instances/alpine4
- /1.0/instances/alpine5
```
