### ISSUE TITLE
The ServiceMonitor sample presented in “System components monitoring” is unfriendly.

### ISSUE THREAD

**Issue by chattytak** [k0sproject/k0s#5213]
```
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: k0s
  namespace: k0s-system
spec:
  endpoints:
  - port: http
  selector:
    matchLabels:
      app: k0s-observability
      component: pushgateway
      k0s.k0sproject.io/stack: metrics
```

The above sample is provided, but the metrics retrieved using this sample are prefixed with “exported_”.
Example: If the original metric is job=“etcd”, then job=“k0s-pushgateway”, exported_job=“etcd”.
The job will be the actual pod name, k0s-pushgateway, and the original job name will be prefixed with “exported_”.
Therefore, it does not match the Prometheus rules provided.

I think this is an unfriendly sample.
If you add the following option, the original metrics data is retained and no replacement is performed.
Shouldn't this be a sample?

```
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: k0s
  namespace: k0s-system
spec:
  endpoints:
  - port: http
    honorLabels: true  <--- Add 
  selector:
    matchLabels:
      app: k0s-observability
      component: pushgateway
      k0s.k0sproject.io/stack: metrics
```
