### ISSUE TITLE
k0s upgrade of single node cluster borked it

### ISSUE THREAD

**Issue by till** [k0sproject/k0s#5287]
We tried to upgrade a single node cluster yesterday and it ended up in a somewhat borked state. The initial version of k0s was `1.27.5+k0s.0` and we upgraded one by one to e.g. `1.28.x` (always latest patch release) all the way to `1.31.2`.

This is the config (extract from k0sctl's config):

```yaml
apiVersion: k0s.k0sproject.io/v1beta1
kind: ClusterConfig
metadata:
  creationTimestamp: null
  name: runway-support
spec:
  controllerManager:
    extraArgs:
      flex-volume-plugin-dir: /opt/libexec/k0s/kubelet-plugins/volume/exec
  workerProfiles:
  - name: flatcar
    values:
      volumePluginDir: /opt/libexec/k0s/kubelet-plugins/volume/exec
  api:
    address: PRIVATE.IP.OF.THE.NODE
    externalAddress: PUBLIC.IP.OF.THE.NODE
  extensions:
    helm:
      repositories:
      - name: cpo
        url: https://kubernetes.github.io/cloud-provider-openstack
      charts:
      - name: cinder-csi
        order: 2
        chartname: cpo/openstack-cinder-csi
        version: 2.28.1
        namespace: kube-system
        values: |
          clusterID: support
          secret:
            enabled: true
            hostMount: false
            create: false
            name: cloud-config
          storageClass:
            enabled: true
          csi:
            plugin:
              nodePlugin:
                kubeletDir: /var/lib/k0s/kubelet
      - name: openstack-cloud-controller-manager
        order: 1
        chartname: cpo/openstack-cloud-controller-manager
        version: 2.28.2
        namespace: kube-system
        values: |
          cluster:
            name: support
          secret:
            enabled: true
            name: cloud-config
            create: false
          tolerations:
          - key: node.cloudprovider.kubernetes.io/uninitialized
            value: "true"
            effect: NoSchedule
          extraVolumes:
          - name: flexvolume-dir
            hostPath:
              path: /opt/libexec/k0s/kubelet-plugins/volume/exec
          - name: k8s-certs
            hostPath:
              path: /var/lib/k0s/pki
          # Where the additional volumes should be mounted into the pods:
          extraVolumeMounts:
            - name: flexvolume-dir
              mountPath: /opt/libexec/k0s/kubelet-plugins/volume/exec
              readOnly: true
            - name: k8s-certs
              mountPath: /var/lib/k0s/pki
              readOnly: true
    storage:
      create_default_storage_class: false
      type: external_storage
  storage:
    type: kine
  telemetry:
    enabled: false
```

The upgrades were done using k0sctl and all the upgrades seemed to have worked until we got to `1.31.2`. The upgrade hung and eventually errored that two pods in `kube-system` were not ready.

So, one of the pods at the time was CoreDNS — but before someone jumps on "it's a DNS problem", it did not seem to be.

We had other pods in namespaces failing, one common thing was that they are all using the Kubernetes API (via the `kubernetes` (service) that creates the virtual `https://10.96.0.0.1`). And all other failures were actually DNS because CoreDNS was not running.

The fun thing is, this IP is working from the node itself, but would not work from within a pod. Other service IPs did work (anything that was not this service basically), but of course DNS was also broken because CoreDNS was still in a weird crash loop because it couldn't access the  the Kubernetes API using the `10.96.0.0.1` host.

I think I read almost anything one can find on Google, the fact that the service is called `kubernetes` makes it of course extra hard to Google.

Basically the k8s api would work (from **pod and host**):

 - https://public.ip:6433 ✅ 
 - https://private.ip:6433 ✅ 

From the host: `https://10.96.0.1:443` ✅ 

From a pod: `https://10.96.0.1:443` 👎 

I also verified that other service IPs worked — anything but the `kubernetes` service was working on an IP level.

I also looked through Contrack, and see a ton of connections in waiting state. So these then/maybe/probably reflect the timeouts about API calls in the pod logs.

---

A couple things that we tried (that did not help):

- tried to tcpdump (e.g. `tcpdump -i eth0 dst 10.96.0.0.1`) on the host — nothing, it seems like traffic to the API does not leave the pod, I've also tried to fetch anything from specific pods, and I can generally see traffic, but nothing for the API service)
- tried to create a route for the service (some blog posts etc. suggested that, but to no avail)
- cleared iptables and prayed that a restart of kube-router/-proxy would recreate everything (it does recreate rules, but not "enough" to make the kubernetes service work)
- manually disabled kube-proxy and let kube-router also advertise services
- upgraded flatcar to the latest stable, etc.

The only thing that sort of helped — not really, but kinda — was patching all deployments and overriding the environment variables that do service discovery. Really ugly hack, but that made CoreDNS run at least. ;)

Anyway, I was hoping anyone else had any insights into this. I still have the node/cluster around to test and prod.
