### ISSUE TITLE
pushgateway-ttl image ignores global repository setting

### ISSUE THREAD

**Issue by byDimasik** [k0sproject/k0s#5455]
### Before creating an issue, make sure you've checked the following:

- [x] You are running the latest released version of k0s
- [x] Make sure you've searched for existing issues, both open and closed
- [x] Make sure you've searched for PRs too, a fix might've been merged already
- [x] You're looking at docs for the released version, "main" branch docs are usually ahead of released versions.

### Platform

```shell
PRETTY_NAME="Ubuntu 22.04.5 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.5 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
```

### Version

v1.31.1+k0s.1

### Sysinfo

<details><summary>`k0s sysinfo`</summary>
<pre>
Total memory: 15.4 GiB (pass)
File system of /var/lib/k0s: ext4 (pass)
Disk space available for /var/lib/k0s: 89.4 GiB (pass)
Relative disk space available for /var/lib/k0s: 92% (pass)
Name resolution: localhost: [::1 127.0.0.1] (pass)
Operating system: Linux (pass)
  Linux kernel release: 6.8.0-1021-aws (pass)
  Max. file descriptors per process: current: 1048576 / max: 1048576 (pass)
  AppArmor: active (pass)
  Executable in PATH: modprobe: /usr/sbin/modprobe (pass)
  Executable in PATH: mount: /usr/bin/mount (pass)
  Executable in PATH: umount: /usr/bin/umount (pass)
  /proc file system: mounted (0x9fa0) (pass)
  Control Groups: version 2 (pass)
    cgroup controller "cpu": available (is a listed root controller) (pass)
    cgroup controller "cpuacct": available (via cpu in version 2) (pass)
    cgroup controller "cpuset": available (is a listed root controller) (pass)
    cgroup controller "memory": available (is a listed root controller) (pass)
    cgroup controller "devices": available (device filters attachable) (pass)
    cgroup controller "freezer": available (cgroup.freeze exists) (pass)
    cgroup controller "pids": available (is a listed root controller) (pass)
    cgroup controller "hugetlb": available (is a listed root controller) (pass)
    cgroup controller "blkio": available (via io in version 2) (pass)
  CONFIG_CGROUPS: Control Group support: built-in (pass)
    CONFIG_CGROUP_FREEZER: Freezer cgroup subsystem: built-in (pass)
    CONFIG_CGROUP_PIDS: PIDs cgroup subsystem: built-in (pass)
    CONFIG_CGROUP_DEVICE: Device controller for cgroups: built-in (pass)
    CONFIG_CPUSETS: Cpuset support: built-in (pass)
    CONFIG_CGROUP_CPUACCT: Simple CPU accounting cgroup subsystem: built-in (pass)
    CONFIG_MEMCG: Memory Resource Controller for Control Groups: built-in (pass)
    CONFIG_CGROUP_HUGETLB: HugeTLB Resource Controller for Control Groups: built-in (pass)
    CONFIG_CGROUP_SCHED: Group CPU scheduler: built-in (pass)
      CONFIG_FAIR_GROUP_SCHED: Group scheduling for SCHED_OTHER: built-in (pass)
        CONFIG_CFS_BANDWIDTH: CPU bandwidth provisioning for FAIR_GROUP_SCHED: built-in (pass)
    CONFIG_BLK_CGROUP: Block IO controller: built-in (pass)
  CONFIG_NAMESPACES: Namespaces support: built-in (pass)
    CONFIG_UTS_NS: UTS namespace: built-in (pass)
    CONFIG_IPC_NS: IPC namespace: built-in (pass)
    CONFIG_PID_NS: PID namespace: built-in (pass)
    CONFIG_NET_NS: Network namespace: built-in (pass)
  CONFIG_NET: Networking support: built-in (pass)
    CONFIG_INET: TCP/IP networking: built-in (pass)
      CONFIG_IPV6: The IPv6 protocol: built-in (pass)
    CONFIG_NETFILTER: Network packet filtering framework (Netfilter): built-in (pass)
      CONFIG_NETFILTER_ADVANCED: Advanced netfilter configuration: built-in (pass)
      CONFIG_NF_CONNTRACK: Netfilter connection tracking support: module (pass)
      CONFIG_NETFILTER_XTABLES: Netfilter Xtables support: module (pass)
        CONFIG_NETFILTER_XT_TARGET_REDIRECT: REDIRECT target support: module (pass)
        CONFIG_NETFILTER_XT_MATCH_COMMENT: "comment" match support: module (pass)
        CONFIG_NETFILTER_XT_MARK: nfmark target and match support: module (pass)
        CONFIG_NETFILTER_XT_SET: set target and match support: module (pass)
        CONFIG_NETFILTER_XT_TARGET_MASQUERADE: MASQUERADE target support: module (pass)
        CONFIG_NETFILTER_XT_NAT: "SNAT and DNAT" targets support: module (pass)
        CONFIG_NETFILTER_XT_MATCH_ADDRTYPE: "addrtype" address type match support: module (pass)
        CONFIG_NETFILTER_XT_MATCH_CONNTRACK: "conntrack" connection tracking match support: module (pass)
        CONFIG_NETFILTER_XT_MATCH_MULTIPORT: "multiport" Multiple port match support: module (pass)
        CONFIG_NETFILTER_XT_MATCH_RECENT: "recent" match support: module (pass)
        CONFIG_NETFILTER_XT_MATCH_STATISTIC: "statistic" match support: module (pass)
      CONFIG_NETFILTER_NETLINK: module (pass)
      CONFIG_NF_NAT: module (pass)
      CONFIG_IP_SET: IP set support: module (pass)
        CONFIG_IP_SET_HASH_IP: hash:ip set support: module (pass)
        CONFIG_IP_SET_HASH_NET: hash:net set support: module (pass)
      CONFIG_IP_VS: IP virtual server support: module (pass)
        CONFIG_IP_VS_NFCT: Netfilter connection tracking: built-in (pass)
        CONFIG_IP_VS_SH: Source hashing scheduling: module (pass)
        CONFIG_IP_VS_RR: Round-robin scheduling: module (pass)
        CONFIG_IP_VS_WRR: Weighted round-robin scheduling: module (pass)
      CONFIG_NF_CONNTRACK_IPV4: IPv4 connetion tracking support (required for NAT): unknown (warning)
      CONFIG_NF_REJECT_IPV4: IPv4 packet rejection: module (pass)
      CONFIG_NF_NAT_IPV4: IPv4 NAT: unknown (warning)
      CONFIG_IP_NF_IPTABLES: IP tables support: module (pass)
        CONFIG_IP_NF_FILTER: Packet filtering: module (pass)
          CONFIG_IP_NF_TARGET_REJECT: REJECT target support: module (pass)
        CONFIG_IP_NF_NAT: iptables NAT support: module (pass)
        CONFIG_IP_NF_MANGLE: Packet mangling: module (pass)
      CONFIG_NF_DEFRAG_IPV4: module (pass)
      CONFIG_NF_CONNTRACK_IPV6: IPv6 connetion tracking support (required for NAT): unknown (warning)
      CONFIG_NF_NAT_IPV6: IPv6 NAT: unknown (warning)
      CONFIG_IP6_NF_IPTABLES: IP6 tables support: module (pass)
        CONFIG_IP6_NF_FILTER: Packet filtering: module (pass)
        CONFIG_IP6_NF_MANGLE: Packet mangling: module (pass)
        CONFIG_IP6_NF_NAT: ip6tables NAT support: module (pass)
      CONFIG_NF_DEFRAG_IPV6: module (pass)
    CONFIG_BRIDGE: 802.1d Ethernet Bridging: module (pass)
      CONFIG_LLC: module (pass)
      CONFIG_STP: module (pass)
  CONFIG_EXT4_FS: The Extended 4 (ext4) filesystem: built-in (pass)
  CONFIG_PROC_FS: /proc file system support: built-in (pass)
</pre>
</details>

### What happened?

When I set `.spec.images.repository` to a custom value, the image registry doesn't change for `quay.io/k0sproject/pushgateway-ttl` in the resulting `RuntimeConfig` at `/var/run/k0s/k0s.yaml`. Thus, all images except this one use the registry I set, but the pushgateway stays in the default registry, which is unavailable in my airgap env. 

<details>
<summary>/etc/k0s/k0s.yaml</summary>

```yaml
# generated-by-k0sctl 2025-01-20T15:41:03-05:00
apiVersion: k0s.k0sproject.io/v1beta1
kind: Cluster
metadata:
  name: mke
spec:
  api:
    externalAddress: 8m1d9u-mke4-lb-7db5d72781ebbb64.elb.us-east-2.amazonaws.com
    extraArgs:
      authentication-config: /var/lib/k0s/oidc-config.yaml
      encryption-provider-config: /var/lib/k0s/encryption.cfg
      profiling: "false"
      request-timeout: 1m0s
      service-node-port-range: 32768-35535
    sans:
    - 8m1d9u-mke4-lb-7db5d72781ebbb64.elb.us-east-2.amazonaws.com
    - 3.144.128.135
    - 172.31.32.29
  controllerManager:
    extraArgs:
      profiling: "false"
      terminated-pod-gc-threshold: "12500"
  images:
    repository: ghcr.io/mirantiscontainers
  network:
    clusterDomain: cluster.local
    dualStack: {}
    kubeProxy:
      iptables:
        minSyncPeriod: 0s
        syncPeriod: 0s
      ipvs:
        minSyncPeriod: 0s
        syncPeriod: 0s
        tcpFinTimeout: 0s
        tcpTimeout: 0s
        udpTimeout: 0s
      metricsBindAddress: 0.0.0.0:10249
      mode: iptables
    podCIDR: 192.168.0.0/16
    provider: custom
    serviceCIDR: 10.96.0.0/16
  scheduler:
    extraArgs:
      bind-address: 127.0.0.1
      profiling: "false"
  storage:
    etcd:
      extraArgs: {}
      peerAddress: 172.31.32.29
    type: etcd
  telemetry:
    enabled: true
  workerProfiles:
  - name: mke-default-worker
    values:
      eventRecordQPS: 50
      kubeReserved:
        cpu: 50m
        ephemeral-storage: 500Mi
        memory: 300Mi
      maxPods: 110
      podPidsLimit: -1
      podsPerCore: 0
      protectKernelDefaults: false
      seccompDefault: false
  - name: mke-default-manager
    values:
      eventRecordQPS: 50
      kubeReserved:
        cpu: 250m
        ephemeral-storage: 4Gi
        memory: 2Gi
      maxPods: 110
      podPidsLimit: -1
      podsPerCore: 0
      protectKernelDefaults: false
      seccompDefault: false
```

</details>

<details>
<summary>/var/run/k0s/k0s.yaml</summary>

```yaml
apiVersion: k0s.k0sproject.io/v1beta1
kind: RuntimeConfig
metadata:
  creationTimestamp: "2025-01-20T20:42:49Z"
spec:
  k0sVars:
    AdminKubeConfigPath: /var/lib/k0s/pki/admin.conf
    BinDir: /var/lib/k0s/bin
    CertRootDir: /var/lib/k0s/pki
    DataDir: /var/lib/k0s
    DefaultStorageType: etcd
    EnableDynamicConfig: false
    EtcdCertDir: /var/lib/k0s/pki/etcd
    EtcdDataDir: /var/lib/k0s/etcd
    HelmHome: /var/lib/k0s/helmhome
    HelmRepositoryCache: /var/lib/k0s/helmhome/cache
    HelmRepositoryConfig: /var/lib/k0s/helmhome/repositories.yaml
    InvocationID: 326134562200d09a7b3974811aed1902
    KineSocketPath: /run/k0s/kine/kine.sock:2379
    KonnectivityKubeConfigPath: /var/lib/k0s/pki/konnectivity.conf
    KonnectivitySocketDir: /run/k0s/konnectivity-server
    KubeletAuthConfigPath: /var/lib/k0s/kubelet.conf
    KubeletVolumePluginDir: /usr/libexec/k0s/kubelet-plugins/volume/exec
    ManifestsDir: /var/lib/k0s/manifests
    OCIBundleDir: /var/lib/k0s/images
    RunDir: /run/k0s
    RuntimeConfigPath: /run/k0s/k0s.yaml
    StartupConfigPath: /etc/k0s/k0s.yaml
    StatusSocketPath: /run/k0s/status.sock
  nodeConfig:
    apiVersion: k0s.k0sproject.io/v1beta1
    kind: Cluster
    metadata:
      creationTimestamp: null
      name: mke
    spec:
      api:
        address: 172.31.32.29
        externalAddress: 8m1d9u-mke4-lb-7db5d72781ebbb64.elb.us-east-2.amazonaws.com
        extraArgs:
          authentication-config: /var/lib/k0s/oidc-config.yaml
          encryption-provider-config: /var/lib/k0s/encryption.cfg
          profiling: "false"
          request-timeout: 1m0s
          service-node-port-range: 32768-35535
        k0sApiPort: 9443
        port: 6443
        sans:
        - 8m1d9u-mke4-lb-7db5d72781ebbb64.elb.us-east-2.amazonaws.com
        - 3.144.128.135
        - 172.31.32.29
      controllerManager:
        extraArgs:
          profiling: "false"
          terminated-pod-gc-threshold: "12500"
      extensions:
        helm:
          concurrencyLevel: 5
      images:
        calico:
          cni:
            image: ghcr.io/mirantiscontainers/k0sproject/calico-cni
            version: v3.28.2-0
          kubecontrollers:
            image: ghcr.io/mirantiscontainers/k0sproject/calico-kube-controllers
            version: v3.28.2-0
          node:
            image: ghcr.io/mirantiscontainers/k0sproject/calico-node
            version: v3.28.2-0
        coredns:
          image: ghcr.io/mirantiscontainers/k0sproject/coredns
          version: 1.11.3
        default_pull_policy: IfNotPresent
        konnectivity:
          image: ghcr.io/mirantiscontainers/k0sproject/apiserver-network-proxy-agent
          version: v0.30.3
        kubeproxy:
          image: ghcr.io/mirantiscontainers/k0sproject/kube-proxy
          version: v1.31.1
        kuberouter:
          cni:
            image: ghcr.io/mirantiscontainers/k0sproject/kube-router
            version: v2.2.1-iptables1.8.9-0
          cniInstaller:
            image: ghcr.io/mirantiscontainers/k0sproject/cni-node
            version: 1.3.0-k0s.0
        metricsserver:
          image: ghcr.io/mirantiscontainers/metrics-server/metrics-server
          version: v0.7.2
        pause:
          image: ghcr.io/mirantiscontainers/pause
          version: "3.9"
        pushgateway:
          image: quay.io/k0sproject/pushgateway-ttl
          version: 1.4.0-k0s.0
        repository: ghcr.io/mirantiscontainers
      installConfig:
        users:
          etcdUser: etcd
          kineUser: kube-apiserver
          konnectivityUser: konnectivity-server
          kubeAPIserverUser: kube-apiserver
          kubeSchedulerUser: kube-scheduler
      konnectivity:
        adminPort: 8133
        agentPort: 8132
      network:
        clusterDomain: cluster.local
        dualStack:
          enabled: false
        kubeProxy:
          iptables:
            minSyncPeriod: 0s
            syncPeriod: 0s
          ipvs:
            minSyncPeriod: 0s
            syncPeriod: 0s
            tcpFinTimeout: 0s
            tcpTimeout: 0s
            udpTimeout: 0s
          metricsBindAddress: 0.0.0.0:10249
          mode: iptables
          nftables:
            minSyncPeriod: 0s
            syncPeriod: 0s
        kuberouter:
          autoMTU: true
          hairpin: Enabled
          metricsPort: 8080
        nodeLocalLoadBalancing:
          enabled: false
          envoyProxy:
            apiServerBindPort: 7443
            image:
              image: ghcr.io/mirantiscontainers/k0sproject/envoy-distroless
              version: v1.31.1
            konnectivityServerBindPort: 7132
          type: EnvoyProxy
        podCIDR: 192.168.0.0/16
        provider: custom
        serviceCIDR: 10.96.0.0/16
      scheduler:
        extraArgs:
          bind-address: 127.0.0.1
          profiling: "false"
      storage:
        etcd:
          peerAddress: 172.31.32.29
        type: etcd
      telemetry:
        enabled: true
      workerProfiles:
      - name: mke-default-worker
        values:
          eventRecordQPS: 50
          kubeReserved:
            cpu: 50m
            ephemeral-storage: 500Mi
            memory: 300Mi
          maxPods: 110
          podPidsLimit: -1
          podsPerCore: 0
          protectKernelDefaults: false
          seccompDefault: false
      - name: mke-default-manager
        values:
          eventRecordQPS: 50
          kubeReserved:
            cpu: 250m
            ephemeral-storage: 4Gi
            memory: 2Gi
          maxPods: 110
          podPidsLimit: -1
          podsPerCore: 0
          protectKernelDefaults: false
          seccompDefault: false
  pid: 13300
```

</details>

### Steps to reproduce

1. In k0s config, set `.spec.images.repository` to a custom value, e.g. `ghcr.io/mirantiscontainers`
2. Deploy k0s
3. Check the resulting `RuntimeConfig` located at `/var/run/k0s/k0s.yaml` on a controller node

### Expected behavior

All images with no exceptions should use the globally set image repository.

Pushgateway image should use the repository from the config, not the default `quay.io`

```
        pushgateway:
          image: ghcr.io/mirantiscontainers/k0sproject/pushgateway-ttl
          version: 1.4.0-k0s.0
```

### Actual behavior

Pushgateway image uses the default registry `quay.io`; instead it should use the value from the config, `ghcr.io/mirantiscontainers`

```
        pushgateway:
          image: quay.io/k0sproject/pushgateway-ttl
          version: 1.4.0-k0s.0
```

### Screenshots and logs

```
% k0s kubectl get pods --all-namespaces -o jsonpath="{.items[*].spec['initContainers', 'containers'][*].image}" |\
tr -s '[[:space:]]' '\n' |\
sort |\
uniq |\
grep k0s
ghcr.io/mirantiscontainers/k0sproject/coredns:1.11.3
ghcr.io/mirantiscontainers/k0sproject/kube-proxy:v1.31.1
quay.io/k0sproject/pushgateway-ttl:1.4.0-k0s.0
```
