### ISSUE TITLE
Non-overlay networking

### ISSUE THREAD

**Issue by paveq** [k0sproject/k0s#558]
It should be possible to use non-overlay networking for calico when operating inside single L2 subnet, as this option has the least overhead.

Currently the documentation states only IPIP and VXLAN are possible options.

**Comment by paveq** [comment]
One option how it could look like:
```
  network:
    provider: calico
    calico:
      mode: vxlan
      overlay: Always (default), CrossSubnet, Never
```
Depending if IPIP or VXLAN is being used, this might be easy as pass that parameter to either CALICO_IPV4POOL_IPIP or CALICO_IPV4POOL_VXLAN env variable on calico node.

**Comment by binoychitale** [comment]
I would like to pick this up. 
Currently overlay configuration is hard-coded to `Always` in `static/manifests/calico/DaemonSet/calico-node.yaml`

We can pick up the overlay mode from the config yaml (while defaulting to `Always`), similar to the format described above :

```yaml
network:
    provider: calico
    calico:
      mode: vxlan
      overlay: Always (default), CrossSubnet, Never
``` 

I'll spin up a PR for this
