### ISSUE TITLE
Custom network provider

### ISSUE THREAD

**Issue by jnummelin** [k0sproject/k0s#56]
Not everyone is gonna want to use calico, so we'd need to support a custom CNI provider. Maybe the config could be something like:
```
apiVersion: mke.mirantis.com/v1beta1
kind: Cluster
metadata:
  name: foobar
spec:
  network:
    provider: custom
```

It is then up to the user to make the CNI work. Fairly easy by pushing their CNI manifests into `/var/lib/mke/manifests` :)
