### ISSUE TITLE
[QUESTION] Migrating k0s from Embedded etcd to External etcd – Missing Data

### ISSUE THREAD

**Issue by Bugs5382** [k0sproject/k0s#5718]
Greetings k0s team,  

I recently migrated from embedded etcd due to a secret exceeding 1MB, which caused issues when applying changes via Helm updates. Here’s what I’ve done so far:  

1. Backed up the embedded etcd database.  
2. Restored the etcd database to a remote server.  
3. Deployed an etcd instance (using the Bitnami image) in Docker with the restored data. The etcd server confirms that data exists.  
4. Reconfigured the k0s controller using `k0scontrol` with the following configuration:  

   ```yaml
   k0s:
     version: 1.30.5+k0s.0
     config:
       apiVersion: k0s.k0sproject.io/v1beta1
       kind: ClusterConfig
       metadata:
         name: test-k0s-cluster
       spec:
         storage:
           type: etcd
           etcd:
             externalCluster:
               etcdPrefix: k0s
               endpoints:
                 - https://FQDN:2379
               caFile: /etc/k0s/pki/etcd-ca.crt
               clientCertFile: /etc/k0s/pki/etcd-client.crt
               clientKeyFile: /etc/k0s/pki/etcd-client.key
   ```

5. All applications were deployed via Helm orginially. However, after switching to the new API, none of the data from etcd is being read to re-deploy the helm releases or charts, etc.

I checked the `etcdctl endpoint health` command, and it confirms that k0s is successfully connecting to the etcd server. However, I couldn't find documentation on the default `etcdPrefix` used by embedded etcd. I assumed it was `k0s`, but I’m unsure.  

Does anyone know the default etcd prefix for embedded etcd in k0s? Or have any suggestions on what might be causing this issue?  

Any insights would be greatly appreciated!
