### ISSUE TITLE
Support for configuring Spegel.dev

### ISSUE THREAD

**Issue by Tokynet** [k0sproject/k0s#5746]
I am running k0s (v1.31.1+k0s.1) and I'm trying to configure spegel in my cluster (to help alleviate the docker hub pulls).

From the k0s docs, I found that containerd is Not installed in the default location, it is installed in the following paths:

```shell
/var/lib/k0s/bin/containerd \
    --root=/var/lib/k0s/containerd \
    --state=/run/k0s/containerd \
    --address=/run/k0s/containerd.sock \
    --config=/etc/k0s/containerd.toml
```
I have edited the (helm) values file to reflect these different paths:
(Helm chart => https://github.com/spegel-org/spegel/tree/main/charts/spegel )

```yaml
spegel:
  # -- Minimum log level to output. Value should be DEBUG, INFO, WARN, or ERROR.
  logLevel: "INFO"

  # -- Registries for which mirror configuration will be created. Empty means all registires will be mirrored.
  mirroredRegistries: []
    # - https://docker.io
    # - https://ghcr.io


  # -- Additional target mirror registries other than Spegel.
  additionalMirrorTargets: []

  # -- Max amount of mirrors to attempt.
  mirrorResolveRetries: 3

  # -- Max duration spent finding a mirror.
  mirrorResolveTimeout: "20ms"

  # -- Path to Containerd socket.
  containerdSock: "/run/k0s/containerd.sock"

  # -- Containerd namespace where images are stored.
  containerdNamespace: "k8s.io"

  # -- Path to Containerd mirror configuration.
  containerdRegistryConfigPath: "/run/k0s"

  # -- Path to Containerd content store..
  containerdContentPath: "/var/lib/k0s/containerd/io.containerd.content.v1.content"

```

However, the pods fail to start with the following message:

```json
{
  "level": "error",
  "ts": 1744302440.6794097,
  "caller": "build/main.go:63",
  "msg": "could not create containerd client",
  "error": "failed to dial \"/run/k0s/containerd.sock\": context deadline exceeded: connection error: desc = \"transport: error while dialing: dial unix:///run/k0s/containerd.sock: timeout\"",
  "stacktrace": "main.main\n\t/build/main.go:63\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:250"
}
```

Not expecting help with spegel itself, just hoping to get any pointers/issues on my config for the containerd parameters from k0s.

Thanks in advance

*edited to add the URL for the helm chart*

**Comment by phillebaba** [comment]
@Tokynet you are right that the configuration is stored and picked up from different non standard locations. The documentation however does a really good job describing most of the configuration. Most of the critical information can be found in the runtime documentation.

https://docs.k0sproject.io/stable/runtime/

I quickly did some tests running k0s in Docker and managed to get Spegel working. I will add the instructions to the compatibility guide for future users. I think the main concern is that the error you see are related to the containerd socket which is correctly configured by you.

To get Spegel working you will need to append to the Containerd configuration. Luckily enough k0s has already configured a a directory where it will pickup configuration from. Note that you need to write this configuration before k0s is started as it is not hot reloaded. The following file needs to be placed in `/etc/k0s/containerd.d/`, in my case I called the file `spegel.toml`.

```toml
[plugins."io.containerd.grpc.v1.cri".registry]
   config_path = "/etc/containerd/certs.d"
[plugins."io.containerd.grpc.v1.cri".containerd]
   discard_unpacked_layers = false
```

Here are the values that you need to use that deviate from the defaults.

```yaml
spegel:
  containerdSock: "/run/k0s/containerd.sock"
  containerdContentPath: "/var/lib/k0s/containerd/io.containerd.content.v1.content"
```

After all of this configuration is set you should be able to install Spegel in your k0s cluster.

```shell
helm upgrade --create-namespace --namespace spegel -f values.yaml --install spegel oci://ghcr.io/spegel-org/helm-charts/spegel
```

Hopefully these instructions will help you get things working.
