### ISSUE TITLE
k0s in docker multi controller node

### ISSUE THREAD

**Issue by tdesaules** [k0sproject/k0s#5758]
Hello community, I'm trying to achieve something specific: configuring a multi-controller K0s cluster directly within Docker.

I managed without too much difficulty to set up a cluster with a single controller and multiple workers using Docker Compose. However, I'm stuck on adding more controller nodes.

Has anyone already tried this (I have an etcd leader election problem) ?

Here's my docker-compose.yaml file (I did a little experimentation with Traefik without much success):

```yaml
name: k0s

services:

  k0s-traefik-1:
    image: docker.io/traefik:v3.3.5
    container_name: k0s-traefik-1
    hostname: k0s-traefik-1
    network_mode: bridge
    privileged: true
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.kube-api.address=:6443"
      - "--entryPoints.controller-api.address=:9443"
      - "--entryPoints.konnectivity.address=:8132"
      - '--log.level=INFO'
    ports:
      - 6443:6443
      - 9443:9443
      - 8132:8132
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

  k0s-controller-1:
    image: docker.io/k0sproject/k0s:v1.32.3-k0s.0
    container_name: k0s-controller-1
    hostname: k0s-controller-1
    network_mode: bridge
    privileged: true
    depends_on:
      - k0s-traefik-1
    command: k0s controller --enable-worker
    post_start:
      - command: ["/bin/sh", "-c", "sleep 10"]
      - command: ["/bin/sh", "-c", "k0s token create --role=controller | tee /k0s-token-controller/token"]
      - command: ["/bin/sh", "-c", "k0s token create --role=worker | tee /k0s-token-worker/token"]
    volumes:
      - /var/lib/k0s
      - /var/log/pods
      - k0s-token-controller:/k0s-token-controller
      - k0s-token-worker:/k0s-token-worker
    tmpfs:
      - /run
      - /tmp
    configs:
      - source: k0s.yaml
        target: /etc/k0s/k0s.yaml
    labels:
      - "traefik.enable=true"
      - "traefik.tcp.routers.kube-api.service=kube-api"
      - "traefik.tcp.routers.kube-api.rule=HostSNI(`*`)"
      - "traefik.tcp.routers.kube-api.entrypoints=kube-api"
      - "traefik.tcp.services.kube-api.loadbalancer.server.port=6443"
      - "traefik.tcp.routers.controller-api.service=controller-api"
      - "traefik.tcp.routers.controller-api.rule=HostSNI(`*`)"
      - "traefik.tcp.routers.controller-api.entrypoints=controller-api"
      - "traefik.tcp.services.controller-api.loadbalancer.server.port=9443"
      - "traefik.tcp.routers.konnectivity.service=konnectivity"
      - "traefik.tcp.routers.konnectivity.rule=HostSNI(`*`)"
      - "traefik.tcp.routers.konnectivity.entrypoints=konnectivity"
      - "traefik.tcp.services.konnectivity.loadbalancer.server.port=8132"

  k0s-controller-2:
    image: docker.io/k0sproject/k0s:v1.32.3-k0s.0
    container_name: k0s-controller-2
    hostname: k0s-controller-2
    network_mode: bridge
    privileged: true
    depends_on:
      - k0s-controller-1
    command: k0s controller --token-file /k0s-token-controller/token --enable-worker
    volumes:
      - /var/lib/k0s
      - /var/log/pods
      - k0s-token-controller:/k0s-token-controller:ro
    tmpfs:
      - /run
      - /tmp
    configs:
      - source: k0s.yaml
        target: /etc/k0s/k0s.yaml
    labels:
      - "traefik.enable=true"
      - "traefik.tcp.routers.kube-api.service=kube-api"
      - "traefik.tcp.routers.kube-api.rule=HostSNI(`*`)"
      - "traefik.tcp.routers.kube-api.entrypoints=kube-api"
      - "traefik.tcp.services.kube-api.loadbalancer.server.port=6443"
      - "traefik.tcp.routers.controller-api.service=controller-api"
      - "traefik.tcp.routers.controller-api.rule=HostSNI(`*`)"
      - "traefik.tcp.routers.controller-api.entrypoints=controller-api"
      - "traefik.tcp.services.controller-api.loadbalancer.server.port=9443"
      - "traefik.tcp.routers.konnectivity.service=konnectivity"
      - "traefik.tcp.routers.konnectivity.rule=HostSNI(`*`)"
      - "traefik.tcp.routers.konnectivity.entrypoints=konnectivity"
      - "traefik.tcp.services.konnectivity.loadbalancer.server.port=8132"

  k0s-controller-3:
    image: docker.io/k0sproject/k0s:v1.32.3-k0s.0
    container_name: k0s-controller-3
    hostname: k0s-controller-3
    network_mode: bridge
    privileged: true
    depends_on:
      - k0s-controller-1
    command: k0s controller --token-file /k0s-token-controller/token --enable-worker
    volumes:
      - /var/lib/k0s
      - /var/log/pods
      - k0s-token-controller:/k0s-token-controller:ro
    tmpfs:
      - /run
      - /tmp
    configs:
      - source: k0s.yaml
        target: /etc/k0s/k0s.yaml
    labels:
      - "traefik.enable=true"
      - "traefik.tcp.routers.kube-api.service=kube-api"
      - "traefik.tcp.routers.kube-api.rule=HostSNI(`*`)"
      - "traefik.tcp.routers.kube-api.entrypoints=kube-api"
      - "traefik.tcp.services.kube-api.loadbalancer.server.port=6443"
      - "traefik.tcp.routers.controller-api.service=controller-api"
      - "traefik.tcp.routers.controller-api.rule=HostSNI(`*`)"
      - "traefik.tcp.routers.controller-api.entrypoints=controller-api"
      - "traefik.tcp.services.controller-api.loadbalancer.server.port=9443"
      - "traefik.tcp.routers.konnectivity.service=konnectivity"
      - "traefik.tcp.routers.konnectivity.rule=HostSNI(`*`)"
      - "traefik.tcp.routers.konnectivity.entrypoints=konnectivity"
      - "traefik.tcp.services.konnectivity.loadbalancer.server.port=8132"

  k0s-worker-1:
    image: docker.io/k0sproject/k0s:v1.32.3-k0s.0
    container_name: k0s-worker-1
    hostname: k0s-worker-1
    network_mode: bridge
    privileged: true
    command: k0s worker --token-file /k0s-token-worker/token
    depends_on:
      - k0s-controller-1
    volumes:
      - /var/lib/k0s
      - /var/log/pods
      - k0s-token-worker:/k0s-token-worker:ro
    tmpfs:
      - /run
      - /tmp
    configs:
      - source: k0s.yaml
        target: /etc/k0s/k0s.yaml

  k0s-worker-2:
    image: docker.io/k0sproject/k0s:v1.32.3-k0s.0
    container_name: k0s-worker-2
    hostname: k0s-worker-2
    network_mode: bridge
    privileged: true
    command: k0s worker --token-file /k0s-token-worker/token
    depends_on:
      - k0s-controller-1
    volumes:
      - /var/lib/k0s
      - /var/log/pods
      - k0s-token-worker:/k0s-token-worker:ro
    tmpfs:
      - /run
      - /tmp
    configs:
      - source: k0s.yaml
        target: /etc/k0s/k0s.yaml

  k0s-worker-3:
    image: docker.io/k0sproject/k0s:v1.32.3-k0s.0
    container_name: k0s-worker-3
    hostname: k0s-worker-3
    network_mode: bridge
    privileged: true
    command: k0s worker --token-file /k0s-token-worker/token
    depends_on:
      - k0s-controller-1
    volumes:
      - /var/lib/k0s
      - /var/log/pods
      - k0s-token-worker:/k0s-token-worker:ro
    tmpfs:
      - /run
      - /tmp
    configs:
      - source: k0s.yaml
        target: /etc/k0s/k0s.yaml

configs:
  k0s.yaml:
    content: |
      apiVersion: k0s.k0sproject.io/v1beta1
      kind: ClusterConfig
      metadata:
        name: k0s
      spec:
        api:
          externalAddress: 172.17.0.2
          sans:
            - 172.17.0.2

volumes:
  k0s-token-controller:
    name: k0s-token-controller
  k0s-token-worker:
    name: k0s-token-worker
```
