### ISSUE TITLE
vSphere CSI not fully functional 

### ISSUE THREAD

**Issue by ChrisJLittle** [k0sproject/k0s#580]
**Version**
```
v0.8.1
```
**Platform**
Which platform did you run k0s on?
```
Ubuntu 20.10
```
**What happened?**

K0s relies on helm charts to automate the deployment of any extra components, like CNS/CSI. I'm using https://github.com/cormachogan/vsphere-csi-helmchart to help get CNS/CSI deployed in an automated fashion.

The first issue I hit was that k0s deploys the kubelet to `/var/lib/k0s/kubelet` and there is little that can be done to change this. I found that the vSphere CNS/CSI deployment was expecting kubelet to be running under `/var/lib/kubelet` and was not getting properly registered with the cluster. To work around this, I created a symlink such for `/var/lib/kubelet` that points to `/var/lib/k0s/kubelet` which helped to get around the first problem.

What I'm seeing now is that PVs/PVCs can successfully be created but when a pod tries to mount one, the following is occurring:

```
Events:
  Type     Reason                  Age                From                     Message
  ----     ------                  ----               ----                     -------
  Warning  FailedScheduling        52s                default-scheduler        persistentvolumeclaim "mysql-pv-claim" not found
  Warning  FailedScheduling        47s (x3 over 52s)  default-scheduler        0/2 nodes are available: 2 pod has unbound immediate PersistentVolumeClaims.
  Normal   Scheduled               38s                default-scheduler        Successfully assigned default/wordpress-mysql-6dc7b989c9-dk5d5 to wrk1
  Normal   SuccessfulAttachVolume  37s                attachdetach-controller  AttachVolume.Attach succeeded for volume "pvc-f60e0b4c-c511-415d-96b9-c1fb367d08e8"
  Warning  FailedMount             15s (x6 over 31s)  kubelet                  MountVolume.MountDevice failed for volume "pvc-f60e0b4c-c511-415d-96b9-c1fb367d08e8" : rpc error: code = FailedPrecondition desc = target: /var/lib/k0s/kubelet/plugins/kubernetes.io/csi/pv/pvc-f60e0b4c-c511-415d-96b9-c1fb367d08e8/globalmount not pre-created
```

I checked on the worker node and there is nothing under `/var/lib/k0s/kubelet/plugins/kubernetes.io/csi/pv`.

**How To Reproduce**

Deploy k0s on Ubuntu 20.10, running on vSphere 7.0

On control plane and worker nodes:
```
sudo mkdir -p /var/lib/k0s/kubelet
sudo ln -s /var/lib/k0s/kubelet /var/lib/kubelet
```
On control plane node:
```
sudo ./k0s server -c k0s.yaml --enable-worker
sudo ./k0s token create --role=worker
```
On worker node:
```
sudo ./k0s worker --enable-cloud-provider=true "<token>"
```
Taint and label the control plane node (required for vSphere CNS to work):
```
kubectl taint node cp1 node-role.kubernetes.io/master:NoSchedule
kubectl label node cp1 node-role.kubernetes.io/master=
```
Update providerID on control plane and worker nodes (required for vSphere CNS to work):
```
for vm in $(govc ls "/RegionA01/vm"); do
  MACHINE_INFO=$(govc vm.info -json -dc=RegionA01 -vm.ipath="/$vm" -e=true)
  VM_NAME=$(jq -r ' .VirtualMachines[] | .Name' <<< $MACHINE_INFO | awk '{print tolower($0)}')
  VM_UUID=$(jq -r ' .VirtualMachines[] | .Config.Uuid' <<< $MACHINE_INFO | awk '{print toupper($0)}')
  kubectl patch node $VM_NAME -p "{\"spec\":{\"providerID\":\"vsphere://$VM_UUID\"}}"
done
```
Deploy a stateful app and the noted errors will be generated

**Expected behavior**

That the pod is able to mount the pvc

**Screenshots & Logs**

```
INFO[2020-12-23 09:43:48] E1223 09:43:48.179674    8630 csi_attacher.go:328] kubernetes.io/csi: attacher.MountDevice failed: rpc error: code = FailedPrecondition desc = target: /var/lib/k0s/kubelet/plugins/kubernetes.io/csi/pv/pvc-17d11c38-9c94-436f-b0a1-a3bdb41bf833/globalmount not pre-created  component=kubelet
INFO[2020-12-23 09:43:48] E1223 09:43:48.179860    8630 nestedpendingoperations.go:301] Operation for "{volumeName:kubernetes.io/csi/csi.vsphere.vmware.com^c0ed09ac-71a8-4569-a08a-59d32c130e34 podName: nodeName:}" failed. No retries permitted until 2020-12-23 09:45:50.179834134 -0700 MST m=+2240.807216184 (durationBeforeRetry 2m2s). Error: "MountVolume.MountDevice failed for volume \"pvc-17d11c38-9c94-436f-b0a1-a3bdb41bf833\" (UniqueName: \"kubernetes.io/csi/csi.vsphere.vmware.com^c0ed09ac-71a8-4569-a08a-59d32c130e34\") pod \"wordpress-5b95c8b995-4tmlb\" (UID: \"df09c0d4-5a17-440f-bc73-6ea75bea53f3\") : rpc error: code = FailedPrecondition desc = target: /var/lib/k0s/kubelet/plugins/kubernetes.io/csi/pv/pvc-17d11c38-9c94-436f-b0a1-a3bdb41bf833/globalmount not pre-created"  component=kubelet
```

**Additional context**

k0s.yaml:

```
apiVersion: k0s.k0sproject.io/v1beta1
kind: Cluster
metadata:
  name: k0s
spec:
  api:
    address: 192.168.110.101
    sans:
    - 192.168.110.101
    - 192.168.110.101
    extraArgs: {}
  controllerManager:
    extraArgs: {}
  scheduler:
    extraArgs: {}
  storage:
    type: etcd
    kine: null
    etcd:
      peerAddress: 192.168.110.101
  network:
    podCIDR: 10.244.0.0/16
    serviceCIDR: 10.96.0.0/12
    provider: calico
    calico:
      mode: vxlan
      vxlanPort: 4789
      vxlanVNI: 4096
      mtu: 1450
      wireguard: false
  podSecurityPolicy:
    defaultPolicy: 00-k0s-privileged
  workerProfiles: []
extensions:
  helm:
    repositories:
    - name: cormachogan
      url: https://cormachogan.github.io/vsphere-csi-helmchart
    - name: bitnami
      url: https://charts.bitnami.com/bitnami
    charts:
    - name: vsphere-csi
      chartname: cormachogan/vsphere-csi
      version: 0.0.3
      values: |
        vsphere-cpi:
          config:
            enabled: true
            vcenter: vcsa-01a.corp.tanzu
            username: administrator@vsphere.local
            password: VMware1!
            datacenter: RegionA01
        global:
          config:
            enabled: true
            vcenter: vcsa-01a.corp.tanzu
            username: administrator@vsphere.local
            password: VMware1!
            datacenter: RegionA01
        config:
          enabled: true
          create: true
          name: vsphere-config-secret
          clusterId: RegionA01-MGMT
          port: 443
        netconfig:
          enabled: false
      namespace: kube-system
    - name: metallb
      chartname: bitnami/metallb
      version: 2.0.0
      values: |
        configInline: 
          peers:
          - peer-address: 192.168.100.1
            peer-asn: 65002
            my-asn: 65022
          address-pools:
          - name: default
            protocol: bgp
            addresses:
            - 10.40.14.0/27
            bgp-advertisements:
            - aggregation-length: 27
      namespace: default
images:
  konnectivity:
    image: us.gcr.io/k8s-artifacts-prod/kas-network-proxy/proxy-agent
    version: v0.0.13
  metricsserver:
    image: gcr.io/k8s-staging-metrics-server/metrics-server
    version: v0.3.7
  kubeproxy:
    image: k8s.gcr.io/kube-proxy
    version: v1.19.4
  coredns:
    image: docker.io/coredns/coredns
    version: 1.7.0
  calico:
    cni:
      image: calico/cni
      version: v3.16.2
    flexvolume:
      image: calico/pod2daemon-flexvol
      version: v3.16.2
    node:
      image: calico/node
      version: v3.16.2
    kubecontrollers:
      image: calico/kube-controllers
      version: v3.16.2
  repository: ""
telemetry:
  interval: 10m0s
  enabled: true
```

It seems like providing the ability to specify just the location of kubelet files may help here. I tried using the `--data-dir` parameter to get kubelet under `/var/lib` but that resulted in everything being dumped under `/var/lib`, and caused more problems.
