### ISSUE TITLE
k0s metrics-server "No agent available"

### ISSUE THREAD

**Issue by Rodri2911** [k0sproject/k0s#5809]
### Before creating an issue, make sure you've checked the following:

- [x] You are running the latest released version of k0s
- [x] Make sure you've searched for existing issues, both open and closed
- [x] Make sure you've searched for PRs too, a fix might've been merged already
- [x] You're looking at docs for the released version, "main" branch docs are usually ahead of released versions.

### Platform

```shell
NAME="Oracle Linux Server"
VERSION="8.10"
ID="ol"
ID_LIKE="fedora"
VARIANT="Server"
VARIANT_ID="server"
VERSION_ID="8.10"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Oracle Linux Server 8.10"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:oracle:linux:8:10:server"
HOME_URL="https://linux.oracle.com/"
BUG_REPORT_URL="https://github.com/oracle/oracle-linux"

ORACLE_BUGZILLA_PRODUCT="Oracle Linux 8"
ORACLE_BUGZILLA_PRODUCT_VERSION=8.10
ORACLE_SUPPORT_PRODUCT="Oracle Linux"
ORACLE_SUPPORT_PRODUCT_VERSION=8.10
```

### Version

v1.32.4+k0s.0

### Sysinfo

<details><summary>`k0s sysinfo`</summary>
<pre>
Total memory: 3.5 GiB (pass)
File system of /var/lib/k0s: xfs (pass)
Disk space available for /var/lib/k0s: 3.2 GiB (pass)
Relative disk space available for /var/lib/k0s: 18% (pass)
Name resolution: localhost: [::1 127.0.0.1] (pass)
Operating system: Linux (pass)
  Linux kernel release: 5.15.0-303.171.5.2.el8uek.x86_64 (pass)
  Max. file descriptors per process: current: 262144 / max: 262144 (pass)
  AppArmor: unavailable (pass)
  Executable in PATH: modprobe: /usr/sbin/modprobe (pass)
  Executable in PATH: mount: /usr/bin/mount (pass)
  Executable in PATH: umount: /usr/bin/umount (pass)
  /proc file system: mounted (0x9fa0) (pass)
  Control Groups: version 1 (pass)
    cgroup controller "cpu": available (pass)
    cgroup controller "cpuacct": available (pass)
    cgroup controller "cpuset": available (pass)
    cgroup controller "memory": available (pass)
    cgroup controller "devices": available (pass)
    cgroup controller "freezer": available (pass)
    cgroup controller "pids": available (pass)
    cgroup controller "hugetlb": available (pass)
    cgroup controller "blkio": available (pass)
  CONFIG_CGROUPS: Control Group support: built-in (pass)
    CONFIG_CGROUP_FREEZER: Freezer cgroup subsystem: built-in (pass)
    CONFIG_CGROUP_PIDS: PIDs cgroup subsystem: built-in (pass)
    CONFIG_CGROUP_DEVICE: Device controller for cgroups: built-in (pass)
    CONFIG_CPUSETS: Cpuset support: built-in (pass)
    CONFIG_CGROUP_CPUACCT: Simple CPU accounting cgroup subsystem: built-in (pass)
    CONFIG_MEMCG: Memory Resource Controller for Control Groups: built-in (pass)
    CONFIG_CGROUP_HUGETLB: HugeTLB Resource Controller for Control Groups: built-in (pass)
    CONFIG_CGROUP_SCHED: Group CPU scheduler: built-in (pass)
      CONFIG_FAIR_GROUP_SCHED: Group scheduling for SCHED_OTHER: built-in (pass)
        CONFIG_CFS_BANDWIDTH: CPU bandwidth provisioning for FAIR_GROUP_SCHED: built-in (pass)
    CONFIG_BLK_CGROUP: Block IO controller: built-in (pass)
  CONFIG_NAMESPACES: Namespaces support: built-in (pass)
    CONFIG_UTS_NS: UTS namespace: built-in (pass)
    CONFIG_IPC_NS: IPC namespace: built-in (pass)
    CONFIG_PID_NS: PID namespace: built-in (pass)
    CONFIG_NET_NS: Network namespace: built-in (pass)
  CONFIG_NET: Networking support: built-in (pass)
    CONFIG_INET: TCP/IP networking: built-in (pass)
      CONFIG_IPV6: The IPv6 protocol: built-in (pass)
    CONFIG_NETFILTER: Network packet filtering framework (Netfilter): built-in (pass)
      CONFIG_NETFILTER_ADVANCED: Advanced netfilter configuration: built-in (pass)
      CONFIG_NF_CONNTRACK: Netfilter connection tracking support: module (pass)
      CONFIG_NETFILTER_XTABLES: Netfilter Xtables support: built-in (pass)
        CONFIG_NETFILTER_XT_TARGET_REDIRECT: REDIRECT target support: module (pass)
        CONFIG_NETFILTER_XT_MATCH_COMMENT: "comment" match support: module (pass)
        CONFIG_NETFILTER_XT_MARK: nfmark target and match support: module (pass)
        CONFIG_NETFILTER_XT_SET: set target and match support: module (pass)
        CONFIG_NETFILTER_XT_TARGET_MASQUERADE: MASQUERADE target support: module (pass)
        CONFIG_NETFILTER_XT_NAT: "SNAT and DNAT" targets support: module (pass)
        CONFIG_NETFILTER_XT_MATCH_ADDRTYPE: "addrtype" address type match support: module (pass)
        CONFIG_NETFILTER_XT_MATCH_CONNTRACK: "conntrack" connection tracking match support: module (pass)
        CONFIG_NETFILTER_XT_MATCH_MULTIPORT: "multiport" Multiple port match support: module (pass)
        CONFIG_NETFILTER_XT_MATCH_RECENT: "recent" match support: module (pass)
        CONFIG_NETFILTER_XT_MATCH_STATISTIC: "statistic" match support: module (pass)
      CONFIG_NETFILTER_NETLINK: built-in (pass)
      CONFIG_NF_NAT: module (pass)
      CONFIG_IP_SET: IP set support: module (pass)
        CONFIG_IP_SET_HASH_IP: hash:ip set support: module (pass)
        CONFIG_IP_SET_HASH_NET: hash:net set support: module (pass)
      CONFIG_IP_VS: IP virtual server support: module (pass)
        CONFIG_IP_VS_NFCT: Netfilter connection tracking: built-in (pass)
        CONFIG_IP_VS_SH: Source hashing scheduling: module (pass)
        CONFIG_IP_VS_RR: Round-robin scheduling: module (pass)
        CONFIG_IP_VS_WRR: Weighted round-robin scheduling: module (pass)
      CONFIG_NF_CONNTRACK_IPV4: IPv4 connection tracking support (required for NAT): unknown (warning)
      CONFIG_NF_REJECT_IPV4: IPv4 packet rejection: module (pass)
      CONFIG_NF_NAT_IPV4: IPv4 NAT: unknown (warning)
      CONFIG_IP_NF_IPTABLES: IP tables support: module (pass)
        CONFIG_IP_NF_FILTER: Packet filtering: module (pass)
          CONFIG_IP_NF_TARGET_REJECT: REJECT target support: module (pass)
        CONFIG_IP_NF_NAT: iptables NAT support: module (pass)
        CONFIG_IP_NF_MANGLE: Packet mangling: module (pass)
      CONFIG_NF_DEFRAG_IPV4: module (pass)
      CONFIG_NF_CONNTRACK_IPV6: IPv6 connection tracking support (required for NAT): unknown (warning)
      CONFIG_NF_NAT_IPV6: IPv6 NAT: unknown (warning)
      CONFIG_IP6_NF_IPTABLES: IP6 tables support: module (pass)
        CONFIG_IP6_NF_FILTER: Packet filtering: module (pass)
        CONFIG_IP6_NF_MANGLE: Packet mangling: module (pass)
        CONFIG_IP6_NF_NAT: ip6tables NAT support: module (pass)
      CONFIG_NF_DEFRAG_IPV6: module (pass)
    CONFIG_BRIDGE: 802.1d Ethernet Bridging: built-in (pass)
      CONFIG_LLC: built-in (pass)
      CONFIG_STP: built-in (pass)
  CONFIG_EXT4_FS: The Extended 4 (ext4) filesystem: module (pass)
  CONFIG_PROC_FS: /proc file system support: built-in (pass)</pre>
</details>

### What happened?

After installing a fresh k0s cluster using k0sctl with 1 controller and 1 worker, I’m unable to use kubectl top nodes. The metrics-server pod is running, but the APIService v1beta1.metrics.k8s.io shows status:

```
k0s kubectl top nodes
error: Metrics API not available
```

192.168.1.41 Controller
192.168.1.42 Worker

All ports between nodes are open (1025–65535 TCP/UDP).
The konnectivity-agent is running on the worker and the konnectivity-server is running on the controller.

```
[root@controller rodrigo]# k0s kubectl get pods -n kube-system
NAME                              READY   STATUS    RESTARTS        AGE
coredns-5555f45c94-bj8f8          1/1     Running   2 (4h24m ago)   13h
konnectivity-agent-st8p6          1/1     Running   1 (4h24m ago)   5h
kube-proxy-xs9w2                  1/1     Running   2 (4h24m ago)   13h
kube-router-wxrnr                 1/1     Running   1 (4h24m ago)   5h1m
metrics-server-7778865875-9wkhg   1/1     Running   4 (4h24m ago)   13h
```
```
[root@controller rodrigo]# cat /etc/k0s/k0s.yaml 
# generated-by-k0sctl 2025-05-04T02:42:31-05:00
apiVersion: k0s.k0sproject.io/v1beta1
kind: ClusterConfig
metadata:
  name: k0s
  namespace: kube-system
spec:
  api:
    address: 192.168.1.41
    k0sApiPort: 9443
    port: 6443
    sans:
    - 192.168.1.41
    - 172.17.0.1
    - 172.18.0.1
    - 2001:1388:1c42:b6a7:a00:27ff:fe3d:ca54
    - fe80::a00:27ff:fe3d:ca54
  controllerManager: {}
  extensions:
    helm:
      concurrencyLevel: 5
  installConfig:
    users:
      etcdUser: etcd
      kineUser: kube-apiserver
      konnectivityUser: konnectivity-server
      kubeAPIserverUser: kube-apiserver
      kubeSchedulerUser: kube-scheduler
  konnectivity:
    adminPort: 8133
    agentPort: 8132
  network:
    clusterDomain: cluster.local
    dualStack:
      enabled: false
    kubeProxy:
      iptables:
        minSyncPeriod: 0s
        syncPeriod: 0s
      ipvs:
        minSyncPeriod: 0s
        syncPeriod: 0s
        tcpFinTimeout: 0s
        tcpTimeout: 0s
        udpTimeout: 0s
      metricsBindAddress: 0.0.0.0:10249
      mode: iptables
      nftables:
        minSyncPeriod: 0s
        syncPeriod: 0s
    kuberouter:
      autoMTU: true
      hairpin: Enabled
      metricsPort: 8080
    nodeLocalLoadBalancing:
      enabled: false
      envoyProxy:
        apiServerBindPort: 7443
        konnectivityServerBindPort: 7132
      type: EnvoyProxy
    podCIDR: 10.244.0.0/16
    provider: kuberouter
    serviceCIDR: 10.96.0.0/12
  scheduler: {}
  storage:
    etcd:
      peerAddress: 192.168.1.41
    type: etcd
  telemetry:
    enabled: true
```

```
root@controller rodrigo]# k0s kubectl describe pods metrics-server-7778865875-9wkhg -n kube-system
Name:                 metrics-server-7778865875-9wkhg
Namespace:            kube-system
Priority:             2000000000
Priority Class Name:  system-cluster-critical
Service Account:      metrics-server
Node:                 worker/192.168.1.42
Start Time:           Sun, 04 May 2025 02:46:27 -0500
Labels:               k8s-app=metrics-server
                      pod-template-hash=7778865875
Annotations:          <none>
Status:               Running
IP:                   10.244.0.27
IPs:
  IP:           10.244.0.27
Controlled By:  ReplicaSet/metrics-server-7778865875
Containers:
  metrics-server:
    Container ID:  containerd://eaad25786fe510d6a2dfe803751b70189a992435e90f1509e6a2b5f51f8e2af7
    Image:         registry.k8s.io/metrics-server/metrics-server:v0.7.2
    Image ID:      registry.k8s.io/metrics-server/metrics-server@sha256:ffcb2bf004d6aa0a17d90e0247cf94f2865c8901dcab4427034c341951c239f9
    Port:          10250/TCP
    Host Port:     0/TCP
    Args:
      --cert-dir=/tmp
      --secure-port=10250
      --kubelet-preferred-address-types=InternalIP,ExternalIP,Hostname
      --kubelet-use-node-status-port
      --metric-resolution=15s
    State:          Running
      Started:      Sun, 04 May 2025 12:08:39 -0500
    Last State:     Terminated
      Reason:       Error
      Exit Code:    2
      Started:      Sun, 04 May 2025 12:08:13 -0500
      Finished:     Sun, 04 May 2025 12:08:15 -0500
    Ready:          True
    Restart Count:  4
    Requests:
      cpu:        10m
      memory:     30M
    Liveness:     http-get https://:https/livez delay=0s timeout=1s period=10s #success=1 #failure=3
    Readiness:    http-get https://:https/readyz delay=20s timeout=1s period=10s #success=1 #failure=3
    Environment:  <none>
    Mounts:
      /tmp from tmp-dir (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-2c7bw (ro)
Conditions:
  Type                        Status
  PodReadyToStartContainers   True 
  Initialized                 True 
  Ready                       True 
  ContainersReady             True 
  PodScheduled                True 
Volumes:
  tmp-dir:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     
    SizeLimit:  <unset>
  kube-api-access-2c7bw:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   Burstable
Node-Selectors:              kubernetes.io/os=linux
Tolerations:                 node-role.kubernetes.io/master:NoSchedule op=Exists
                             node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason     Age                   From     Message
  ----     ------     ----                  ----     -------
  Warning  Unhealthy  56m (x9 over 4h1m)    kubelet  Liveness probe failed: Get "https://10.244.0.27:10250/livez": context deadline exceeded
  Warning  Unhealthy  42m (x20 over 4h21m)  kubelet  Liveness probe failed: Get "https://10.244.0.27:10250/livez": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
  Warning  Unhealthy  26m (x3 over 3h37m)   kubelet  Liveness probe failed: Get "https://10.244.0.27:10250/livez": context deadline exceeded (Client.Timeout exceeded while awaiting headers)  Warning  Unhealthy  26m (x5 over 3h54m)   kubelet  Liveness probe failed: Get "https://10.244.0.27:10250/livez": net/http: request canceled (Client.Timeout exceeded while awaiting headers)
```

```
[root@controller rodrigo]# k0s kubectl get apiservices -n kube-system
NAME                              SERVICE                      AVAILABLE                      AGE
v1.                               Local                        True                           13h
v1.admissionregistration.k8s.io   Local                        True                           13h
v1.apiextensions.k8s.io           Local                        True                           13h
v1.apps                           Local                        True                           13h
v1.authentication.k8s.io          Local                        True                           13h
v1.authorization.k8s.io           Local                        True                           13h
v1.autoscaling                    Local                        True                           13h
v1.batch                          Local                        True                           13h
v1.certificates.k8s.io            Local                        True                           13h
v1.coordination.k8s.io            Local                        True                           13h
v1.discovery.k8s.io               Local                        True                           13h
v1.events.k8s.io                  Local                        True                           13h
v1.flowcontrol.apiserver.k8s.io   Local                        True                           13h
v1.networking.k8s.io              Local                        True                           13h
v1.node.k8s.io                    Local                        True                           13h
v1.policy                         Local                        True                           13h
v1.rbac.authorization.k8s.io      Local                        True                           13h
v1.scheduling.k8s.io              Local                        True                           13h
v1.storage.k8s.io                 Local                        True                           13h
v1beta1.etcd.k0sproject.io        Local                        True                           13h
v1beta1.helm.k0sproject.io        Local                        True                           13h
v1beta1.metrics.k8s.io            kube-system/metrics-server   False (FailedDiscoveryCheck)   13h
v1beta2.autopilot.k0sproject.io   Local                        True                           13h
v2.autoscaling                    Local                        True                           13h
```

```
[root@controller rodrigo]# k0s kubectl describe apiservices v1beta1.metrics.k8s.io -n kube-system
Name:         v1beta1.metrics.k8s.io
Namespace:    
Labels:       k0s.k0sproject.io/stack=metricserver
              k8s-app=metrics-server
Annotations:  k0s.k0sproject.io/last-applied-configuration:
                {"apiVersion":"apiregistration.k8s.io/v1","kind":"APIService","metadata":{"labels":{"k8s-app":"metrics-server"},"name":"v1beta1.metrics.k8...
              k0s.k0sproject.io/stack-checksum: f46335047740a30cd79c90be43ee087f
API Version:  apiregistration.k8s.io/v1
Kind:         APIService
Metadata:
  Creation Timestamp:  2025-05-04T07:45:41Z
  Resource Version:    7603
  UID:                 fd8d30ca-4b0c-4c19-af5b-77f738dc2a89
Spec:
  Group:                     metrics.k8s.io
  Group Priority Minimum:    100
  Insecure Skip TLS Verify:  true
  Service:
    Name:            metrics-server
    Namespace:       kube-system
    Port:            443
  Version:           v1beta1
  Version Priority:  100
Status:
  Conditions:
    Last Transition Time:  2025-05-04T07:45:41Z
    Message:               failing or missing response from https://10.97.131.110:443/apis/metrics.k8s.io/v1beta1: Get "https://10.97.131.110:443/apis/metrics.k8s.io/v1beta1": No agent available
    Reason:                FailedDiscoveryCheck
    Status:                False
    Type:                  Available
Events:                    <none>
```

### Steps to reproduce

1.Install K0sctl: 1 Controller 1 Worker
2.k0s kubectl top nodes

### Expected behavior

I need to restore konnectivity between the API server and the worker node so that metrics-server and commands like kubectl top and kubectl exec work properly.

### Screenshots and logs

Logs journalctl -u k0scontroller:
may 04 16:31:02 controller k0s[1129]: time="2025-05-04 16:31:02" level=info msg="E0504 16:31:02.473224    1858 remote_available_controller.go:448] \"Unhandled Error\" err=\"v1beta1.metrics.k8s.io failed with: failing or missing response from https://10.97.131.110:443/apis/metrics.k8s.io/v1beta1: Get \\\"https://10.97.131.110:443/apis/metrics.k8s.io/v1beta1\\\": No agent available\" logger=\"UnhandledError\"" component=kube-apiserver stream=stderr
may 04 16:31:08 controller k0s[1129]: time="2025-05-04 16:31:08" level=info msg="E0504 16:31:08.864858    2010 server.go:528] \"Failed to get a backend\" err=\"No agent available\" dialID=896810405210690112" component=konnectivity stream=stderr
may 04 16:31:08 controller k0s[1129]: time="2025-05-04 16:31:08" level=info msg="E0504 16:31:08.864983    2010 server.go:528] \"Failed to get a backend\" err=\"No agent available\" dialID=8578046729939631916" component=konnectivity stream=stderr
may 04 16:31:08 controller k0s[1129]: time="2025-05-04 16:31:08" level=info msg="E0504 16:31:08.865051    2010 server.go:528] \"Failed to get a backend\" err=\"No agent available\" dialID=4301276117342089643" component=konnectivity stream=stderr
may 04 16:31:08 controller k0s[1129]: time="2025-05-04 16:31:08" level=info msg="E0504 16:31:08.865293    2010 server.go:528] \"Failed to get a backend\" err=\"No agent available\" dialID=2614289875624524556" component=konnectivity stream=stderr
may 04 16:31:08 controller k0s[1129]: time="2025-05-04 16:31:08" level=info msg="E0504 16:31:08.865826    2010 server.go:528] \"Failed to get a backend\" err=\"No agent available\" dialID=2871246251020862313" component=konnectivity stream=stderr
may 04 16:31:08 controller k0s[1129]: time="2025-05-04 16:31:08" level=info msg="E0504 16:31:08.868466    1858 remote_available_controller.go:448] \"Unhandled Error\" err=\"v1beta1.metrics.k8s.io failed with: failing or missing response from https://10.97.131.110:443/apis/metrics.k8s.io/v1beta1: Get \\\"https://10.97.131.110:443/apis/metrics.k8s.io/v1beta1\\\": No agent available\" logger=\"UnhandledError\"" component=kube-apiserver stream=stderr
may 04 16:31:09 controller k0s[1129]: time="2025-05-04 16:31:09" level=info msg="E0504 16:31:09.415686    1988 resource_quota_controller.go:446] \"Unhandled Error\" err=\"unable to retrieve the complete list of server APIs: metrics.k8s.io/v1beta1: stale GroupVersion discovery: metrics.k8s.io/v1beta1\" logger=\"UnhandledError\"" component=kube-controller-manager stream=stderr
may 04 16:31:09 controller k0s[1129]: time="2025-05-04 16:31:09" level=info msg="W0504 16:31:09.866598    1858 handler_proxy.go:99] no RequestInfo found in the context" component=kube-apiserver stream=stderr
may 04 16:31:09 controller k0s[1129]: time="2025-05-04 16:31:09" level=info msg="E0504 16:31:09.866653    1858 controller.go:113] \"Unhandled Error\" err=\"loading OpenAPI spec for \\\"v1beta1.metrics.k8s.io\\\" failed with: Error, could not get list of group versions for APIService\" logger=\"UnhandledError\"" component=kube-apiserver stream=stderr
may 04 16:31:09 controller k0s[1129]: time="2025-05-04 16:31:09" level=info msg="W0504 16:31:09.867190    1858 handler_proxy.go:99] no RequestInfo found in the context" component=kube-apiserver stream=stderr
may 04 16:31:09 controller k0s[1129]: time="2025-05-04 16:31:09" level=info msg="E0504 16:31:09.867838    1858 controller.go:102] \"Unhandled Error\" err=<" component=kube-apiserver stream=stderr
may 04 16:31:09 controller k0s[1129]: time="2025-05-04 16:31:09" level=info msg="\tloading OpenAPI spec for \"v1beta1.metrics.k8s.io\" failed with: failed to download v1beta1.metrics.k8s.io: failed to retrieve openAPI spec, http error: ResponseCode: 503, Body: service unavailable" component=kube-apiserver stream=stderr
may 04 16:31:09 controller k0s[1129]: time="2025-05-04 16:31:09" level=info msg="\t, Header: map[Content-Type:[text/plain; charset=utf-8] X-Content-Type-Options:[nosniff]]" component=kube-apiserver stream=stderr
may 04 16:31:09 controller k0s[1129]: time="2025-05-04 16:31:09" level=info msg=" > logger=\"UnhandledError\"" component=kube-apiserver stream=stderr
may 04 16:31:09 controller k0s[1129]: time="2025-05-04 16:31:09" level=info msg="I0504 16:31:09.868537    1858 controller.go:126] OpenAPI AggregationController: action for item v1beta1.metrics.k8s.io: Rate Limited Requeue." component=kube-apiserver stream=stderr
may 04 16:31:09 controller k0s[1129]: time="2025-05-04 16:31:09" level=info msg="I0504 16:31:09.869340    1858 controller.go:109] OpenAPI AggregationController: action for item v1beta1.metrics.k8s.io: Rate Limited Requeue." component=kube-apiserver stream=stderr
may 04 16:31:10 controller k0s[1129]: time="2025-05-04 16:31:10" level=info msg="E0504 16:31:10.876282    1858 queueset.go:474] \"Overflow\" err=\"queueset::currentR overflow\" QS=\"leader-election\" when=\"2025-05-04 16:31:10.876270504\" prevR=\"164.55732879ss\" incrR=\"184467440737.09543595ss\" currentR=\"164.55724858ss\"" component=kube-apiserver stream=stderr
may 04 16:31:12 controller k0s[1129]: time="2025-05-04 16:31:12" level=info msg="current cfg matches existing, not gonna do anything" component=coredns

**Comment by jnummelin** [comment]
`No agent available` pretty much always boils down to the konnectivity agent not being able to register with konnectivity server.

So check that the agent pods are connecting to the right address in `--proxy-server-host=<ctrl-ip>`

Also check the agent pod logs. Now as you noticed, we can't get the logs via `kubectl logs ...` so you need to ssh into the node and check `/var/log/containers/konnectivity-agent....`. It probably has some clues why it cannot connect.

**Comment by Rodri2911** [comment]
Thank you for the response. I followed the steps you provided, and here are the results:

```
[root@controller rodrigo]# k0s kubectl -n kube-system get pod -l k8s-app=konnectivity-agent -o yaml | grep proxy-server-host
      - --proxy-server-host=192.168.1.41
```

```
[root@worker rodrigo]# cat /var/log/containers/konnectivity-agent-sh4hz_kube-system_konnectivity-agent-da4b595b67e88db4e8781ceb6a46293e3c0973de3d11e46f7ad69baeea6f345d.log 

2025-05-05T11:48:03.213617621-05:00 stderr F E0505 16:48:03.213218       1 clientset.go:204] "cannot connect once" err="rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing: dial tcp 192.168.1.41:8132: connect: no route to host\""
2025-05-05T11:48:13.577698981-05:00 stderr F E0505 16:48:13.577145       1 clientset.go:204] "cannot connect once" err="rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing: dial tcp 192.168.1.41:8132: connect: no route to host\""
2025-05-05T11:48:23.940133633-05:00 stderr F E0505 16:48:23.940037       1 clientset.go:204] "cannot connect once" err="rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing: dial tcp 192.168.1.41:8132: connect: no route to host\""
2025-05-05T11:48:34.594462386-05:00 stderr F E0505 16:48:34.593948       1 clientset.go:204] "cannot connect once" err="rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing: dial tcp 192.168.1.41:8132: connect: no route to host\""
2025-05-05T11:48:45.091675374-05:00 stderr F E0505 16:48:45.091314       1 clientset.go:204] "cannot connect once" err="rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing: dial tcp 192.168.1.41:8132: connect: no route to host\""
2025-05-05T11:48:55.465259291-05:00 stderr F E0505 16:48:55.464838       1 clientset.go:204] "cannot connect once" err="rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing: dial tcp 192.168.1.41:8132: connect: no route to host\""
2025-05-05T11:49:06.313219798-05:00 stderr F E0505 16:49:06.312871       1 clientset.go:204] "cannot connect once" err="rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing: dial tcp 192.168.1.41:8132: connect: no route to host\""
2025-05-05T11:49:16.575240618-05:00 stderr F E0505 16:49:16.574884       1 clientset.go:204] "cannot connect once" err="rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing: dial tcp 192.168.1.41:8132: connect: no route to host\""
2025-05-05T11:49:27.568463699-05:00 stderr F E0505 16:49:27.568050       1 clientset.go:204] "cannot connect once" err="rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing: dial tcp 192.168.1.41:8132: connect: no route to host\""
2025-05-05T11:49:38.170622898-05:00 stderr F E0505 16:49:38.170388       1 clientset.go:204] "cannot connect once" err="rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing: dial tcp 192.168.1.41:8132: connect: no route to host\""
2025-05-05T11:49:48.575881724-05:00 stderr F E0505 16:49:48.575587       1 clientset.go:204] "cannot connect once" err="rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing: dial tcp 192.168.1.41:8132: connect: no route to host\""
```

```
[root@worker rodrigo]# ping 192.168.1.41
PING 192.168.1.41 (192.168.1.41) 56(84) bytes of data.
64 bytes from 192.168.1.41: icmp_seq=1 ttl=64 time=0.965 ms
64 bytes from 192.168.1.41: icmp_seq=2 ttl=64 time=0.713 ms
64 bytes from 192.168.1.41: icmp_seq=3 ttl=64 time=0.759 ms
--- 192.168.1.41 ping statistics ---
3 packets transmitted, 3 received, 0% packet loss, time 2060ms
rtt min/avg/max/mdev = 0.713/0.812/0.965/0.112 ms
[root@worker rodrigo]# traceroute 192.168.1.41
traceroute to 192.168.1.41 (192.168.1.41), 30 hops max, 60 byte packets
 1  192.168.1.41 (192.168.1.41)  0.780 ms  0.605 ms  1.047 ms
```

```
[root@controller rodrigo]# ss -ltnp | grep 8132
LISTEN 0      4096               *:8132             *:*    users:(("konnectivity-se",pid=1998,fd=6))
[root@controller rodrigo]# k0s kubectl logs metrics-server-7778865875-pbvj7 -n kube-system 
Error from server: Get "https://192.168.1.42:10250/containerLogs/kube-system/metrics-server-7778865875-pbvj7/metrics-server": No agent available
```

Additionally, I switched to the official metrics-server from the official repository, but the issue persists.

```
[root@controller rodrigo]# cat components.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    k8s-app: metrics-server
  name: metrics-server
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    k8s-app: metrics-server
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
    rbac.authorization.k8s.io/aggregate-to-view: "true"
  name: system:aggregated-metrics-reader
rules:
- apiGroups:
  - metrics.k8s.io
  resources:
  - pods
  - nodes
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    k8s-app: metrics-server
  name: system:metrics-server
rules:
- apiGroups:
  - ""
  resources:
  - nodes/metrics
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - pods
  - nodes
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    k8s-app: metrics-server
  name: metrics-server-auth-reader
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: extension-apiserver-authentication-reader
subjects:
- kind: ServiceAccount
  name: metrics-server
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    k8s-app: metrics-server
  name: metrics-server:system:auth-delegator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
- kind: ServiceAccount
  name: metrics-server
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    k8s-app: metrics-server
  name: system:metrics-server
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:metrics-server
subjects:
- kind: ServiceAccount
  name: metrics-server
  namespace: kube-system
---
apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: metrics-server
  name: metrics-server
  namespace: kube-system
spec:
  ports:
  - name: https
    port: 443
    protocol: TCP
    targetPort: https
  selector:
    k8s-app: metrics-server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: metrics-server
  name: metrics-server
  namespace: kube-system
spec:
  selector:
    matchLabels:
      k8s-app: metrics-server
  strategy:
    rollingUpdate:
      maxUnavailable: 0
  template:
    metadata:
      labels:
        k8s-app: metrics-server
    spec:
      containers:
      - args:
        - --cert-dir=/tmp
        - --secure-port=4443
        - --kubelet-preferred-address-types=InternalIP,ExternalIP,Hostname
        - --kubelet-use-node-status-port
        - --metric-resolution=15s
        - --kubelet-insecure-tls
        image: registry.k8s.io/metrics-server/metrics-server:v0.7.2
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /livez
            port: https
            scheme: HTTPS
          periodSeconds: 10
        name: metrics-server
        ports:
        - containerPort: 4443
          name: https
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /readyz
            port: https
            scheme: HTTPS
          initialDelaySeconds: 20
          periodSeconds: 10
        resources:
          requests:
            cpu: 100m
            memory: 200Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 1000
          seccompProfile:
            type: RuntimeDefault
        volumeMounts:
        - mountPath: /tmp
          name: tmp-dir
      hostNetwork: true
      nodeSelector:
        kubernetes.io/os: linux
      priorityClassName: system-cluster-critical
      serviceAccountName: metrics-server
      volumes:
      - emptyDir: {}
        name: tmp-dir
---
apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  labels:
    k8s-app: metrics-server
  name: v1beta1.metrics.k8s.io
spec:
  group: metrics.k8s.io
  groupPriorityMinimum: 100
  insecureSkipTLSVerify: true
  service:
    name: metrics-server
    namespace: kube-system
  version: v1beta1
  versionPriority: 100
```
