### ISSUE TITLE
Dual-stack IPv4/IPv6 networking with kube-router not working

### ISSUE THREAD

**Issue by neris** [k0sproject/k0s#5833]
### Before creating an issue, make sure you've checked the following:

- [x] You are running the latest released version of k0s
- [x] Make sure you've searched for existing issues, both open and closed
- [x] Make sure you've searched for PRs too, a fix might've been merged already
- [x] You're looking at docs for the released version, "main" branch docs are usually ahead of released versions.

### Platform

```shell
Linux 6.1.0-33-cloud-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.133-1 (2025-04-10) x86_64 GNU/Linux
PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
NAME="Debian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

### Version

v1.32.4+k0s.0

### Sysinfo

<details><summary>`k0s sysinfo`</summary>
<pre>
Total memory: 1.9 GiB (pass)
File system of /var/lib/k0s: ext4 (pass)
Disk space available for /var/lib/k0s: 28.1 GiB (pass)
Relative disk space available for /var/lib/k0s: 89% (pass)
Name resolution: localhost: [::1 127.0.0.1] (pass)
Operating system: Linux (pass)
  Linux kernel release: 6.1.0-33-cloud-amd64 (pass)
  Max. file descriptors per process: current: 1048576 / max: 1048576 (pass)
  AppArmor: active (pass)
  Executable in PATH: modprobe: /usr/sbin/modprobe (pass)
  Executable in PATH: mount: /usr/bin/mount (pass)
  Executable in PATH: umount: /usr/bin/umount (pass)
  /proc file system: mounted (0x9fa0) (pass)
  Control Groups: version 2 (pass)
    cgroup controller "cpu": available (is a listed root controller) (pass)
    cgroup controller "cpuacct": available (via cpu in version 2) (pass)
    cgroup controller "cpuset": available (is a listed root controller) (pass)
    cgroup controller "memory": available (is a listed root controller) (pass)
    cgroup controller "devices": available (device filters attachable) (pass)
    cgroup controller "freezer": available (cgroup.freeze exists) (pass)
    cgroup controller "pids": available (is a listed root controller) (pass)
    cgroup controller "hugetlb": available (is a listed root controller) (pass)
    cgroup controller "blkio": available (via io in version 2) (pass)
  CONFIG_CGROUPS: Control Group support: built-in (pass)
    CONFIG_CGROUP_FREEZER: Freezer cgroup subsystem: built-in (pass)
    CONFIG_CGROUP_PIDS: PIDs cgroup subsystem: built-in (pass)
    CONFIG_CGROUP_DEVICE: Device controller for cgroups: built-in (pass)
    CONFIG_CPUSETS: Cpuset support: built-in (pass)
    CONFIG_CGROUP_CPUACCT: Simple CPU accounting cgroup subsystem: built-in (pass)
    CONFIG_MEMCG: Memory Resource Controller for Control Groups: built-in (pass)
    CONFIG_CGROUP_HUGETLB: HugeTLB Resource Controller for Control Groups: built-in (pass)
    CONFIG_CGROUP_SCHED: Group CPU scheduler: built-in (pass)
      CONFIG_FAIR_GROUP_SCHED: Group scheduling for SCHED_OTHER: built-in (pass)
        CONFIG_CFS_BANDWIDTH: CPU bandwidth provisioning for FAIR_GROUP_SCHED: built-in (pass)
    CONFIG_BLK_CGROUP: Block IO controller: built-in (pass)
  CONFIG_NAMESPACES: Namespaces support: built-in (pass)
    CONFIG_UTS_NS: UTS namespace: built-in (pass)
    CONFIG_IPC_NS: IPC namespace: built-in (pass)
    CONFIG_PID_NS: PID namespace: built-in (pass)
    CONFIG_NET_NS: Network namespace: built-in (pass)
  CONFIG_NET: Networking support: built-in (pass)
    CONFIG_INET: TCP/IP networking: built-in (pass)
      CONFIG_IPV6: The IPv6 protocol: built-in (pass)
    CONFIG_NETFILTER: Network packet filtering framework (Netfilter): built-in (pass)
      CONFIG_NETFILTER_ADVANCED: Advanced netfilter configuration: built-in (pass)
      CONFIG_NF_CONNTRACK: Netfilter connection tracking support: module (pass)
      CONFIG_NETFILTER_XTABLES: Netfilter Xtables support: module (pass)
        CONFIG_NETFILTER_XT_TARGET_REDIRECT: REDIRECT target support: module (pass)
        CONFIG_NETFILTER_XT_MATCH_COMMENT: "comment" match support: module (pass)
        CONFIG_NETFILTER_XT_MARK: nfmark target and match support: module (pass)
        CONFIG_NETFILTER_XT_SET: set target and match support: module (pass)
        CONFIG_NETFILTER_XT_TARGET_MASQUERADE: MASQUERADE target support: module (pass)
        CONFIG_NETFILTER_XT_NAT: "SNAT and DNAT" targets support: module (pass)
        CONFIG_NETFILTER_XT_MATCH_ADDRTYPE: "addrtype" address type match support: module (pass)
        CONFIG_NETFILTER_XT_MATCH_CONNTRACK: "conntrack" connection tracking match support: module (pass)
        CONFIG_NETFILTER_XT_MATCH_MULTIPORT: "multiport" Multiple port match support: module (pass)
        CONFIG_NETFILTER_XT_MATCH_RECENT: "recent" match support: module (pass)
        CONFIG_NETFILTER_XT_MATCH_STATISTIC: "statistic" match support: module (pass)
      CONFIG_NETFILTER_NETLINK: module (pass)
      CONFIG_NF_NAT: module (pass)
      CONFIG_IP_SET: IP set support: module (pass)
        CONFIG_IP_SET_HASH_IP: hash:ip set support: module (pass)
        CONFIG_IP_SET_HASH_NET: hash:net set support: module (pass)
      CONFIG_IP_VS: IP virtual server support: module (pass)
        CONFIG_IP_VS_NFCT: Netfilter connection tracking: built-in (pass)
        CONFIG_IP_VS_SH: Source hashing scheduling: module (pass)
        CONFIG_IP_VS_RR: Round-robin scheduling: module (pass)
        CONFIG_IP_VS_WRR: Weighted round-robin scheduling: module (pass)
      CONFIG_NF_CONNTRACK_IPV4: IPv4 connection tracking support (required for NAT): unknown (warning)
      CONFIG_NF_REJECT_IPV4: IPv4 packet rejection: module (pass)
      CONFIG_NF_NAT_IPV4: IPv4 NAT: unknown (warning)
      CONFIG_IP_NF_IPTABLES: IP tables support: module (pass)
        CONFIG_IP_NF_FILTER: Packet filtering: module (pass)
          CONFIG_IP_NF_TARGET_REJECT: REJECT target support: module (pass)
        CONFIG_IP_NF_NAT: iptables NAT support: module (pass)
        CONFIG_IP_NF_MANGLE: Packet mangling: module (pass)
      CONFIG_NF_DEFRAG_IPV4: module (pass)
      CONFIG_NF_CONNTRACK_IPV6: IPv6 connection tracking support (required for NAT): unknown (warning)
      CONFIG_NF_NAT_IPV6: IPv6 NAT: unknown (warning)
      CONFIG_IP6_NF_IPTABLES: IP6 tables support: module (pass)
        CONFIG_IP6_NF_FILTER: Packet filtering: module (pass)
        CONFIG_IP6_NF_MANGLE: Packet mangling: module (pass)
        CONFIG_IP6_NF_NAT: ip6tables NAT support: module (pass)
      CONFIG_NF_DEFRAG_IPV6: module (pass)
    CONFIG_BRIDGE: 802.1d Ethernet Bridging: module (pass)
      CONFIG_LLC: module (pass)
      CONFIG_STP: module (pass)
  CONFIG_EXT4_FS: The Extended 4 (ext4) filesystem: built-in (pass)
  CONFIG_PROC_FS: /proc file system support: built-in (pass)
</pre>
</details>

### What happened?

When following the latest documentation [Enabling dual-stack using the default CNI (kube-router)](https://docs.k0sproject.io/stable/dual-stack/) on a cleanly installed two virtual machines, the cluster ends up in a broken state.

### Steps to reproduce

1. Create two identical virtual machines that have both public IPv6 and private IPv4 (more details below).
2. In each virtual machine run `curl --proto '=https' --tlsv1.2 -sSf https://get.k0s.sh | sudo sh`
3. On the virtual machine designated for the controller node:
   a. `mkdir -p /etc/k0s`
   b. `k0s config create > /etc/k0s/k0s.yaml`
   c. Modify `/etc/k0s/k0s.yaml`, changing `spec.network.enabled` to `true` and adding `IPv6podCIDR: fd00::/108` and `IPv6serviceCIDR: fd01::/108` next to it according to the documentation.
   d. `sudo k0s install controller -c /etc/k0s/k0s.yaml`
   e. `sudo k0s start`
   f. `sudo k0s token create --role=worker`, write down the token.
4. On the virtual machine designated for the worker node:
   a. `sudo k0s install worker --token-file /path/to/token/file`
   b. `sudo k0s start`

### Expected behavior

A working cluster as a result.

### Actual behavior

A cluster in a broken state, nodes cannot communicate with each other.

### Screenshots and logs

`sudo k0s kubectl get po -A`:
```
NAMESPACE     NAME                              READY   STATUS              RESTARTS      AGE
kube-system   coredns-5555f45c94-mdrwl          0/1     ContainerCreating   0             3m33s
kube-system   konnectivity-agent-bsct8          0/1     ContainerCreating   0             2m14s
kube-system   kube-proxy-qj6xr                  1/1     Running             0             2m14s
kube-system   kube-router-66sgj                 0/1     CrashLoopBackOff    4 (13s ago)   2m14s
kube-system   metrics-server-7778865875-m5zqx   0/1     ContainerCreating   0             3m26s
```

`sudo k0s kubectl logs kube-router-66sgj -n kube-system`:
```
Defaulted container "kube-router" out of: kube-router, install-cni-bins (init), install-cniconf (init)
Error from server: Get "https://10.72.8.2:10250/containerLogs/kube-system/kube-router-66sgj/kube-router": No agent available
```

`tail /var/log/containers/kube-router-66sgj_kube-system_install-cni-bins-c068234725440c13218cc66cfc518d72a1acf729a9086265cc909c2e52262a65.log`:
```
2025-05-11T15:48:25.004352775Z stdout F Installing CNI plugins...
2025-05-11T15:48:25.004389191Z stderr F + main install
2025-05-11T15:48:25.004392767Z stderr F + installBins
2025-05-11T15:48:25.004395163Z stderr F + echo 'Installing CNI plugins...'
2025-05-11T15:48:25.004397423Z stderr F + mkdir -p /host/opt/cni/bin
2025-05-11T15:48:25.004549997Z stderr F + install /opt/cni/bin/bandwidth /opt/cni/bin/bridge /opt/cni/bin/dhcp /opt/cni/bin/dummy /opt/cni/bin/firewall /opt/cni/bin/host-device /opt/cni/bin/host-local /opt/cni/bin/ipvlan /opt/cni/bin/loopback /opt/cni/bin/macvlan /opt/cni/bin/portmap /opt/cni/bin/ptp /opt/cni/bin/sbr /opt/cni/bin/static /opt/cni/bin/tap /opt/cni/bin/tuning /opt/cni/bin/vlan /opt/cni/bin/vrf /host/opt/cni/bin/
2025-05-11T15:48:25.041159445Z stderr F + echo ...done
2025-05-11T15:48:25.041176694Z stdout F ...done
```

`tail /var/log/containers/kube-router-66sgj_kube-system_install-cniconf-3c395af9294ed883a5ddc9b4a494d037dd97903ce7850dcf00811e2e27ff8eed.log`:
```
2025-05-11T15:48:30.327639137Z stderr F + '[' '!' -f /etc/cni/net.d/10-kuberouter.conflist ]
2025-05-11T15:48:30.327705829Z stderr F + '[' -f '/etc/cni/net.d/*.conf' ]
2025-05-11T15:48:30.327710592Z stderr F + TMP=/etc/cni/net.d/.tmp-kuberouter-cfg
2025-05-11T15:48:30.327713288Z stderr F + cp /etc/kube-router/cni-conf.json /etc/cni/net.d/.tmp-kuberouter-cfg
2025-05-11T15:48:30.328202148Z stderr F + mv /etc/cni/net.d/.tmp-kuberouter-cfg /etc/cni/net.d/10-kuberouter.conflist
```

`tail /var/log/containers/kube-router-66sgj_kube-system_kube-router-70837d5c7e41ee6e0be6ecc4f67b66445e2ce20099fe0ab563390399dec1b587.log`:
```
2025-05-11T15:51:45.38434501Z stderr F I0511 15:51:45.384258   32243 version.go:66] Running /usr/local/bin/kube-router version v2.4.1, built on 2024-12-13T09:23:32-0600, go1.23.4
2025-05-11T15:51:45.4857753Z stderr F I0511 15:51:45.485682   32243 metrics_controller.go:256] Starting metrics controller
2025-05-11T15:51:45.487504178Z stderr F failed to run kube-router: failed to create network routing controller: IPv6 was enabled, but no IPv6 address was found on the node
```

`sudo k0s kubectl get node -o yaml`:
```
apiVersion: v1
items:
- apiVersion: v1
  kind: Node
  metadata:
    annotations:
      node.alpha.kubernetes.io/ttl: "0"
      volumes.kubernetes.io/controller-managed-attach-detach: "true"
    creationTimestamp: "2025-05-11T15:48:20Z"
    labels:
      beta.kubernetes.io/arch: amd64
      beta.kubernetes.io/os: linux
      kubernetes.io/arch: amd64
      kubernetes.io/hostname: yh-k8s-test-worker01
      kubernetes.io/os: linux
    name: yh-k8s-test-worker01
    resourceVersion: "1531"
    uid: 1e4e8335-2295-41c7-abcf-5f7c8ca2de8e
  spec:
    podCIDR: fd00::/110
    podCIDRs:
    - fd00::/110
    - 10.244.0.0/24
  status:
    addresses:
    - address: 10.72.8.2
      type: InternalIP
    - address: yh-k8s-test-worker01
      type: Hostname
    allocatable:
      cpu: "2"
      ephemeral-storage: "30243052290"
      hugepages-1Gi: "0"
      hugepages-2Mi: "0"
      memory: 1924632Ki
      pods: "110"
    capacity:
      cpu: "2"
      ephemeral-storage: 32815812Ki
      hugepages-1Gi: "0"
      hugepages-2Mi: "0"
      memory: 2027032Ki
      pods: "110"
    conditions:
    - lastHeartbeatTime: "2025-05-11T15:53:57Z"
      lastTransitionTime: "2025-05-11T15:48:20Z"
      message: kubelet has sufficient memory available
      reason: KubeletHasSufficientMemory
      status: "False"
      type: MemoryPressure
    - lastHeartbeatTime: "2025-05-11T15:53:57Z"
      lastTransitionTime: "2025-05-11T15:48:20Z"
      message: kubelet has no disk pressure
      reason: KubeletHasNoDiskPressure
      status: "False"
      type: DiskPressure
    - lastHeartbeatTime: "2025-05-11T15:53:57Z"
      lastTransitionTime: "2025-05-11T15:48:20Z"
      message: kubelet has sufficient PID available
      reason: KubeletHasSufficientPID
      status: "False"
      type: PIDPressure
    - lastHeartbeatTime: "2025-05-11T15:53:57Z"
      lastTransitionTime: "2025-05-11T15:48:30Z"
      message: kubelet is posting ready status
      reason: KubeletReady
      status: "True"
      type: Ready
    daemonEndpoints:
      kubeletEndpoint:
        Port: 10250
    images:
    - names:
      - quay.io/k0sproject/kube-router@sha256:badf324c57b6f503d6093cc3ce10b888ce08fc0b2a5113c66860339ad59bb8a2
      - quay.io/k0sproject/kube-router:v2.4.1-iptables1.8.9-0
      sizeBytes: 36666414
    - names:
      - quay.io/k0sproject/cni-node@sha256:f9ae72f1be998ba3d0a9298d35cbd5577758cc08326406c63fb4804b0664391a
      - quay.io/k0sproject/cni-node:1.3.0-k0s.0
      sizeBytes: 26155832
    - names:
      - quay.io/k0sproject/kube-proxy@sha256:2c9cc5936ed9b9d1610e9c2ab89839d7fdc08a5224bede99f95b3d7f7c74de9d
      - quay.io/k0sproject/kube-proxy:v1.32.4
      sizeBytes: 25220690
    - names:
      - registry.k8s.io/pause@sha256:7031c1b283388d2c2e09b57badb803c05ebed362dc88d84b480cc47f72a21097
      - registry.k8s.io/pause:3.9
      sizeBytes: 321520
    nodeInfo:
      architecture: amd64
      bootID: ec2c4511-f386-4be0-9803-8bbbe5c2169a
      containerRuntimeVersion: containerd://1.7.27
      kernelVersion: 6.1.0-33-cloud-amd64
      kubeProxyVersion: v1.32.4+k0s
      kubeletVersion: v1.32.4+k0s
      machineID: 922b002ec0584be0932abb70aa4e430d
      operatingSystem: linux
      osImage: Debian GNU/Linux 12 (bookworm)
      systemUUID: 922b002e-c058-4be0-932a-bb70aa4e430d
kind: List
metadata:
  resourceVersion: ""
```

`ip a`:
```
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host noprefixroute
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether bc:24:11:f5:57:db brd ff:ff:ff:ff:ff:ff
    altname enp0s18
    altname ens18
    inet6 2a01:<MASKED>:1/64 scope global
       valid_lft forever preferred_lft forever
    inet6 fe80::be24:11ff:fef5:57db/64 scope link
       valid_lft forever preferred_lft forever
3: eth1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether bc:24:11:c9:38:0e brd ff:ff:ff:ff:ff:ff
    altname enp0s19
    altname ens19
    inet 10.72.8.1/16 brd 10.72.255.255 scope global eth1
       valid_lft forever preferred_lft forever
    inet6 fe80::be24:11ff:fec9:380e/64 scope link
       valid_lft forever preferred_lft forever
```

### Additional context

I used Proxmox to create the virtual machines.
Each virtual machine is created from a Debian Cloud-Init image.
Each machine has two network interfaces: eth0 for public IPv4/IPv6 addresses; eth1 for cluster-local IPv4 addresses. Both statically configured via the cloud-init and tested to be working.

**Comment by jnummelin** [comment]
I think this boils down to this:

```
  status:
    addresses:
    - address: 10.72.8.2
      type: InternalIP
    - address: yh-k8s-test-worker01
      type: Hostname
```

so kubelet does not pick up the IPv6 address on the node addresses. And thus kube-router crashes as it cannot know how to do routing.

Can you check k0s is passing the ipv6 address for kubelet:
```
cat /proc/$(pidof kubelet)/cmdline | xargs -0
```

@neris can you share the full k0s.yaml config you used, just to double check everything is correct there

**Comment by neris** [comment]
`cat /proc/$(pidof kubelet)/cmdline | xargs -0`:
```
/var/lib/k0s/bin/kubelet --kubeconfig=/var/lib/k0s/kubelet.conf --v=1 --cert-dir=/var/lib/k0s/kubelet/pki --containerd=/run/k0s/containerd.sock --runtime-cgroups=/system.slice/containerd.service --root-dir=/var/lib/k0s/kubelet --config=/run/k0s/kubelet/config.yaml
```

`cat /etc/k0s/k0s.yaml`:
```
apiVersion: k0s.k0sproject.io/v1beta1
kind: ClusterConfig
metadata:
  name: k0s
  namespace: kube-system
spec:
  api:
    address: 10.72.8.1
    k0sApiPort: 9443
    port: 6443
    sans:
    - 10.72.8.1
    - 2a01:<MASKED>:1
    - fe80::be24:11ff:fef5:57db
    - fe80::be24:11ff:fec9:380e
  controllerManager: {}
  extensions:
    helm:
      concurrencyLevel: 5
  installConfig:
    users:
      etcdUser: etcd
      kineUser: kube-apiserver
      konnectivityUser: konnectivity-server
      kubeAPIserverUser: kube-apiserver
      kubeSchedulerUser: kube-scheduler
  konnectivity:
    adminPort: 8133
    agentPort: 8132
  network:
    clusterDomain: cluster.local
    dualStack:
      enabled: true
      IPv6podCIDR: fd00::/108
      IPv6serviceCIDR: fd01::/108
    kubeProxy:
      iptables:
        minSyncPeriod: 0s
        syncPeriod: 0s
      ipvs:
        minSyncPeriod: 0s
        syncPeriod: 0s
        tcpFinTimeout: 0s
        tcpTimeout: 0s
        udpTimeout: 0s
      metricsBindAddress: 0.0.0.0:10249
      mode: iptables
      nftables:
        minSyncPeriod: 0s
        syncPeriod: 0s
    kuberouter:
      autoMTU: true
      hairpin: Enabled
      metricsPort: 8080
    nodeLocalLoadBalancing:
      enabled: false
      envoyProxy:
        apiServerBindPort: 7443
        konnectivityServerBindPort: 7132
      type: EnvoyProxy
    podCIDR: 10.244.0.0/16
    provider: kuberouter
    serviceCIDR: 10.96.0.0/12
  scheduler: {}
  storage:
    etcd:
      peerAddress: 10.72.8.1
    type: etcd
  telemetry:
    enabled: true
```

(I masked the real IPv6 address in the k0s.yaml, but it's there and it's correct)

**Comment by neris** [comment]
Also, probably not related, but I tried setting `spec.api.externalAddress` to the controller's public IPv6, that didn't help. And I tried adding another node that only have a public IPv6 address to the cluster, which resulted in this in the node's logs:

`tail /var/log/containers/kube-router-nzt4h_kube-system_kube-router-8b4f9b0291ba79bd7b6150183e8abf10257699c89e76967bcf1208389bc86a7e.log`:
```
2025-05-12T13:44:42.526132199Z stderr F E0512 13:44:42.526021   96414 reflector.go:158] "Unhandled Error" err="k8s.io/client-go@v0.31.3/tools/cache/reflector.go:243: Failed to watch *v1.Pod: failed to list *v1.Pod: Get \"https://10.96.0.1:443/api/v1/pods?limit=500&resourceVersion=0\": dial tcp 10.96.0.1:443: connect: network is unreachable" logger="UnhandledError"
2025-05-12T13:44:46.539290454Z stderr F W0512 13:44:46.539141   96414 reflector.go:561] k8s.io/client-go@v0.31.3/tools/cache/reflector.go:243: failed to list *v1.Node: Get "https://10.96.0.1:443/api/v1/nodes?limit=500&resourceVersion=0": dial tcp 10.96.0.1:443: connect: network is unreachable
```

**Comment by jnummelin** [comment]
ok, let's verify the controller(s) are telling workers to be dual-stack:
```
kubectl -n kube-system get cm worker-config-default-1.32 -o json | jq '.data.dualStackEnabled'
```

If that yields true, then the most likely cause is that the [hostname lookup](https://github.com/k0sproject/k0s/blob/main/pkg/component/worker/kubelet.go#L146-L161) k0s does doesn't yield both the ipv4&6 addresses so k0s does not put that in for kubelet automatically.

k0s uses the same logic to "detect" the addresses as kubelet does, essentially gets the adresses the hostname is mapped to.

If this speculation proves true, then the workaround is to force kubelet to have the appropriate addresses. In the k0s systemd unit:
```
k0s worker ... --kubelet-extra-args="--node-ip=1.2.3.4,2a01:<MASKED>:1"
```

**Comment by neris** [comment]
`sudo k0s kubectl -n kube-system get cm worker-config-default-1.32 -o json | jq '.data.dualStackEnabled'`:
```
"true"
```

Not sure how exactly it does the hostname lookup and how I can replicate that in plain bash, but `getent hosts yh-k8s-test-worker01` returns:
```
2a01:<MASKED>:2 yh-k8s-test-worker01
fe80::be24:11ff:fe35:848a yh-k8s-test-worker01
fe80::be24:11ff:fe4f:3dfa yh-k8s-test-worker01
fe80::947e:23ff:fe20:b2c3 yh-k8s-test-worker01
```

**Comment by neris** [comment]
Adding both IPv4 and IPv6 addresses to `/etc/hosts` fixed the problem. Would that be the correct way of fixing this? Can't it automatically read the IP addresses from the network interfaces?

**Comment by jnummelin** [comment]
I think the thinking behind that logic, both in k0s and kubelet is "If the hostname maps to _this_ address it must be the default/cross-node routable"

Adding those to hosts file seems like a ok solution to me.

**Comment by twz123** [comment]
> Adding both IPv4 and IPv6 addresses to `/etc/hosts` fixed the problem. Would that be the correct way of fixing this?

Yes, that is the correct way of fixing this, currently.

> Can't it automatically read the IP addresses from the network interfaces?

I was wondering this, too, today. The only reason k0s relies on the name resolution is that upstream kubelet does it that way. However, it might indeed be a good idea to have a fallback in case the lookup doesn't return IPs for both families.

**Comment by jnummelin** [comment]
I think we should add some notes on the ipv6 detection on the docs

**Comment by neris** [comment]
Welp looks like the hosts file trick doesn't help when installing via k0sctl. Back to the same error message on the kube-router.


`cat k0sctl.yaml`:
```
apiVersion: k0sctl.k0sproject.io/v1beta1
kind: Cluster
metadata:
  name: yh-k8s
  user: yh-k8s-neris
spec:
  hosts:
  - ssh:
      address: 2a01:<MASKED>:1
      user: neris
      port: 22
      keyPath: ~/.ssh/id_ed25519
    role: controller
  - ssh:
      address: 2a01:<MASKED>:2
      user: neris
      port: 22
      keyPath: ~/.ssh/id_ed25519
    role: worker
  k0s:
    version: v1.32.4+k0s.0
    config:
      apiVersion: k0s.k0sproject.io/v1beta1
      kind: ClusterConfig
      metadata:
        name: yh-k8s
      spec:
        network:
          podCIDR: 10.244.0.0/16
          serviceCIDR: 10.96.0.0/12
          dualStack:
            enabled: true
            IPv6podCIDR: fd01::/108
            IPv6serviceCIDR: fd02::/108
```


`cat /proc/$(pidof kubelet)/cmdline | xargs -0`:
```
/var/lib/k0s/bin/kubelet --cert-dir=/var/lib/k0s/kubelet/pki --containerd=/run/k0s/containerd.sock --node-ip=10.72.8.2 --runtime-cgroups=/system.slice/containerd.service --root-dir=/var/lib/k0s/kubelet --config=/run/k0s/kubelet/config.yaml --kubeconfig=/var/lib/k0s/kubelet.conf --v=1
```


`cat /etc/k0s/k0s.yaml`:
```
# generated-by-k0sctl 2025-05-13T18:03:27-04:00
apiVersion: k0s.k0sproject.io/v1beta1
kind: ClusterConfig
metadata:
  name: yh-k8s
spec:
  api:
    sans:
    - 2a01:<MASKED>:1
    - 10.72.8.1
  network:
    dualStack:
      IPv6podCIDR: fd01::/108
      IPv6serviceCIDR: fd02::/108
      enabled: true
    podCIDR: 10.244.0.0/16
    serviceCIDR: 10.96.0.0/12
  storage:
    etcd:
      peerAddress: 10.72.8.1
```

**Comment by jnummelin** [comment]
I think that happens because k0sctl [sets](https://github.com/k0sproject/k0sctl/blob/main/pkg/apis/k0sctl.k0sproject.io/v1beta1/cluster/host.go#L322-L325) the node-ip to the given ssh address. The way at least I generally work with k0sctl is that I pretty much force all the addresses to _known_ ones with it. So you could do something like:
```yaml
apiVersion: k0sctl.k0sproject.io/v1beta1
kind: Cluster
metadata:
  name: yh-k8s
  user: yh-k8s-neris
spec:
  hosts:
  - ssh:
      address: 2a01:<MASKED>:1
      user: neris
      port: 22
      keyPath: ~/.ssh/id_ed25519
    role: controller
    installFlags:
      - --kubelet-extra-args=--node-ip=2a01:<MASKED>:1,1.2.3.4
  - ssh:
      address: 2a01:<MASKED>:2
      user: neris
      port: 22
      keyPath: ~/.ssh/id_ed25519
    role: worker
    installFlags:
      - --kubelet-extra-args=--node-ip=2a02:<MASKED>:1,1.2.3.5

```
