### ISSUE TITLE
metric-server ServiceUnavailable/context deadline in single node mode

### ISSUE THREAD

**Issue by hptf** [k0sproject/k0s#5898]
### Before creating an issue, make sure you've checked the following:

- [x] You are running the latest released version of k0s
- [x] Make sure you've searched for existing issues, both open and closed
- [x] Make sure you've searched for PRs too, a fix might've been merged already
- [x] You're looking at docs for the released version, "main" branch docs are usually ahead of released versions.

### Platform

```shell
$uname -srvmo; cat /etc/os-release || lsb_release -a
Linux 5.14.0-583.el9.x86_64 #1 SMP PREEMPT_DYNAMIC Tue May 6 21:54:50 UTC 2025 x86_64 GNU/Linux
NAME="CentOS Stream"
VERSION="9"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="9"
PLATFORM_ID="platform:el9"
PRETTY_NAME="CentOS Stream 9"
ANSI_COLOR="0;31"
LOGO="fedora-logo-icon"
CPE_NAME="cpe:/o:centos:centos:9"
HOME_URL="https://centos.org/"
BUG_REPORT_URL="https://issues.redhat.com/"
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux 9"
REDHAT_SUPPORT_PRODUCT_VERSION="CentOS Stream"
```

### Version

v1.33.1+k0s.0

### Sysinfo

<details><summary>`k0s sysinfo`</summary>
<pre>
Total memory: 46.8 GiB (pass)
File system of /var/lib/k0s: xfs (pass)
Disk space available for /var/lib/k0s: 25.9 GiB (pass)
Relative disk space available for /var/lib/k0s: 29% (pass)
Name resolution: localhost: [::1 127.0.0.1] (pass)
Operating system: Linux (pass)
  Linux kernel release: 5.14.0-583.el9.x86_64 (pass)
  Max. file descriptors per process: current: 524287 / max: 524288 (pass)
  AppArmor: unavailable (pass)
  Executable in PATH: modprobe: /sbin/modprobe (pass)
  Executable in PATH: mount: /bin/mount (pass)
  Executable in PATH: umount: /bin/umount (pass)
  /proc file system: mounted (0x9fa0) (pass)
  Control Groups: version 2 (pass)
    cgroup controller "cpu": available (is a listed root controller) (pass)
    cgroup controller "cpuacct": available (via cpu in version 2) (pass)
    cgroup controller "cpuset": available (is a listed root controller) (pass)
    cgroup controller "memory": available (is a listed root controller) (pass)
    cgroup controller "devices": available (device filters attachable) (pass)
    cgroup controller "freezer": available (cgroup.freeze exists) (pass)
    cgroup controller "pids": available (is a listed root controller) (pass)
    cgroup controller "hugetlb": available (is a listed root controller) (pass)
    cgroup controller "blkio": available (via io in version 2) (pass)
  CONFIG_CGROUPS: Control Group support: built-in (pass)
    CONFIG_CGROUP_SCHED: Group CPU scheduler: built-in (pass)
      CONFIG_FAIR_GROUP_SCHED: Group scheduling for SCHED_OTHER: built-in (pass)
        CONFIG_CFS_BANDWIDTH: CPU bandwidth provisioning for FAIR_GROUP_SCHED: built-in (pass)
    CONFIG_BLK_CGROUP: Block IO controller: built-in (pass)
  CONFIG_NAMESPACES: Namespaces support: built-in (pass)
    CONFIG_UTS_NS: UTS namespace: built-in (pass)
    CONFIG_IPC_NS: IPC namespace: built-in (pass)
    CONFIG_PID_NS: PID namespace: built-in (pass)
    CONFIG_NET_NS: Network namespace: built-in (pass)
  CONFIG_NET: Networking support: built-in (pass)
    CONFIG_INET: TCP/IP networking: built-in (pass)
      CONFIG_IPV6: The IPv6 protocol: built-in (pass)
    CONFIG_NETFILTER: Network packet filtering framework (Netfilter): built-in (pass)
      CONFIG_NETFILTER_ADVANCED: Advanced netfilter configuration: built-in (pass)
      CONFIG_NF_CONNTRACK: Netfilter connection tracking support: module (pass)
      CONFIG_NETFILTER_XTABLES: Netfilter Xtables support: built-in (pass)
        CONFIG_NETFILTER_XT_TARGET_REDIRECT: REDIRECT target support: module (pass)
        CONFIG_NETFILTER_XT_MATCH_COMMENT: "comment" match support: module (pass)
        CONFIG_NETFILTER_XT_MARK: nfmark target and match support: module (pass)
        CONFIG_NETFILTER_XT_SET: set target and match support: module (pass)
        CONFIG_NETFILTER_XT_TARGET_MASQUERADE: MASQUERADE target support: module (pass)
        CONFIG_NETFILTER_XT_NAT: "SNAT and DNAT" targets support: module (pass)
        CONFIG_NETFILTER_XT_MATCH_ADDRTYPE: "addrtype" address type match support: module (pass)
        CONFIG_NETFILTER_XT_MATCH_CONNTRACK: "conntrack" connection tracking match support: module (pass)
        CONFIG_NETFILTER_XT_MATCH_MULTIPORT: "multiport" Multiple port match support: module (pass)
        CONFIG_NETFILTER_XT_MATCH_RECENT: "recent" match support: module (pass)
        CONFIG_NETFILTER_XT_MATCH_STATISTIC: "statistic" match support: module (pass)
      CONFIG_NETFILTER_NETLINK: module (pass)
      CONFIG_NF_NAT: module (pass)
      CONFIG_IP_SET: IP set support: module (pass)
        CONFIG_IP_SET_HASH_IP: hash:ip set support: module (pass)
        CONFIG_IP_SET_HASH_NET: hash:net set support: module (pass)
      CONFIG_IP_VS: IP virtual server support: module (pass)
        CONFIG_IP_VS_NFCT: Netfilter connection tracking: built-in (pass)
        CONFIG_IP_VS_SH: Source hashing scheduling: module (pass)
        CONFIG_IP_VS_RR: Round-robin scheduling: module (pass)
        CONFIG_IP_VS_WRR: Weighted round-robin scheduling: module (pass)
      CONFIG_NF_CONNTRACK_IPV4: IPv4 connection tracking support (required for NAT): unknown (warning)
      CONFIG_NF_REJECT_IPV4: IPv4 packet rejection: module (pass)
      CONFIG_NF_NAT_IPV4: IPv4 NAT: unknown (warning)
      CONFIG_IP_NF_IPTABLES: IP tables support: module (pass)
        CONFIG_IP_NF_FILTER: Packet filtering: module (pass)
          CONFIG_IP_NF_TARGET_REJECT: REJECT target support: module (pass)
        CONFIG_IP_NF_NAT: iptables NAT support: module (pass)
        CONFIG_IP_NF_MANGLE: Packet mangling: module (pass)
      CONFIG_NF_DEFRAG_IPV4: module (pass)
      CONFIG_NF_CONNTRACK_IPV6: IPv6 connection tracking support (required for NAT): unknown (warning)
      CONFIG_NF_NAT_IPV6: IPv6 NAT: unknown (warning)
      CONFIG_IP6_NF_IPTABLES: IP6 tables support: module (pass)
        CONFIG_IP6_NF_FILTER: Packet filtering: module (pass)
        CONFIG_IP6_NF_MANGLE: Packet mangling: module (pass)
        CONFIG_IP6_NF_NAT: ip6tables NAT support: module (pass)
      CONFIG_NF_DEFRAG_IPV6: module (pass)
    CONFIG_BRIDGE: 802.1d Ethernet Bridging: module (pass)
      CONFIG_LLC: module (pass)
      CONFIG_STP: module (pass)
  CONFIG_EXT4_FS: The Extended 4 (ext4) filesystem: module (pass)
  CONFIG_PROC_FS: /proc file system support: built-in (pass)
</pre>
</details>

### What happened?

I have been using k0s for local testing for years now.
With the latest version, the **kube-system/metrics-server does not work anymore**.

$ kubectl top node
Error from server (**ServiceUnavailable**): the server is currently unable to handle the request (get nodes.metrics.k8s.io)

I can't find a workaround for this, which makes my node unusable, as my application requires a metrics server.

Would you happen to have any clue?

Thanks for your help
hptf

### Steps to reproduce

**What I do:**
I am using latest K0S, single node mode, running on a CentOS Stream release 9.
I am installing it using k0sctl (version: v0.24.0,  'go version go1.24.3 linux/amd64')

$ k0sctl init > k0sctlbase.yaml
some edit to tune single node on 127.0.0.1, see below

○ → more k0sctlbase.yaml
```
apiVersion: k0sctl.k0sproject.io/v1beta1
kind: Cluster
metadata:
  name: k0s-cluster
  user: admin
spec:
  hosts:
  - ssh:
      address: 127.0.0.1
      user: root
      port: 22
      keyPath: null
    role: single
  options:
    wait:
      enabled: true
    drain:
      enabled: true
      gracePeriod: 2m0s
      timeout: 5m0s
      force: true
      ignoreDaemonSets: true
      deleteEmptyDirData: true
      podSelector: ""
      skipWaitForDeleteTimeout: 0s
    concurrency:
      limit: 30
      uploads: 5
    evictTaint:
      enabled: false
      taint: k0sctl.k0sproject.io/evict=true
      effect: NoExecute
      controllerWorkers: false
```

**What I see**
```
[...]
INFO k0s cluster version v1.33.1+k0s.0 is now installed
[...]
```

**Monitoring start event** I see
```
oc get event -w -A --sort-by='{.lastTimestamp}'
Successfully pulled image "quay.io/k0sproject/kube-proxy:v1.33.1"
Successfully pulled image "quay.io/k0sproject/kube-router:v2.5.0-iptables1
Successfully pulled image "quay.io/k0sproject/coredns:1.12.1"
Successfully pulled image "quay.io/k0sproject/metrics-server:v0.7.2-0"
```
```

oc get pod -A
NAMESPACE     NAME                             READY   STATUS    RESTARTS   AGE
kube-system   coredns-7494494fcf-pqs9s         1/1     Running   0          2m25s
kube-system   kube-proxy-99mld                 1/1     Running   0          2m24s
kube-system   kube-router-wg9bh                1/1     Running   0          2m24s
kube-system   metrics-server-7db8586f5-wf82s   1/1     Running   0          2m21s
```

so far so good...
**BUT**

```
oc get apiservices
NAME                              SERVICE                      AVAILABLE                      AGE
[...]
v1beta1.helm.k0sproject.io        Local                        True                           3m40s
v1beta1.metrics.k8s.io            kube-system/metrics-server   False (FailedDiscoveryCheck)   3m28s
v1beta2.autopilot.k0sproject.io   Local                        True                           3m37s
```

**oc get apiservices v1beta1.metrics.k8s.io -o yaml**
```

apiVersion: apiregistration.k8s.io/v1
kind: APIService
spec:
  group: metrics.k8s.io
  groupPriorityMinimum: 100
  insecureSkipTLSVerify: true
  service:
    name: metrics-server
    namespace: kube-system
    port: 443
  version: v1beta1
  versionPriority: 100
status:
  conditions:
  - lastTransitionTime: "2025-05-29T06:09:23Z"
    message: 'failing or missing response from https://10.96.145.235:443/apis/metrics.k8s.io/v1beta1:
      Get "https://10.96.145.235:443/apis/metrics.k8s.io/v1beta1": context deadline
      exceeded'
    reason: FailedDiscoveryCheck
    status: "False"
    type: Available
```

Get "https://10.96.145.235:443/apis/metrics.k8s.io/v1beta1": **context deadline exceeded**

### Expected behavior

I expect 

- metricserver to communicate with other elements, 
- kubectl top node to work as expected.

### Actual behavior

○ → **kubectl top node**
Error from server (ServiceUnavailable): the server is currently **unable to handle the request** (get nodes.metrics.k8s.io)

### Additional context

NOTE: all the description above is on a strictly unmodified version to ease problem reproduction by Subject matter expert

I play with curl, and notice that
`curl -k --header "Authorization: Bearer $TOKEN"  https://10.106.188.169:443/apis `
is ok

but not 
```
curl -k --header "Authorization: Bearer $TOKEN"  https://10.106.188.169:443/apis/metrics.k8s.io/v1beta1/nodes
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {},
  "status": "Failure",
  "message": "nodes.metrics.k8s.io is forbidden: User \"system:serviceaccount:kube-system:metrics-server\" cannot list resource \"nodes\" in API group \"metrics.k8s.io\" at the cluster scope",
  "reason": "Forbidden",
  "details": {
    "group": "metrics.k8s.io",
    "kind": "nodes"
  },
  "code": 403
```

We try to dig a lot and play with different tunings of service/api-service/clusterrole, etc.... 

Maybe some cluster roles are not good/missing  for this service ?

 oc edit clusterrole system:metrics-server 
 - apiGroups:
  - metrics.k8s.io
  resources:
  - nodes
  verbs:
  - get
  - list
  - watch

With some changes in this area I succed in getting the curl working
```
$ curl -k --header "Authorization: Bearer $TOKEN"  https://10.106.188.169:443/apis/metrics.k8s.io/v1beta1/nodes
{
  "kind": "NodeMetricsList",
  "apiVersion": "metrics.k8s.io/v1beta1",
  "metadata": {},
  "items": [
    {
      "metadata": {
        "name": "centos.localos",
        "creationTimestamp": "2025-05-28T16:18:07Z",
        "labels": {
          "beta.kubernetes.io/arch": "amd64",
          "beta.kubernetes.io/os": "linux",
          "kubernetes.io/arch": "amd64",
          "kubernetes.io/hostname": "centos.localos",
          "kubernetes.io/os": "linux",
          "node-role.kubernetes.io/control-plane": "true",
          "node.k0sproject.io/role": "control-plane"
        }
      },
      "timestamp": "2025-05-28T16:17:43Z",
      "window": "10.027s",
      "usage": {
        "cpu": "341883813n",
        "memory": "9358204Ki"
      }
    }
  ]
```
But the api-service/kubectl top node is still not working

**Comment by 3uzbcqje** [comment]
I'm having the same issue with 1.33.2+k0s.0 and 1.32.6+k0s.0. Here's my k0sctl.yaml:

```
apiVersion: k0sctl.k0sproject.io/v1beta1
kind: Cluster
metadata:
  name: tp1-pfops3
  user: admin
spec:
  k0s:
    config:
      apiVersion: k0s.k0sproject.io/v1beta1
      kind: ClusterConfig
      metadata:
        name: k0s
        namespace: kube-system
      spec:
        network:
          provider: calico
          calico:
            mode: bird
          podCIDR: 10.244.0.0/16
          serviceCIDR: 10.96.0.0/12
          dualStack:
            enabled: true
            IPv6podCIDR: fd00::/108
            IPv6serviceCIDR: fd01::/108
    version: 1.33.2+k0s.0
  hosts:
    - ssh:
        address: host1.example.org
        user: ubuntu
        keyPath: /home/u8055/.ssh/id_ed25519
      role: controller+worker
      installFlags:
        - --no-taints
    - ssh:
        address: host2.example.org
        user: ubuntu
        keyPath: /home/u8055/.ssh/id_ed25519
      role: controller+worker
      installFlags:
        - --no-taints
    - ssh:
        address: host3.example.org
        user: ubuntu
        keyPath: /home/u8055/.ssh/id_ed25519
      role: controller+worker
      installFlags:
        - --no-taints
```
