### ISSUE TITLE
maxPods configuration is not getting applied

### ISSUE THREAD

**Issue by NileshChandekar** [k0sproject/k0s#5998]
### Before creating an issue, make sure you've checked the following:

- [x] You are running the latest released version of k0s
- [x] Make sure you've searched for existing issues, both open and closed
- [x] Make sure you've searched for PRs too, a fix might've been merged already
- [x] You're looking at docs for the released version, "main" branch docs are usually ahead of released versions.

### Platform

```shell
[root@k0s-node k0s]# uname -srvmo; cat /etc/os-release || lsb_release -a
Linux 5.15.0-205.149.5.1.el9uek.x86_64 #2 SMP Fri Apr 5 11:29:36 PDT 2024 x86_64 GNU/Linux
NAME="Oracle Linux Server"
VERSION="9.4"
ID="ol"
ID_LIKE="fedora"
VARIANT="Server"
VARIANT_ID="server"
VERSION_ID="9.4"
PLATFORM_ID="platform:el9"
PRETTY_NAME="Oracle Linux Server 9.4"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:oracle:linux:9:4:server"
HOME_URL="https://linux.oracle.com/"
BUG_REPORT_URL="https://github.com/oracle/oracle-linux"
 
ORACLE_BUGZILLA_PRODUCT="Oracle Linux 9"
ORACLE_BUGZILLA_PRODUCT_VERSION=9.4
ORACLE_SUPPORT_PRODUCT="Oracle Linux"
ORACLE_SUPPORT_PRODUCT_VERSION=9.4
[root@k0s-node k0s]#
```

### Version

[root@k0s-node k0s]# k0s version v1.32.1+k0s.0 [root@k0s-node k0s]#

### Sysinfo

<details><summary>`k0s sysinfo`</summary>
<pre>
[root@k0s-node k0s]# k0s sysinfo

Total memory: 7.1 GiB (pass)

File system of /var/lib/k0s: xfs (pass)

Disk space available for /var/lib/k0s: 4.3 GiB (pass)

Relative disk space available for /var/lib/k0s: 47% (pass)

Name resolution: localhost: [::1 127.0.0.1] (pass)

Operating system: Linux (pass)

  Linux kernel release: 5.15.0-205.149.5.1.el9uek.x86_64 (pass)

  Max. file descriptors per process: current: 524288 / max: 524288 (pass)

  AppArmor: unavailable (pass)

  Executable in PATH: modprobe: /usr/sbin/modprobe (pass)

  Executable in PATH: mount: /usr/bin/mount (pass)

  Executable in PATH: umount: /usr/bin/umount (pass)

  /proc file system: mounted (0x9fa0) (pass)

  Control Groups: version 2 (pass)

    cgroup controller "cpu": available (is a listed root controller) (pass)

    cgroup controller "cpuacct": available (via cpu in version 2) (pass)

    cgroup controller "cpuset": available (is a listed root controller) (pass)

    cgroup controller "memory": available (is a listed root controller) (pass)

    cgroup controller "devices": available (device filters attachable) (pass)

    cgroup controller "freezer": available (cgroup.freeze exists) (pass)

    cgroup controller "pids": available (is a listed root controller) (pass)

    cgroup controller "hugetlb": available (is a listed root controller) (pass)

    cgroup controller "blkio": available (via io in version 2) (pass)

  CONFIG_CGROUPS: Control Group support: built-in (pass)

    CONFIG_CGROUP_FREEZER: Freezer cgroup subsystem: built-in (pass)

    CONFIG_CGROUP_PIDS: PIDs cgroup subsystem: built-in (pass)

    CONFIG_CGROUP_DEVICE: Device controller for cgroups: built-in (pass)

    CONFIG_CPUSETS: Cpuset support: built-in (pass)

    CONFIG_CGROUP_CPUACCT: Simple CPU accounting cgroup subsystem: built-in (pass)

    CONFIG_MEMCG: Memory Resource Controller for Control Groups: built-in (pass)

    CONFIG_CGROUP_HUGETLB: HugeTLB Resource Controller for Control Groups: built-in (pass)

    CONFIG_CGROUP_SCHED: Group CPU scheduler: built-in (pass)

      CONFIG_FAIR_GROUP_SCHED: Group scheduling for SCHED_OTHER: built-in (pass)

        CONFIG_CFS_BANDWIDTH: CPU bandwidth provisioning for FAIR_GROUP_SCHED: built-in (pass)

    CONFIG_BLK_CGROUP: Block IO controller: built-in (pass)

  CONFIG_NAMESPACES: Namespaces support: built-in (pass)

    CONFIG_UTS_NS: UTS namespace: built-in (pass)

    CONFIG_IPC_NS: IPC namespace: built-in (pass)

    CONFIG_PID_NS: PID namespace: built-in (pass)

    CONFIG_NET_NS: Network namespace: built-in (pass)

  CONFIG_NET: Networking support: built-in (pass)

    CONFIG_INET: TCP/IP networking: built-in (pass)

      CONFIG_IPV6: The IPv6 protocol: built-in (pass)

    CONFIG_NETFILTER: Network packet filtering framework (Netfilter): built-in (pass)

      CONFIG_NETFILTER_ADVANCED: Advanced netfilter configuration: built-in (pass)

      CONFIG_NF_CONNTRACK: Netfilter connection tracking support: module (pass)

      CONFIG_NETFILTER_XTABLES: Netfilter Xtables support: built-in (pass)

        CONFIG_NETFILTER_XT_TARGET_REDIRECT: REDIRECT target support: module (pass)

        CONFIG_NETFILTER_XT_MATCH_COMMENT: "comment" match support: module (pass)

        CONFIG_NETFILTER_XT_MARK: nfmark target and match support: module (pass)

        CONFIG_NETFILTER_XT_SET: set target and match support: module (pass)

        CONFIG_NETFILTER_XT_TARGET_MASQUERADE: MASQUERADE target support: module (pass)

        CONFIG_NETFILTER_XT_NAT: "SNAT and DNAT" targets support: module (pass)

        CONFIG_NETFILTER_XT_MATCH_ADDRTYPE: "addrtype" address type match support: module (pass)

        CONFIG_NETFILTER_XT_MATCH_CONNTRACK: "conntrack" connection tracking match support: module (pass)

        CONFIG_NETFILTER_XT_MATCH_MULTIPORT: "multiport" Multiple port match support: module (pass)

        CONFIG_NETFILTER_XT_MATCH_RECENT: "recent" match support: module (pass)

        CONFIG_NETFILTER_XT_MATCH_STATISTIC: "statistic" match support: module (pass)

      CONFIG_NETFILTER_NETLINK: built-in (pass)

      CONFIG_NF_NAT: module (pass)

      CONFIG_IP_SET: IP set support: module (pass)

        CONFIG_IP_SET_HASH_IP: hash:ip set support: module (pass)

        CONFIG_IP_SET_HASH_NET: hash:net set support: module (pass)

      CONFIG_IP_VS: IP virtual server support: module (pass)

        CONFIG_IP_VS_NFCT: Netfilter connection tracking: built-in (pass)

        CONFIG_IP_VS_SH: Source hashing scheduling: module (pass)

        CONFIG_IP_VS_RR: Round-robin scheduling: module (pass)

        CONFIG_IP_VS_WRR: Weighted round-robin scheduling: module (pass)

      CONFIG_NF_CONNTRACK_IPV4: IPv4 connection tracking support (required for NAT): unknown (warning)

      CONFIG_NF_REJECT_IPV4: IPv4 packet rejection: module (pass)

      CONFIG_NF_NAT_IPV4: IPv4 NAT: unknown (warning)

      CONFIG_IP_NF_IPTABLES: IP tables support: module (pass)

        CONFIG_IP_NF_FILTER: Packet filtering: module (pass)

          CONFIG_IP_NF_TARGET_REJECT: REJECT target support: module (pass)

        CONFIG_IP_NF_NAT: iptables NAT support: module (pass)

        CONFIG_IP_NF_MANGLE: Packet mangling: module (pass)

      CONFIG_NF_DEFRAG_IPV4: module (pass)

      CONFIG_NF_CONNTRACK_IPV6: IPv6 connection tracking support (required for NAT): unknown (warning)

      CONFIG_NF_NAT_IPV6: IPv6 NAT: unknown (warning)

      CONFIG_IP6_NF_IPTABLES: IP6 tables support: module (pass)

        CONFIG_IP6_NF_FILTER: Packet filtering: module (pass)

        CONFIG_IP6_NF_MANGLE: Packet mangling: module (pass)

        CONFIG_IP6_NF_NAT: ip6tables NAT support: module (pass)

      CONFIG_NF_DEFRAG_IPV6: module (pass)

    CONFIG_BRIDGE: 802.1d Ethernet Bridging: built-in (pass)

      CONFIG_LLC: built-in (pass)

      CONFIG_STP: built-in (pass)

  CONFIG_EXT4_FS: The Extended 4 (ext4) filesystem: module (pass)

  CONFIG_PROC_FS: /proc file system support: built-in (pass)

[root@k0s-node k0s]#
 </pre>
</details>

### Steps to reproduce

1. trying to increase the default pod limit from 110 - 250 
2. its not getting changed

```
apiVersion: k0sctl.k0sproject.io/v1beta1
kind: Cluster
metadata:
  name: k0s-cpg
spec:
  hosts:
    - ssh:
        address: 192.168.122.190
        user: root
        port: 22
        keyPath: /root/.ssh/id_rsa
      role: controller+worker
      noTaints: true
      installFlags:
      - --debug
      - --disable-components=konnectivity-server
      - --profile=k0s-profile
  k0s:
    version: v1.30.9+k0s.0
    dynamicConfig: false
    config:
      spec:
        network:
          podCIDR: 10.244.0.0/16
          serviceCIDR: 10.96.0.0/12
          provider: calico
          controlPlaneLoadBalancing:
            enabled: true
            type: Keepalived
            keepalived:
              vrrpInstances:
                - virtualIPs: ["192.168.122.250/32"]
                  authPass: dmok0s01
                  interface: enp1s0
        workerProfiles:
            - name: k0s-profile
              values:
                max-pods: "250"
```

### Expected behavior

defailt pod limit is 110, should be changed to 250 

### Actual behavior

its still 110

**Comment by makhov** [comment]
I believe it should be `maxPods`, not `max-pods`

**Comment by twz123** [comment]
Moreover I think it's an integer, not a string, like so:

```yaml
spec:
  k0s:
    config:
      spec:
        workerProfiles:
          - name: k0s-profile
            values:
              maxPods: 250
```

Reference: https://kubernetes.io/docs/reference/config-api/kubelet-config.v1beta1/#kubelet-config-k8s-io-v1beta1-KubeletConfiguration

**Comment by NileshChandekar** [comment]
* we tried so many permutations and combinations, our observation is on a deployed clusters the new config value is not updating. 
* If we reset the cluster, change the value then its getting applied 


```
[root@localhost k0s-releases]# cat k0s-test-automation.yaml
apiVersion: k0sctl.k0sproject.io/v1beta1
kind: Cluster
metadata:
  name: k0s-test-automation
spec:
  hosts:
  - ssh:
      address: 192.168.122.233
      user: root
      port: 22
      keyPath: /root/.ssh/id_rsa
    role: controller+worker
    noTaints: true
    installFlags:
    - --profile=podmax
    - --debug
    - --disable-components=konnectivity-server
    uploadBinary: true
    k0sBinaryPath: /opt/k0s-releases/k0s-v1.32.1+k0s.0-amd64
    files:
      # This airgap bundle file will be uploaded from the k0sctl
      # host to the specified directory on the target host
      #- src: /opt/k0s-releases/k0s-airgap-bundle-v1.32.1+k0s.0-amd64
      - src: /opt/k0s-releases/k0s-airgap-bundle-v1.32.1+k0s.0-amd64
        dstDir: /var/lib/k0s/images
        perm: 0755 
  k0s:
    version: v1.32.1+k0s.0
      #dynamicConfig: false
    dynamicConfig: true
    config:
      spec:
        network:
          podCIDR: 10.244.0.0/16
          serviceCIDR: 10.96.0.0/12
          provider: calico
        workerProfiles:
          - name: podmax
            values:
              #    max-pods: "250"
              maxPods: 180
[root@localhost k0s-releases]# 
```

```
[root@localhost k0s-releases]# kubectl describe no k0s-node.ct.lan | grep -i pods:
  pods:               180
  pods:               180
Non-terminated Pods:          (5 in total)
```

>[!NOTE] - But for this I need to reset the cluster and then change, 

> - Wanted a on-the-fly method to change the value.
