### ISSUE TITLE
Disabling kube-router in a pre-existing installation

### ISSUE THREAD

**Issue by Starttoaster** [k0sproject/k0s#6027]
I'll preface with stating I understand the documentation states it is not supported to disable kube-router in an existing installation. Because I often ignore warnings in documentation, I've already manually uninstalled kube-router, and installed a CNI (Cilium) that replaces its function. I've verified that all my Pods are currently managed by Cilium, and everything is working great. 

On cluster upgrades however, kube-router is getting reinstalled. I update my cluster with k0sctl, but it's not clear to me if the thing reinstalling kube-router is actually due to k0sctl, or some lingering configuration that k0sctl is recognizing on my hosts. Any idea?

My k0s.yaml configuration looks like this:
```yaml
apiVersion: k0s.k0sproject.io/v1beta1
kind: ClusterConfig
spec:
  api:
    sans:
    - {list of IPs}
  network:
    kubeProxy:
      disabled: true
    nodeLocalLoadBalancing:
      enabled: true
      type: EnvoyProxy
    provider: custom
  storage:
    etcd:
      peerAddress: 192.168.1.240
```

Everything there in the network block matches what's in my k0sctl configuration, so that all seems fine. Not sure why it's getting reinstalled. If you happen to know of an extra bit of configuration somewhere that might cause kube-router to get reinstalled, I'd appreciate any help you can give me. But I understand I'm in unsupported territory :)
