### ISSUE TITLE
Missing kube-scheduler and kube-controller-manager services

### ISSUE THREAD

**Issue by niemannd** [k0sproject/k0s#611]
**Version**
```
$ k0s version v0.9.1
```
**Platform**
Which platform did you run k0s on?
```
Ubuntu 20.04.1 LTS
```
**What happened?**
I set up a k0s Cluster and tried to add the prometheus operator. Looks like the kube-scheduler and kube-controller-manager services are missing, so i can't get metrics from them. I can see the processes running by running the command 
`sudo ps aux | awk '{print $11}' | grep k0s` on the hst but there is no pod/deployment/service/etc with that name. 

**How To Reproduce**
`k0s server -c k0s.yaml --enable-worker`

**Expected behavior**
I would expect that the mentioned services are visible in the cluster and possible to scrape.

**Comment by jnummelin** [comment]
There's no pods or services for the kube components as they are NOT running in pods. They are "naked" processes managed by the k0s main process.

Currently prometheus, running in the cluster, cannot actually scrape the metrics:
- by default kube-scheduler and controller manager are only binding to localhost
- when NOT running with `--enable-worker` option, the controller/server is not joining the cluster network. Thus there's no guarantee that a prom pod in the cluster could even scrape the metrics from another nodes.

Did not really test this, but there might be a way to overcome this with some config tweaks and bit of "manual" intervention:
- in the k0s config, add extra args for kube CM :
```
spec:
  controllerManager:
    extraArgs:
      bind-address: "accessible IP"
```
- then add manually a service&ep, something like:
```
apiVersion: v1
kind: Service
metadata:
  name: kube-cm-svc
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: "10257"
spec:
  ports:
  - name:  metrics
    port: 10257
    targetPort: 10257
---
apiVersion: v1
kind: Endpoints
metadata:
  name: kube-cm-svc
  namespace: default
subsets:
- addresses:
  - ip: <controller IP>
  ports:
  - name: metrics
    port: 10257
    protocol: TCP
```
