### ISSUE TITLE
Support offline installation

### ISSUE THREAD

**Issue by imuxin** [k0sproject/k0s#614]
**Describe the solution you'd like**
I hope that k0s could load images in some specific directory that were precompressed.

**Comment by usrbinkat** [comment]
docker registry v2 compliant image content can be served as a mirror source to containerd via basic go http(s) web service over the `docker/registry/v2/{blobs,repositories}` directories.

For example, containerd honors /etc/containers/registries.conf:
```
[[registry]]
  prefix = "docker.io"
  location = "docker.io"
  mirror-by-digest-only = false

  [[registry.mirror]]
    location = "localhost:5000"
    insecure = true
```
And with a basic tool like [Koffer](https://github.com/CloudCtl/Koffer) artifacts can be made available to restricted and airgap deployment scenarios via standard `mirror < to > mirror` `scopeo / docker{pull,push}` etc practices with negligible additional effort or technology bloat.

A designed method for k0s binary to serve images via simple web service would resolve the remaining airgap/disconnected hurdles and would not require a full docker registry api implementation.

**Comment by deskoh** [comment]
To add on, I managed to run k0s v0.9.1 in an offline environment with an insecure private registry.

Other than configuring [`images.repository`](https://docs.k0sproject.io/latest/configuration/#images), customization is required for [`containerd.toml`](https://docs.k0sproject.io/v0.10.0/containerd_config/) to

   * specify image fo `k8s.gcr.io/pause` image
   * Add endpoint for private registry if it is insecure

Note that the socket address has been changed from `/var/lib/k0s/run/containerd.sock` to `/run/k0s/containerd.sock` from in `v0.10.0` when running `k0s` as root.

```toml
version = 2
root = "/var/lib/k0s/containerd"
state = "/var/lib/k0s/run/containerd"
...
[grpc]
  address = "/run/k0s/containerd.sock"
...
    sandbox_image = "<<private repo>>/k8s.gcr.io/pause:3.2"
...
    [plugins."io.containerd.grpc.v1.cri".registry]
      [plugins."io.containerd.grpc.v1.cri".registry.mirrors]
        ...
        [plugins."io.containerd.grpc.v1.cri".registry.mirrors."<<private repo>>"]
          endpoint = ["http://<<private repo>>"]
```
