### ISSUE TITLE
k0s running on Fedora coreos

### ISSUE THREAD

**Issue by pinghe** [k0sproject/k0s#640]
**Version**
```
$ k0s version
v0.9.1
```
**Platform**
Which platform did you run k0s on?
```
$ uname -a
Linux 5.9.11-200.fc33.x86_64 #1 SMP Tue Nov 24 18:18:01 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

fedora coreos
```
**What happened?**
```
E0120 15:21:48.059804  188061 leaderelection.go:321] error retrieving resource lock kube-node-lease/k0s-endpoint-reconciler: Get "https://localhost:6443/apis/coordination.k8s.io/v1/namespaces/kube-node-lease/leases/k0s-endpoint-reconciler": dial tcp [::1]:6443: connect: connection refused
E0120 15:21:48.063344  188061 leaderelection.go:321] error retrieving resource lock kube-node-lease/k0s-manifest-applier: Get "https://localhost:6443/apis/coordination.k8s.io/v1/namespaces/kube-node-lease/leases/k0s-manifest-applier": dial tcp [::1]:6443: connect: connection refused
time="2021-01-20 15:21:50" level=info msg="E0120 15:21:50.650191  188081 instance.go:392] Could not construct pre-rendered responses for ServiceAccountIssuerDiscovery endpoints. Endpoints will not be enabled. Error: issuer URL must use https scheme, got: api" component=kube-apiserver
time="2021-01-20 15:21:55" level=info msg="E0120 15:21:55.490062  188087 leaderelection.go:325] error retrieving resource lock kube-system/kube-controller-manager: leases.coordination.k8s.io \"kube-controller-manager\" is forbidden: User \"system:kube-controller-manager\" cannot get resource \"leases\" in API group \"coordination.k8s.io\" in the namespace \"kube-system\"" component=kube-controller-manager
time="2021-01-20 15:21:55" level=info msg="W0120 15:21:55.520851  188096 authentication.go:332] Error looking up in-cluster authentication configuration: configmaps \"extension-apiserver-authentication\" is forbidden: User \"system:kube-scheduler\" cannot get resource \"configmaps\" in API group \"\" in the namespace \"kube-system\"" component=kube-scheduler


I0120 15:22:05.108527  188061 request.go:645] Throttling request took 1.059372709s, request: GET:https://localhost:6443/api/v1/limitranges?limit=1
time="2021-01-20 15:22:08" level=info msg="E0120 15:22:08.250743  188081 controller.go:116] loading OpenAPI spec for \"v1beta1.metrics.k8s.io\" failed with: failed to retrieve openAPI spec, http error: ResponseCode: 503, Body: service unavailable" component=kube-apiserver
time="2021-01-20 15:22:12" level=info msg="E0120 15:22:12.782213  188087 plugins.go:605] Error initializing dynamic plugin prober: Error (re-)creating driver directory: mkdir /usr/libexec/kubernetes: read-only file system" component=kube-controller-manager

```

````
time="2021-01-20 15:42:35" level=info msg="E0120 15:42:35.458799  189175 reflector.go:138] k8s.io/apiserver/pkg/server/dynamiccertificates/configmap_cafile_content.go:206: Failed to watch *v1.ConfigMap: failed to list *v1.ConfigMap: configmaps \"extension-apiserver-authentication\" is forbidden: User \"system:kube-scheduler\" cannot list resource \"configmaps\" in API group \"\" in the namespace \"kube-system\"" component=kube-scheduler
time="2021-01-20 15:42:35" level=info msg="E0120 15:42:35.459048  189175 reflector.go:138] k8s.io/client-go/informers/factory.go:134: Failed to watch *v1.StatefulSet: failed to list *v1.StatefulSet: statefulsets.apps is forbidden: User \"system:kube-scheduler\" cannot list resource \"statefulsets\" in API group \"apps\" at the cluster scope" component=kube-scheduler
time="2021-01-20 15:42:35" level=info msg="E0120 15:42:35.459182  189175 reflector.go:138] k8s.io/client-go/informers/factory.go:134: Failed to watch *v1.Node: failed to list *v1.Node: nodes is forbidden: User \"system:kube-scheduler\" cannot list resource \"nodes\" in API group \"\" at the cluster scope" component=kube-scheduler


time="2021-01-20 15:42:37" level=warning msg="failed to get initial kubelet config with join token: failed to get kubelet config from API: configmaps \"kubelet-config-default-1.20\" is forbidden: User \"system:bootstrap:bk5wbm\" cannot get resource \"configmaps\" in API group \"\" in the namespace \"kube-system\""
time="2021-01-20 15:42:37" level=warning msg="failed to get initial kubelet config with join token: failed to get kubelet config from API: configmaps \"kubelet-config-default-1.20\" is forbidden: User \"system:bootstrap:bk5wbm\" cannot get resource \"configmaps\" in API group \"\" in the namespace \"kube-system\""



````

**How To Reproduce**
1 In a local area network environment
2 k0s server --enable-worker
failed

mkdir /usr/libexec/kubernetes: read-only file system
```

https://docs.fedoraproject.org/en-US/fedora-coreos/migrate-cl/

There is no way to create directories below the / directory. Changes are restricted to /etc and /var. Refer to the documentation for the storage node of the FCC configuration for details about writing directories and files to FCOS.

**Comment by kstych** [comment]
Please see #584 #494

**Comment by pinghe** [comment]
k0s.yaml
```
  network:
    podCIDR: 172.168.0.0/20
    serviceCIDR: 172.168.128.0/17
    provider: calico
    calico:
      mode: vxlan
      vxlanPort: 4789
      vxlanVNI: 4096
      mtu: 1450
      wireguard: false
      flexVolumeDriverPath: /var/libexec/k0s/kubelet-plugins/volume/exec/nodeagent~uds
      withWindowsNodes: false
  podSecurityPolicy:
    defaultPolicy: 00-k0s-privileged
  workerProfiles: 
    - name: coreos
      values:
         volumePluginDir: /var/libexec/k0s/kubelet-plugins/volume/exec 

```

```
k0s -d server -c k0s.yaml --enable-worker --profile coreos
```
k0s not working

log
```
time="2021-01-21 02:32:36" level=info msg="I0121 02:32:36.496445  568178 horizontal.go:169] Starting HPA controller" component=kube-controller-manager
time="2021-01-21 02:32:36" level=info msg="I0121 02:32:36.496475  568178 shared_informer.go:240] Waiting for caches to sync for HPA" component=kube-controller-manager
time="2021-01-21 02:32:36" level=info msg="W0121 02:32:36.546293  568178 probe.go:268] Flexvolume plugin directory at /usr/libexec/kubernetes/kubelet-plugins/volume/exec/ does not exist. Recreating." component=kube-controller-manager
time="2021-01-21 02:32:36" level=info msg="E0121 02:32:36.546404  568178 plugins.go:605] Error initializing dynamic plugin prober: Error (re-)creating driver directory: mkdir /usr/libexec/kubernetes: read-only file system" component=kube-controller-manager


NAMESPACE     NAME                                       READY   STATUS    RESTARTS   AGE
kube-system   calico-kube-controllers-7d9b8b4d87-cn8l6   0/1     Pending   0          78s
kube-system   coredns-65975dd9b9-vhz4x                   0/1     Pending   0          78s
kube-system   metrics-server-645f4dbf57-txblh            0/1     Pending   0          78s

```

**Comment by jnummelin** [comment]
@pinghe Can you verify couple things:
- Is the worker profile (kubelet config) properly created? `kubectl -n kube-system get cm kubelet-config-coreos-1.20 -o yaml`
- is the `flexVolumeDriverPath ` properly set at calico daemonset manifest at `/var/lib/k0s/manifests/calico/calico-DaemonSet-calico-node.yaml `

Based on the logs it seems none of those are properly set. 🤔

**Comment by pinghe** [comment]
k0s.yaml

add extraArgs for fixed mkdir error
```
  controllerManager:
    extraArgs: 
      flex-volume-plugin-dir: /var/libexec/k0s/kubelet-plugins/volume/exec
  scheduler:
    extraArgs: {}
  storage:
    type: etcd
    kine: null
    etcd:
      peerAddress: {localip}
  network:
    podCIDR: 172.168.0.0/20
    serviceCIDR: 172.168.128.0/17
    provider: calico
    calico:
      mode: vxlan
      vxlanPort: 4789
      vxlanVNI: 4096
      mtu: 1450
      wireguard: false
      flexVolumeDriverPath: /var/libexec/k0s/kubelet-plugins/volume/exec/nodeagent~uds
      withWindowsNodes: false
  podSecurityPolicy:
    defaultPolicy: 00-k0s-privileged
  workerProfiles: 
    - name: coreos
      values:
         volumePluginDir: /var/libexec/k0s/kubelet-plugins/volume/exec  
```

logs
```
time="2021-01-21 11:14:25" level=info msg="E0121 11:14:25.835265  616789 instance.go:392] Could not construct pre-rendered responses for ServiceAccountIssuerDiscovery endpoints. Endpoints will not be enabled. Error: issuer URL must use https scheme, got: api" component=kube-apiserver
time="2021-01-21 11:14:28" level=info msg="E0121 11:14:28.272119  616807 leaderelection.go:325] error retrieving resource lock kube-system/kube-controller-manager: leases.coordination.k8s.io \"kube-controller-manager\" is forbidden: User \"system:kube-controller-manager\" cannot get resource \"leases\" in API group \"coordination.k8s.io\" in the namespace \"kube-system\"" component=kube-controller-manager
time="2021-01-21 11:14:28" level=info msg="W0121 11:14:28.285336  616806 authentication.go:332] Error looking up in-cluster authentication configuration: configmaps \"extension-apiserver-authentication\" is forbidden: User \"system:kube-scheduler\" cannot get resource \"configmaps\" in API group \"\" in the namespace \"kube-system\"" component=kube-scheduler
time="2021-01-21 11:14:30" level=info msg="E0121 11:14:30.815206  616807 leaderelection.go:325] error retrieving resource lock kube-system/kube-controller-manager: leases.coordination.k8s.io \"kube-controller-manager\" is forbidden: User \"system:kube-controller-manager\" cannot get resource \"leases\" in API group \"coordination.k8s.io\" in the namespace \"kube-system\"" component=kube-controller-manager


NAMESPACE     NAME                                       READY   STATUS    RESTARTS   AGE
kube-system   calico-kube-controllers-7d9b8b4d87-2gdqd   0/1     Pending   0          25s
kube-system   coredns-65975dd9b9-gdmtd                   0/1     Pending   0          47s
kube-system   metrics-server-fd76b84cf-k826s             0/1     Pending   0          28s
```

kubectl -n kube-system get cm kubelet-config-coreos-1.20 -o yaml
````
apiVersion: v1
data:
  kubelet: |2

    apiVersion: kubelet.config.k8s.io/v1beta1
    authentication:
      anonymous:
        enabled: false
      webhook:
        cacheTTL: 0s
        enabled: true
      x509:
        clientCAFile: /var/lib/k0s/pki/ca.crt
    authorization:
      mode: Webhook
      webhook:
        cacheAuthorizedTTL: 0s
        cacheUnauthorizedTTL: 0s
    clusterDNS:
    - 172.168.128.10
    clusterDomain: cluster.local
    failSwapOn: false
    kind: KubeletConfiguration
    tlsCipherSuites:
    - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
    - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
    - TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305
    - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
    - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305
    - TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
    - TLS_RSA_WITH_AES_256_GCM_SHA384
    - TLS_RSA_WITH_AES_128_GCM_SHA256
    volumePluginDir: /var/libexec/k0s/kubelet-plugins/volume/exec
    volumeStatsAggPeriod: 0s
kind: ConfigMap
metadata:
  annotations:
    k0s.k0sproject.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"kubelet":"\napiVersion: kubelet.config.k8s.io/v1beta1\nauthentication:\n  anonymous:\n    enabled: false\n  webhook:\n    cacheTTL: 0s\n    enabled: true\n  x509:\n    clientCAFile: /var/lib/k0s/pki/ca.crt\nauthorization:\n  mode: Webhook\n  webhook:\n    cacheAuthorizedTTL: 0s\n    cacheUnauthorizedTTL: 0s\nclusterDNS:\n- 172.168.128.10\nclusterDomain: cluster.local\nfailSwapOn: false\nkind: KubeletConfiguration\ntlsCipherSuites:\n- TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256\n- TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256\n- TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305\n- TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384\n- TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305\n- TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384\n- TLS_RSA_WITH_AES_256_GCM_SHA384\n- TLS_RSA_WITH_AES_128_GCM_SHA256\nvolumePluginDir: /var/libexec/k0s/kubelet-plugins/volume/exec\nvolumeStatsAggPeriod: 0s\n"},"kind":"ConfigMap","metadata":{"name":"kubelet-config-coreos-1.20","namespace":"kube-system"}}
    k0s.k0sproject.io/stack-checksum: f85f3b10a58f6db39f8e74946a6b50c7
  creationTimestamp: "2021-01-21T11:46:29Z"
  labels:
    k0s.k0sproject.io/stack: kubelet
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:kubelet: {}
      f:metadata:
        f:annotations:
          .: {}
          f:k0s.k0sproject.io/last-applied-configuration: {}
          f:k0s.k0sproject.io/stack-checksum: {}
        f:labels:
          .: {}
          f:k0s.k0sproject.io/stack: {}
    manager: k0s
    operation: Update
    time: "2021-01-21T11:46:29Z"
  name: kubelet-config-coreos-1.20
  namespace: kube-system
  resourceVersion: "209"
  uid: 358759eb-0549-4b35-9508-00e61cf8032a

```


/var/lib/k0s/manifests/calico/calico-DaemonSet-calico-node.yaml
```
---
# Source: calico/templates/calico-node.yaml
# This manifest installs the calico-node container, as well
# as the CNI plugins and network config on
# each master and worker node in a Kubernetes cluster.
kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: calico-node
  namespace: kube-system
  labels:
    k8s-app: calico-node
spec:
  selector:
    matchLabels:
      k8s-app: calico-node
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  template:
    metadata:
      labels:
        k8s-app: calico-node
    spec:
      nodeSelector:
        kubernetes.io/os: linux
      hostNetwork: true
      tolerations:
        # Make sure calico-node gets scheduled on all nodes.
        - effect: NoSchedule
          operator: Exists
        # Mark the pod as a critical add-on for rescheduling.
        - key: CriticalAddonsOnly
          operator: Exists
        - effect: NoExecute
          operator: Exists
      serviceAccountName: calico-node
      # Minimize downtime during a rolling upgrade or deletion; tell Kubernetes to do a "force
      # deletion": https://kubernetes.io/docs/concepts/workloads/pods/pod/#termination-of-pods.
      terminationGracePeriodSeconds: 0
      priorityClassName: system-node-critical
      initContainers:
        # This container performs upgrade from host-local IPAM to calico-ipam.
        # It can be deleted if this is a fresh installation, or if you have already
        # upgraded to use calico-ipam.
        - name: upgrade-ipam
          image: myharbor.localhost/calico/cni:v3.16.2
          command: ["/opt/cni/bin/calico-ipam", "-upgrade"]
          envFrom:
          - configMapRef:
              # Allow KUBERNETES_SERVICE_HOST and KUBERNETES_SERVICE_PORT to be overridden for eBPF mode.
              name: kubernetes-services-endpoint
              optional: true
          env:
            - name: KUBERNETES_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: CALICO_NETWORKING_BACKEND
              valueFrom:
                configMapKeyRef:
                  name: calico-config
                  key: calico_backend
          volumeMounts:
            - mountPath: /var/lib/cni/networks
              name: host-local-net-dir
            - mountPath: /host/opt/cni/bin
              name: cni-bin-dir
          securityContext:
            privileged: true
        # This container installs the CNI binaries
        # and CNI network config file on each node.
        - name: install-cni
          image: myharbor.localhost/calico/cni:v3.16.2
          command: ["/opt/cni/bin/install"]
          envFrom:
          - configMapRef:
              # Allow KUBERNETES_SERVICE_HOST and KUBERNETES_SERVICE_PORT to be overridden for eBPF mode.
              name: kubernetes-services-endpoint
              optional: true
          env:
            # Name of the CNI config file to create.
            - name: CNI_CONF_NAME
              value: "10-calico.conflist"
            # The CNI network config to install on each node.
            - name: CNI_NETWORK_CONFIG
              valueFrom:
                configMapKeyRef:
                  name: calico-config
                  key: cni_network_config
            # Set the hostname based on the k8s node name.
            - name: KUBERNETES_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            # CNI MTU Config variable
            - name: CNI_MTU
              valueFrom:
                configMapKeyRef:
                  name: calico-config
                  key: veth_mtu
            # Prevents the container from sleeping forever.
            - name: SLEEP
              value: "false"
          volumeMounts:
            - mountPath: /host/opt/cni/bin
              name: cni-bin-dir
            - mountPath: /host/etc/cni/net.d
              name: cni-net-dir
          securityContext:
            privileged: true
        # Adds a Flex Volume Driver that creates a per-pod Unix Domain Socket to allow Dikastes
        # to communicate with Felix over the Policy Sync API.
        - name: flexvol-driver
          image: myharbor.localhost/calico/pod2daemon-flexvol:v3.16.2
          volumeMounts:
          - name: flexvol-driver-host
            mountPath: /host/driver
          securityContext:
            privileged: true
      containers:
        # Runs calico-node container on each Kubernetes node. This
        # container programs network policy and routes on each
        # host.
        - name: calico-node
          image: myharbor.localhost/calico/node:v3.16.2
          envFrom:
          - configMapRef:
              # Allow KUBERNETES_SERVICE_HOST and KUBERNETES_SERVICE_PORT to be overridden for eBPF mode.
              name: kubernetes-services-endpoint
              optional: true
          env:
            # Use Kubernetes API as the backing datastore.
            - name: DATASTORE_TYPE
              value: "kubernetes"
            # Wait for the datastore.
            - name: WAIT_FOR_DATASTORE
              value: "true"
            # Set based on the k8s node name.
            - name: NODENAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            # Choose the backend to use.
            - name: CALICO_NETWORKING_BACKEND
              valueFrom:
                configMapKeyRef:
                  name: calico-config
                  key: calico_backend
            # Cluster type to identify the deployment type
            - name: CLUSTER_TYPE
              value: "k8s"
            # Auto-detect the BGP IP address.
            - name: IP
              value: "autodetect"
            # Auto detect the iptables backend
            - name: FELIX_IPTABLESBACKEND
              value: "auto"
            # Disable IPIP
            - name: CALICO_IPV4POOL_IPIP
              value: "Never"
            # Enable VXLAN on the default IP pool.
            - name: CALICO_IPV4POOL_VXLAN
              value: Always
            - name: FELIX_VXLANPORT
              value: "4789"
            - name: FELIX_VXLANVNI
              value: "4096"
            # Set MTU for tunnel device used if ipip is enabled
            - name: FELIX_IPINIPMTU
              valueFrom:
                configMapKeyRef:
                  name: calico-config
                  key: veth_mtu
            # Set MTU for the VXLAN tunnel device.
            - name: FELIX_VXLANMTU
              valueFrom:
                configMapKeyRef:
                  name: calico-config
                  key: veth_mtu
            # Set MTU for the Wireguard tunnel device.
            - name: FELIX_WIREGUARDMTU
              valueFrom:
                configMapKeyRef:
                  name: calico-config
                  key: veth_mtu
            # The default IPv4 pool to create on startup if none exists. Pod IPs will be
            # chosen from this range. Changing this value after installation will have
            # no effect. This should fall within `--cluster-cidr`.
            - name: CALICO_IPV4POOL_CIDR
              value: "172.168.0.0/20"
            # Disable file logging so `kubectl logs` works.
            - name: CALICO_DISABLE_FILE_LOGGING
              value: "true"
            # Set Felix endpoint to host default action to ACCEPT.
            - name: FELIX_DEFAULTENDPOINTTOHOSTACTION
              value: "ACCEPT"
            # Disable IPv6 on Kubernetes.
            - name: FELIX_IPV6SUPPORT
              value: "false"
            # Set Felix logging to "info"
            - name: FELIX_LOGSEVERITYSCREEN
              value: "info"
            - name: FELIX_HEALTHENABLED
              value: "true"
          securityContext:
            privileged: true
          resources:
            requests:
              cpu: 250m
          livenessProbe:
            exec:
              command:
              - /bin/calico-node
              - -felix-live
            periodSeconds: 10
            initialDelaySeconds: 10
            failureThreshold: 6
          readinessProbe:
            exec:
              command:
              - /bin/calico-node
              - -felix-ready
            periodSeconds: 10
          volumeMounts:
            - mountPath: /lib/modules
              name: lib-modules
              readOnly: true
            - mountPath: /run/xtables.lock
              name: xtables-lock
              readOnly: false
            - mountPath: /var/run/calico
              name: var-run-calico
              readOnly: false
            - mountPath: /var/lib/calico
              name: var-lib-calico
              readOnly: false
            - name: policysync
              mountPath: /var/run/nodeagent
      volumes:
        # Used by calico-node.
        - name: lib-modules
          hostPath:
            path: /lib/modules
        - name: var-run-calico
          hostPath:
            path: /var/run/calico
        - name: var-lib-calico
          hostPath:
            path: /var/lib/calico
        - name: xtables-lock
          hostPath:
            path: /run/xtables.lock
            type: FileOrCreate
        # Used to install CNI.
        - name: cni-bin-dir
          hostPath:
            path: /opt/cni/bin
        - name: cni-net-dir
          hostPath:
            path: /etc/cni/net.d
        # Mount in the directory for host-local IPAM allocations. This is
        # used when upgrading from host-local to calico-ipam, and can be removed
        # if not using the upgrade-ipam init container.
        - name: host-local-net-dir
          hostPath:
            path: /var/lib/cni/networks
        # Used to create per-pod Unix Domain Sockets
        - name: policysync
          hostPath:
            type: DirectoryOrCreate
            path: /var/run/nodeagent
        # Used to install Flex Volume Driver
        - name: flexvol-driver-host
          hostPath:
            type: DirectoryOrCreate
            path: /var/libexec/k0s/kubelet-plugins/volume/exec/nodeagent~uds

```
