### ISSUE TITLE
Output of default-config can not be parsed by k0s

### ISSUE THREAD

**Issue by kke** [k0sproject/k0s#658]
```
# k0s version
v0.10.0-beta2
# k0s default-config
```

==> 

```yaml
apiVersion: k0s.k0sproject.io/v1beta1
images:  # <-- is this supposed to be on top level?
# ...
spec:
# ...
  storage:
    kine: null # <-- breaks yaml unmarshal
# ...
```
