### ISSUE TITLE
Items from config top level should be nested under spec

### ISSUE THREAD

**Issue by kke** [k0sproject/k0s#660]
Currently:

```yaml
apiVersion: xyz
kind: xyz
spec:
  some: 
    stuff: goes in here
images:
- xyz: xyz
telemetry:
  xyz: xyz
  ```
  
Anything but `apiVersion`, `kind`, `spec` and `metadata` should go under spec. If I've understood correctly, the top level is there to describe what kind of object to interpret the `spec` to be. This seems to be how it is in the other "kube style" yamls I've looked at (well except KUBECONFIG which also has plenty of stuff on top level)
  
  ==>

```yaml
apiVersion: xyz
kind: xyz
metadata:
  name: foo
spec:
  some: 
    stuff: goes in here
  images:
  - xyz: xyz
  telemetry:
    xyz: xyz
```
