### ISSUE TITLE
kubectl port-forwarding, exec & logs dont work on fresh cluster

### ISSUE THREAD

**Issue by tecbeast42** [k0sproject/k0s#665]
**Version**
```
$ k0s version

v0.9.1
```

**Platform**
Which platform did you run k0s on?
```
$ lsb_release -a

No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.1 LTS
Release:	20.04
Codename:	focal
```
**What happened?**

I have simple pod that is an nginx image. I want to access that with kubectl port-forwarding or kubectl exec.
kubectl get <resource> and kubectl apply etc work fine.

But forwarding and exec produce an error.

```
kubectl port-forward frontend-deployment-786ddcb47-p5kkv 7000:80
error: error upgrading connection: error dialing backend: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial unix /var/lib/k0s/run/konnectivity-server/konnectivity-server.sock: connect: connection refused"
```

Extract from pod describe

```
Containers:
  frontend:
    Container ID:   containerd://897a8911cd31c6d58aef4b22da19dc8166cb7de713a7838bc1e486e497e9f1b2
    Image:          nginx:1.16
    Image ID:       docker.io/library/nginx@sha256:d20aa6d1cae56fd17cd458f4807e0de462caf2336f0b70b5eeb69fcaaf30dd9c
    Port:           80/TCP
    Host Port:      0/TCP
    State:          Running
      Started:      Thu, 28 Jan 2021 14:20:58 +0100
    Ready:          True
    Restart Count:  0
    Environment:    <none>
Events:
  Type    Reason     Age    From               Message
  ----    ------     ----   ----               -------
  Normal  Scheduled  3m43s  default-scheduler  Successfully assigned remove-me/frontend-deployment-786ddcb47-p5kkv to k0s-worker-2
  Normal  Pulling    3m42s  kubelet            Pulling image "nginx:1.16"
  Normal  Pulled     3m33s  kubelet            Successfully pulled image "nginx:1.16" in 9.702313183s
  Normal  Created    3m32s  kubelet            Created container frontend
  Normal  Started    3m32s  kubelet            Started container frontend
```

**How To Reproduce**
How can we reproduce this issue? (as minimally and as precisely as possible)

kubectl apply 

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: nginx:1.16
        ports:
        - containerPort: 80
 ----
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
```

**Expected behavior**
I can use port-forward and exec.

**Screenshots & Logs**
Also add any output from kubectl if applicable:
```
$ export KUBECONFIG=/var/lib/k0s/pki/admin.conf
$ kubectl logs ...
```

logs does not work either

```
kubectl logs frontend-deployment-786ddcb47-p5kkv

Error from server: Get "https://192.168.2.61:10250/containerLogs/remove-me/frontend-deployment-786ddcb47-p5kkv/frontend": rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial unix /var/lib/k0s/run/konnectivity-server/konnectivity-server.sock: connect: connection refused"
```

**Additional context**
