### ISSUE TITLE
Failure in parsing the config will result default config to be used

### ISSUE THREAD

**Issue by jnummelin** [k0sproject/k0s#705]
**Version**
```
0.10.0
```

**What happened?**
When using an invalid or non-existing config, k0s commands will "revert" to use the default config in which e.g. the api addresses are autodetected. See #704 for example behaviour in token commands.

**How To Reproduce**
```
/ # cat k0s.yaml 
kind: Cluster
metadata:
  name: k0s
spec:
  api:
    address: 10.0.20.11
gf.bv,;)

/ # ./k0s token create -c /non/existing/k0s.yaml --role=worker | base64 -d | gunzip - | grep "server:"
    server: https://172.17.0.2:6443
```

**Expected behavior**
The user should be given a clear and concise error status that the config is invalid.
