### ISSUE TITLE
Unable to create clusterrolebinding

### ISSUE THREAD

**Issue by vmarkovtsev** [k0sproject/k0s#714]
**Version**
```
v0.10.0
```
**Platform**
```
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.2 LTS
Release:	20.04
Codename:	focal
```

**What happened?**
I've followed the official docs on the [multi-node cluster](https://docs.k0sproject.io/latest/create-cluster/) and got stuck on adding the user.

First of all, `~/.kube` does not exist so the command `k0s kubeconfig create --groups "system:masters" $clusterUser > ~/.kube/config` fails. The docs should mention `mkdir -p ~/.kube`.

Here is my log:

```
$ sudo k0s kubeconfig create --groups "system:masters" $clusterUser > ~/.kube/config
-bash: /home/vadim/.kube/config: No such file or directory
$ mkdir ~/.kube
$ sudo k0s kubeconfig create --groups "system:masters" $clusterUser > ~/.kube/config
$ kubectl get pods
Error from server (Forbidden): pods is forbidden: User "vadim" cannot list resource "pods" in API group "" in the namespace "default"
$ kubectl create clusterrolebinding $clusterUser-admin-binding --clusterrole=admin --user=$clusterUser
error: failed to create clusterrolebinding: clusterrolebindings.rbac.authorization.k8s.io is forbidden: User "vadim" cannot create resource "clusterrolebindings" in API group "rbac.authorization.k8s.io" at the cluster scope
``` 

So I cannot access my cluster. Is there anything missing?

**Comment by jasmingacic** [comment]
Can you please send us actual kubeconfig that you are using? Also can you run `k0s default-config` and send us the output.

Make sure to remove all the secrets from it.

**Comment by vmarkovtsev** [comment]
Sure, thanks for the help.

`.kube/config`
```yaml
apiVersion: v1
clusters:
- cluster:
    server: https://192.168.1.140:6443
    certificate-authority-data: <blob>
  name: k0s
contexts:
- context:
    cluster: k0s
    user: vadim
  name: k0s
current-context: k0s
kind: Config
preferences: {}
users:
- name: vadim
  user:
    client-certificate-data: <blob>
    client-key-data: <blob>
```

`k0s default-config`
```
apiVersion: k0s.k0sproject.io/v1beta1
images:
  konnectivity:
    image: us.gcr.io/k8s-artifacts-prod/kas-network-proxy/proxy-agent
    version: v0.0.13
  metricsserver:
    image: gcr.io/k8s-staging-metrics-server/metrics-server
    version: v0.3.7
  kubeproxy:
    image: k8s.gcr.io/kube-proxy
    version: v1.20.2
  coredns:
    image: docker.io/coredns/coredns
    version: 1.7.0
  calico:
    cni:
      image: calico/cni
      version: v3.16.2
    flexvolume:
      image: calico/pod2daemon-flexvol
      version: v3.16.2
    node:
      image: calico/node
      version: v3.16.2
    kubecontrollers:
      image: calico/kube-controllers
      version: v3.16.2
installConfig:
  users:
    etcdUser: etcd
    kineUser: kube-apiserver
    konnectivityUser: konnectivity-server
    kubeAPIserverUser: kube-apiserver
    kubeSchedulerUser: kube-scheduler
kind: Cluster
metadata:
  name: k0s
spec:
  api:
    address: 192.168.1.140
    sans:
    - 192.168.1.140
    - 192.168.2.1
  storage:
    type: etcd
    etcd:
      peerAddress: 192.168.1.140
  network:
    podCIDR: 10.244.0.0/16
    serviceCIDR: 10.96.0.0/12
    provider: calico
    calico:
      mode: vxlan
      vxlanPort: 4789
      vxlanVNI: 4096
      mtu: 1450
      wireguard: false
      flexVolumeDriverPath: /usr/libexec/k0s/kubelet-plugins/volume/exec/nodeagent~uds
      withWindowsNodes: false
      overlay: Always
  podSecurityPolicy:
    defaultPolicy: 00-k0s-privileged
telemetry:
  interval: 10m0s
  enabled: true
```
