### ISSUE TITLE
how add MutatingAdmissionWebhook in enable-admission-plugins

### ISSUE THREAD

**Issue by PetterTables** [k0sproject/k0s#758]
Hi
Good day

how add MutatingAdmissionWebhook in enable-admission-plugins

or 

i should change

##############################################
var apiDefaultArgs = map[string]string{

	"allow-privileged":                   "true",
	"enable-admission-plugins":           "NodeRestriction",
	"requestheader-extra-headers-prefix": "X-Remote-Extra-",
	"requestheader-group-headers":        "X-Remote-Group",
	"requestheader-username-headers":     "X-Remote-User",
	"secure-port":                        "6443",
}
#######################################################

and compile ???

thanks

**Comment by jnummelin** [comment]
Both MutatingAdmissionWebhook and ValidatingAdmissionWebhook are enabled by default.

If there are any other admission plugins you need to enable you can use the `extraArgs` setting for api, something like:
```yaml
...
spec:
  api:
    extraArgs:
      enable-admission-plugins: SecurityContextDeny,TaintNodesByCondition
...
```
