### ISSUE TITLE
ipv6 only clusters (and more straightforward dualstack config)

### ISSUE THREAD

**Issue by asteven** [k0sproject/k0s#773]
**Is your feature request related to a problem? Please describe.**
I want to use k0s to run pure ipv6 clusters. This is currently not supported. It crashes when generating the DNSAddress.

**Describe the solution you'd like**
I'd like k0s to support ipv4 only, ipv6 only or dual stack configurations, same as kubeadm does.

**Additional context**
The existing dualstack configuration is somewhat conflicting (or at least redundant) to implement a ipv6 only network config.
I therefore propose to refactor the existing network configuration to work like explained below.

The following config results in a ipv4 only cluster.

```
apiVersion: k0s.k0sproject.io/v1beta1
kind: Cluster
metadata:
  name: k0s
spec:
  api:
    address: 192.168.68.104
  network:
    podCIDR: 10.244.0.0/16
    serviceCIDR: 10.96.0.0/12
```

The following config results in a ipv6 only cluster:

```
apiVersion: k0s.k0sproject.io/v1beta1
kind: Cluster
metadata:
  name: k0s
spec:
  api:
    address: fd00:101::100
  network:
    podCIDR: fd00:102::/64
    serviceCIDR: fd00:103::/108
```

And the following config results in a dual stack cluster:

```
apiVersion: k0s.k0sproject.io/v1beta1
kind: Cluster
metadata:
  name: k0s
spec:
  api:
    # Either should work
    address: 192.168.68.104
    #address: fd00:101::100
  network:
    podCIDR: 10.244.0.0/16,fd00:102::/64
    serviceCIDR: 10.96.0.0/12,fd00:103::/108
```

I believe this is more straight forward then the current dualstack configuration and also inline with the approach taken by kubeadm which is good for user understanding and adoption.

I've basically already put this into code and wanted to discuss/check if you would accept a PR that implements this.
