### ISSUE TITLE
'k0s validate config' could detect mistyped/unsupported configuration parameters

### ISSUE THREAD

**Issue by mviitane** [k0sproject/k0s#774]
**Is your feature request related to a problem? Please describe.**

When I mistype a configuration parameter name or value (in k0s.yaml), I don't easily find the problem. For example:
```
installConfig:
  users:
    etcdUserWRONG: etcd
````
or
```
spec:
  api:
    address: 172.WRONG.x.x
    addressWRONG: 172.x.x.x
    sansWRONG:
    - 172.x.x.x
  storageWRONG:
    type: etcd
    etcd:
      peerAddress: 172.x.x.x
  network:
    podCIDR__WRONG: 10.x.0.0/16
````

**Describe the solution you'd like**
'k0s validate config' could help detecting problems like this. Also when starting a controller, the faulty configuration could be detected before actually launching the controller.
