### ISSUE TITLE
Cannot make a deployment - sqlite is readonly

### ISSUE THREAD

**Issue by toomyem** [k0sproject/k0s#819]
Config:
------
```
~$ sudo k0s status
Version: v0.12.1
Process ID: 357
Parent Process ID: 1
Role: controller
Init System: linux-systemd
```

```
$ lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 10 (buster)
Release:        10
Codename:       buster
```

Loads on worker plane are enabled:

```
[Service]
ExecStart=/usr/bin/k0s controller --single=true
```

Issue:
------

I tried to deploy simple service:

~$ cat nginx.yaml
```
apiVersion: apps/v1
kind: Deployment
metadata:
    name: nginx
    labels:
        app: nginx
spec:
    selector:
        matchLabels:
            app: nginx
    replicas: 1
    template:
        metadata:
            labels:
                app: nginx
        spec:
            containers:
                - name: nginx
                  image: nginx
                  ports:
                      - containerPort: 80
```

```
$ sudo k0s kubectl create -f nginx.yaml
Error from server: error when creating "nginx.yaml": rpc error: code = Unknown desc = attempt to write a readonly database
```
Why sqlite is readonly? Db is owned by kube-apiserver:

```
$ sudo ls -l /var/lib/k0s/db
total 7156
-rw-r--r-- 1 kube-apiserver root 3084288 Mar 31 13:10 state.db
-rw-r--r-- 1 root           root   32768 Mar 31 13:13 state.db-shm
-rw-r--r-- 1 root           root 4206552 Mar 31 13:13 state.db-wal
```

kine also is running as kube-apiserver:
```
$ ps -fe | grep kine
kube-ap+   404   357 99 17:55 ?        01:11:22 /var/lib/k0s/bin/kine --endpoint=sqlite:///var/lib/k0s/db/state.db?more=rwc&_journal=WAL&cache=shared --listen-address=unix:///run/k0s/kine/kine.sock:2379
```
