### ISSUE TITLE
OIDC Auth Provider

### ISSUE THREAD

**Issue by aduzsardi** [k0sproject/k0s#864]
Kubeadm bootstrapping allows for setting up OIDC provider like G Suite/Google/GitHub, etc for authentication, is there some config option to allow this on k0s as well ?

**Comment by jnummelin** [comment]
Essentially setting up OIDC needs bunch of `--oidc-*` flags on api-server. k0s allows users to pass in extra flags via config. An example (you need to figure the proper oidc flags 😄 ):
```yaml
apiVersion: k0s.k0sproject.io/v1beta1
kind: Cluster
metadata:
  name: k0s
spec:
  api:
    address: 172.31.36.24
   extraArgs:
    oidc-issuer-url: https://accounts.google.com
    oidc-client-id: foobar
    ...
```

See https://docs.k0sproject.io/v0.13.1/configuration/#specapi

**Comment by aduzsardi** [comment]
Thank you , i got it working with k8s-oidc-helper , this was easier than i expected

**Comment by jnummelin** [comment]
@aduzsardi good to hear. We'd definitely be interested in having a small tutorial/example in the docs for setting up k0s with OIDC, would you want to contribute that?

**Comment by aduzsardi** [comment]
yes i would , i'll just have to see when i have a little time

thank you again

**Comment by sdeoras** [comment]
yes, it was certainly easier than i also expected. below are steps i took:

added `OIDC` info to `extraArgs` in the k0s default config and entered client id of `gcloud` CLI, so that `gcloud` could be used as auth provider in kubeconfig:

```yaml
apiVersion: k0s.k0sproject.io/v1beta1
kind: Cluster
metadata:
  name: k0s
spec:
  api:
    address: redacted
    port: 6443
    k0sApiPort: 9443
    sans:
    - redacted
    extraArgs:
      oidc-issuer-url: https://accounts.google.com 
      oidc-username-claim: email
      oidc-client-id: 32555940559.apps.googleusercontent.com
# ... remaining default config redacted
```

then gave users required permissions, for instance:
```
kubectl create clusterrolebinding my-user-crb --clusterrole=cluster-admin --user=<username>
```

finally, configured `kubeconfig` to use `gcloud` as the auth provider in `users` section:

```yaml
# beginning part of kubeconfig redacted
users:
- name: k0s
  user:
    auth-provider:
      config:
        cmd-args: config config-helper --format=json
        cmd-path: gcloud
        expiry-key: '{.credential.token_expiry}'
        token-key: '{.credential.id_token}'
      name: gcp
```
