### ISSUE TITLE
k0s -c default value is not used in kubeconfig create

### ISSUE THREAD

**Issue by matti** [k0sproject/k0s#875]
config should have default `./k0s.yaml`:

```
$ k0s kubeconfig create --help
...
Global Flags:
  -c, --config string          config file (default: ./k0s.yaml)
```

but with the  following `./k0s.yaml`

```
kind: Cluster
metadata:
  name: k0s
spec:
  api:
    externalAddress: 192.168.60.60
```

```
k0s kubeconfig -c ./k0s.yaml create admin
```

kubeconfig has the right server address
```
clusters:
- cluster:
    server: https://192.168.60.60:6443
```

but when the `-c ` is omitted:

```
k0s kubeconfig create admin
```

the kubeconfig has wrong server address:

```
apiVersion: v1
clusters:
- cluster:
    server: https://192.168.65.11:6443
```
