### ISSUE TITLE
Can't Start, Stop, Reset or recover in anyway.

### ISSUE THREAD

**Issue by gnoejuan** [k0sproject/k0s#944]
**Version**
```
$ v1.21.1+k0s.0
```
**Platform**
Which platform did you run k0s on?
```
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.2 LTS
Release:        20.04
Codename:       focal
```
**What happened?**

<details>
  <summary>Yaml Config: added 127.0.0.1 and two helm charts</summary>
  
```yaml
apiVersion: k0s.k0sproject.io/v1beta1
kind: Cluster
metadata:
  name: k0s
spec:
  api:
    address: 192.168.1.30
    port: 6443
    k0sApiPort: 9443
    sans:
    - 192.168.1.30
    - 10.33.8.1
    - 192.168.122.1
    - 172.17.0.1
    - 127.0.0.1 
  storage:
    type: etcd
    etcd:
      peerAddress: 192.168.1.30
  network:
    podCIDR: 10.244.0.0/16
    serviceCIDR: 10.96.0.0/12
    provider: kuberouter
    calico: null
    kuberouter:
      mtu: 0
      peerRouterIPs: ""
      peerRouterASNs: ""
      autoMTU: true
  podSecurityPolicy:
    defaultPolicy: 00-k0s-privileged
  telemetry:
    interval: 10m0s
    enabled: true
  installConfig:
    users:
      etcdUser: etcd
      kineUser: kube-apiserver
      konnectivityUser: konnectivity-server
      kubeAPIserverUser: kube-apiserver
      kubeSchedulerUser: kube-scheduler
  images:
    konnectivity:
      image: us.gcr.io/k8s-artifacts-prod/kas-network-proxy/proxy-agent
      version: v0.0.16
    metricsserver:
      image: gcr.io/k8s-staging-metrics-server/metrics-server
      version: v0.3.7
    kubeproxy:
      image: k8s.gcr.io/kube-proxy
      version: v1.21.1
    coredns:
      image: docker.io/coredns/coredns
      version: 1.7.0
    calico:
      cni:
        image: docker.io/calico/cni
        version: v3.18.1
      node:
        image: docker.io/calico/node
        version: v3.18.1
      kubecontrollers:
        image: docker.io/calico/kube-controllers
        version: v3.18.1
    kuberouter:
      cni:
        image: docker.io/cloudnativelabs/kube-router
        version: v1.2.1
      cniInstaller:
        image: quay.io/k0sproject/cni-node
        version: 0.1.0
    default_pull_policy: IfNotPresent
  konnectivity:
    agentPort: 8132
    adminPort: 8133
  extensions:
    helm:
      repositories:
      - name: ingress-nginx
        url: https://kubernetes.github.io/ingress-nginx
      - name: openebs
        url: https://openebs.github.io/charts
      charts:
      - name: ingress-nginx
        chartname: ingress-nginx/ingress-nginx
        version: "1.11.3"
        namespace: ingress-nginx
      - name: openebs
        chartname: openebs/openebs
        namespace: openebs

```
</details>

```bash
sudo k0s install controller --single -c k0s.yaml
sudo systemctl start k0scontroller
sudo systemctl enable k0scontroller
sudo systemctl status k0scontroller

● k0scontroller.service - k0s - Zero Friction Kubernetes
     Loaded: loaded (/etc/systemd/system/k0scontroller.service; enabled; vendor preset: enabled)
     Active: inactive (dead) (Result: exit-code) since Sat 2021-05-29 06:46:32 CDT; 35min ago
       Docs: https://docs.k0sproject.io
    Process: 11973 ExecStart=/usr/local/bin/k0s controller --config=k0s.yaml --single=true (code=exited, status=1/FAILURE)
   Main PID: 11973 (code=exited, status=1/FAILURE)

May 29 06:46:32 E560 systemd[1]: Stopped k0s - Zero Friction Kubernetes.
```

```bash
charlesrod@E560:~$ sudo k0s reset
INFO[2021-05-29 07:28:58] Uninstalling the k0s service                 
INFO failed to uninstall k0s service: failed to remove the k0s service: exit status 1 
FATA[2021-05-29 07:28:58] failed clean up pre-flight-checks: failed to find directory `/var/lib/k0s`, check if the node is provisioned 
charlesrod@E560:~$ sudo k0s stop
charlesrod@E560:~$ sudo k0s reset
INFO[2021-05-29 07:29:14] Uninstalling the k0s service                 
INFO failed to uninstall k0s service: failed to remove the k0s service: exit status 1 
FATA[2021-05-29 07:29:14] failed clean up pre-flight-checks: failed to find directory `/var/lib/k0s`, check if the node is provisioned 
charlesrod@E560:~$ sudo k0s install controller --single -c k0s.yaml
INFO[2021-05-29 07:29:39] Installing k0s service                       
Error: failed to install k0s service: failed to install service: Init already exists: /etc/systemd/system/k0scontroller.service
2021-05-29 07:29:39.204862 I | failed to install k0s service: failed to install service: Init already exists: /etc/systemd/system/k0scontroller.service

```

**How To Reproduce**
How can we reproduce this issue? (as minimally and as precisely as possible)

I **believe** I provided a bad config **but** I would love to know how to dig in further. 

Any help in starting at square 0 would be nice. A manual uninstall process, I guess

**Screenshots & Logs**
Also add any output from kubectl if applicable:
```
$ export KUBECONFIG=/var/lib/k0s/pki/admin.conf
$ kubectl logs ...
```

**Additional context**
