### ISSUE TITLE
CNI provider addon not deploying

### ISSUE THREAD

**Issue by sphr2k** [k0sproject/k0s#988]
**Version**
```
v1.21.2+k0s.0
```
**Platform**
Which platform did you run k0s on?
```
Ubuntu 20.04.2 LTS
```
**What happened?**
Trying to deploy a HA cluster w/ 3x controller+worker nodes with `network.provider: custom`, `kubeProxy.disabled: true` and Cilium 1.10.1 deployed as an addon in `kubeProxyReplacement: strict` mode.

The cluster is deployed, but the Cilium addon is not deployed (and nothing else, of course, since the nodes don't become ready. A manual Helm deployment of Cilium with the exact same settings works fine and the other addon deployments (Nginx Ingress, MetalLB) succeed afterwards.

**How To Reproduce**
Deploy cluster from this `k0sctl` config

```
apiVersion: k0sctl.k0sproject.io/v1beta1
kind: Cluster
metadata:
  name: k0s-cluster
spec:
  hosts:
  - ssh:
      address: k0s-cp-1
      user: ubuntu
      port: 22
      keyPath: /home/user/.ssh/id_rsa
    role: controller+worker
  - ssh:
      address: k0s-cp-2
      user: ubuntu
      port: 22
      keyPath: /home/user/.ssh/id_rsa
    role: controller+worker
  - ssh:
      address: k0s-cp-3
      user: ubuntu
      port: 22
      keyPath: /home/user/.ssh/id_rsa
    role: controller+worker
  k0s:
    version: v1.21.2+k0s.0
    config:
      spec:
        api:
          externalAddress: cluster-lb.my.tld
          sans:
          - cluster-lb.my.tld
        network:
          provider: custom
          kubeProxy:
            disabled: true
        extensions:
          helm:
            repositories:
            - name: cilium
              url: https://helm.cilium.io
            charts:
            - name: cilium
              chartname: cilium/cilium
              version: "1.10.1"
              namespace: kube-system
              values: |2
                kubeProxyReplacement: "strict"
                k8sServiceHost: cluster.j8s.it
                k8sServicePort: 6443
                global:
                  encryption:
                    enabled: true
                    nodeEncryption: true
                operator:
                  replicas: 1
                ipam:
                  mode: "cluster-pool"
                  operator:
                    clusterPoolIPv4PodCIDR: "10.43.0.0/16"
                    clusterPoolIPv4MaskSize: 24
                    clusterPoolIPv6PodCIDR: "fd00::/104"
                    clusterPoolIPv6MaskSize: 120
```

**Expected behavior**
Cilium addon should be installed

**Comment by jasmingacic** [comment]
I used pretty much the same setup with three controller+workers behind an ELB and Cilium gets deployed:

```
# kubectl get pods -A
NAMESPACE     NAME                               READY   STATUS              RESTARTS   AGE
kube-system   cilium-2l9m8                       0/1     Running             3          3m29s
kube-system   cilium-gz7z4                       0/1     Running             3          3m39s
kube-system   cilium-gz8qx                       0/1     Running             4          3m59s
kube-system   cilium-operator-7bdbfd79cb-rg6vj   1/1     Running             2          4m31s
```
The config:
```
apiVersion: k0sctl.k0sproject.io/v1beta1
kind: Cluster
metadata:
  name: k0s-cluster
spec:
  hosts:
  - ssh:
      address: 13.49.57.155
      user: ubuntu
      port: 22
      keyPath: ../aws-tf/aws_private.pem
    role: controller+worker
  - ssh:
      address: 13.49.226.224
      user: ubuntu
      port: 22
      keyPath: ../aws-tf/aws_private.pem
    role: controller+worker
  - ssh:
      address: 13.49.65.164
      user: ubuntu
      port: 22
      keyPath: ../aws-tf/aws_private.pem
    role: controller+worker
  k0s:
    version: v1.21.2+k0s.0
    config:
      spec:
        api:
          externalAddress: elb-1663416988.eu-north-1.elb.amazonaws.com
          sans:
          - elb-1663416988.eu-north-1.elb.amazonaws.com
        network:
          provider: custom
          kubeProxy:
            disabled: true
        extensions:
          helm:
            repositories:
            - name: cilium
              url: https://helm.cilium.io
            charts:
            - name: cilium
              chartname: cilium/cilium
              version: "1.10.1"
              namespace: kube-system
              values: |2
                kubeProxyReplacement: "strict"
                k8sServiceHost: cluster.j8s.it
                k8sServicePort: 6443
                global:
                  encryption:
                    enabled: true
                    nodeEncryption: true
                operator:
                  replicas: 1
                ipam:
                  mode: "cluster-pool"
                  operator:
                    clusterPoolIPv4PodCIDR: "10.43.0.0/16"
                    clusterPoolIPv4MaskSize: 24
                    clusterPoolIPv6PodCIDR: "fd00::/104"
                    clusterPoolIPv6MaskSize: 120
```

**Comment by sphr2k** [comment]
Thanks for your feedback, I'll try again :)

**Comment by jnummelin** [comment]
One possibility is that this triggers some or similar issue as seen on #1058

**Comment by soider** [comment]
@sphr2k have you had success with cillium deployment?

**Comment by sphr2k** [comment]
@soider Tried again today, but to no avail. Same configuration as before, just a newer k8s/k0s version (1.22.2). I think @jnummelin is right. To me this looks like a chicken/egg problem where all nodes are tainted because CoreDNS is not ready, causing the Cilium manifest to deploy. After deploying the same Cilium chart manually, everything is fine.

**Comment by ruskofd** [comment]
I can confirm the issue with any Charts deployed when using multiple Controller in HA mode. Here is my configuration : 

```YAML
apiVersion: k0sctl.k0sproject.io/v1beta1
kind: Cluster
metadata:
  name: k0s-cluster
spec:
  hosts:
  #### Controllers
  #
  - role: controller
    ssh:
      address: 192.168.122.12
      user: core
      port: 22
  - role: controller
    ssh:
      address: 192.168.122.13
      user: core
      port: 22
  - role: controller
    ssh:
      address: 192.168.122.14
      user: core
      port: 22

  #### Workers
  #
  - role: worker
    ssh:
      address: 192.168.122.15
      user: core
      port: 22
  - role: worker
    ssh:
      address: 192.168.122.16
      user: core
      port: 22
  - role: worker
    ssh:
      address: 192.168.122.17
      user: core
      port: 22

  #### k0s configuration
  #
  k0s:
    version: "v1.22.4+k0s.1"
    config:
      apiVersion: k0s.k0sproject.io/v1beta1
      kind: Cluster
      metadata:
        name: k0s
      spec:
        api:
          externalAddress: 192.168.122.11
          sans:
            - 192.168.122.11
        storage:
          type: etcd
        network:
          provider: calico
        podSecurityPolicy:
          defaultPolicy: 00-k0s-privileged
        telemetry:
          enabled: false
        extensions:
          helm:
            repositories:
            - name: metallb
              url: https://metallb.github.io/metallb
            - name: traefik
              url: https://helm.traefik.io/traefik
            charts:
            - name: metallb
              chartname: metallb/metallb
              version: "0.11.0"
              namespace: metallb-system
              values: |
                configInline:
                  address-pools:
                  - name: default
                    protocol: layer2
                    addresses:
                      - 192.168.122.10/32
            - name: traefik
              chartname: traefik/traefik
              version: "v10.7.1"
              namespace: ingress
```

Here are the logs from the first node provisionned : 

```
ec 06 20:50:35 mk8s01 k0s[1775]: time="2021-12-06 20:50:35" level=warning msg="stack apply failed" bundle=helm component=applier error="mapping error: no matches for kind \"Chart\" in version \"helm.k0sproject.io/v1beta1\""
Dec 06 20:50:36 mk8s01 k0s[1775]: time="2021-12-06 20:50:36" level=warning msg="stack apply failed" bundle=helm component=applier error="mapping error: no matches for kind \"Chart\" in version \"helm.k0sproject.io/v1beta1\""
Dec 06 20:50:36 mk8s01 k0s[1775]: time="2021-12-06 20:50:36" level=warning msg="stack apply failed" bundle=helm component=applier error="mapping error: no matches for kind \"Chart\" in version \"helm.k0sproject.io/v1beta1\""
Dec 06 20:50:36 mk8s01 k0s[1775]: time="2021-12-06 20:50:36" level=warning msg="stack apply failed" bundle=helm component=applier error="mapping error: no matches for kind \"Chart\" in version \"helm.k0sproject.io/v1beta1\""
Dec 06 20:50:36 mk8s01 k0s[1775]: time="2021-12-06 20:50:36" level=warning msg="failed to apply manifests: mapping error: no matches for kind \"Chart\" in version \"helm.k0sproject.io/v1beta1\"" component=applier-helm
Dec 06 20:51:07 mk8s01 k0s[1775]: time="2021-12-06 20:51:07" level=info msg="I1206 20:51:07.852825    1890 resource_quota_monitor.go:229] QuotaMonitor created object count evaluator for charts.helm.k0sproject.io" component=kube-controller-manager
```

One thing I saw is, after rebooting the first provisionned controller node (where I can find these logs), all the Charts specified above are deployed without any problems when k0s start again. From what I understand, when the Chart are deployed, the CRD is not present and therefore the Chart deployment failed, is that right ?

However, this problem does not appear when using a single controller and multiple workers.
