### ISSUE TITLE
Centos 7 based k0s image sometimes has CNI plugin errors on startup

### ISSUE THREAD

**Issue by nanoandrew4** [k0sproject/k0s#993]
**Version**
```
v1.21.1+k0s.0
```
**Platform**
Which platform did you run k0s on?
```
centos:7 docker image
```
**What happened?**

For our integration test environment, we needed a docker container running k0s. Sadly, the official image won't work for us because we need our containers to be based off centos 7, so I tried copying the Dockerfile and other files of the k0s official image to my own Dockerfile, based off centos 7. However, I noticed that sometimes k0s starts fine, and becomes ready, but a lot of other times, the CNI plugin fails to initialize, leaving k0s in a NotReady state indefinitely. The following is part of the message I get when I run `kubectl describe node`:
```
Ready            False   Fri, 25 Jun 2021 22:56:55 +0000   Fri, 25 Jun 2021 22:56:45 +0000   KubeletNotReady              container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:Network plugin returns error: cni plugin not initialized
```

However, running `systemctl restart k0scontroller` once we see the CNI plugin error, and waiting a couple minutes seems to fix the issue, the cluster becomes Ready and we can use it to install our helm charts. 

**How To Reproduce**
Here are the files I am using:

Dockerfile:
```dockerfile
FROM centos:7

EXPOSE 22

RUN echo "root:root" | chpasswd

RUN yum update -y

RUN yum install openssh-server openssl net-tools iproute wget zip unzip -y

RUN curl -LO https://storage.googleapis.com/kubernetes-release/release/v1.20.1/bin/linux/amd64/kubectl \
       && chmod +x ./kubectl \
       && mv ./kubectl /usr/local/bin/kubectl

ADD get_k0s.sh /get_k0s.sh
ADD k0sconfig.yaml /k0sconfig.yaml

RUN curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash

RUN /get_k0s.sh && k0s install controller --single -c /k0sconfig.yaml && systemctl enable k0scontroller

ADD entrypoint.sh /entrypoint.sh
ADD kubeconfig.sh /kubeconfig.sh

ENTRYPOINT ["/entrypoint.sh"]

VOLUME [ "/sys/fs/cgroup" ]
CMD ["/usr/sbin/init"]
```

Files mentioned in the Dockerfile are as follows:

get_k0s.sh:
```bash
#!/bin/sh

export k0s_version=v1.21.1+k0s.0

k0s version &> /dev/null
if [[ "$(echo $?)" -eq 0 ]] && [[ "$(k0s version)" == "$k0s_version" ]]; then
  echo "The version of k0s has not been changed, skipping download and installation..."
else
  printf "Downloading k0s... "
  curl -sSLf "https://github.com/k0sproject/k0s/releases/download/$k0s_version/k0s-$k0s_version-amd64" > /usr/local/bin/k0s
  echo done
  chmod 755 /usr/local/bin/k0s
  echo "k0s is now executable in /usr/local/bin"
fi
```

k0sconfig.yaml:
```yaml
apiVersion: k0s.k0sproject.io/v1beta1
kind: Cluster
metadata:
  name: k0s
spec:
  api:
    address: 172.0.0.4
    port: 6443
    k0sApiPort: 9443
    sans:
    - 172.0.0.4
    extraArgs:
      service-node-port-range: 30000-30100
      event-ttl: 6h
  storage:
    type: etcd
    etcd:
      peerAddress: 172.0.0.4
  network:
    podCIDR: 10.244.0.0/16
    serviceCIDR: 10.96.0.0/12
    provider: kuberouter
    calico: null
    kuberouter:
      mtu: 0
      peerRouterIPs: ""
      peerRouterASNs: ""
      autoMTU: true
  podSecurityPolicy:
    defaultPolicy: 00-k0s-privileged
  telemetry:
    interval: 10m0s
    enabled: true
  installConfig:
    users:
      etcdUser: etcd
      kineUser: kube-apiserver
      konnectivityUser: konnectivity-server
      kubeAPIserverUser: kube-apiserver
      kubeSchedulerUser: kube-scheduler
  images:
    konnectivity:
      image: us.gcr.io/k8s-artifacts-prod/kas-network-proxy/proxy-agent
      version: v0.0.16
    metricsserver:
      image: gcr.io/k8s-staging-metrics-server/metrics-server
      version: v0.3.7
    kubeproxy:
      image: k8s.gcr.io/kube-proxy
      version: v1.21.1
    coredns:
      image: docker.io/coredns/coredns
      version: 1.7.0
    calico:
      cni:
        image: docker.io/calico/cni
        version: v3.18.1
      node:
        image: docker.io/calico/node
        version: v3.18.1
      kubecontrollers:
        image: docker.io/calico/kube-controllers
        version: v3.18.1
    kuberouter:
      cni:
        image: docker.io/cloudnativelabs/kube-router
        version: v1.2.1
      cniInstaller:
        image: quay.io/k0sproject/cni-node
        version: 0.1.0
    default_pull_policy: IfNotPresent
  konnectivity:
    agentPort: 8132
    adminPort: 8133
```

entrypoint.sh:
```bash
#!/bin/sh

# Ensure we have some semi-random machine-id
if [ ! -f  /etc/machine-id ]; then
    dd if=/dev/urandom status=none bs=16 count=1 | md5sum | cut -d' ' -f1 > /etc/machine-id
fi

# Network fixups adapted from kind: https://github.com/kubernetes-sigs/kind/blob/master/images/base/files/usr/local/bin/entrypoint#L176
docker_embedded_dns_ip='127.0.0.11'
# first we need to detect an IP to use for reaching the docker host
docker_host_ip="$(ip -4 route show default | cut -d' ' -f3)"

# patch docker's iptables rules to switch out the DNS IP
iptables-save \
  | sed \
    `# switch docker DNS DNAT rules to our chosen IP` \
    -e "s/-d ${docker_embedded_dns_ip}/-d ${docker_host_ip}/g" \
    `# we need to also apply these rules to non-local traffic (from pods)` \
    -e 's/-A OUTPUT \(.*\) -j DOCKER_OUTPUT/\0\n-A PREROUTING \1 -j DOCKER_OUTPUT/' \
    `# switch docker DNS SNAT rules rules to our chosen IP` \
    -e "s/--to-source :53/--to-source ${docker_host_ip}:53/g"\
  | iptables-restore

# now we can ensure that DNS is configured to use our IP
cp /etc/resolv.conf /etc/resolv.conf.original
sed -e "s/${docker_embedded_dns_ip}/${docker_host_ip}/g" /etc/resolv.conf.original >/etc/resolv.conf

# write config from environment variable
if [ ! -z "$K0S_CONFIG" ]; then
  mkdir -p /etc/k0s
  echo -n "$K0S_CONFIG" > /etc/k0s/config.yaml
fi

./kubeconfig.sh &

exec $@
```

kubeconfig.sh:
```bash
while [ ! -f /var/lib/k0s/pki/admin.conf ]
do
  sleep 2
done
mkdir /root/.kube && cp /var/lib/k0s/pki/admin.conf /root/.kube/config
chmod 400 /root/.kube/config
chmod 400 /var/lib/k0s/pki/admin.conf
```

**Expected behavior**
I would expect k0s to always create the cluster and for it to become Ready without having to sometimes do a restart, adding several minutes to our build time.

**Additional information**
We run the image generated from this Dockerfile with docker-compose, and mount a directory containing a tar file with images we want imported into k0s, mapping it to the directory `/var/lib/k0s/images`. The tar file with the images is about 3.5GB in size.
